force-app/main/default/objects/Campaign/fields/EV_Encuesta__c.field-meta.xml
<CustomField>
    <fullName>EV_Encuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Encuesta asociada</description>
    <inlineHelpText>Por defecto, seleccionar “CaixaBank Talks MVP”</inlineHelpText>
    <label>Encuesta asociada</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>EV_ExternalID__c</fullName>
    <description>Id externo securizado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_Origen__c.field-meta.xml
<CustomField>
    <fullName>EV_Origen__c</fullName>
    <description>Campo origen para saber desde donde se realizó la creación y saltar validaciones</description>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta masiva</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_TechSummit__c.field-meta.xml
<CustomField>
    <fullName>EV_TechSummit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check para identificar los eventos de portales Tech Summit.</description>
    <label>Tech Summit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_ContadorCheckInVirtual__c.field-meta.xml
<CustomField>
    <fullName>EV_ContadorCheckInVirtual__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Contador que registra las veces que se ha ingresado a la página de check in virtual. Lo actualiza portales</description>
    <label>Contador CheckIn virtual</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_EmailDeCampana__c.field-meta.xml
<CustomField>
    <fullName>EV_EmailDeCampana__c</fullName>
    <description>Email de cliente exclusivo para el evento</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email de campaña</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_Empresa__c.field-meta.xml
<CustomField>
    <fullName>EV_Empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check para controlar si el miembro de campaña proviene de una empresa o no.</description>
    <label>Empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>EV_ExternalID__c</fullName>
    <description>Id externo securizado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_InvitacionEncuesta__c.field-meta.xml
<CustomField>
    <fullName>EV_InvitacionEncuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invitación a encuesta</description>
    <label>Invitación encuesta</label>
    <referenceTo>SurveyInvitation</referenceTo>
    <relationshipLabel>Campaign Members (Survey Invitation)</relationshipLabel>
    <relationshipName>Miembros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/EV_URLEncuesta__c.field-meta.xml
<CustomField>
    <fullName>EV_URLEncuesta__c</fullName>
    <description>URL invitación encuesta</description>
    <formula>$CustomMetadata.EV_URL_portal__mdt.URLs.urlComunidadEncuestas__c &amp;&apos;/survey/runtimeApp.app?invitationId=&apos;&amp; EV_InvitacionEncuesta__r.Id&amp;&apos;&amp;surveyName=&apos;&amp;Campaign.EV_Encuesta__r.DeveloperName&amp;&apos;&amp;UUID=&apos;&amp;EV_InvitacionEncuesta__r.UUID &amp;&apos;&amp;guestUserLang=&apos; &amp;
	IF(ISBLANK(LeadId), 
	IF(ISBLANK(ContactId),IF(ISBLANK(AccountId),&apos;es&apos;,CASE(Account.AV_Idioma__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;)), CASE(Contact.Account.AV_Idioma__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;)),
	CASE(Lead.EV_Idiomas__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL encuesta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/CC_InterfaceSettings__mdt.object-meta.xml
<CustomObject>
    <description>Configuración de integraciones</description>
    <label>Configuración interfaz</label>
    <pluralLabel>Configuración interfases</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>CC_EndPoint__c</fullName>
    <description>End point del servicio</description>
    <inlineHelpText>End point del servicio</inlineHelpText>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/EV_CampaignMemberC__c.object-meta.xml
<CustomObject>
    <label>CampaignMember</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Identificador Miembro de Campaña</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CampaignMembers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_AccountId__c.field-meta.xml
<CustomField>
    <fullName>EV_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_CampaignId__c.field-meta.xml
<CustomField>
    <fullName>EV_CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_ContadorCheckInVirtual__c.field-meta.xml
<CustomField>
    <fullName>EV_ContadorCheckInVirtual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Contador CheckIn virtual</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_EmailDeCampana__c.field-meta.xml
<CustomField>
    <fullName>EV_EmailDeCampana__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email de campaña</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_Empresa__c.field-meta.xml
<CustomField>
    <fullName>EV_Empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Empresa</description>
    <label>Empresa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>EV_ExternalID__c</fullName>
    <description>Id externo securizado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_InvitacionEncuesta__c.field-meta.xml
<CustomField>
    <fullName>EV_InvitacionEncuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invitación encuesta</label>
    <referenceTo>SurveyInvitation</referenceTo>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_LeadId__c.field-meta.xml
<CustomField>
    <fullName>EV_LeadId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>CampaignMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_Status__c.field-meta.xml
<CustomField>
    <fullName>EV_Status__c</fullName>
    <description>Estado</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asistió</fullName>
            </value>
            <value>
                <fullName>Asistió en diferido</fullName>
            </value>
            <value>
                <fullName>Baja del evento</fullName>
            </value>
            <value>
                <fullName>Error envio</fullName>
            </value>
            <value>
                <fullName>Invitación enviada</fullName>
            </value>
            <value>
                <fullName>Invitacion no enviada</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>QR enviado</fullName>
            </value>
            <value>
                <fullName>Registro confirmado</fullName>
            </value>
            <value>
                <fullName>Accedio a la oferta</fullName>
                <label>Accedió a la oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberC__c/fields/EV_URLEncuesta__c.field-meta.xml
<CustomField>
    <fullName>EV_URLEncuesta__c</fullName>
    <description>URL encuesta</description>
    <formula>$CustomMetadata.EV_URL_portal__mdt.URLs.urlComunidadEncuestas__c &amp;&apos;/survey/runtimeApp.app?invitationId=&apos;&amp; EV_InvitacionEncuesta__r.Id&amp;&apos;&amp;surveyName=&apos;&amp;EV_CampaignId__r.EV_Encuesta__r.DeveloperName&amp;&apos;&amp;UUID=&apos;&amp;EV_InvitacionEncuesta__r.UUID &amp;&apos;&amp;guestUserLang=&apos; &amp;
IF(ISBLANK(EV_LeadId__c),
IF(ISBLANK(EV_ContactId__c),IF(ISBLANK(EV_AccountId__c),&apos;es&apos;,CASE(EV_AccountId__r.AV_Idioma__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;)), CASE(EV_ContactId__r.Account.AV_Idioma__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;)),
CASE(EV_LeadId__r.EV_Idiomas__c, &apos;001&apos;, &apos;ca&apos;, &apos;002&apos;,&apos;es&apos;,&apos;010&apos;,&apos;en&apos;,&apos;es&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL encuesta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EV_CampaignMemberHistory__c/EV_CampaignMemberHistory__c.object-meta.xml
<CustomObject>
    <label>Historial miembros de campaña</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>CampaignMemberHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historiales miembros de campaña</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EV_CampaignMemberHistory__c/fields/EV_CampaignMember_Id__c.field-meta.xml
<CustomField>
    <fullName>EV_CampaignMember_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CampaignMember Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EV_CampaingMemeberStaging__c/EV_CampaingMemeberStaging__c.object-meta.xml
<CustomObject>
    <label>Campaing Memeber Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CampaingMemeberStaging Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaing Memebers Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EV_CampaingMemeberStaging__c/fields/EV_ContadorCheckInVirtual__c.field-meta.xml
<CustomField>
    <fullName>EV_ContadorCheckInVirtual__c</fullName>
    <description>Contador que registra las veces que se ha ingresado a la página de check in virtual. Lo actualiza portales</description>
    <label>Contador CheckIn virtual</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EV_CampaingMemeberStaging__c/fields/EV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>EV_ExternalID__c</fullName>
    <description>Id externo securizado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EV_CampaingMemeberStaging__c/fields/EV_Status__c.field-meta.xml
<CustomField>
    <fullName>EV_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Reprocess</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/EV_Account__c.field-meta.xml
<CustomField>
    <fullName>EV_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EV_CampaignId__c.field-meta.xml
<CustomField>
    <fullName>EV_CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Id de la campaña relacionada</description>
    <label>CampaignId</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EV_CampaignMemberCTriggerHelper_Test.cls
/**********************************************************************************************************************
 Name:	  EV_CampaignMemberCTriggerHelper_Test
 Copyright © 2023  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
* @description  Clase de test para el TriggerHelper de CampaignMember
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
	VERSION		USER_STORY			AUTHOR								DATE				Description
	1.0			US584499            Mamen Arias         				20/04/2023          Init Version
	1.1			US586998			Daniel Rodriguez					07/06/2023			Add method contadorCheckIn_Test
	1.2			US635293			Carolina Lopez/Humberto Vilchez	    23/06/2023			Add method executeCampaignMemberSendEmail
    1.3			US661500			Carolina Lopez	   				    25/07/2023			Modify method executeCampaignMemberSendEmail to include new field EV_TechSummit__c and remove RT TechSummit
    1.4			US680535			Humberto Vilchez   				    01/08/2023			Modify method executeCampaignMemberSendEmail for fix test error WS, add SeeAllData = true in linkUniqueSurveyGenerationAsistio_Tes, linkUniqueSurveyGenerationAsistioNew_Test methods
	1.5         US680535            Carolina Lopez                      18/08/2023			Add method executeCampaignMemberSendEmailFisico	
	1.6			US657362			Mamen Arias							01/09/2023			Modify method contadorCheckIn_Test with active Survey		
	1.7			US738796			Carolina Lopez						19/10/2023			Include CC_InterfaceSettings__mdt in methods executeCampaignMemberBUTriggerGenerarQR, testEventSurvey, executeCampaignMemberSendEmail, executeCampaignMemberSendEmailFisico and contadoresTest	
	1.8			US785364            Daniel Rodriguez    				21/12/2023 			Modify methods to new callout Adobe Campaign
	1.9			TechSummit			Carolina Lopez						22/05/2024			Modify methods executeCampaignMemberSendEmail, executeCampaignMemberSendEmailFisico.
	2.0			TechSummit			Carolina Lopez						05/06/2024			Modify logic of methods executeCampaignMemberSendEmail, executeCampaignMemberSendEmailFisico.
***********************************************************************************************************************/
@isTest
public with sharing class EV_CampaignMemberCTriggerHelper_Test {

	@isTest
	private static void memberCampaignWithoutAccountTest(){
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','EV Gestor Eventos Senior','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		Test.startTest();
		
		System.runAs(newUser){
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
			campMember.EV_Empresa__c = true;
			Database.update(campMember);
		}
		
		Test.stopTest();

		System.assertEquals(true, campMember.EV_Empresa__c, 'UPDATE OK');
	}

	@isTest (SeeAllData=true)
	public static void executeCampaignMemberBUTriggerGenerarQR() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		Test.startTest(); 

		System.runAs(newUser){
			Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
			header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));

            CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
			header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
			
            if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
            } else {
                header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
            }
            
			HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
			Test.setMock(HttpCalloutMock.class, multiCalloutMock);
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);

			campMember.EV_Status__c ='Invitación enviada';
			update campMember;
			
			Survey surv = [SELECT Id FROM Survey WHERE ActiveVersionId != null LIMIT 1];
			Campaign camp = new Campaign(Id=campMember.EV_CampaignId__c, EV_Encuesta__c=surv.Id);
			update camp;
			
			campMember.EV_ContadorCheckInVirtual__c = 1;
			campMember.EV_Status__c ='Registro Confirmado';
			update campMember;
		}

		Test.stopTest();

		System.assertEquals('Registro Confirmado', campMember.EV_Status__c, 'Se ha confirmado el registro');
	}
	
	@isTest (SeeAllData=true)
	public static void testEventSurvey(){
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		System.runAs(newUser){
			Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
			header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));
			
            CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
			header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
			
            if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
            } else {
                header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
            }
            
			HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
			Test.setMock(HttpCalloutMock.class, multiCalloutMock);
			
			campMember =  EV_TestHelper.createCampaignMemberCustomLead(true,false);
			Survey surv = [SELECT Id FROM Survey WHERE ActiveVersionId != null LIMIT 1];        
			Campaign camp = new Campaign(Id=campMember.EV_CampaignId__c, EV_Encuesta__c=surv.Id);
			update camp;
		}

		Test.startTest();
		System.runAs(newUser){
			Account acc = EV_TestHelper.createEmpresa();
            
            Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
            header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));
            
            CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
			header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
			
            if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
            } else {
                header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
            }
            
            HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
            
            Test.setMock(HttpCalloutMock.class, multiCalloutMock);
            
			EV_CampaignMemberC__c campMem = new EV_CampaignMemberC__c();
			campMem.EV_AccountId__c =acc.Id;
			campMem.EV_CampaignId__c = campMember.EV_CampaignId__c;
			campMem.EV_ExternalId__c = '123456789';
			campMem.EV_Status__c = 'Pendiente';
			insert campMem;

			Lead l = [SELECT Id, EV_Account__c FROM Lead WHERE Id = :campMember.EV_LeadId__c ];
			l.EV_Account__c = acc.Id;
			update l;

			campMember.EV_Status__c = 'Asistió';
			update campMember;
		}
		Test.stopTest();
		
		System.assertEquals('Asistió', campMember.EV_Status__c, 'Ha asistido al evento');
	}

	@isTest (SeeAllData=true)
	public static void linkUniqueSurveyGenerationAsistioTest() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','EV Gestor Eventos Senior','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		Test.startTest();
		System.runAs(newUser){
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
			Survey surv = [SELECT Id FROM Survey WHERE ActiveVersionId != null LIMIT 1];
            Campaign camp = [SELECT Id, EV_Encuesta__c FROM Campaign WHERE Id = :campMember.EV_CampaignId__c LIMIT 1];
            camp.EV_Encuesta__c = surv.Id;
			update camp;
			campMember.EV_Status__c ='Asistió';
			update campMember;

			campMember = [SELECT Id, EV_URLEncuesta__c, EV_InvitacionEncuesta__c FROM EV_CampaignMemberC__c WHERE Id = :campMember.Id LIMIT 1];
		}
		Test.stopTest();

		System.assertEquals(String.isNotBlank(campMember.EV_URLEncuesta__c), true, 'LINK de encuesta');
	}

	@isTest (SeeAllData=true)
	public static void linkUniqueSurveyGenerationAsistioNewTest() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','EV Gestor Eventos Senior','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();
 
		Test.startTest();

		System.runAs(newUser){
			campMember = EV_TestHelper.createCampaignMemberCustomContactFisicaSurvey('Asistió');
			campMember = [SELECT Id, EV_InvitacionEncuesta__c FROM EV_CampaignMemberC__c WHERE Id = :campMember.Id LIMIT 1];
		}

		Test.stopTest();

		System.assertEquals(String.isNotBlank(campMember.EV_InvitacionEncuesta__c), true, 'Invitación enviada');
	}
    
    @isTest
	public static void deleteCM() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();
        EV_CampaignMemberHistory__c campH = new EV_CampaignMemberHistory__c();
		
        System.runAs(newUser){
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
		}

		Test.startTest();
		System.runAs(newUser){
			delete campMember;
            campH = [SELECT Id, EV_CampaignMember_Id__c FROM EV_CampaignMemberHistory__c where EV_CampaignMember_Id__c = :campMember.Id];
		}
		Test.stopTest();

        System.assertEquals(campH.EV_CampaignMember_Id__c, campMember.Id, 'DELETE OK');
    }
    
     @isTest (SeeAllData=true)
	public static void inscriptionNRTCliente() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','EV Gestor Eventos Senior','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		Test.startTest();
		System.runAs(newUser){
			Test.setMock(HttpCalloutMock.class, new EV_ConexionQR_Mock(200));
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
			campMember.EV_Status__c='Registro confirmado';
			campMember.EV_EmailDeCampana__c = 'prueba@prueba.com';
			update campMember;		
		}
		Test.stopTest();

		System.assertEquals(campMember.EV_ExternalID__c != null, campMember.EV_ExternalID__c != null, 'El external ID es incorrecto');
	}
    
    @isTest (SeeAllData=true)
	public static void contadorCheckInTest() {
		User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','EV Gestor Eventos Senior','Eventos');
		EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();

		Test.startTest();
		System.runAs(newUser){
			campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
			Survey surv = [SELECT Id FROM Survey WHERE ActiveVersionId != null LIMIT 1];
            Campaign camp = [SELECT Id, EV_Encuesta__c FROM Campaign WHERE Id = :campMember.EV_CampaignId__c LIMIT 1];
            camp.EV_Encuesta__c = surv.Id;
			update camp;
			campMember = [SELECT Id,EV_ExternalId__c, Recordtype.name FROM EV_CampaignMemberC__c WHERE Id = :campMember.Id LIMIT 1];
            EV_CampaingMemeberStaging__c cmpC = new EV_CampaingMemeberStaging__c(
            EV_ExternalId__c = campMember.EV_ExternalID__c,
            EV_ContadorCheckInVirtual__c= 1,
		    EV_Origen__c = 'Newsletter',
			EV_Canal__c = 'I');
            insert cmpC;
		}
		Test.stopTest();

		System.assertEquals(String.isNotBlank(campMember.EV_ExternalId__c), true, 'OK');
	}

    @isTest(SeeAllData=true)
    public static void executeCampaignMemberSendEmail() {
        User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		Lead interlocutor = new Lead();
		Campaign campTechSumm = new Campaign();
		EV_CampaignMemberC__c campMember  = new EV_CampaignMemberC__c();
		System.runAs(newUser){  
            interlocutor = EV_TestHelper.createLeadAuxTechSummit('Tech Summit Virtual');
            campTechSumm = EV_TestHelper.createCampaignTechSummit(true, false);
			campMember = EV_TestHelper.createCampaignMemberLeadCampaignTechSummit(interlocutor.Id, campTechSumm.Id, 'Registro Confirmado');

		}
        System.runAs(newUser){  
            Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
            header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));
            CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
			header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
            if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
            } else {
                header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
            }
            HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
            Test.setMock(HttpCalloutMock.class, multiCalloutMock);
            Test.startTest();
            EV_CampaignMemberC__c campMemToCheck = [SELECT id FROM EV_CampaignMemberC__c WHERE EV_LeadId__c =: interlocutor.Id];
            System.assertEquals(campMemToCheck.Id, campMember.Id, 'Envío de email');
            Test.stopTest();
        }
    }

	@isTest(SeeAllData=true)
    public static void executeCampaignMemberSendEmailFisico() {
        User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		Lead interlocutor = new Lead();
		Campaign campTechSumm = new Campaign();
		EV_CampaignMemberC__c campMember  = new EV_CampaignMemberC__c();
		System.runAs(newUser){ 
			interlocutor = EV_TestHelper.createLeadAuxTechSummit('Tech Summit Fisico');
            campTechSumm = EV_TestHelper.createCampaignTechSummit(false, true);
			campMember = EV_TestHelper.createCampaignMemberLeadCampaignTechSummit(interlocutor.Id, campTechSumm.Id, 'Registro Confirmado');
		}
        System.runAs(newUser){  
            Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
            header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));
            CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
			header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
            if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
            } else {
                header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
            }
            HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
			Test.setMock(HttpCalloutMock.class, multiCalloutMock);      
            Test.startTest();
            EV_CampaignMemberC__c campMemToCheck = [SELECT id FROM EV_CampaignMemberC__c WHERE EV_LeadId__c =: interlocutor.Id];
            System.assertEquals(campMemToCheck.Id, campMember.Id, 'Envío de email evento fisico');
            Test.stopTest();
        }
    }
    
    @isTest (SeeAllData=true)
		public static void contadoresTest() {
            User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
            EV_CampaignMemberC__c campMember = new EV_CampaignMemberC__c();
            Campaign camp = new Campaign();
 
    
            Test.startTest();
            System.runAs(newUser){
                Map<String, HttpCalloutMock> header2TestResp = new Map<String,HttpCalloutMock>();
                header2TestResp.put('https://qrpass-qrpass.tst.icp-1.internet.cloud.lacaixa.es/qrpass/NEMzNzU4MTg1QjM2MzcxQTAxMzYwQ0MzQTYxMjU5QzM3N0Y2OTMzMjZFREExQUYwQ0IyQzE0Q0M3ODMwNUVBOQ==',new EV_ConexionQR_Mock(200));
                
                CC_InterfaceSettings__mdt dataInterface = AV_IntegrationUtilities.fetchMetadataInterface('EV_QRPKPASS');
                header2TestResp.put(String.valueOf(dataInterface.CC_EndPoint__c),new EV_ConexionQR_Mock(200));
                
                if (DomainParser.parse(DomainCreator.getOrgMyDomainHostname()).getSandboxName() == null) {
                    header2TestResp.put('callout:EV_AdobeCampaignPRO',new EV_AdobeCampaignInscripcion_Mock());
                } else {
                    header2TestResp.put('callout:EV_AdobeCampaignPRE',new EV_AdobeCampaignInscripcion_Mock());
                }
                
                HttpCalloutMock multiCalloutMock = new EV_multipleRequestConexionMock_Test(header2TestResp);
                
                Test.setMock(HttpCalloutMock.class, multiCalloutMock);
                campMember = EV_TestHelper.createCampaignMemberCustomContact(false, true);
            
                camp = [SELECT Id, Status, EV_TotalInscritosC__c FROM Campaign WHERE Id = :campMember.EV_CampaignId__c LIMIT 1];
                
                campMember = [SELECT Id, EV_ExternalId__c, EV_Status__c FROM EV_CampaignMemberC__c WHERE Id = :campMember.Id LIMIT 1];
                campMember.EV_Status__c = 'Registro Confirmado';
                update campMember;
                
                EV_CampaignMemberC__c campMember2 = new EV_CampaignMemberC__c();
                campMember2 = EV_TestHelper.createCampaignMemberCustomContact(true, false);
                campMember2.EV_CampaignId__c = camp.Id;
                campMember2.EV_Status__c = 'Registro Confirmado';
                update campMember2;
                
                camp.EV_TotalInscritosC__c = 2;
                update camp;
            }
            Test.stopTest();
                
            System.assertEquals(2, camp.EV_TotalInscritosC__c, 'Total inscritos');
        }
}