force-app/main/default/objects/Campaign/fields/EV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>EV_ExternalID__c</fullName>
    <description>Id externo securizado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_HoraFin__c.field-meta.xml
<CustomField>
    <fullName>EV_HoraFin__c</fullName>
    <description>Hora de finalización del evento</description>
    <label>Hora fin</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>EV_HoraInicio__c</fullName>
    <description>Hora de inicio del evento</description>
    <label>Hora inicio</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EV_Idioma__c.field-meta.xml
<CustomField>
    <fullName>EV_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_IdiomasGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/EV_EventoFisico.recordType-meta.xml
<RecordType>
    <fullName>EV_EventoFisico</fullName>
    <active>true</active>
    <label>Evento físico</label>
</RecordType>

force-app/main/default/objects/EV_TraduccionDeEvento__c/EV_TraduccionDeEvento__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar las traducciones a los distintos idiomas del un evento.</description>
    <label>Traducción de evento</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Traducción Evento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Traducciones de evento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EV_TraduccionDeEvento__c/fields/EV_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>EV_Descripcion__c</fullName>
    <description>Descripcion de evento traducida.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Descripción que aparecerá en portal.</inlineHelpText>
    <label>Descripción</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EV_TraduccionDeEvento__c/fields/EV_Evento__c.field-meta.xml
<CustomField>
    <fullName>EV_Evento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relación directa a evento para registrar una traducción de sus distintos campos</description>
    <label>Evento</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Idiomas_de_Eventos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EV_TraduccionDeEvento__c/fields/EV_Idioma__c.field-meta.xml
<CustomField>
    <fullName>EV_Idioma__c</fullName>
    <description>Idioma del registro al que se traducirán todos los campos</description>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_IdiomasGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/EV_TraduccionDeEventoTriggerHelper_Test.cls
/**********************************************************************************************************************
 Name:	EV_TraduccionDeEventoTriggerHelper_Test
 Copyright © 2022  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito: Clase Test de EV_TraduccionEventosTriggerHelper
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
	VERSION		USER_STORY			AUTHOR				DATE				Description
	1.0			                    Mamen Arias 		28/11/2022			Init version

***********************************************************************************************************************/
@isTest
public with sharing class EV_TraduccionDeEventoTriggerHelper_Test {
    @isTest
	public static void checkInsertTraduccionDuplicada(){
		Id rtEvento = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('EV_EventoFisico').getRecordTypeId();
        User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		Test.startTest();
        System.runAs(newUser){
          	Campaign campFisica = new Campaign(
			Name = 'TestCampaign',
			RecordTypeId = rtEvento,
			EV_ExternalId__c = '1234567895',
			StartDate = Date.today(),
			EV_HoraInicio__c = Time.newInstance(16, 30, 00, 00),
			EV_HoraFin__c = Time.newInstance(19, 30, 00, 00)
			); 
            insert campFisica;
    
            EV_TestHelper.createTraduccionesDeEvento(campFisica.Id);
    
            EV_TraduccionDeEvento__c traduccion3 = new EV_TraduccionDeEvento__c(
                Name = 'Traduccion castellano 2',
                EV_Evento__c = campFisica.Id,
                EV_Idioma__c = '002',
                EV_Descripcion__c = 'Traduccion castellano test, Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test,Traduccion castellano test'
            );
            try{
                insert traduccion3;
            } catch (Exception e){
                Test.stopTest();
                System.assertEquals(e.getMessage().contains('Ya existe una traducción con ese idioma. Es necesario eliminar la anterior para crear una nueva.'), true);
            }
        }
	}

	@isTest
	public static void checkUpdateTraduccion(){
		Id rtEvento = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('EV_EventoFisico').getRecordTypeId();

        User newUser = EV_TestHelper.createUserTest('EV_Governance_Eventos','System Administrator','Eventos');
		Test.startTest();
        System.runAs(newUser){
            Campaign campFisica = new Campaign(
			Name = 'TestCampaign',
			RecordTypeId = rtEvento,
			EV_ExternalId__c = '1234567895',
			StartDate = Date.today(),
			EV_HoraInicio__c = Time.newInstance(16, 30, 00, 00),
			EV_HoraFin__c = Time.newInstance(19, 30, 00, 00)
			); 
            insert campFisica;
            List<EV_TraduccionDeEvento__c> listTraducciones = EV_TestHelper.createTraduccionesDeEvento(campFisica.Id);
            EV_TraduccionDeEvento__c traduccion2 = listTraducciones[1];
            traduccion2.EV_Idioma__c = '002';
    
            try{
                update traduccion2;
            } catch (Exception e){
                Test.stopTest();
                System.assertEquals(e.getMessage().contains('Ya existe una traducción con ese idioma. Es necesario eliminar la anterior para crear una nueva.'), true);
            }
        }
	}
}