force-app/main/default/objects/Case/fields/CBK_Case_Extension_Id__c.field-meta.xml
<CustomField>
    <fullName>CBK_Case_Extension_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Field to Case Extension object</description>
    <label>Case Extension Id</label>
    <referenceTo>CBK_Case_Extension__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_FechaRecepcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaRecepcion__c</fullName>
    <description>Fecha de recepción de la reclamación</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha recepción</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_FechaVencimientoSLA__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaVencimientoSLA__c</fullName>
    <description>Campo que se rellena con la fecha limite del SLA Regulatorio</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha vencimiento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_TipoConsumidor__c.field-meta.xml
<CustomField>
    <fullName>SAC_TipoConsumidor__c</fullName>
    <label>Consumidor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
                <label>Sí</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_DiasProrroga__c.field-meta.xml
<CustomField>
    <fullName>SPV_DiasProrroga__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Campo que almacena los días de prorroga de la reclamación de SPV</description>
    <label>Días prórroga</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_Organismo__c.field-meta.xml
<CustomField>
    <fullName>SPV_Organismo__c</fullName>
    <description>Campo para informar el organismo al que pertenecen los casos de SPV</description>
    <label>Organismo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV_CNMV</fullName>
                <label>CNMV</label>
            </value>
            <value>
                <fullName>SPV_DGS</fullName>
                <label>DGS</label>
            </value>
            <value>
                <fullName>SPV_Consumo</fullName>
                <label>Consumo</label>
            </value>
            <value>
                <fullName>SPV_BDE</fullName>
                <label>BDE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/SAC_Pretension.recordType-meta.xml
<RecordType>
    <fullName>SAC_Pretension</fullName>
    <active>true</active>
    <businessProcess>SAC_SupportProcessPretension</businessProcess>
    <description>Record type para proyecto SAC - pretension</description>
    <label>Pretension</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SAC_Reclamacion.recordType-meta.xml
<RecordType>
    <fullName>SAC_Reclamacion</fullName>
    <active>true</active>
    <businessProcess>SAC_Support Process</businessProcess>
    <description>Reclamación equipo SAC</description>
    <label>Reclamacion</label>
</RecordType>

force-app/main/default/objects/CBK_Case_Extension__c/CBK_Case_Extension__c.object-meta.xml
<CustomObject>
    <description>Extension Object related to Case object</description>
    <label>Case Extension</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Extension</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SPV_MilestonePlazoRegAnalisis.cls
public with sharing class SPV_MilestonePlazoRegAnalisis implements Support.MilestoneTriggerTimeCalculator {
    //Obtener record Type
    Set<String> objetos = new Set<String>{'Case'};
    Map<String, Map<String,Schema.RecordTypeInfo>> mapRTsObjects = SPV_Utils.getRecordTypesObjects(objetos);
    Id recTypeReclamacion = mapRTsObjects.get('Case').get('SAC_Reclamacion').getRecordTypeId();
    Id recTypePretension = mapRTsObjects.get('Case').get('SAC_Pretension').getRecordTypeId();

    public Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId){
        Integer tiempo = 21600; // 15 días naturales
        Case caso;
        Id ideBH;
        Datetime fechaFin;
        Datetime fechaInicial; 

        if (Schema.sObjectType.Case.isAccessible()) {
            caso = [SELECT Id, CreatedDate, RecordTypeId, CBK_Case_Extension_Id__r.SPV_FechaAnalisisDecision__c, SAC_TipoConsumidor__c, SPV_Organismo__c, SAC_FechaRecepcion__c, SAC_FechaVencimientoSLA__c, SPV_DiasProrroga__c, CBK_Case_Extension_Id__r.SPV_MotivoAnulacionProrroga__c, CBK_Case_Extension_Id__r.SPV_FechaAnulacionProrroga__c FROM Case WHERE Id = :caseId];

            if (Cache.Org.contains('local.SAC.SACCalendario')) {
                String calend = (String)Cache.Org.get('local.SAC.SACCalendario');
                ideBH = Id.valueOf(calend);
            }
            else{
                ideBH = [SELECT Id, name FROM BusinessHours where name ='SPV_Calendario'].id;
                Cache.Org.put('local.SAC.SACCalendario', String.valueOf(ideBH),300);
            }

            
            fechaInicial = calcularFechaInicial(caso);
            fechaInicial = fechaInicial.addDays(1);

            // Si NO es organismo Consumo
            if(caso.SPV_Organismo__c != 'SPV_Consumo') {
                if(caso.SAC_TipoConsumidor__c == 'Si') {
                    fechaFin = fechaInicial.addDays(21); 
                } else {
                    fechaFin = BusinessHours.add(ideBH, fechaInicial, calcularMilisegundos(15));
                }
            // Si es organismo Consumo
            } else {
                if(caso.SAC_FechaVencimientoSLA__c != null) {
                    fechaFin = caso.SAC_FechaVencimientoSLA__c.addDays(1);
                }
            }

            if(fechaFin != null) {
                //Añade los días correspondientes en caso de que se haya prorrogado la reclamación y no se haya anulado la prórroga
                if(caso.SPV_DiasProrroga__c != 0 && caso.CBK_Case_Extension_Id__r.SPV_MotivoAnulacionProrroga__c == null) {
                    fechaFin = fechaFin.addDays(caso.SPV_DiasProrroga__c.intValue());   
                } 
            
                //Añade los minutos necesarios a la fecha fin del SLA regulatorio para que siempre acabe a las 23:59 del día de finalización
                Integer minutosDiaCompleto = SPV_Utils.minutosHastaMedianoche(fechaFin);
                fechaFin = fechaFin.addMinutes(minutosDiaCompleto);
                Long restaTiempo = fechaFin.getTime() - fechaInicial.getTime();
                tiempo = (restaTiempo / 60000).intValue(); 
            }   
        }
        
        return tiempo;
    }

    public Datetime calcularFechaInicial(Case caso) {
        Datetime fechaInicial; 
        if(caso.CBK_Case_Extension_Id__r.SPV_FechaAnalisisDecision__c == null){
            fechaInicial = CBK_UtilsDate.nowSYS();
        }else{
            fechaInicial = caso.CBK_Case_Extension_Id__r.SPV_FechaAnalisisDecision__c;
        }
        return fechaInicial;
    }


    public Long calcularMilisegundos(Integer dias) {
        Long milisegundos = dias * 24 * 60 * 60 * 1000L;
        return milisegundos;
    }
}