force-app/main/default/objects/Case/fields/CC_Agrupador_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Agrupador_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agrupador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Agrupador__c.CC_Publica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Agrupador__c.CC_Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_Agrupador__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Causa__c.field-meta.xml
<CustomField>
    <fullName>CC_Causa__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Causa (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Causa__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Causa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Causa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Causa</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Causa)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Motivo (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Contacto__c</fullName>
    <description>Campo para indicar que tipo de contacto tiene el caso.</description>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_TipoContacto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/CC_Agrupador__c.object-meta.xml
<CustomObject>
    <label>Agrupador</label>
    <nameField>
        <displayFormat>GRP-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Causa__c.field-meta.xml
<CustomField>
    <fullName>CC_Causa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Causa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CC_Causa</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_Motivo__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Motivo__c</valueField>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Agrupadores (Causa)</relationshipLabel>
    <relationshipName>CC_Agrupadores_Causa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CC_Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_Producto_Servicio__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Agrupadores (Motivo)</relationshipLabel>
    <relationshipName>Agrupadores2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa</fullName>
    <active>true</active>
    <label>Comunicación Informativa</label>
</RecordType>

force-app/main/default/objects/CC_Caracteristica__c/CC_Caracteristica__c.object-meta.xml
<CustomObject>
    <label>Característica</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Características</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Caracteristica__c/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <formula>IF( ( NOT(ISBLANK(CC_Fecha_vigencia_fin__c)) &amp;&amp; NOW() &gt;= CC_Fecha_vigencia_inicio__c &amp;&amp; NOW() &lt; CC_Fecha_vigencia_fin__c ) || ( ISBLANK(CC_Fecha_vigencia_fin__c) &amp;&amp; NOW() &gt;= CC_Fecha_vigencia_inicio__c ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica__c/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Característica de Empleado</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <formula>IF( ( NOT(ISBLANK(CC_Fecha_Vigencia_Fin__c)) &amp;&amp; NOW() &gt;= CC_Fecha_Vigencia_Inicio__c &amp;&amp; NOW() &lt; CC_Fecha_Vigencia_Fin__c ) || ( ISBLANK(CC_Fecha_Vigencia_Fin__c) &amp;&amp; NOW() &gt;= CC_Fecha_Vigencia_Inicio__c ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Causa__c.field-meta.xml
<CustomField>
    <fullName>CC_Causa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Causa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Causa</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Soluciones</relationshipLabel>
    <relationshipName>CC_Soluciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Desviacion_Media_LV__c.field-meta.xml
<CustomField>
    <fullName>CC_Desviacion_Media_LV__c</fullName>
    <label>Desviación media de días laborales (L-V)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Desviacion_Media_SD__c.field-meta.xml
<CustomField>
    <fullName>CC_Desviacion_Media_SD__c</fullName>
    <label>Desviación media fin de semana (S-D)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Causas</relationshipLabel>
    <relationshipName>CC_MCC_Causas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC_Causa__c/CC_MCC_Causa__c.object-meta.xml
<CustomObject>
    <label>MCC Causa</label>
    <nameField>
        <displayFormat>MCC-Causa-{000000}</displayFormat>
        <label>MCC Causa Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MCC Causas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC_Causa__c/fields/CC_MCC_Causa__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Causa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Causa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Causa</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Causas</relationshipLabel>
    <relationshipName>MCC_Causas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC_Causa__c/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <label>Motivo</label>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Causas</relationshipLabel>
    <relationshipName>CC_Motivos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CC_Prevision__c/CC_Prevision__c.object-meta.xml
<CustomObject>
    <label>Previsión</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Previsión Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Previsiones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Prevision__c/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo utilizado para saber si esta activo el registro</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Prevision__c/fields/CC_MCC__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo utilizado para relacionar con el objeto MCC</description>
    <label>MCC</label>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Previsiones</relationshipLabel>
    <relationshipName>Previsiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Prevision__c/fields/CC_Tipo_Dia__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Dia__c</fullName>
    <description>Campo utilizado para saber si el registro es L-V o S-D</description>
    <label>Tipo de día</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lunes a viernes</fullName>
                <default>true</default>
                <label>Lunes a viernes</label>
            </value>
            <value>
                <fullName>Sábado y domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_Agrupador_CI_Asignacion_Casos.cls
public with sharing class CC_Agrupador_CI_Asignacion_Casos {

    @InvocableMethod
    public static void asociarCasosAComunicacionInformativa(List<Id> idsCasos) {

        DateTime dt = DateTime.now();
		Long dateInMilliseconds = dt.getTime();
		
		try {
			asociarCasosAComunicacionInformativaQueueable asociarCasos = new asociarCasosAComunicacionInformativaQueueable();
            List<Id> idsCasosList = idsCasos;
		    asociarCasos.setParams(idsCasosList);

            AsyncOptions options = new AsyncOptions();
                options.DuplicateSignature = 
                QueueableDuplicateSignature.Builder()
                                .addId(UserInfo.getUserId())
                                .addString(String.valueOf(dateInMilliseconds))
                                .build();

            Integer jobsInProgress = [SELECT COUNT()
                                      FROM AsyncApexJob 
                                      WHERE ApexClass.Name ='CC_Agrupador_CI_Asignacion_Casos' AND JobType = 'Queueable' AND Status IN ('Processing', 'Queued')];
            
            if(jobsInProgress > 0){
                Integer randomInt = Integer.valueof((Math.random() * 10));
                options.MinimumQueueableDelayInMinutes = randomInt;
            }
          
            System.enqueueJob(asociarCasos, options);
		
		} catch (DuplicateMessageException ex) {
			//Exception is thrown if there is already an enqueued job with the same signature
            CBK_log.debug('CC_Agrupador_CI_Asignacion_Casos.asociarCasosAComunicacionInformativa: ' + ex);
        }
    }

    public class asociarCasosAComunicacionInformativaQueueable implements Queueable {
     
        private List<Id> idsCasos;
		
		public void setParams(List<Id> idsCasos) {
			this.idsCasos = idsCasos;
		}

		public void execute(QueueableContext context) {        

           	asociarCasosAComunicacionInformativaNoFuture(idsCasos);
    	}

	}

    private static Boolean evaluarPrevisionesCasosFuture(Set<Id> idCausas, Boolean finDeSemana, Integer horaInicioFranja) {
        Boolean crearAgrupador = false;
        for (Id idCausa : idCausas) {
            PrevisionCasos previsionCasos = new PrevisionCasos(idCausa, finDeSemana);
            crearAgrupador = previsionCasos.evaluarPrevisionFranja(horaInicioFranja, finDeSemana);
        }
        return crearAgrupador;
    }

    private with sharing class PrevisionCasos {
        Id idCausa;
        Boolean finDeSemana;
        Map<Integer, Decimal> previsionFranjas;

        PrevisionCasos(Id idCausa, Boolean finDeSemana) {
            String query = '';
            for (Integer i = 0; i < 24; i++) {
                query += ' CC_' + String.valueOf(i).leftPad(2, '0') + '__c,';
            }
            query = 'SELECT' + query.removeEnd(',') + ' FROM CC_Prevision__c WHERE CC_Activo__c = TRUE AND CC_MCC__c = :idCausa AND CC_Tipo_Dia__c = :tipoDia LIMIT 1';
            Map<String, Object> queryBinds = new Map<String, Object>{'idCausa' => idCausa, 'tipoDia' => finDeSemana ? 'Sábado y domingo' : 'Lunes a viernes'};

            CC_Prevision__c prevision = Database.queryWithBinds(query, queryBinds, AccessLevel.USER_MODE) ?? null;
            if (prevision != null) {
                this.idCausa = idCausa;
                this.finDeSemana = finDeSemana;
                this.previsionFranjas = new Map<Integer, Decimal>();
                for (Integer i = 0; i < 24; i++) {
                    previsionFranjas.put(i, (Decimal)prevision.get('CC_' + String.valueOf(i).leftPad(2, '0') + '__c'));
                }
            }
        }

        public Boolean evaluarPrevisionFranja(Integer horaIniciofranja, Boolean finDeSemana) {

            Boolean crearAgrupador = false;
            if (previsionFranjas != null) {

                Decimal previsionCasos = this.previsionFranjas.get(horaInicioFranja) ?? 0;
                Date hoy = System.today();

                // Recuperar la volumetría de casos con esa causa
                Integer numCasosPrevision = [SELECT COUNT() FROM Case WHERE Status = 'Cerrado' AND RecordType.DeveloperName = 'CC_Cliente'
                                            AND CC_MCC_Causa__c = :this.idCausa AND CreatedDate = TODAY AND CC_Tipo_Contacto__c != 'Incidencia' AND CC_Agrupador_Id__c = null
                                            AND ClosedDate <= :Datetime.newInstance(hoy.year(), hoy.month(), hoy.day(), horaInicioFranja, 0, 0).addHours(1)];

                // Recuperar la configuración del MCC.
                List<CC_MCC__c> mccsCausa = [SELECT Id, CC_Desviacion_Media_SD__c, CC_Desviacion_Media_LV__c FROM CC_MCC__c WHERE Id = :this.idCausa];

                    if (!mccsCausa.isEmpty()){
                        // Determinar la creación del agrupador. 
                        if(numCasosPrevision > previsionCasos) {

                            if (previsionCasos == 0) {
                                crearAgrupador = true;
                            }else{
                                Decimal porcentajeCasosSobrante = (finDeSemana == true) ? (previsionCasos * mccsCausa[0].CC_Desviacion_Media_SD__c) / 100 : (previsionCasos * mccsCausa[0].CC_Desviacion_Media_LV__c) / 100;
                                crearAgrupador = (numCasosPrevision > previsionCasos + porcentajeCasosSobrante) ? true : crearAgrupador;
                            }
                        }
                    }
            }
            return crearAgrupador;
        }
    }


    public static Map<Id, List<Case>> casosExistentesEmpleadosSinAgrupar(List<Id> casesActuales, Map<Id, List<Case>> mapCausaCasosEmpleados){
        Id rtEmpleado = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'CC_Empleado');
     
        List<Case> casosExistentes = [
            SELECT Id, CC_MCC_Tematica__c, CC_MCC_ProdServ__c, CC_MCC_Motivo__c, CC_MCC_Causa__c,
            CC_MCC_Tematica__r.Name, CC_MCC_ProdServ__r.Name, CC_MCC_Motivo__r.Name, CC_MCC_Causa__r.Name,
            CC_Comunicacion_Informativa__c, CC_Admin__c,  CC_Campana__c, CC_Campana__r.Name, RecordTypeId
            FROM Case WHERE CC_MCC_Tematica__r.CC_Activo__c = TRUE
            AND CC_MCC_ProdServ__R.CC_Activo__c = TRUE
            AND CC_MCC_Motivo__R.CC_Activo__c = TRUE
            AND CC_MCC_Causa__R.CC_Activo__c = TRUE 
            AND Id NOT IN :casesActuales
            AND CC_Comunicacion_Informativa__c = NULL 
            AND CreatedDate = TODAY
            AND Status = 'Cerrado'
            AND CC_Tipo_Contacto__c != 'Incidencia'
            AND RecordTypeId =: rtEmpleado
            AND CC_MCC_Causa__c IN: mapCausaCasosEmpleados.keySet()
            FOR UPDATE];
     
        for(Case caseExist : casosExistentes){
            mapCausaCasosEmpleados.get(caseExist.CC_MCC_Causa__c).add(caseExist);
        }

        return mapCausaCasosEmpleados;
      
    }

    public static CC_Agrupador__c crearAgrupador(Case casoConMismaCausa){
        String recordTypeDeveloperName = 'CC_Comunicacion_Informativa';
        CC_Agrupador__c comunicacionInformativaNueva = new CC_Agrupador__c();
        Id comunicacionInformativaCampanaRecordTypeId = Schema.SObjectType.CC_Agrupador__c.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId();
        comunicacionInformativaNueva.RecordTypeId = comunicacionInformativaCampanaRecordTypeId;
        comunicacionInformativaNueva.CC_Estado__c = 'Activo';
        comunicacionInformativaNueva.CC_Titulo__c = casoConMismaCausa.CC_MCC_Tematica__r.Name + ' > ' + casoConMismaCausa.CC_MCC_ProdServ__r.Name + ' > ' + casoConMismaCausa.CC_MCC_Motivo__r.Name + ' > ' + casoConMismaCausa.CC_MCC_Causa__r.Name;
        comunicacionInformativaNueva.CC_Tematica_Id__c = casoConMismaCausa.CC_MCC_Tematica__c;
        comunicacionInformativaNueva.CC_Producto_Servicio__c = casoConMismaCausa.CC_MCC_ProdServ__c;
        comunicacionInformativaNueva.CC_Motivo__c = casoConMismaCausa.CC_MCC_Motivo__c;
        comunicacionInformativaNueva.CC_Causa__c = casoConMismaCausa.CC_MCC_Causa__c;

        return comunicacionInformativaNueva;
    }

    public static void asociarCasosAComunicacionInformativaNoFuture(List<Id> idsCasos) {
        Boolean crearAgrupador = false;
        List<Case> casosActualizar = new List<Case>();
        List<Case> lstCasosConMismaCausa = new List<Case>();
        Map<Id,CC_Agrupador__c> comunicacionesInformativasInsertar = new Map<Id,CC_Agrupador__c>();
        List<CC_Agrupador__c> comunicacionesInformativasExistentes = new List<CC_Agrupador__c>();
        Map<String, String> mapAgrupadorCausa = new Map<String, String>();
        Map<Id, List<Case>> mapCausaCasos = new Map<Id, List<Case>>();
        Map<Id, List<Case>> mapCausaCasosEmpleados = new Map<Id, List<Case>>();

        String umbralPrimerAvisoString = [SELECT CC_Valor__c FROM CC_Lista_Valores__c WHERE CC_Lista__r.Name = 'Avisos sobre agrupadores' AND Name = :CC_MetodosUtiles.getRecordTypeNameFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa') + ' - Umbral primer aviso'].CC_Valor__c;
        Integer umbralPrimerAviso = Integer.valueOf(umbralPrimerAvisoString);
		Id rtCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'CC_Cliente');
        Id rtEmpleado = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'CC_Empleado');

        lstCasosConMismaCausa = [SELECT Id, CC_MCC_Tematica__c, CC_MCC_ProdServ__c, CC_MCC_Motivo__c, CC_MCC_Causa__c,
                                     CC_MCC_Tematica__r.Name, CC_MCC_ProdServ__r.Name, CC_MCC_Motivo__r.Name, CC_MCC_Causa__r.Name,
                                     CC_Comunicacion_Informativa__c, CC_Admin__c,  CC_Campana__c, CC_Campana__r.Name, RecordTypeId
                                     FROM Case WHERE CC_MCC_Tematica__r.CC_Activo__c = TRUE
                                     AND CC_MCC_ProdServ__R.CC_Activo__c = TRUE
                                     AND CC_MCC_Motivo__R.CC_Activo__c = TRUE
                                     AND CC_MCC_Causa__R.CC_Activo__c = TRUE 
                                     AND Id IN :idsCasos
                                     FOR UPDATE];

        if(lstCasosConMismaCausa.isEmpty()){
            return;
        }

        for (Case casoConMismaCausa : lstCasosConMismaCausa) {
            if(casoConMismaCausa.RecordTypeId == rtCliente){             
                if(!mapCausaCasos.containsKey(casoConMismaCausa.CC_MCC_Causa__c)) {
                    mapCausaCasos.put(casoConMismaCausa.CC_MCC_Causa__c, new List<Case>());                 
                }              
                mapCausaCasos.get(casoConMismaCausa.CC_MCC_Causa__c).add(casoConMismaCausa);
            } else{
                if(!mapCausaCasosEmpleados.containsKey(casoConMismaCausa.CC_MCC_Causa__c)) {
                    mapCausaCasosEmpleados.put(casoConMismaCausa.CC_MCC_Causa__c, new List<Case>());                 
                }              
                mapCausaCasosEmpleados.get(casoConMismaCausa.CC_MCC_Causa__c).add(casoConMismaCausa);            
            }            
        }  

        mapCausaCasosEmpleados = casosExistentesEmpleadosSinAgrupar(idsCasos, mapCausaCasosEmpleados);

        String hoyDiaSemana = System.now().format('E');
        //Esto aplica para CC_Cliente
        crearAgrupador = evaluarPrevisionesCasosFuture(mapCausaCasos.keySet(), hoyDiaSemana == 'Sat' || hoyDiaSemana == 'Sun', System.now().hour());

        comunicacionesInformativasExistentes = [SELECT Id, CC_Campana__c, CC_Causa__c  FROM CC_Agrupador__c WHERE RecordType.DeveloperName = 'CC_Comunicacion_Informativa' AND CC_Estado__c = 'Activo' AND (CC_Causa__c IN :mapCausaCasos.keySet() OR CC_Causa__c IN :mapCausaCasosEmpleados.keySet())  AND CreatedDate = TODAY];

        if (!comunicacionesInformativasExistentes.isEmpty()) {
                   
            for (CC_Agrupador__c comunicacionExistente : comunicacionesInformativasExistentes) {
                mapAgrupadorCausa.put(comunicacionExistente.CC_Causa__c , comunicacionExistente.Id);
            }
        }
        
        for (Case casoConMismaCausa : lstCasosConMismaCausa) {       

            if(mapAgrupadorCausa.containsKey(casoConMismaCausa.CC_MCC_Causa__c) && casoConMismaCausa.CC_Comunicacion_Informativa__c == null)
            {
                casoConMismaCausa.CC_Comunicacion_Informativa__c = mapAgrupadorCausa.get(casoConMismaCausa.CC_MCC_Causa__c);
                casoConMismaCausa.CC_Admin__c = true;
                casosActualizar.add(casoConMismaCausa);
            }
            else if (mapAgrupadorCausa.containsKey(casoConMismaCausa.CC_MCC_Causa__c) && casoConMismaCausa.CC_Comunicacion_Informativa__c != mapAgrupadorCausa.get(casoConMismaCausa.CC_MCC_Causa__c)) {
                casoConMismaCausa.CC_Comunicacion_Informativa__c = mapAgrupadorCausa.get(casoConMismaCausa.CC_MCC_Causa__c);
                casoConMismaCausa.CC_Admin__c = true;
                casosActualizar.add(casoConMismaCausa);
            }
            else if(!mapAgrupadorCausa.containsKey(casoConMismaCausa.CC_MCC_Causa__c)){
                if(casoConMismaCausa.RecordTypeId == rtCliente && crearAgrupador) {

                    if(!comunicacionesInformativasInsertar.containsKey(casoConMismaCausa.CC_MCC_Causa__c)){
                        CC_Agrupador__c comunicacionInformativaNueva = crearAgrupador(casoConMismaCausa);
                        comunicacionesInformativasInsertar.put(casoConMismaCausa.CC_MCC_Causa__c, comunicacionInformativaNueva);
                    }                

                } else if(casoConMismaCausa.RecordTypeId == rtEmpleado){
                    if (mapCausaCasosEmpleados.get(casoConMismaCausa.CC_MCC_Causa__c).size() >= umbralPrimerAviso) {

                        if(!comunicacionesInformativasInsertar.containsKey(casoConMismaCausa.CC_MCC_Causa__c)){
                            CC_Agrupador__c comunicacionInformativaNueva = crearAgrupador(casoConMismaCausa);
                            comunicacionesInformativasInsertar.put(casoConMismaCausa.CC_MCC_Causa__c, comunicacionInformativaNueva);
                        }       
                    } 
                }
            }
        }

        if(!comunicacionesInformativasInsertar.isEmpty()){

            List<Database.SaveResult> resultadosInsertados = CBK_DMLUtility.insertRecords(comunicacionesInformativasInsertar.values(), false);
            
            for (CC_Agrupador__c agrupadorInsertado : comunicacionesInformativasInsertar.values()) {
                if(agrupadorInsertado.Id != null){
                    List<Case> casosAProcesar = new List<Case>();
                    if(mapCausaCasos.containsKey(agrupadorInsertado.CC_Causa__c)){
                        casosAProcesar.addAll(mapCausaCasos.get(agrupadorInsertado.CC_Causa__c));
                    }
                    if(mapCausaCasosEmpleados.containsKey(agrupadorInsertado.CC_Causa__c)){
                        casosAProcesar.addAll(mapCausaCasosEmpleados.get(agrupadorInsertado.CC_Causa__c));
                    }
                    for (Case casoAgrupado : casosAProcesar) {
                        casoAgrupado.CC_Comunicacion_Informativa__c = agrupadorInsertado.Id;
                        casoAgrupado.CC_Admin__c = true;
                        casosActualizar.add(casoAgrupado);
                    }
                }
            }
        }
 
        if(!casosActualizar.isEmpty() && Schema.sObjectType.Case.fields.CC_Comunicacion_Informativa__c.isUpdateable() &&  Schema.sObjectType.Case.fields.CC_Admin__c.isUpdateable()){   
            update casosActualizar;
        }
        
        for (Case casoActualizar : casosActualizar) {
            casoActualizar.CC_Admin__c = false;
        }
        update casosActualizar;
        
    }
}