force-app/main/default/objects/Case/fields/CC_Agrupador_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Agrupador_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agrupador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Agrupador__c.CC_Publica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Agrupador__c.CC_Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_Agrupador__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/HDT_Empleado.recordType-meta.xml
<RecordType>
    <fullName>HDT_Empleado</fullName>
    <active>true</active>
    <businessProcess>HDT_Empleados</businessProcess>
    <label>Empleado (HDT)</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HDT_Parametros__c/HDT_Parametros__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>HDT_Parametros</label>
</CustomObject>

force-app/main/default/objects/HDT_Parametros__c/fields/HDT_Configuracion_1__c.field-meta.xml
<CustomField>
    <fullName>HDT_Configuracion_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Configuración_1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HDT_Asociar_Casos_Masivas.cls
public with sharing class HDT_Asociar_Casos_Masivas {

    @AuraEnabled(cacheable=true)
    public static List<Case> buscarCasos(String cadenaBusqueda) {
        return [SELECT CaseNumber, Subject, CreatedDate, CC_MCC_Tematica__r.Name, Status
                FROM Case WHERE CaseNumber LIKE :(cadenaBusqueda + '%') AND Status = 'Activo'
                AND RecordType.DeveloperName = 'HDT_Empleado'
                ORDER BY CreatedDate DESC LIMIT 10];
    }

    @AuraEnabled
    public static void vincularCasos(Id idAgrupador, List<Id> idCasos) {
        List<Case> casosUpdate = new List<Case>();
        try {
            for (Id idCaso : idCasos) {
                Case caso = new Case(Id = idCaso);
                caso.CC_Agrupador_Id__c = idAgrupador;
                caso.Status = 'Pendiente Incidencia';
                casosUpdate.add(caso);
            }
            Database.update(casosUpdate, true);

        } catch (Exception e) {
            CBK_Log.error(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Integer numeroMaximoCasosAsociados() {
        List<HDT_Parametros__c> parametro =  [SELECT HDT_Configuracion_1__c FROM HDT_Parametros__c WHERE Name = 'HDT_Casos_Asociados_Maximo'];
        return Integer.valueOf(parametro[0].HDT_Configuracion_1__c);
    }
}