force-app/main/default/objects/Case/fields/CC_Agrupador_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Agrupador_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agrupador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Agrupador__c.CC_Publica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Agrupador__c.CC_Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_Agrupador__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_CanalNotifCli__c.field-meta.xml
<CustomField>
    <fullName>CC_CanalNotifCli__c</fullName>
    <defaultValue>&quot;Email&quot;</defaultValue>
    <description>Canal para enviar la notificación de seguimiento al cliente</description>
    <inlineHelpText>Canal para enviar la notificación de seguimiento al cliente</inlineHelpText>
    <label>Canal notificación cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_NotIncidencia__c.field-meta.xml
<CustomField>
    <fullName>CC_NotIncidencia__c</fullName>
    <description>Indicador del estado de envío de la notificación de incidencia</description>
    <inlineHelpText>Indicador del estado de envío de la notificación de incidencia</inlineHelpText>
    <label>Notificar incidencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_EstadoEnvioNotif</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/CC_Agrupador__c.object-meta.xml
<CustomObject>
    <label>Agrupador</label>
    <nameField>
        <displayFormat>GRP-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Estado__c.field-meta.xml
<CustomField>
    <fullName>CC_Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Pendiente Revision</fullName>
                <label>Pendiente revisión solución</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Fecha_Asociacion_Caso__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Asociacion_Caso__c</fullName>
    <description>Guarda el valor de la fecha en la que se vincula a un agrupador un segundo o tercer caso.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha asociación caso</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Fecha_creacion_MAXIMO__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_creacion_MAXIMO__c</fullName>
    <description>Fecha en la que se crea el MAXIMO</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha creación MAXIMO</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Notificar_Clientes__c.field-meta.xml
<CustomField>
    <fullName>CC_Notificar_Clientes__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notificar cierre a clientes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Numero_Casos__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Casos__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Número de casos</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa</fullName>
    <active>true</active>
    <label>Comunicación Informativa</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa_de_Campana.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa_de_Campana</fullName>
    <active>true</active>
    <label>Comunicación Informativa de Campaña</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa_de_Marca.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa_de_Marca</fullName>
    <active>true</active>
    <label>Comunicación Informativa de Marca</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Incidencia.recordType-meta.xml
<RecordType>
    <fullName>CC_Incidencia</fullName>
    <active>true</active>
    <label>Incidencia</label>
</RecordType>

force-app/main/default/objects/CC_PlantillaAsociada__c/CC_PlantillaAsociada__c.object-meta.xml
<CustomObject>
    <description>Plantilla asociada a un objeto</description>
    <label>Plantilla asociada</label>
    <nameField>
        <displayFormat>NF-{0000000000}</displayFormat>
        <label>Plantilla</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plantillas asociadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_PlantillaAsociada__c/fields/CC_Agrupador__c.field-meta.xml
<CustomField>
    <fullName>CC_Agrupador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Agrupador asociado</description>
    <inlineHelpText>Agrupador asociado</inlineHelpText>
    <label>Agrupador</label>
    <referenceTo>CC_Agrupador__c</referenceTo>
    <relationshipLabel>Notificaciones cierre</relationshipLabel>
    <relationshipName>CC_AgrPlantillas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_PlantillaAsociada__c/fields/CC_Canal__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal__c</fullName>
    <description>Canal de comunicación</description>
    <inlineHelpText>Canal de comunicación</inlineHelpText>
    <label>Canal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Canal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_PlantillaAsociada__c/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <description>Idioma para la comunicación</description>
    <inlineHelpText>Idioma para la comunicación</inlineHelpText>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_PlantillaAsociada__c/fields/CC_Revisada__c.field-meta.xml
<CustomField>
    <fullName>CC_Revisada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Revisada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_PlantillaAsociada__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo Cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Empleado Bankia</fullName>
            </value>
            <value>
                <fullName>Empleado (HDT)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_Agrupador_BU_TRHan.cls
public class CC_Agrupador_BU_TRHan extends CC_TriggerHandlerBase {
    
    public override void mainEntry(CC_TriggerParameters tp) {
        process((Map<Id, CC_Agrupador__c>)tp.oldMap, (Map<Id, CC_Agrupador__c>)tp.newMap, (List<CC_Agrupador__c>)tp.newList);
    }

    private void process(Map<Id, CC_Agrupador__c> mapOldObj, Map<Id, CC_Agrupador__c> mapNewObj, List<CC_Agrupador__c> listNewObj) {
        cierreAgrupadores(mapOldObj, mapNewObj);
        actualizarFechaAsociacion(mapOldObj, listNewObj);
    }

    private void cierreAgrupadores(Map<Id, CC_Agrupador__c> mapOldObj, Map<Id, CC_Agrupador__c> mapNewObj) {
        //Comprobar si se está cerrando alguno de los agrupadores modificados (no aplican
        //agrupadores de tipo Comunicación Informativa ni agrupadores sin notificación de cierre)
        Map<Id, CC_Agrupador__c> agrupadoresCerrados = recuperarAgrupadoresCerrados(mapOldObj, mapNewObj);

        if (!agrupadoresCerrados.isEmpty()) { //Hay agrupadores cerrados

            //Se prepara un mapa con las plantillas que cada agrupador necesita en función de sus casos
            Map<Id, List<CC_Agrupador_BU_TRHan.PlantillaRequerida>> plantillasRequeridas = new Map<Id, List<CC_Agrupador_BU_TRHan.PlantillaRequerida>>();

            for (AggregateResult aggregateResult : [SELECT CC_Agrupador_Id__c, CC_CanalNotifCli__c, CC_Idioma__c, RecordTypeId
                                                    FROM Case WHERE CC_NotIncidencia__c = '1' AND CC_Agrupador_Id__c IN :agrupadoresCerrados.keySet()
                                                    GROUP BY CC_Agrupador_Id__c, CC_CanalNotifCli__c, CC_Idioma__c, RecordTypeId]) {
                
                CC_Agrupador_BU_TRHan.PlantillaRequerida plantillaRequerida = new CC_Agrupador_BU_TRHan.PlantillaRequerida();
                plantillaRequerida.tipoCliente = Schema.SObjectType.Case.getRecordTypeInfosById().get((Id)aggregateResult.get('RecordTypeId')).getName();
                plantillaRequerida.canal = String.valueOf(aggregateResult.get('CC_CanalNotifCli__c'));
                plantillaRequerida.idioma = String.valueOf(aggregateResult.get('CC_Idioma__c'));
                plantillaRequerida.estado = EstadoPlantilla.SIN_ASOCIAR;

                String idAgrupadorCaso = String.valueOf(AggregateResult.get('CC_Agrupador_Id__c'));
                if (!plantillasRequeridas.containsKey(idAgrupadorCaso)) {
                    plantillasRequeridas.put(idAgrupadorCaso, new List<CC_Agrupador_BU_TRHan.PlantillaRequerida>{plantillaRequerida});
                } else {
                    plantillasRequeridas.get(idAgrupadorCaso).add(plantillaRequerida);
                }
            }

            //Se quitan del mapa las plantillas que SÍ tiene cada agrupador y se marcan las que no están revisadas
            for (CC_PlantillaAsociada__c plantillaAsociada : [SELECT CC_Agrupador__c, CC_Canal__c, CC_Idioma__c, CC_Tipo_Cliente__c, CC_Revisada__c FROM CC_PlantillaAsociada__c
                                                                WHERE CC_Agrupador__c IN :agrupadoresCerrados.keySet()]) {
                
                if (plantillasRequeridas.get(plantillaAsociada.CC_Agrupador__c) == null) continue;

                Integer indice = indicePlantilla(plantillaAsociada, plantillasRequeridas.get(plantillaAsociada.CC_Agrupador__c));
                
                if (indice != -1) {
                    List<PlantillaRequerida> listaPlantillas = plantillasRequeridas.get(plantillaAsociada.CC_Agrupador__c);
                    if (plantillaAsociada.CC_Revisada__c) {
                        listaPlantillas.remove(indice);
                    }
                    else {
                        listaPlantillas.get(indice).estado = EstadoPlantilla.SIN_REVISAR;
                    }
                }
            }

            //Los agrupadores que aún quedan en el mapa son aquellos que NO tienen alguna plantilla requerida por sus casos
            for (Id idAgrupador : plantillasRequeridas.keySet()) {
                List<PlantillaRequerida> plantillasRequeridasAgrupador = plantillasRequeridas.get(idAgrupador);
                if (plantillasRequeridasAgrupador.size() != 0) {
                    List<PlantillaRequerida> listaPlantillasSinRevisar = new List<PlantillaRequerida>();
                    List<PlantillaRequerida> listaPlantillasSinDefinir = new List<PlantillaRequerida>();
                    for (PlantillaRequerida pr : plantillasRequeridasAgrupador) {
                        if (pr.estado == EstadoPlantilla.SIN_REVISAR)
                            listaPlantillasSinRevisar.add(pr);
                        else
                            listaPlantillasSinDefinir.add(pr);
                    }

                    String textoError;
                    if (listaPlantillasSinDefinir.size() == 0) {
                        textoError = 'El agrupador no se puede cerrar porque no están revisadas todas las plantillas necesarias.';
                    }
                    else {
                        // Esto no debería saltar nunca, pero por si acaso. Quien sabe, quizás les da por borrar una plantilla a mano o algo
                        textoError = 'El agrupador no se puede cerrar porque no están definidas todas las plantillas necesarias.';
                        for (PlantillaRequerida pr : listaPlantillasSinDefinir) {
                            textoError += ' (' + pr.getNombreIdioma() + '/' + pr.canal + '/' + pr.tipoCliente + ')';
                        }
                    }

                    mapNewObj.get(idAgrupador).addError(textoError);
                }
            }
        }
    }
    private void actualizarFechaAsociacion(Map<Id, CC_Agrupador__c> mapOldObj, List<CC_Agrupador__c> listNewObj) {

        for (CC_Agrupador__c agrupador : listNewObj) {
            if (agrupador.recordTypeId == CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Incidencia') 
            && agrupador.CC_Numero_Casos__c != mapOldObj.get(agrupador.Id).CC_Numero_Casos__c && (agrupador.CC_Numero_Casos__c == 2 || agrupador.CC_Numero_Casos__c == 3) && agrupador.CC_Fecha_creacion_MAXIMO__c == null) {
                Datetime fechaAsociacion = System.now();
                agrupador.CC_Fecha_Asociacion_Caso__c = fechaAsociacion;
            }
        }

    }
    
    private enum EstadoPlantilla {SIN_ASOCIAR, SIN_REVISAR}
    private class PlantillaRequerida {
        public String tipoCliente {get;set;}
        public String canal {get;set;}
        public String idioma {get;set;}
        public EstadoPlantilla estado {get; set;}

        public String getNombreIdioma() {
            String result = '';
            for (Schema.PicklistEntry f : CC_PlantillaAsociada__c.CC_Idioma__c.getDescribe().getPicklistValues()) {
                if (f.getValue() == idioma) {
                    result = f.getLabel();
                    break;
                }
            }
            return result;
        }
    }

    private static Map<Id, CC_Agrupador__c> recuperarAgrupadoresCerrados(Map<Id, CC_Agrupador__c> mapOldObj, Map<Id, CC_Agrupador__c> mapNewObj) {
        //Comprobar si se está cerrando alguno de los agrupadores modificados (no aplican
        //comunicaciones informativas ni agrupadores sin notificación de cierre
        Map<Id, CC_Agrupador__c> agrupadoresCerrados = new Map<Id, CC_Agrupador__c>();
        
        for (Id idAgrupador : mapOldObj.keySet()) {
            if (mapNewObj.get(idAgrupador).RecordTypeId != CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa')
                && mapNewObj.get(idAgrupador).RecordTypeId != CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa_de_Campana')
                && mapNewObj.get(idAgrupador).RecordTypeId != CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa_de_Marca')
                && mapOldObj.get(idAgrupador).CC_Estado__c == 'Activo'
                && mapNewObj.get(idAgrupador).CC_Estado__c == 'Cerrado'
                && mapNewObj.get(idAgrupador).CC_Notificar_Clientes__c) {
                    agrupadoresCerrados.put(mapNewObj.get(idAgrupador).Id, mapNewObj.get(idAgrupador));
            }
        }
        return agrupadoresCerrados;
    }

    private static Integer indicePlantilla(CC_PlantillaAsociada__c plantillaAsociada, List<CC_Agrupador_BU_TRHan.PlantillaRequerida> plantillasRequeridas) {
        for (Integer indice = 0; indice < plantillasRequeridas.size(); ++indice) {
            PlantillaRequerida plantillaRequerida = plantillasRequeridas[indice];
            if ((plantillaRequerida.tipoCliente == plantillaAsociada.CC_Tipo_Cliente__c)
             && (plantillaRequerida.canal == plantillaAsociada.CC_Canal__c)
             && (plantillaRequerida.idioma == plantillaAsociada.CC_Idioma__c))
             {
                 return indice;
             }
        }
        return -1;
    }
}