force-app/main/default/objects/Case/fields/CC_Agrupador_Id__c.field-meta.xml
<CustomField>
    <fullName>CC_Agrupador_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agrupador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Agrupador__c.CC_Publica__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Agrupador__c.CC_Estado__c</field>
            <operation>equals</operation>
            <value>Activo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_Agrupador__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/CC_Agrupador__c.object-meta.xml
<CustomObject>
    <label>Agrupador</label>
    <nameField>
        <displayFormat>GRP-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>CC_Titulo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CC_Agrupador_Rechazado_Test.cls
@IsTest
public class CC_Agrupador_Rechazado_Test {
    @isTest
    static void test() {
		CC_Agrupador__c agrupador = new CC_Agrupador__c();
        agrupador.CC_Titulo__c = 'Agrupador Test';
        insert agrupador;
        
        Case caso = new Case();
        caso.Subject = 'Caso Test';       
        caso.CC_Agrupador_Id__c = agrupador.Id;
        insert caso;	
        
        Task task = new Task();
		task.Type = 'Traslado Incidencia';
        task.status = 'Open';
        task.Subject = 'Email'; 
        task.WhatId = caso.Id;
        insert task; 
        
        List<Id> listId = new List<Id> ();
        listId.add(agrupador.Id);
        
        CC_Agrupador_Rechazado.agrupadorRechazado(listId);
    }
}