force-app/main/default/objects/Case/fields/CC_Canal_Operativo__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Operativo__c</fullName>
    <description>Campo para indicar el canal donde se haya el problema.</description>
    <label>Canal operativo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>App CaixaBankPay</fullName>
            </value>
            <value>
                <fullName>App CaixaBankSign</fullName>
            </value>
            <value>
                <fullName>App CBKNow</fullName>
            </value>
            <value>
                <fullName>App Imagin</fullName>
            </value>
            <value>
                <fullName>App imaginKids</fullName>
                <isActive>false</isActive>
                <label>App imaginKids</label>
            </value>
            <value>
                <fullName>App imaginTeens</fullName>
            </value>
            <value>
                <fullName>Cajero</fullName>
            </value>
            <value>
                <fullName>Cajero ATM NOW</fullName>
                <isActive>false</isActive>
                <label>Cajero ATM NOW</label>
            </value>
            <value>
                <fullName>App BrokerNow</fullName>
                <label>OCEAN Broker</label>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Otras App</fullName>
                <isActive>false</isActive>
                <label>Otras App</label>
            </value>
            <value>
                <fullName>Plataforma virtual</fullName>
                <isActive>false</isActive>
                <label>Plataforma virtual</label>
            </value>
            <value>
                <fullName>Portal CBK</fullName>
                <isActive>false</isActive>
                <label>Portal CBK</label>
            </value>
            <value>
                <fullName>Portal Wivai</fullName>
                <label>Portal Facilitea</label>
            </value>
            <value>
                <fullName>RRSS</fullName>
            </value>
            <value>
                <fullName>Servicios Centrales</fullName>
                <isActive>false</isActive>
                <label>Servicios Centrales</label>
            </value>
            <value>
                <fullName>Sin canal</fullName>
            </value>
            <value>
                <fullName>SmartPhone</fullName>
                <isActive>false</isActive>
                <label>SmartPhone</label>
            </value>
            <value>
                <fullName>Web CBKNow</fullName>
            </value>
            <value>
                <fullName>Web Imagin</fullName>
                <isActive>false</isActive>
                <label>Web Imagin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de resolución</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Detalles_Consulta__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalles_Consulta__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalles consulta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Contacto__c</fullName>
    <description>Campo para indicar que tipo de contacto tiene el caso.</description>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_TipoContacto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_Task_Verificacion_Cliente.cls
public class CC_Task_Verificacion_Cliente {

    @InvocableMethod(label='CC_Task_Verificacion_Cliente' description='Cuando se crea un tarea tipo "Verificación cliente" se cambia estado caso a Pendiente Revision o Cerrado')
    public static void CC_Task_Verificacion_Cliente (List<Id> idTask) {
    //--------------------------------------
    // Sergio Castro -> "25-02-2020" -> Cuando se crea un tarea tipo "Verificación cliente" se cambia estado caso a "Pendiente Revision" o "Cerrado"
    //--------------------------------------
    List<Task> listaTarea = [SELECT Status, WhatId FROM Task WHERE Id IN :idTask];
    List<Id> idCase = new List<Id>();
    for (Task tarea : listaTarea) {
        idCase.add(tarea.WhatId);  
    }

    List<Task> listasDeTareas = [SELECT Status, Subject FROM Task WHERE WhatId IN :idCase AND Status = 'Open' ]; 
    List<Case> listaCasos = [SELECT Status, CC_Detalles_Consulta__c, CC_Tipo_Contacto__c, CC_MCC_Motivo__c, CC_Canal_Procedencia__c,
                                CC_Canal_Resolucion__c, CC_Canal_Operativo__c, AccountId, ContactId 
                                FROM Case WHERE Id IN :idCase];

    //Preparamos las listas de casos
    List<Case> listaCasosCerrar = new List<Case>();
    List<Case> listaCasosRevisar = new List<Case>();
    List<Task> listaTaskCerradas = new List<Task>();

    //cerrar los caso de subject verificacion cliente antes primero comprar si hay mas de 1 
    //un for para recorrreme todas las listasdetareas luego si hay 1 y es verfiicacion cliente el subject pasarla a cerrada y cerrar el caso y si no si hay 2 o mas pasarlas a pendiente reviison
    for (Task tarea : listasDeTareas) {
        if(tarea.Subject == 'Verificación cliente' && listasDeTareas.size() == 1 ){ //lista de tareas abiertas = 1
            tarea.Status = 'Completed';
            listaTaskCerradas.add(tarea);
        }else if(tarea.Subject == 'Verificación cliente' && listasDeTareas.size() > 1 ){ //lista de tareas abiertas + 1
            tarea.Status = 'Completed';
            listaTaskCerradas.add(tarea);
        }
    }
    update listaTaskCerradas;
    List<Task> listasDeTareasActualizada = [SELECT Status, Subject FROM Task WHERE WhatId IN :idCase AND Status = 'Open' ]; //vuelvo a buscarlo para ver si la lista es isEmpty por si las tareas solo son 1

    for (Case caso : listaCasos) { 
        //compruebo que su estado no cambie
        if (caso.Status == 'Pendiente Cliente') {
            if (String.isNotBlank(caso.CC_MCC_Motivo__c) //solo hace falta validar el motivo ya que los demas dependen de él
            && String.isNotBlank(caso.CC_Detalles_Consulta__c) && String.isNotBlank(caso.CC_Canal_Procedencia__c) && String.isNotBlank(caso.CC_Canal_Resolucion__c) 
            && String.isNotBlank(caso.CC_Tipo_Contacto__c) && String.isNotBlank(caso.CC_Canal_Operativo__c) && String.isNotBlank(caso.AccountId) 
            && String.isNotBlank(caso.ContactId) && listasDeTareasActualizada.isEmpty()) {   //Cerramos el caso si tenemos todos los datos para cerrar y NO HAY ninguna actividad abierta
                caso.Status = 'Activo';
                listaCasosCerrar.add(caso);
            } else {
                caso.Status = 'Pendiente Revisión';
                listaCasosRevisar.add(caso);  
            }
        }
    }

    //actualizamos casos a cerrar 
    update listaCasosCerrar;
    for (Case caso : listaCasosCerrar) {
        caso.Status = 'Cerrado';
    }
    update listaCasosCerrar;

    //actualizamos casos a revisar
    update listaCasosRevisar;      
    }
}