force-app/main/default/objects/Case/fields/CC_Catalogo_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>CC_Catalogo_Facturacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catálogo Facturación</label>
    <referenceTo>CBK_CatalogoFacturacion__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Facturado__c.field-meta.xml
<CustomField>
    <fullName>CC_Facturado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Siendo un caso facturable, indica si ya ha sido facturado</description>
    <label>Facturado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Precio_Facturacion__c.field-meta.xml
<CustomField>
    <fullName>CC_Precio_Facturacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Precio Facturación</label>
    <referenceTo>CBK_Precio_Facturacion__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>PrecioFacturacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Precio_Facturar__c.field-meta.xml
<CustomField>
    <fullName>CC_Precio_Facturar__c</fullName>
    <label>Precio a Facturar</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/classes/CC_FacturarCasosCerrados_Batch.cls
global class CC_FacturarCasosCerrados_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    global CC_FacturarCasosCerrados_Batch() {}

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query;
        if(Test.isRunningTest()){
            query  = 'SELECT Id, CC_Catalogo_Facturacion__c,CC_Precio_Facturacion__c,CC_Precio_Facturar__c,CC_Facturado__c FROM Case ' + 
            'WHERE RecordType.DeveloperName IN (\'CC_Cliente\', \'CC_Empleado\') AND Status = \'Cerrado\' AND CC_Catalogo_Facturacion__c !=null LIMIT 10';
        }else{
            query  = 'SELECT Id, CC_Catalogo_Facturacion__c,CC_Precio_Facturacion__c,CC_Precio_Facturar__c,CC_Facturado__c FROM Case ' + 
            'WHERE ClosedDate = LAST_MONTH AND RecordType.DeveloperName IN (\'CC_Cliente\', \'CC_Empleado\') AND Status IN(\'Cerrado\',\'Rechazado\') AND CC_Catalogo_Facturacion__c !=null AND CC_Precio_Facturacion__c !=null AND CC_Precio_Facturar__c !=null';
        }
            return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {
        List<Case> casosActualizar = new List<Case>();
        for(Case caso:scope){
            caso.CC_Facturado__c = true;
            casosActualizar.add(caso);
            
        }

        if(!casosActualizar.isEmpty()){
            Database.update(casosActualizar, false);
        }
    }

    global void finish(Database.BatchableContext bc) {
        
    }
}