force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Numero_Reclamaciones_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Reclamaciones_Cliente__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Número de reclamaciones realizadas por el cliente.</description>
    <label>Número de reclamaciones de cliente</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Contacto__c</fullName>
    <description>Campo para indicar que tipo de contacto tiene el caso.</description>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_TipoContacto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/CC_Task.recordType-meta.xml
<RecordType>
    <fullName>CC_Task</fullName>
    <active>true</active>
    <description>Tarea (Contact Center)</description>
    <label>Tarea</label>
</RecordType>

force-app/main/default/classes/CC_Case_Reclamaciones_Cliente_Test.cls
@isTest
public class CC_Case_Reclamaciones_Cliente_Test {

	@isTest
    public static void actualizarContadorReclamacionesCliente() {
        //Alta de datos para la prueba
        List<Id> idsCaso = new List<Id>();
        Case caso = new Case();
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();
        caso.CC_Idioma__c = 'es';
        caso.Origin = 'Chat';
        caso.CC_Canal_Procedencia__c = 'Web';
        caso.CC_Tipo_Contacto__c = 'Consulta';
        caso.Subject = 'Asunto';
        insert caso;
        idsCaso.add(caso.Id);
        
        //Ejecución de la prueba
        Test.startTest();
        CC_Case_Reclamaciones_Cliente.actualizarContadorReclamacionesCliente(idsCaso);
        Test.stopTest();
                
        //Evaluación del resultado de la prueba
        Case casoResultado = [SELECT CC_Numero_Reclamaciones_Cliente__c FROM Case WHERE Id = :caso.Id];
        System.assertEquals(0, casoResultado.CC_Numero_Reclamaciones_Cliente__c);
    }
    
    @isTest
    public static void contadorReclamacionesCliente() {
        //Alta de datos para la prueba
        List<Id> idsCaso = new List<Id>();
        Case caso = new Case();
        caso.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();
        caso.CC_Idioma__c = 'es';
        caso.Origin = 'Chat';
        caso.CC_Canal_Procedencia__c = 'Web';
        caso.CC_Tipo_Contacto__c = 'Consulta';
        caso.Subject = 'Asunto';
        insert caso;
        idsCaso.add(caso.Id);
        
        Task tarea = new Task();
        tarea.Subject = 'Reclamación de cliente';
        tarea.WhatId = caso.Id;
		tarea.Type = 'Traslado Tercer Nivel';
        tarea.RecordTypeId = Schema.getGlobalDescribe().get('Task').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Task').getRecordTypeId();
       	insert tarea;
        
        //Ejecución de la prueba
        Test.startTest();
        CC_Case_Reclamaciones_Cliente.actualizarContadorReclamacionesCliente(idsCaso);
        Test.stopTest();
                
        //Evaluación del resultado de la prueba
        Case casoResultado = [SELECT CC_Numero_Reclamaciones_Cliente__c FROM Case WHERE Id = :caso.Id];
        System.assertEquals(1, casoResultado.CC_Numero_Reclamaciones_Cliente__c);
    }
    
}