force-app/main/default/objects/Case/fields/CC_Canal_Operativo__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Operativo__c</fullName>
    <description>Campo para indicar el canal donde se haya el problema.</description>
    <label>Canal operativo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>App CaixaBankPay</fullName>
            </value>
            <value>
                <fullName>App CaixaBankSign</fullName>
            </value>
            <value>
                <fullName>App CBKNow</fullName>
            </value>
            <value>
                <fullName>App Imagin</fullName>
            </value>
            <value>
                <fullName>App imaginKids</fullName>
                <isActive>false</isActive>
                <label>App imaginKids</label>
            </value>
            <value>
                <fullName>App imaginTeens</fullName>
            </value>
            <value>
                <fullName>Cajero</fullName>
            </value>
            <value>
                <fullName>Cajero ATM NOW</fullName>
                <isActive>false</isActive>
                <label>Cajero ATM NOW</label>
            </value>
            <value>
                <fullName>App BrokerNow</fullName>
                <label>OCEAN Broker</label>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Otras App</fullName>
                <isActive>false</isActive>
                <label>Otras App</label>
            </value>
            <value>
                <fullName>Plataforma virtual</fullName>
                <isActive>false</isActive>
                <label>Plataforma virtual</label>
            </value>
            <value>
                <fullName>Portal CBK</fullName>
                <isActive>false</isActive>
                <label>Portal CBK</label>
            </value>
            <value>
                <fullName>Portal Wivai</fullName>
                <label>Portal Facilitea</label>
            </value>
            <value>
                <fullName>RRSS</fullName>
            </value>
            <value>
                <fullName>Servicios Centrales</fullName>
                <isActive>false</isActive>
                <label>Servicios Centrales</label>
            </value>
            <value>
                <fullName>Sin canal</fullName>
            </value>
            <value>
                <fullName>SmartPhone</fullName>
                <isActive>false</isActive>
                <label>SmartPhone</label>
            </value>
            <value>
                <fullName>Web CBKNow</fullName>
            </value>
            <value>
                <fullName>Web Imagin</fullName>
                <isActive>false</isActive>
                <label>Web Imagin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de resolución</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Detalles_Consulta__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalles_Consulta__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalles consulta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Contacto__c</fullName>
    <description>Campo para indicar que tipo de contacto tiene el caso.</description>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_TipoContacto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de Resolucion</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_resolucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Detalle__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalle__c</fullName>
    <description>Campo para poder indicar el detalle.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalle</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_Task_Verificacion_Cliente_Test.cls
@isTest
public with sharing class CC_Task_Verificacion_Cliente_Test {
    @isTest
    public static void CasoPendienteRevision() {

        Case caso = new Case();
        caso.CC_Idioma__c = 'es';
        caso.Subject = 'Prueba';
        caso.CC_Tipo_Cliente__c = 'Cliente';
        caso.Status = 'Pendiente Cliente';
        caso.Origin = 'Comentarios Stores';
        caso.CC_Tipo_Contacto__c = 'Consulta';
        caso.CC_Canal_Procedencia__c = 'Google Play Store';
        insert caso;

        Task actividad = new Task();
        actividad.WhatId = caso.Id;
        actividad.Type = 'Rechazar Primer Nivel';
        actividad.Status = 'Open';
        insert actividad;

        List<Id> listaIdsTask = new List<Id>();
        listaIdsTask.add(actividad.Id);

        Test.startTest();
        CC_Task_Verificacion_Cliente.CC_Task_Verificacion_Cliente(listaIdsTask);
        Test.stopTest();
        
        Case resultadoCaso = [SELECT Status FROM Case WHERE Id = :actividad.WhatId LIMIT 1];
        System.assertEquals('Pendiente Revisión', resultadoCaso.Status);
    }

    @isTest
    public static void CasoCerrado() {

        CC_MCC__c tematica = new CC_MCC__c();
        tematica.RecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
        tematica.Name = 'App\'s';
        tematica.CC_Tipo_Cliente__c = 'Cliente';
        tematica.CC_Codigo_Externo__c = 'TE-000001';
        insert tematica;

        CC_MCC__c productoServicio = new CC_MCC__c();
        productoServicio.RecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
        productoServicio.Name = 'APP CaixaBank';
        productoServicio.CC_Detalle__c = 'CaixaBank';
        productoServicio.CC_Tipo_Cliente__c = 'Cliente';
        productoServicio.CC_Tematica__c = tematica.Id;
        productoServicio.CC_Codigo_Externo__c = 'PR-000001';
        insert productoServicio;

        CC_MCC__c motivo = new CC_MCC__c();
        motivo.RecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
        motivo.Name = 'Valoración positiva';
        motivo.CC_Tipo_Cliente__c = 'Cliente';
        motivo.CC_Producto_Servicio__c = productoServicio.Id;
        motivo.CC_Codigo_Externo__c = 'MO-000001';
        insert motivo;

        // Add account
        Account ac = new Account();
        ac.name='Acme Inc.';
        ac.name='Acme';                                   
        insert ac;

        // Add a contact 
        Contact c = new Contact(FirstName='Joe',LastName='Merged');
        insert c;

        Case caso = new Case();
        caso.CC_Idioma__c = 'es';
        caso.Subject = 'Prueba';
        caso.Status = 'Pendiente Cliente';
        caso.AccountId = ac.Id;
        caso.ContactId = c.Id;

        caso.CC_MCC_Tematica__c = tematica.Id;
        caso.CC_MCC_ProdServ__c = productoServicio.Id;
        caso.CC_MCC_Motivo__c = motivo.Id;

        caso.Origin = 'Email';
        caso.CC_Canal_Procedencia__c = 'Accionista';
        caso.CC_Canal_Resolucion__c = 'Cajeros';
        caso.CC_Tipo_Contacto__c = 'Consulta';

        caso.CC_Detalles_Consulta__c = 'Cliente contacta para consultar un cajero.';
        caso.CC_Tipo_Cliente__c = 'Cliente';
        caso.CC_Canal_Operativo__c = 'Cajero';
        insert caso;

        Task actividad = new Task();
        actividad.WhatId = caso.Id;
        actividad.Type = 'Actividad manual';
        actividad.Subject = 'Verificación cliente';
        actividad.Status = 'Completed';
        actividad.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'CC_Task');
        insert actividad;
    }
}