force-app/main/default/objects/Case/fields/CC_CasoRelacionado__c.field-meta.xml
<CustomField>
    <fullName>CC_CasoRelacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso relacionado</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Case.ContactId</field>
            <operation>equals</operation>
            <valueField>Case.ContactId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Id_Related_Mail__c.field-meta.xml
<CustomField>
    <fullName>SEG_Id_Related_Mail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Identificador email relacionado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Subestado__c.field-meta.xml
<CustomField>
    <fullName>SEG_Subestado__c</fullName>
    <label>Subestado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subestado1</fullName>
            </value>
            <value>
                <fullName>Pendiente aplicación reglas de CR</fullName>
            </value>
            <value>
                <fullName>Pendiente clasificación Cognitive</fullName>
            </value>
            <value>
                <fullName>Pendiente asignación grupo por MCC</fullName>
            </value>
            <value>
                <fullName>Pendiente asignación de propietario</fullName>
            </value>
            <value>
                <fullName>Pendiente valija</fullName>
            </value>
            <value>
                <fullName>Incongruencia reglas de clasificación</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Reactivada por comunicación de cliente</fullName>
            </value>
            <value>
                <fullName>Incidencia Valija</fullName>
            </value>
            <value>
                <fullName>Casos vinculados pendientes</fullName>
            </value>
            <value>
                <fullName>Contratos pendientes</fullName>
            </value>
            <value>
                <fullName>En canal BPO</fullName>
            </value>
            <value>
                <fullName>En canal Valija</fullName>
            </value>
            <value>
                <fullName>En canal Valija pendiente recepción justificantes</fullName>
            </value>
            <value>
                <fullName>En colaborador</fullName>
            </value>
            <value>
                <fullName>En Gestor Operativo de la empresa</fullName>
            </value>
            <value>
                <fullName>Por agrupación</fullName>
            </value>
            <value>
                <fullName>Tareas finalizadas</fullName>
            </value>
            <value>
                <fullName>Por gestor</fullName>
            </value>
            <value>
                <fullName>Lista negra</fullName>
            </value>
            <value>
                <fullName>Por duplicidad</fullName>
            </value>
            <value>
                <fullName>Por comunicación de cliente</fullName>
            </value>
            <value>
                <fullName>Planificado manualmente</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Recibida respuesta Colaborador</fullName>
            </value>
            <value>
                <fullName>Pendiente Robot</fullName>
            </value>
            <value>
                <fullName>Envío cierre Cliente</fullName>
            </value>
            <value>
                <fullName>Envío cierre Colaborador</fullName>
            </value>
            <value>
                <fullName>Envío pendiente respuesta Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/OS_Cliente.recordType-meta.xml
<RecordType>
    <fullName>OS_Cliente</fullName>
    <active>true</active>
    <businessProcess>OS_Support_Process</businessProcess>
    <label>Cliente (COPS)</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/OS_Empleado.recordType-meta.xml
<RecordType>
    <fullName>OS_Empleado</fullName>
    <active>true</active>
    <businessProcess>OS_Support_Process</businessProcess>
    <label>Empleado (COPS)</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SEG_Cliente.recordType-meta.xml
<RecordType>
    <fullName>SEG_Cliente</fullName>
    <active>true</active>
    <businessProcess>SEG_Clientes</businessProcess>
    <label>Cliente (SEG)</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SEG_Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>SEG_Seguimiento</fullName>
    <active>true</active>
    <businessProcess>SEG_Clientes</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/OS_Task.recordType-meta.xml
<RecordType>
    <fullName>OS_Task</fullName>
    <active>true</active>
    <label>Tarea (COPS)</label>
</RecordType>

force-app/main/default/classes/SEG_CasosSEG_COPSrelacionados.cls
public with sharing class SEG_CasosSEG_COPSrelacionados implements Queueable{
    private String messageId;
    private String body;
    private String subject;
    
    public SEG_CasosSEG_COPSrelacionados(String messageId, String body, String subject){
        this.messageId= messageId;
        this.body= body;
        this.subject= subject;
    }

    public void execute(QueueableContext context) {
        Id recordTypeTask=CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'OS_Task');
        List<Task> tareasCOPS = new List<Task>();
        List<Case> casos = [SELECT Id, CC_CasoRelacionado__c, RecordType.DeveloperName FROM Case WHERE Createddate = TODAY AND Recordtype.Developername IN ('SEG_Cliente','SEG_Seguimiento','OS_Cliente','OS_Empleado') AND SEG_Id_Related_Mail__c = :messageId ORDER BY CREATEDDATE DESC LIMIT 2];
        if(casos.size()==2){
            casos[0].CC_CasoRelacionado__c =casos[1].Id;
            casos[1].CC_CasoRelacionado__c =casos[0].Id;
            for(Case caso : casos){
                /* if(caso.RecordType.DeveloperName.startsWith('SEG')){
                    caso.Status = 'Pendiente';
                    caso.SEG_Subestado__c='En gestión UAFE';
                } else */
                if(caso.RecordType.DeveloperName.startsWith('OS')){
                    Task tarea = new Task();
                    tarea.RecordTypeId = recordTypeTask;
                    tarea.Type = 'Relación Segmentos';
                    tarea.Subject = subject;
                    tarea.ActivityDate = System.today();
                    tarea.Status = 'Completed';
                    tarea.Description = body;
                    tarea.WhatId = caso.Id; 
                    tareasCOPS.add(tarea);
                }
            }      
            if(!tareasCOPS.isEmpty()){
                try {
                    List<Database.SaveResult> results = Database.insert(tareasCOPS, false); 
                } catch (Exception e) {
                    
                    CBK_Log.error(e, 'Error en insertar tarea', tareasCOPS);
                }
            }
            if(!casos.isEmpty()){
                try {
                    List<Database.SaveResult> results = Database.update(casos, false); 
                } catch (Exception e) {
                    
                    CBK_Log.error(e, 'Error en actualizar casos', casos);
                }
            }
            
        }
    }
}