force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Detalle__c.field-meta.xml
<CustomField>
    <fullName>SEG_Detalle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Detalle del MCC</description>
    <inlineHelpText>Detalle del MCC</inlineHelpText>
    <label>Detalle</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SAC Detalle</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Motivo__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Motivo__c</valueField>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Detalle</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Casos (MCC)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Grupo__c.field-meta.xml
<CustomField>
    <fullName>SEG_Grupo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo asignado al caso</description>
    <label>Grupo de trabajo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo colaborador, Grupo Operativo Segmentos</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Cases (Grupo)</relationshipLabel>
    <relationshipName>SEG_Grupo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/SAC_ParametrizacionSLATME__c.object-meta.xml
<CustomObject>
    <label>Parametrización SLA / TMO</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizaciones SLA / TMO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_CanalProcedencia__c.field-meta.xml
<CustomField>
    <fullName>SAC_CanalProcedencia__c</fullName>
    <label>Procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_DuplicadoMCCProcedenciaEstado__c.field-meta.xml
<CustomField>
    <fullName>SAC_DuplicadoMCCProcedenciaEstado__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>DuplicadoMCCProcedenciaEstado</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_Duracion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Duracion__c</fullName>
    <label>Duración(Días)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_Estados__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estados__c</fullName>
    <label>Estados</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_001</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>SAC_002</fullName>
                <label>Análisis</label>
            </value>
            <value>
                <fullName>SAC_003</fullName>
                <label>Redacción</label>
            </value>
            <value>
                <fullName>SAC_004</fullName>
                <label>Ejecución</label>
            </value>
            <value>
                <fullName>SAC_006</fullName>
                <label>Subsanación</label>
            </value>
            <value>
                <fullName>SAC_007</fullName>
                <label>Negociación</label>
            </value>
            <value>
                <fullName>SAC_009</fullName>
                <isActive>false</isActive>
                <label>Baja</label>
            </value>
            <value>
                <fullName>SAC_008</fullName>
                <isActive>false</isActive>
                <label>Derivación</label>
            </value>
            <value>
                <fullName>SAC_005</fullName>
                <isActive>false</isActive>
                <label>Inadmisión</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_MCC__c.field-meta.xml
<CustomField>
    <fullName>SAC_MCC__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MCC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SAC Detalle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipName>Parametrizaciones_SLA_TME</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_TMEGeneral__c.field-meta.xml
<CustomField>
    <fullName>SAC_TMEGeneral__c</fullName>
    <defaultValue>true</defaultValue>
    <label>TMO General</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/recordTypes/SAC_TME.recordType-meta.xml
<RecordType>
    <fullName>SAC_TME</fullName>
    <active>true</active>
    <label>TME</label>
</RecordType>

force-app/main/default/objects/SAC_TiempoEstados__c/SAC_TiempoEstados__c.object-meta.xml
<CustomObject>
    <label>Tiempo por estados</label>
    <nameField>
        <displayFormat>TTME-{0000}</displayFormat>
        <label>Nombre de Tiempo por estados</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAC_TiempoEstados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_Duracion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Duracion__c</fullName>
    <formula>SAC_Fin__c -  SAC_Inicio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duración</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_001</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>SAC_002</fullName>
                <label>Análisis</label>
            </value>
            <value>
                <fullName>SAC_003</fullName>
                <label>Redacción</label>
            </value>
            <value>
                <fullName>SAC_004</fullName>
                <label>Ejecución</label>
            </value>
            <value>
                <fullName>SAC_005</fullName>
                <label>Negociación</label>
            </value>
            <value>
                <fullName>SAC_006</fullName>
                <label>Subsanación</label>
            </value>
            <value>
                <fullName>SAC_007</fullName>
                <label>Inadmisión</label>
            </value>
            <value>
                <fullName>SAC_009</fullName>
                <label>Baja</label>
            </value>
            <value>
                <fullName>SAC_008</fullName>
                <label>Derivación</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>SAC_010</fullName>
                <label>Pte. Asignar</label>
            </value>
            <value>
                <fullName>SAC_011</fullName>
                <label>En gestión</label>
            </value>
            <value>
                <fullName>SAC_012</fullName>
                <label>Gestionada</label>
            </value>
            <value>
                <fullName>SAC_013</fullName>
                <label>Descartada</label>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>SAC_014</fullName>
                <label>Cerrada sin resolver</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_Fin__c.field-meta.xml
<CustomField>
    <fullName>SAC_Fin__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_Grupo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Grupo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo del caso</description>
    <label>Grupo</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>SAC_TiempoEstados</relationshipLabel>
    <relationshipName>SAC_TiempoEstados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_Inicio__c.field-meta.xml
<CustomField>
    <fullName>SAC_Inicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SAC_TiempoEstados__c/fields/SAC_TMECaso__c.field-meta.xml
<CustomField>
    <fullName>SAC_TMECaso__c</fullName>
    <label>TMO Caso</label>
    <referenceTo>SAC_TMECaso__c</referenceTo>
    <relationshipLabel>Tiempo Estados</relationshipLabel>
    <relationshipName>SAC_TiempoEstados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/SAC_TMECaso__c.object-meta.xml
<CustomObject>
    <label>TMO Caso</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de TMO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAC_TMECaso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_Caso__c.field-meta.xml
<CustomField>
    <fullName>SAC_Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>TME_Caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_Parametrizacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Parametrizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parametrización</label>
    <referenceTo>SAC_ParametrizacionSLATME__c</referenceTo>
    <relationshipName>SAC_TME_Caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_TMEDefinido__c.field-meta.xml
<CustomField>
    <fullName>SAC_TMEDefinido__c</fullName>
    <label>TMO Definido</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/recordTypes/SAC_PreAlta.recordType-meta.xml
<RecordType>
    <fullName>SAC_PreAlta</fullName>
    <active>true</active>
    <label>PreAlta</label>
</RecordType>

force-app/main/default/objects/SAC_TMECaso__c/recordTypes/SAC_TMECaso.recordType-meta.xml
<RecordType>
    <fullName>SAC_TMECaso</fullName>
    <active>true</active>
    <label>Caso</label>
</RecordType>

force-app/main/default/objects/SAC_TMECaso__c/recordTypes/SAC_TMEGlobal.recordType-meta.xml
<RecordType>
    <fullName>SAC_TMEGlobal</fullName>
    <active>true</active>
    <label>TME Global</label>
</RecordType>

force-app/main/default/classes/SAC_AsignarTMEs.cls
public without sharing class SAC_AsignarTMEs {
/*****************************************************************
 * Name: SAC_AsignarTMEs
 * Copyright © 2021  CaixaBank
 * 
 * Proposito: Updatear TMEs de las reclamaciones
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR         DATE         Description
 * 1.0            US227582         Luis Mesa      03/06/21     Creación
*****************************************************************/

    private static final Id RTSAC_PARAMETRIZACIONTME = Schema.SObjectType.SAC_ParametrizacionSLATME__c.getRecordTypeInfosByDeveloperName().get('SAC_TME').getRecordTypeId();
    private static final Id RTTMECASO = Schema.SObjectType.SAC_TMECaso__c.getRecordTypeInfosByDeveloperName().get('SAC_TMECaso').getRecordTypeId();

    public static void modificarTiemposPretension(List<Case> listNewCase, Map<Id, Case> mapOldCase, List<Case> listOldCase){

    /*****************************************************************
     * Proposito: Método para comprobar que pretensiones han cambiado de estado
     * 
     * Historial
     * -------
     * VERSION        USER_STORY       AUTHOR         DATE         Description
     * 1.0            US227582         Luis Mesa      03/06/21     Creación
    *****************************************************************/
    //update
        List<Case> reclamacionesNew = new List<Case>(); //Modificar el estado de la reclamacion
        List<Case> reclamacionesOld = new List<Case>(); //Modificar el TME asociado, en caso de que exista y su TPE
        
        for (Case caso : listNewCase) {
            if (mapOldCase.containsKey(caso.Id)) {
                if(/*String.isNotBlank( mapOldCase.get(caso.Id).SEG_Detalle__c ) &&*/
                    (caso.Status != mapOldCase.get(caso.Id).Status || caso.SEG_Grupo__c != mapOldCase.get(caso.Id).SEG_Grupo__c /*|| caso.SEG_Detalle__c != mapOldCase.get(caso.Id).SEG_Detalle__c*/)){
                        reclamacionesNew.add(caso);
                        reclamacionesOld.add(mapOldCase.get(caso.Id));
                }
            }
        }

        if(!reclamacionesNew.isEmpty()){
            //si no hay parametrizacion que pasa?
            closeTPE(reclamacionesOld);
            changeSLA(reclamacionesNew);
        }
    }

    public static void changeSLA(List<Case> reclamacionesNew){
 
        /*****************************************************************
         * Proposito: Método para asignar los tiempos de los SLAs a los casos
         *              dependiendo del estado en el que se encuentre la reclamacion 
         * 
         * Historial
         * -------
         * VERSION        USER_STORY       AUTHOR         DATE         Description
         * 1.0            US227582         Luis Mesa      03/06/21     Creación
        *****************************************************************/

        Id tipoRegistro = Schema.SObjectType.SAC_ParametrizacionSLATME__c.getRecordTypeInfosByDeveloperName().get('SAC_TME').getRecordTypeId();
        Id tipoRegistroTMECaso = Schema.SObjectType.SAC_TMECaso__c.getRecordTypeInfosByDeveloperName().get('SAC_TMECaso').getRecordTypeId();
        Id tipoRegistroTMEGlobal = Schema.SObjectType.SAC_TMECaso__c.getRecordTypeInfosByDeveloperName().get('SAC_TMEGlobal').getRecordTypeId();
        Id tipoRegistroTMEPreAlta = Schema.SObjectType.SAC_TMECaso__c.getRecordTypeInfosByDeveloperName().get('SAC_PreAlta').getRecordTypeId();


        Map<Id, Case> mapaReclamacionesNew = new Map<Id, Case>(reclamacionesNew);
        List<SAC_TMECaso__c> tmes = [SELECT Id, SAC_Caso__c, SAC_Parametrizacion__c, SAC_Parametrizacion__r.SAC_Estados__c, SAC_Caso__r.Status, Name, RecordTypeId
                                    FROM SAC_TMECaso__c 
                                    WHERE SAC_Caso__c IN: reclamacionesNew AND RecordTypeId != :tipoRegistroTMEGlobal AND RecordTypeId != :tipoRegistroTMEPreAlta];
        List<String> nombresParametriaciones = new List<String>();
        
        Map<Id,List<String>> nombresParametriacionesMap = new Map<Id,List<String>>();
        for(SAC_TMECaso__c tme : tmes){
            nombresParametriaciones.add(tme.Name);
            //nombresParametriacionesMap.put(tme.SAC_Caso__c);
            
            if(nombresParametriacionesMap.containsKey(tme.SAC_Caso__c)){
                List<String> nomParam = new List<String>();
                nomParam = nombresParametriacionesMap.get(tme.SAC_Caso__c);
                nomParam.add(tme.Name);
                nombresParametriacionesMap.put(tme.SAC_Caso__c, nomParam);
            }
            else{
                List<String> nomParam = new List<String>();
                nomParam.add(tme.Name);
                nombresParametriacionesMap.put(tme.SAC_Caso__c, nomParam);
            }
        }
        
        List<SAC_TMECaso__c> tmesNuevos = new List<SAC_TMECaso__c>();

        List<String> mccsCasos = new List<String>();
        List<String> canalProcedencia = new List<String>();
        Set<String> estados = new Set<String>();
        Map<Id,String> mapEstados = new Map<Id,String>();
        
        for(Case caso : reclamacionesNew){
            mccsCasos.add(caso.SEG_Detalle__c);
            canalProcedencia.add(caso.CC_Canal_Procedencia__c);
            estados.add(caso.Status);
            mapEstados.put(caso.Id, caso.Status);
        }
        if(!tmes.isEmpty()){
            //hay TME en el caso, hay que comprobar si hay que crearlo o no; y crear su TPE nuevo
            //falta filtrar por estado -> para ello siempre que se cree un TME hay que pasarle un objeto parametrizacion relacionado
            Map<Id, SAC_TMECaso__c> mapaTmesNuevos = new Map<Id, SAC_TMECaso__c>();
            for(SAC_TMECaso__c tme : tmes){
                if(tme.SAC_Parametrizacion__r.SAC_Estados__c != null){
                    List<String> estadoParams = tme.SAC_Parametrizacion__r.SAC_Estados__c.split(';');
                    if(!estadoParams.isEmpty()){
                        for(String estadoActual : estadoParams){
                            //es estadoCaso el mismo que el del TME.parametrizacion.SAC_ESTADO??
                            //if(estados.contains(estadoActual) ){
                            if(mapEstados.get(tme.SAC_Caso__c).contains(estadoActual)){
                                //Existe un TME.Name nombre igual al nombre de la parametrizacion?? 
                                if (!mapaTmesNuevos.containsKey(tme.Id)) {
                                    mapaTmesNuevos.put(tme.Id, tme);
                                }
                                //tmesNuevos.add(tme); Esta línea se comentó porque entraban tmes duplicados
                            }
                        }
                        /*if(!tmesNuevos.isEmpty()){
                            insertarTPE(tmesNuevos);
                            tmesNuevos.clear();
                        }*/
                    }
                }
            }
            tmesNuevos.addAll(mapaTmesNuevos.values());
                //comprobar cuales pueden ser las parametrizaciones a los casos
            List<SAC_ParametrizacionSLATME__c> parametrizacionesTMEs = [SELECT Id, SAC_Estados__c, SAC_Duracion__c, SAC_MCC__c, Name, SAC_CanalProcedencia__c, RecordTypeId, SAC_DuplicadoMCCProcedenciaEstado__c
                                                                        FROM SAC_ParametrizacionSLATME__c 
                                                                        WHERE /*SAC_Estados__c IN: estados 
                                                                            AND */((SAC_MCC__c IN: mccsCasos) OR SAC_TMEGeneral__c = TRUE )
                                                                            AND SAC_CanalProcedencia__c IN: canalProcedencia
                                                                            AND RecordTypeId =: tipoRegistro];

            //System.debug('lista parametrizaciones ---> '+parametrizacionesTMEs);
            
            if(!parametrizacionesTMEs.isEmpty()){

                //mapa estado/parametrizacion
                Map<String, List<SAC_ParametrizacionSLATME__c>> mapaEstadoParametrizacion = new Map<String, List<SAC_ParametrizacionSLATME__c>>();
                
                for(SAC_ParametrizacionSLATME__c parametrizacion : parametrizacionesTMEs){
                    List<String> estadoParams = parametrizacion.SAC_Estados__c.split(';');
                    for(String estadoUnico : estadoParams){
                        String llave = /*parametrizacion.SAC_MCC__c + */parametrizacion.SAC_CanalProcedencia__c + estadoUnico;
                        //comprobar si el mapa ya tiene registro
                        List<SAC_ParametrizacionSLATME__c> listadoParams = new List<SAC_ParametrizacionSLATME__c>();
                        if(mapaEstadoParametrizacion.containsKey(llave)){
                            listadoParams = mapaEstadoParametrizacion.get(llave);
                            listadoParams.add(parametrizacion);
                            mapaEstadoParametrizacion.put(llave, listadoParams);
                        }
                        else{
                            listadoParams.add(parametrizacion);
                            mapaEstadoParametrizacion.put(llave, listadoParams);
                        }
                    }

                }
                for(Case caso : reclamacionesNew){
                    String estado = caso.Status;
                    String mcc = caso.SEG_Detalle__c;
                    String canal = caso.CC_Canal_Procedencia__c;

                    String duplicado = /*mcc + */canal + estado;
                    
                    if(mapaEstadoParametrizacion.containsKey(duplicado)){
                        List<SAC_ParametrizacionSLATME__c> parametrizaciones = mapaEstadoParametrizacion.get(duplicado);
                        for(SAC_ParametrizacionSLATME__c parametrizacionFinal : parametrizaciones){
                            //if(!nombresParametriaciones.contains(parametrizacionFinal.Name)){
                            if(!nombresParametriacionesMap.get(caso.Id).contains(parametrizacionFinal.Name)){

                                for(String estadoFinal : estados){
                                    String duplicadoAuxiliar = /*mcc + */canal + estadoFinal;
                                    Integer posicion = nombresParametriaciones.indexOf(duplicadoAuxiliar);
                                    //system.debug(posicion);
                                    //system.debug(parametrizacionFinal.Name);
                                    if(posicion == -1 /*&& parametrizacionFinal.Name == nombresParametriaciones.get(posicion)*/){
                                        SAC_TMECaso__c tmeNuevo = new SAC_TMECaso__c();
                                        tmeNuevo.SAC_Parametrizacion__c = parametrizacionFinal.Id;
                                        tmeNuevo.SAC_Caso__c = caso.Id;
                                        tmeNuevo.SAC_TMEDefinido__c = parametrizacionFinal.SAC_Duracion__c;
                                        tmeNuevo.RecordTypeId = tipoRegistroTMECaso;
                                        tmeNuevo.Name = parametrizacionFinal.Name;
                                        tmesNuevos.add(tmeNuevo);
                                    }
                                }
                            }
                        }
                    }
                }
                if(!tmesNuevos.isEmpty()){   
                    //System.debug('por el primero -> '+tmesNuevos);
                    /*for (SAC_TMECaso__c tme : tmesNuevos) {
                        System.debug('tme dentro del bucle primero --> '+tme);
                    }*/
                    //Añadido 01/03/23 para eliminar posibles tmes duplicados
                    tmesNuevos = controlarTMEsDuplicados(tmesNuevos);
                    insertarTMOconTPE(tmesNuevos, mapaReclamacionesNew);
                }
            }
        }
        //inicio falta
        else{
            //conseguir parametrizacion del nuevo estado / mcc reclamacion
            List<SAC_ParametrizacionSLATME__c> parametrizacionesParaTMES = [SELECT Id, SAC_Estados__c, SAC_Duracion__c, SAC_MCC__c, Name, SAC_CanalProcedencia__c, RecordTypeId, SAC_DuplicadoMCCProcedenciaEstado__c
                                                                            FROM SAC_ParametrizacionSLATME__c 
                                                                            WHERE /*SAC_Estados__c IN: estados 
                                                                                AND */((SAC_MCC__c IN: mccsCasos) OR SAC_TMEGeneral__c = TRUE )
                                                                                AND SAC_CanalProcedencia__c IN: canalProcedencia
                                                                                AND RecordTypeId =: tipoRegistro];

            Map<String, List<SAC_ParametrizacionSLATME__c>> mapaEstadoParametrizacion = new Map<String, List<SAC_ParametrizacionSLATME__c>>();
            if(!parametrizacionesParaTMES.isEmpty()){
                for(SAC_ParametrizacionSLATME__c parametrizacion : parametrizacionesParaTMES){
                    if (!parametrizacion.SAC_Estados__c.split(';').isEmpty()) {
                        List<String> estadoParams = parametrizacion.SAC_Estados__c.split(';');
                        for(String estadoUnico : estadoParams){
                            String llave = /*parametrizacion.SAC_MCC__c +*/ parametrizacion.SAC_CanalProcedencia__c + estadoUnico;
                            //comprobar si el mapa ya tiene registro
                            List<SAC_ParametrizacionSLATME__c> listadoParams = new List<SAC_ParametrizacionSLATME__c>();
                            if(mapaEstadoParametrizacion.containsKey(llave)){
                                listadoParams = mapaEstadoParametrizacion.get(llave);
                                listadoParams.add(parametrizacion);
                                mapaEstadoParametrizacion.put(llave, listadoParams);
                            }
                            else{
                                listadoParams.add(parametrizacion);
                                mapaEstadoParametrizacion.put(llave, listadoParams);
                            }
                        }
                    }
                }
            }
            //for de casos, recuperar para cada caso el mcc entrada estado y crear un string en el que comparar la key del map, 
            //si coincide, ya se que parametrizacion hay que hacerle al nuevo TME para cada caso
            
            for(Case caso : reclamacionesNew){
                String mcc = caso.SEG_Detalle__c;
                String estado = caso.Status;
                String canal = caso.CC_Canal_Procedencia__c;

                String param = /*mcc +*/ canal + estado;
                if(mapaEstadoParametrizacion.containsKey(param)){
                    List<SAC_ParametrizacionSLATME__c> parametrizacionesFinales = mapaEstadoParametrizacion.get(param);
                    for(SAC_ParametrizacionSLATME__c parametrizacionFinal : parametrizacionesFinales){
                        if(!nombresParametriaciones.contains(parametrizacionFinal.Name)){
                            SAC_TMECaso__c tmeNuevo = new SAC_TMECaso__c();
                            tmeNuevo.SAC_Parametrizacion__c = parametrizacionFinal.Id;
                            tmeNuevo.RecordTypeId = tipoRegistroTMECaso;
                            tmeNuevo.SAC_Caso__c = caso.Id;
                            tmeNuevo.SAC_TMEDefinido__c = parametrizacionFinal.SAC_Duracion__c;
                            tmeNuevo.Name = parametrizacionFinal.Name;
                            tmesNuevos.add(tmeNuevo);
                        }
                    }
                }
                else{
                    SAC_TMECaso__c tmeNuevo = new SAC_TMECaso__c();
                    tmeNuevo.SAC_Caso__c = caso.Id;
                    tmeNuevo.RecordTypeId = tipoRegistroTMECaso;
                    tmeNuevo.SAC_TMEDefinido__c = 30;
                    tmeNuevo.Name = 'TME Genérico';
                    tmesNuevos.add(tmeNuevo);
                }
            }
            if(!tmesNuevos.isEmpty()){   
                //System.debug('por el segundo -> '+tmesNuevos);
                insertarTMOconTPE(tmesNuevos, mapaReclamacionesNew);
            }
        }
    }
    
    public static void insertarTPE(List<SAC_TMECaso__c> tmes, Map<Id, Case> mapaReclamacionesNew){ 
        /*****************************************************************
         * Proposito: Método para insertar TPEs 
         * 
         * Historial
         * -------
         * VERSION        USER_STORY       AUTHOR         DATE         Description
         * 1.0            US227582         Luis Mesa      03/06/21     Creación
        *****************************************************************/
            List<SAC_TiempoEstados__c> tpes = new List<SAC_TiempoEstados__c>();

            if(!tmes.isEmpty()){
                for(SAC_TMECaso__c tme : tmes){
                    SAC_TiempoEstados__c tpe = new SAC_TiempoEstados__c();
                    tpe.SAC_Estado__c = tme.SAC_Caso__r.Status;
                    tpe.SAC_Inicio__c = system.now();
                    tpe.SAC_TMECaso__c = tme.Id;
                    if (mapaReclamacionesNew.containsKey(tme.SAC_Caso__c) && String.isNotBlank(mapaReclamacionesNew.get(tme.SAC_Caso__c).SEG_Grupo__c)) {
                        tpe.SAC_Grupo__c = mapaReclamacionesNew.get(tme.SAC_Caso__c).SEG_Grupo__c;
                    }
                    tpes.add(tpe);
                }
            }
            else{
                throw new AuraHandledException('Fallo al crear un TPE');
            } 
            upsert(tpes);
        }

    public static void closeTPE(List<Case> reclamacionesOld){ 
         
    /*****************************************************************
     * Proposito: Método para cerrar los TPEs
     * 
     * Historial
     * -------
     * VERSION        USER_STORY       AUTHOR         DATE         Description
     * 1.0            US227582         Luis Mesa      03/06/21     Creación
    *****************************************************************/
       Id RTTMEGlobal = Schema.SObjectType.SAC_TMECaso__c.getRecordTypeInfosByDeveloperName().get('SAC_TMEGlobal').getRecordTypeId();

        List<SAC_TiempoEstados__c> tpes = [SELECT Id, SAC_Estado__c, SAC_Duracion__c, SAC_Fin__c, SAC_Inicio__c, SAC_TMECaso__r.SAC_Caso__c
                                            FROM SAC_TiempoEstados__c
                                            WHERE SAC_TMECaso__r.SAC_Caso__c IN: reclamacionesOld
                                            AND SAC_TMECaso__r.RecordTypeId != :RTTMEGlobal];


        if(!tpes.isEmpty()){
            for(SAC_TiempoEstados__c tpe : tpes){
                if(tpe.SAC_Fin__c == null){
                    tpe.SAC_Fin__c = system.now();
                }
            }  
            update tpes;
        }
    }

    public static void insertarTMOconTPE(List<SAC_TMECaso__c> tmesNuevos, Map<Id, Case> mapaReclamacionesNew) {   
        List<Database.UpsertResult> result = Database.upsert(tmesNuevos,false);
        List<Id> listOfIds = new List<Id>();
        Map<Id,Id> mapaDeIdesAux = new Map<Id,Id>();

        for (Database.UpsertResult sr : result) {
            if (sr.isSuccess()) {
                listOfIds.add(sr.getId());
                mapaDeIdesAux.put(sr.getId(), sr.getId());
            }
        }

        List<SAC_TMECaso__c> listaTMOAux = new List<SAC_TMECaso__c>();

        if(!tmesNuevos.isEmpty()){
            for (SAC_TMECaso__c tmeAux : tmesNuevos) {
                if(mapaDeIdesAux.containsKey(tmeAux.id)){
                    listaTMOAux.add(tmeAux);
                }
            }
        }

        if(!listaTMOAux.isEmpty()) {
            insertarTPE(listaTMOAux, mapaReclamacionesNew);
        }
        
    }

    private static List<SAC_TMECaso__c> controlarTMEsDuplicados(List<SAC_TMECaso__c> listaTMEsNuevos) {
        List<SAC_TMECaso__c> listaTMEsFiltrados = new List<SAC_TMECaso__c>();
        Map<Id, List<SAC_TMECaso__c>> mapaParamTME = new Map<Id, List<SAC_TMECaso__c>>();
        //Recorrer lista tmes para buscar duplicados
        for (SAC_TMECaso__c tmeNuevo : listaTMEsNuevos) {
            //Si el mapa no contiene la parametrización del tme, se inicializa con la parametrización de key y su lista de tmes de valor, además de la lista final de tmes filtrados
            if (!mapaParamTME.containsKey(tmeNuevo.SAC_Parametrizacion__c)) {
                List<SAC_TMECaso__c> listaTmes = new List<SAC_TMECaso__c>();
                listaTmes.add(tmeNuevo);
                mapaParamTME.put(tmeNuevo.SAC_Parametrizacion__c, listaTmes);
                listaTMEsFiltrados.add(tmeNuevo);
            //Si el mapa contiene tmes con la parametrización, se recorren dichos tmes    
            } else {
                Boolean duplicado = false;
                for (SAC_TMECaso__c tme : mapaParamTME.get(tmeNuevo.SAC_Parametrizacion__c)) {
                    //Si el tme del mapa tiene el mismo nombre, mismo recordtypeId y mismo name que el tme de la listaTMEsNuevos, lo consideramos duplicado
                    if (tme.SAC_Caso__c == tmeNuevo.SAC_Caso__c && tme.RecordTypeId == tmeNuevo.RecordTypeId && tme.Name == tmeNuevo.Name) {
                        duplicado = true; //Activación booleano para indicar que es un duplicado
                    }
                }
                //Si no es duplicado, se añade a la lista de tmes de dicha parametrización en el mapa y a la lista final de tmes filtrados
                if (!duplicado) {
                    mapaParamTME.get(tmeNuevo.SAC_Parametrizacion__c).add(tmeNuevo);
                    listaTMEsFiltrados.add(tmeNuevo);
                }
            }
        }
        //Retornar lista filtrada
        return listaTMEsFiltrados;
    }
        
}