force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_StatusAuxiliar__c.field-meta.xml
<CustomField>
    <fullName>SAC_StatusAuxiliar__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status auxiliar</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>SAC_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Developer Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Externo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Externo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Externo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_NivelGrupo__c.field-meta.xml
<CustomField>
    <fullName>SAC_NivelGrupo__c</fullName>
    <description>Muestra el nivel del grupo para los escalados</description>
    <label>Nivel de grupo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_Nivel2</fullName>
                <label>Nivel 2</label>
            </value>
            <value>
                <fullName>SAC_Nivel3</fullName>
                <label>Nivel 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PermiteConsultas__c.field-meta.xml
<CustomField>
    <fullName>SAC_PermiteConsultas__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para controlar si permite consultas</description>
    <label>Permite consultas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PermiteEscalado__c.field-meta.xml
<CustomField>
    <fullName>SAC_PermiteEscalado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para indicar si el grupo permite escalado</description>
    <label>Permite escalado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_TienePropietario__c.field-meta.xml
<CustomField>
    <fullName>SAC_TienePropietario__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo del grupo colaborador que parametriza si las consultas internas del objeto Interacción tienen propietario</description>
    <label>Tiene Propietario</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/CC_Grupo_Colaborador_Contact__c.object-meta.xml
<CustomObject>
    <label>Colaborador</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Colaborador Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Colaboradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Email1__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email1__c</fullName>
    <description>Campo para almacenar un email del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_EmailRespuesta__c.field-meta.xml
<CustomField>
    <fullName>SAC_EmailRespuesta__c</fullName>
    <description>Email desde donde se ha respondido a la pregunta</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Respuesta</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado en el que se encuentra la interacción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteRespuesta</fullName>
                <default>true</default>
                <label>Pendiente Respuesta</label>
            </value>
            <value>
                <fullName>SAC_Resuelta</fullName>
                <label>Resuelta</label>
            </value>
            <value>
                <fullName>SAC_Atendida</fullName>
                <label>Atendida</label>
            </value>
            <value>
                <fullName>SAC_Reescalada</fullName>
                <label>Re escalada</label>
            </value>
            <value>
                <fullName>SAC_Borrador</fullName>
                <label>Pendiente Respuesta -  Borrador</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadoSinAtender</fullName>
                <label>Finalizado sin atender</label>
            </value>
            <value>
                <fullName>SAC_Cancelado</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>SAC_Devuelto</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>SAC_PendienteRespuestaDefinitiva</fullName>
                <label>Pendiente Respuesta Definitiva</label>
            </value>
            <value>
                <fullName>SPV_PendienteEnviar</fullName>
                <label>Pendiente enviar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_GrupoColaborador__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoColaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo Colaborador</description>
    <label>Grupo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 6) OR (1 AND 2 AND 7) OR (3 AND 4) OR (3 AND 5) OR (4 AND 8) OR (5 AND 8) OR (3 AND 9) OR (1 AND 10)</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteConsultas__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consulta</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteEscalado__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV2</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV3</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_TieneUsuariosActivos__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_Externo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Letrados</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoSPV</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ConsultaSPV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Interacciones (Grupo)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_ImporteAutorizado__c.field-meta.xml
<CustomField>
    <fullName>SAC_ImporteAutorizado__c</fullName>
    <description>Importe autorizado en el escalado</description>
    <label>Importe autorizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Propuesta__c.field-meta.xml
<CustomField>
    <fullName>SAC_Propuesta__c</fullName>
    <description>Propuesta del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Propuesta Letrado</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relaciona el objeto interaccion con las reclamaciones</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Titulo__c</fullName>
    <description>Título del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/SAC_ParametrizacionEscalado__c.object-meta.xml
<CustomObject>
    <label>Parametrización Validación Escalado</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Parametrización Validación Esc</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrización Validación Escalados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/Aplica_escalado__c.field-meta.xml
<CustomField>
    <fullName>Aplica_escalado__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Aplica escalado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_despacho__c.field-meta.xml
<CustomField>
    <fullName>SAC_despacho__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Despacho</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Parametrización Validación Escalados (Despacho)</relationshipLabel>
    <relationshipName>Parametrizaci_n_Validaci_n_Escalados1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_GrupoDestino__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoDestino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo Destino</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteEscalado__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Parametrización Validación Escalados</relationshipLabel>
    <relationshipName>Parametrizaci_n_Validaci_n_Escalados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_Importe__c.field-meta.xml
<CustomField>
    <fullName>SAC_Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>SAC_Mensaje__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mensaje</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_TodosDespachos__c.field-meta.xml
<CustomField>
    <fullName>SAC_TodosDespachos__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Aplica todos los despachos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_todosMCCs__c.field-meta.xml
<CustomField>
    <fullName>SAC_todosMCCs__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Aplica a todos los MCCs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionEscalado__c/fields/SAC_validarImporte__c.field-meta.xml
<CustomField>
    <fullName>SAC_validarImporte__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Validar Importe</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SAC_InteraccionOperativasControllerTest.cls
/*****************************************************************
 * Name: SAC_InteraccionOperativasControllerTest
 * Copyright © 2021  CaixaBank
 * 
 * Proposito: Testear la clase SAC_InteraccionOperativas_Controller
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR               DATE         Description
 * 1.0            US219272         Carlos Solis         23/08/21     Creación
 * 1.1            US563153         Jose Carlos Blanco  	13/04/23     Modificación (test modificada usando el SAC_TestDataFactory)   
*****************************************************************/
@isTest
public with sharing class SAC_InteraccionOperativasControllerTest {
    @TestSetup
    static void makeData(){

        List<User> usuarios = SAC_TestDataFactory.crearUsuarioSACGeneral(3);
        //usuario
        usuarios[0].Username = 'ustestesteo@test.com';
        usuarios[0].Alias = 'alias';
        //usuario 2
        usuarios[1].Username = 'ustestesteo2@test.com';
        usuarios[1].Alias = 'alias2';
        //usuario 3
        usuarios[2].Username = 'ustestesteo3@test.com';
        usuarios[2].Alias = 'alias3';
        
        SAC_DatabaseDML.insertListDML(usuarios, false);
        //Database.insert(usuarios);

        //grupo colaborador
        CC_Grupo_Colaborador__c grupo = SAC_TestDataFactory.crearGrupoColaborador('ResponsableAccion',1)[0];
        grupo.SAC_PermiteEscalado__c = true;
        grupo.SAC_PermiteConsultas__c = true;
        grupo.SAC_NivelGrupo__c = 'SAC_Nivel2';
        grupo.SAC_Externo__c = false;
        grupo.SAC_DeveloperName__c = 'Test';
        grupo.SAC_TienePropietario__c = true;
        SAC_DatabaseDML.insertDML(grupo, false);
        //Database.insert(grupo);

        //grupo colaborador contact
        CC_Grupo_Colaborador_Contact__c grupoColabContact = SAC_TestDataFactory.crearColaboradorContact(usuarios[0].id, grupo.id);
        SAC_DatabaseDML.insertDML(grupoColabContact, false);
        //Database.insert(grupoColabContact);

        //grupo colaborador contact 2
        CC_Grupo_Colaborador_Contact__c grupoColabContact2 = SAC_TestDataFactory.crearColaboradorContact(usuarios[2].id, grupo.id);
        SAC_DatabaseDML.insertDML(grupoColabContact2, false);
        //Database.insert(grupoColabContact2);

        //Reclamacion
        Map<String, Object> camposRecl = new Map<String, Object>();
        camposRecl.put('Subject', 'TestRec');
        camposRecl.put('Origin', 'Backoffice');
        camposRecl.put('Status', 'Alta');
        camposRecl.put('SAC_StatusAuxiliar__c', 'Alta');
        camposRecl.put('OwnerId', usuarios[0].Id);

        Case casoReclamacion = SAC_TestDataFactory.crearCaso('Reclamacion',camposRecl);
        SAC_DatabaseDML.insertDML(casoReclamacion, false);
        //Database.insert(casoReclamacion);

        
        List<SAC_Interaccion__c> escalados = SAC_TestDataFactory.crearInteraccionEsc(2, casoReclamacion.Id, grupo.Id);
        //Interaccion
        escalados[0].SAC_Titulo__c = 'propuesta test';
        escalados[0].SAC_Propuesta__c = 'propuesta test';
        escalados[0].SAC_Email1__c = 'testing@test.test';
        escalados[0].OwnerId = usuarios[1].Id;
        escalados[0].SAC_ImporteAutorizado__c = 20;
        //Interaccion 2
        escalados[1].SAC_Titulo__c = 'propuesta test2';
        escalados[1].SAC_Propuesta__c = 'propuesta test2';
        escalados[1].SAC_Email1__c = 'testing@test.test';
        escalados[1].OwnerId = usuarios[2].Id;
        escalados[1].SAC_ImporteAutorizado__c = 20;

        SAC_DatabaseDML.insertListDML(escalados, false);
        //Database.insert(escalados);
        
        
        SAC_ParametrizacionEscalado__c parametrizacionEscalado = new SAC_ParametrizacionEscalado__c();
        parametrizacionEscalado.Name='Validacion Escalado AJ';
        parametrizacionEscalado.Aplica_escalado__c=true;
        parametrizacionEscalado.SAC_Despacho__c = grupo.id;
        parametrizacionEscalado.SAC_GrupoDestino__c=grupo.id;
        parametrizacionEscalado.SAC_Importe__c=200;
        parametrizacionEscalado.SAC_Mensaje__c= 'Mensaje';
        parametrizacionEscalado.SAC_todosMCCs__c =true;
        parametrizacionEscalado.SAC_TodosDespachos__c = true;
        parametrizacionEscalado.SAC_validarImporte__c = false;
        SAC_DatabaseDML.insertDML(parametrizacionEscalado, false);
        //Database.insert(parametrizacionEscalado);

        //Interaccion Consulta
        Map<String, Object> camposCons = new Map<String, Object>();
        camposCons.put('SAC_Reclamacion__c', casoReclamacion.id);
        camposCons.put('SAC_EmailRespuesta__c', 'emailentrante@entrante.com');
        camposCons.put('SAC_Estado__c', 'SAC_Resuelta');
        camposCons.put('SAC_Titulo__c', 'Consulta');
        camposCons.put('SAC_GrupoColaborador__c', grupo.Id);
        
        SAC_Interaccion__c consulta = SAC_TestDataFactory.crearInteraccion('Consulta',camposCons);
        SAC_DatabaseDML.insertDML(consulta, false);
        //Database.insert(consulta);
    }

    @isTest
    static void autoasignarPropiedadInteraccion(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias' AND isActive = true Limit 1];
        SAC_Interaccion__c escalado = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.autoasignarPropiedadInteraccion(escalado.Id, usuario.Id);
        }
        Test.stopTest();

        SAC_Interaccion__c escaladoResult = [SELECT id, OwnerId FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];
        System.assertEquals(usuario.Id, escaladoResult.OwnerId, 'No se ha podido autoasignar la interacción');
    }

    @isTest
    static void tomarPropiedadInteraccionTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias' AND isActive = true Limit 1];
        User usuarioMismoGrupo = [SELECT id FROM User WHERE Alias = 'alias3' Limit 1];
        SAC_Interaccion__c escalado = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test2' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.tomarPropiedadInteraccion(escalado.Id, usuario.Id);
        }
        Test.stopTest();

        SAC_Interaccion__c escaladoResult = [SELECT id, OwnerId FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test2' LIMIT 1];
        System.assertEquals(usuario.Id, escaladoResult.OwnerId, 'No se ha podido tomar en propiedad el caso');
    }

    @isTest
    static void mostrarBotonTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias' AND isActive = true Limit 1];
        User usuarioMismoGrupo = [SELECT id FROM User WHERE Alias = 'alias3' Limit 1];
        SAC_Interaccion__c escalado = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test2' LIMIT 1];
        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        SAC_InteraccionOperativas_Controller.wrapperInit wpInit = new SAC_InteraccionOperativas_Controller.wrapperInit();

        Test.startTest();
        System.runAs(usuario) {
            wpInit = SAC_InteraccionOperativas_Controller.mostrarBoton(escalado.Id, usuario.Id);
        }
        Test.stopTest();

        System.assertEquals(true, wpInit.mostrarBoton, 'No se ha podido verificar si se tiene que mostrar el botón');
    }

    @isTest
    static void mostrarBotonPropiedadConsultasTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias' AND isActive = true Limit 1];
        SAC_Interaccion__c consulta = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'Consulta' LIMIT 1];
        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Boolean mostrarBoton = false;

        Test.startTest();
        System.runAs(usuario) {
            mostrarBoton = SAC_InteraccionOperativas_Controller.mostrarBotonPropiedadConsultas(consulta.Id);
        }
        Test.stopTest();

        System.assertEquals(true, mostrarBoton, 'No se ha podido verificar si se tiene que mostrar el botón');
    }

    @isTest
    static void esPropietarioTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias2' AND isActive = true Limit 1];
        SAC_Interaccion__c escalado = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Boolean propietario = false;
        Test.startTest();
        System.runAs(usuario) {
            propietario = SAC_InteraccionOperativas_Controller.esPropietario(escalado.Id);
        }
        Test.stopTest();

        System.assertEquals(true, propietario, 'No se ha podido verificar el propietario');
    }

    @isTest
    static void esConsultaTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias2' AND isActive = true Limit 1];
        SAC_Interaccion__c consulta = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'Consulta' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Boolean esConsulta = false;
        Test.startTest();
        System.runAs(usuario) {
            esConsulta = SAC_InteraccionOperativas_Controller.esConsulta(consulta.Id);
        }
        Test.stopTest();

        System.assertEquals(true, esConsulta, 'No se ha podido verificar si es una consulta');
    }

    @isTest
    static void devolverInteraccionTest(){
        User usuario = [SELECT id FROM User WHERE Alias = 'alias' AND isActive = true Limit 1];
        SAC_Interaccion__c escalado = [SELECT id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.devolverInteraccion(escalado.Id);
        }
        Test.stopTest();

        List<Group> cola = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'SAC_PendienteAsignar' LIMIT 1];
        SAC_Interaccion__c escaladoResult = [SELECT id, OwnerId FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];
        System.assertEquals(escaladoResult.OwnerId, cola[0].Id, 'No se ha podido devolver la interacción');
    }
    
    @isTest
    static void adjuntarArchivos() {
        User usuario = [SELECT id FROM User WHERE Username = 'ustestesteo@test.com' AND isActive = true Limit 1];
        Case caso = [SELECT Id, Subject FROM Case WHERE Subject = 'TestRec' LIMIT 1];
        SAC_Interaccion__c escalado = [SELECT id, SAC_Propuesta__c, SAC_CasoEscalado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            
        //Archivo adjunto
        ContentVersion newcont = new ContentVersion();
        newcont.Title  = 'prueba';
        newcont.PathOnClient  = 'caixa.jpeg';
        Blob b=Blob.valueOf('This is version data');
        newcont.VersionData = EncodingUtil.base64Decode('Unit Test Attachment Body');
        newcont.FirstPublishLocationId  = escalado.id;
        SAC_DatabaseDML.insertDML(newcont, false);
        //Database.insert(newcont);
            
        SAC_InteraccionOperativas_Controller.insertarAdjuntoCaso(escalado.Id);
        }
        Test.stopTest();
        System.assertNotEquals(null, 'adjuntado', 'no se ha podido insertar adjunto');
    }

    @isTest
    static void volverAEscalarTest() {
        User usuario = [SELECT id FROM User WHERE Username = 'ustestesteo@test.com' AND isActive = true Limit 1];
        SAC_Interaccion__c escalado = [SELECT id, SAC_Propuesta__c, SAC_CasoEscalado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.volverAEscalar(escalado.Id, 'propuesta letrado test');
        }
        SAC_Interaccion__c escResult = [SELECT Id, SAC_Estado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];
        Test.stopTest();
        System.assertEquals('SAC_PendienteRespuesta', escResult.SAC_Estado__c, 'no se ha podido volver a escalar');
    }

    @isTest
    static void cancelarEscaladoTest() {
        User usuario = [SELECT id FROM User WHERE Username = 'ustestesteo@test.com' AND isActive = true Limit 1];
        SAC_Interaccion__c escalado = [SELECT id, SAC_Propuesta__c, SAC_CasoEscalado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.cancelarEscalado(escalado.Id);
        }
        SAC_Interaccion__c escaladoResult = [SELECT id, SAC_Estado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'propuesta test' LIMIT 1];
        Test.stopTest();
        System.assertEquals('SAC_Cancelado', escaladoResult.SAC_Estado__c, 'no se ha podido cancelar el escalado');
    }

    @isTest
    static void marcarPendienteRespuestaDefinitivaTest() {
        User usuario = [SELECT id FROM User WHERE Alias = 'alias2' AND isActive = true Limit 1];
        SAC_Interaccion__c consulta = [SELECT id, SAC_Estado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'Consulta' LIMIT 1];

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuario.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        SAC_DatabaseDML.insertDML(permiSetAssi, false);
        //Database.insert(permiSetAssi);

        Test.startTest();
        System.runAs(usuario) {
            SAC_InteraccionOperativas_Controller.marcarPendienteRespuestaDefinitiva(consulta.Id);
        }
        Test.stopTest();

        SAC_Interaccion__c consultaPendienteRespuestaDefinitiva = [SELECT id, SAC_Estado__c FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'Consulta' LIMIT 1];
        System.assertEquals('SAC_PendienteRespuestaDefinitiva', consultaPendienteRespuestaDefinitiva.SAC_Estado__c, 'No se ha actualizado el estado de la consulta');
    }
}