force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>SAC_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Developer Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/SAC_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto juntion entre el Maestro de acciones y el objeto Case creando una relación acción-reclamación/pretensión, para el proyecto de SAC Reclamaciones.</description>
    <label>Acción</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Descripcion__c</fullName>
    <description>Descripción de la acción.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_MaestroAccionesReclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_MaestroAccionesReclamacion__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup a el objeto Maestro acciones de reclamación para crear la relación acción - Reclamación/pretensión.</description>
    <inlineHelpText>Incluya T- y pulse la lupa para mostrar el listado de tareas.</inlineHelpText>
    <label>Maestro Acciones Reclamación</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SAC_MaestroAccionesReclamacion__c.SAC_Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SAC_MaestroAccionesReclamacion__c</referenceTo>
    <relationshipLabel>Acciones</relationshipLabel>
    <relationshipName>SAC_AccionesMaestro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_PlazoMaximo__c.field-meta.xml
<CustomField>
    <fullName>SAC_PlazoMaximo__c</fullName>
    <description>Plazo máximo (duración en días) (TME)</description>
    <label>Plazo máximo(Días)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Pretension__c.field-meta.xml
<CustomField>
    <fullName>SAC_Pretension__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a Case, generando la relación Acción - Pretensión.</description>
    <label>Pretensión</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Acciones de ejecución (Pretensión)</relationshipLabel>
    <relationshipName>SAC_AccionesPretension</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Prorroga__c.field-meta.xml
<CustomField>
    <fullName>SAC_Prorroga__c</fullName>
    <description>Prórroga (duración en días) - siempre la misma duración de días que el TME</description>
    <label>Días de prórroga</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/recordTypes/SAC_MaestroDeTareas.recordType-meta.xml
<RecordType>
    <fullName>SAC_MaestroDeTareas</fullName>
    <active>true</active>
    <description>Acciones que ya están predefinidas</description>
    <label>Maestro de tareas</label>
</RecordType>

force-app/main/default/objects/SAC_MaestroAccionesReclamacion__c/SAC_MaestroAccionesReclamacion__c.object-meta.xml
<CustomObject>
    <description>Objeto maestro parametrizable de acciones sobre las Reclamaciones y pretensiones</description>
    <label>Maestro Acciones Reclamación</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de la Acción</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro Acciones de Reclamaciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_MaestroAccionesReclamacion__c/fields/SAC_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Descripcion__c</fullName>
    <description>Campo para guardar la descripción de la Acción</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Descripción</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_MaestroAccionesReclamacion__c/fields/SAC_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>SAC_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_MaestroAccionesReclamacion__c/fields/SAC_PlazoMaximo__c.field-meta.xml
<CustomField>
    <fullName>SAC_PlazoMaximo__c</fullName>
    <description>Campo para guardar el plazo máximo duración en días (TME)</description>
    <label>Plazo máximo (Días)</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_MaestroAccionesReclamacion__c/fields/SAC_Prorroga__c.field-meta.xml
<CustomField>
    <fullName>SAC_Prorroga__c</fullName>
    <description>Campo para guardar la prórroga (duración en días) - siempre la misma duración de días que el TME</description>
    <label>Días de Prórroga</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SAC_AccionGGH_Test.cls
/*****************************************************************
* Name: SAC_AccionGGH_Test
* Copyright © 2022  CaixaBank
* 
* Proposito: Testar la clase SAC_AccionGGH
* 
* Historial
* -------
* VERSION        USER_STORY       AUTHOR              DATE         Description
* 1.0            US431440         Marcela Neira       05/09/22     Creación
* 1.1            US563153         Jose Carlos Blanco  08/03/23     Modificación (test modificada usando el SAC_TestDataFactory)   
*****************************************************************/
@istest
public with sharing class SAC_AccionGGH_Test {

   @TestSetup
   static void makeData(){  
      
      User usuarioGeneral;
      System.runAs(new User(Id = Userinfo.getUserId())) {
         //Usuario SAC General
         usuarioGeneral = SAC_TestDataFactory.crearUsuarioSACGeneral(1)[0];
         Database.insert(usuarioGeneral);
      
         PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
         PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
         permiSetAssi.AssigneeId = usuarioGeneral.Id;
         permiSetAssi.PermissionSetId = permiSet.Id;
         Database.insert(permiSetAssi);
      }

      CC_Grupo_Colaborador__c grupoColaborador = SAC_TestDataFactory.crearGrupoColaborador('ResponsableAccion',1)[0];
      Database.insert(grupoColaborador);

      //Pretension
      Map<String, Object> camposPret = new Map<String, Object>();
      camposPret.put('SuppliedCompany', 'pretension');
      camposPret.put('OwnerId', usuarioGeneral.id);
      
      Case pretension = SAC_TestDataFactory.crearCaso('Pretension',camposPret);
      Database.insert(pretension);    
      
      
      SAC_MaestroAccionesReclamacion__c maestro = SAC_TestDataFactory.crearMaestroAcciones(1,grupoColaborador.Id)[0];
      maestro.SAC_DeveloperName__c ='GGH';
      maestro.SAC_Descripcion__c = 'Maestro';  
      maestro.SAC_PlazoMaximo__c = 4; 
      maestro.SAC_Prorroga__c= 4;
      Database.insert(maestro);

      SAC_Accion__c tarea = SAC_TestDataFactory.crearTareas(1,pretension,true)[0];
      tarea.SAC_MaestroAccionesReclamacion__c = maestro.id;
      Database.insert(tarea);
   }

   @isTest
   static void tareaUnicaGGH_Test() {
      Id recordTypeAccionMaestro = Schema.SObjectType.SAC_Accion__c.getRecordTypeInfosByDeveloperName().get('SAC_MaestroDeTareas').getRecordTypeId();
      Case pretension = [SELECT Id FROM Case WHERE SuppliedCompany = 'pretension'];      
      List<SAC_MaestroAccionesReclamacion__c> maestroGHH = [SELECT id, SAC_DeveloperName__c FROM SAC_MaestroAccionesReclamacion__c WHERE SAC_DeveloperName__c = 'GGH' LIMIT 1]; 
      Boolean hayError = false;

      try{
         SAC_Accion__c tarea = new SAC_Accion__c(RecordTypeId = recordTypeAccionMaestro, SAC_MaestroAccionesReclamacion__c = maestroGHH[0].id, SAC_Pretension__c = pretension.Id);
         Database.insert(tarea);
      } catch (Exception e) {
         hayError = true;
      }

      User usuario = [SELECT Id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND isActive = true LIMIT 1];
		System.runAs(usuario){
         Database.update(pretension);
      }
      System.assertEquals(true, hayError, 'No ha saltado el error.');
   }
}