force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_StatusAuxiliar__c.field-meta.xml
<CustomField>
    <fullName>SAC_StatusAuxiliar__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status auxiliar</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_Organismo__c.field-meta.xml
<CustomField>
    <fullName>SPV_Organismo__c</fullName>
    <description>Campo para informar el organismo al que pertenecen los casos de SPV</description>
    <label>Organismo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SPV_CNMV</fullName>
                <label>CNMV</label>
            </value>
            <value>
                <fullName>SPV_DGS</fullName>
                <label>DGS</label>
            </value>
            <value>
                <fullName>SPV_Consumo</fullName>
                <label>Consumo</label>
            </value>
            <value>
                <fullName>SPV_BDE</fullName>
                <label>BDE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/OS_Negocio__c.field-meta.xml
<CustomField>
    <fullName>OS_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CSI_Bankia</fullName>
            </value>
            <value>
                <fullName>GRR</fullName>
            </value>
            <value>
                <fullName>HDT</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>SEGMENTOS</fullName>
            </value>
            <value>
                <fullName>SPV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email2__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email2__c</fullName>
    <description>Segundo email del grupo.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Para 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email3__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email3__c</fullName>
    <description>tercer email para el grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Para 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email__c</fullName>
    <description>Campo donde se guardaran los emails del grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Dirección de email al cual llegaran las consultas.</inlineHelpText>
    <label>Para</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PeriodoConsulta__c.field-meta.xml
<CustomField>
    <fullName>SAC_PeriodoConsulta__c</fullName>
    <description>periodo de tiempo dentro del cual la consulta debe estar respondida</description>
    <label>Periodo Vencimiento Consulta(días)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PermiteConsultas__c.field-meta.xml
<CustomField>
    <fullName>SAC_PermiteConsultas__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para controlar si permite consultas</description>
    <label>Permite consultas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PermiteEscalado__c.field-meta.xml
<CustomField>
    <fullName>SAC_PermiteEscalado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para indicar si el grupo permite escalado</description>
    <label>Permite escalado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_PermiteTareas__c.field-meta.xml
<CustomField>
    <fullName>SAC_PermiteTareas__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para controlar si permite tareas</description>
    <label>Permite tareas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/recordTypes/SPV_GrupoDeTareas.recordType-meta.xml
<RecordType>
    <fullName>SPV_GrupoDeTareas</fullName>
    <active>true</active>
    <description>Record Type para los grupos de tareas del proyecto de Supervisores</description>
    <label>Grupo de tareas</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Email2__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email2__c</fullName>
    <description>Campo para almacenar un email del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Email3__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email3__c</fullName>
    <description>Campo para almacenar un email del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_GrupoColaborador__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoColaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo Colaborador</description>
    <label>Grupo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 6) OR (1 AND 2 AND 7) OR (3 AND 4) OR (3 AND 5) OR (4 AND 8) OR (5 AND 8) OR (3 AND 9) OR (1 AND 10)</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteConsultas__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consulta</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteEscalado__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV2</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV3</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_TieneUsuariosActivos__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_Externo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Letrados</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoSPV</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ConsultaSPV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Interacciones (Grupo)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relaciona el objeto interaccion con las reclamaciones</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Titulo__c</fullName>
    <description>Título del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SPV_Organismo__c.field-meta.xml
<CustomField>
    <fullName>SPV_Organismo__c</fullName>
    <label>Código ISIN</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDE</fullName>
            </value>
            <value>
                <fullName>CNMV</fullName>
            </value>
            <value>
                <fullName>DGS o Consumo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SPV_LCMP_GestionEmailsConsultas_Test.cls
/*****************************************************************
 * Name: SPV_LCMP_GestionEmailsConsultas_Test
 * Copyright © 2021  CaixaBank
 * 
 * Proposito: Test de la clase SPV_LCMP_GestionEmailsConsultas
 * 
****************************************************************/ 
@isTest
public with sharing class SPV_LCMP_GestionEmailsConsultas_Test {
    
    @TestSetup
    static void makeData(){
    
        Test.startTest();

        User usuarioAdmin = SPV_TestDataFactory.crearUsuarioAdministrador(1)[0];
        Database.insert(usuarioAdmin);

        List<User> listUsuarios ;

        System.runAs(usuarioAdmin){
            listUsuarios  = SPV_TestDataFactory.crearUsuarioSPVGeneral(2);
            Database.insert(listUsuarios );
        }

        Test.stopTest();

        //Grupo
        List<CC_Grupo_Colaborador__c> listGrupos = new List<CC_Grupo_Colaborador__c>();
        CC_Grupo_Colaborador__c grupo = new CC_Grupo_Colaborador__c();
        grupo.RecordTypeId = Schema.SObjectType.CC_Grupo_Colaborador__c.getRecordTypeInfosByDeveloperName().get('SPV_GrupoDeTareas').getRecordTypeId();
        grupo.Name = 'grupotest';
        grupo.SAC_PermiteEscalado__c = true;
        grupo.SAC_PermiteConsultas__c = true;
        grupo.SAC_PermiteTareas__c = true;
        grupo.SAC_Email__c = 'testspv@test.cominvalid';
        grupo.SAC_Email2__c = 'testspv@test.cominvalid';
        grupo.SAC_Email3__c = 'testspv@test.cominvalid';
        grupo.SAC_PeriodoConsulta__c = 12;
        grupo.OS_Negocio__c = 'SPV';
        listGrupos.add(grupo);
        Database.insert(listGrupos);

        //Reclamacion
        List<Case> listaReclamaciones = new List<Case>();
        Map<String, Object> camposReclamacion = new Map<String, Object>();
        camposReclamacion.put('Subject', 'TestRecCrearRec1');
        // camposReclamacion.put('SPV_Organismo__c', 'SPV_CNMV');
        camposReclamacion.put('Status', 'SAC_003');
        camposReclamacion.put('OwnerId', listUsuarios[0].Id);
        camposReclamacion.put('SAC_StatusAuxiliar__c', 'SAC_003');

        Case casoReclamacion = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion);
        listaReclamaciones.add(casoReclamacion);
        Database.insert(listaReclamaciones);

        //Consulta
        List<SAC_Interaccion__c> listConsultas = new List<SAC_Interaccion__c>();
        Map<String, Object> camposObj = new Map<String, Object>();
        camposObj.put('SAC_Reclamacion__c', casoReclamacion.Id);
        camposObj.put('SAC_Titulo__c', 'ConsultaTestSPV');
        camposObj.put('SAC_GrupoColaborador__c', grupo.Id);
        SAC_Interaccion__c consulta = SPV_TestDataFactory.crearInteraccion('Consulta', camposObj);
        listConsultas.add(consulta);
        Database.insert(listConsultas);
    }

    @isTest
    static void obtenerInformacionTest(){
        SAC_Interaccion__c interaccion = [SELECT Id FROM SAC_Interaccion__c WHERE SAC_Titulo__c = 'ConsultaTestSPV' LIMIT 1];
        User usuario = [SELECT Id FROM User WHERE Username = 'useradmintest0@test.com.testSetup' AND IsActive = true LIMIT 1];

        System.runAs(usuario){
            Test.startTest();
            SPV_LCMP_GestionEmailsConsultas.InfoConsulta resultado = SPV_LCMP_GestionEmailsConsultas.obtenerInformacion(interaccion.Id);
            Test.stopTest();

            Assert.areNotEqual(null, resultado, 'La obtención de datos ha fallado');
        }
    }
}