force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_IdentCliente__c.field-meta.xml
<CustomField>
    <fullName>CC_IdentCliente__c</fullName>
    <defaultValue>&apos;0&apos;</defaultValue>
    <description>Tipo de identificación del cliente asociado al caso</description>
    <inlineHelpText>Tipo de identificación del cliente asociado al caso</inlineHelpText>
    <label>Identificación cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_IdentCliente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Motivo (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_No_Identificado__c.field-meta.xml
<CustomField>
    <fullName>CC_No_Identificado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que se pone a true si el cliente no se ha querido identificar.</description>
    <label>No identificado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_CasoRelacionado__c.field-meta.xml
<CustomField>
    <fullName>SAC_CasoRelacionado__c</fullName>
    <description>Campo para apuntar la id del caso padre cuando hagamos copias de un caso y poder gestionar su inserción en el sistema</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Caso relacionado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_EsPrincipal__c.field-meta.xml
<CustomField>
    <fullName>SAC_EsPrincipal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que informa si se trata de la pretensión principal de la reclamación</description>
    <label>Es Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_GrupoLetrado__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoLetrado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo Letrado</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Cases (Grupo Letrado)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_PretensionPrincipal__c.field-meta.xml
<CustomField>
    <fullName>SAC_PretensionPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo utilizado para indicar la pretensión principal de una reclamación. Utilizado en el proyecto SAC.</description>
    <label>Pretension Principal</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reclamacion</relationshipLabel>
    <relationshipName>Reclamacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_StatusAuxiliar__c.field-meta.xml
<CustomField>
    <fullName>SAC_StatusAuxiliar__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status auxiliar</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_TiempoSLALetradoAlta__c.field-meta.xml
<CustomField>
    <fullName>SAC_TiempoSLALetradoAlta__c</fullName>
    <description>Campo con el calculo de los tiempos SLA Letrado para pretension o Alta para reclamación</description>
    <label>TiempoSLALetrado/Alta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_TiempoSLARegulatorio__c.field-meta.xml
<CustomField>
    <fullName>SAC_TiempoSLARegulatorio__c</fullName>
    <description>Campo resultado del calculo de los tiempos de la sla regulatoria</description>
    <label>TiempoSLARegulatorio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_VueltaAlta__c.field-meta.xml
<CustomField>
    <fullName>SPV_VueltaAlta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este campo valdrá true si la reclamación ha pasado de análisis a alta en algún momento. Si no, valdrá false.</description>
    <label>Vuelta alta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/CC_Tipo_cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_cliente__c</fullName>
    <label>Tipo cliente</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>SAC_DeveloperName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Developer Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email__c</fullName>
    <description>Campo donde se guardaran los emails del grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Dirección de email al cual llegaran las consultas.</inlineHelpText>
    <label>Para</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Causas</relationshipLabel>
    <relationshipName>CC_MCC_Causas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/SAC_Detalle.recordType-meta.xml
<RecordType>
    <fullName>SAC_Detalle</fullName>
    <active>true</active>
    <label>SAC_Detalle</label>
</RecordType>

force-app/main/default/classes/SPV_LCMP_InsertarPretensionTest.cls
@isTest
public with sharing class SPV_LCMP_InsertarPretensionTest {
    
    @TestSetup
    static void makeData(){
        
        Test.startTest();
    User usuarioAdmin = SPV_TestDataFactory.crearUsuarioAdministrador(1)[0];
    usuarioAdmin.Username = 'useraadmin@test.com.testdata';
    //Database.insert(usuarioAdmin);
    SPV_DatabaseDML.insertDML(usuarioAdmin, false);

    User usuario;
    System.runAs(usuarioAdmin){
        usuario = SPV_TestDataFactory.crearUsuarioSPVGeneral(1)[0];
        //Database.insert(usuario);
        SPV_DatabaseDML.insertDML(usuario, false);

        PermissionSet permiSetAdmin = [SELECT Id FROM PermissionSet WHERE Name = 'SPV_Administrador'];
        PermissionSetAssignment permiSetAssiAdmin = new PermissionSetAssignment();
        permiSetAssiAdmin.AssigneeId = usuario.Id;
        permiSetAssiAdmin.PermissionSetId = permiSetAdmin.Id;
        //Database.insert(permiSetAssiAdmin);
        SPV_DatabaseDML.insertDML(permiSetAssiAdmin, false);
    }
    Test.stopTest();    

        List<CC_Grupo_Colaborador__c> listGrupos = new List<CC_Grupo_Colaborador__c>();
        CC_Grupo_Colaborador__c grupo = SPV_TestDataFactory.crearGrupoColaborador('GrupoLetrado', 1)[0];
        //grupo.OwnerId = usuario.id;
        grupo.SAC_Email__c = 'testSPV@testemail.com.invalid';
        grupo.SAC_DeveloperName__c = 'SPV_FYRLEGALLETRADO';
   
        listGrupos.add(grupo);
        //Database.insert(listGrupos);
        SPV_DatabaseDML.insertListDML(listGrupos, false);

        //Añadir las reclamaciones
        List<Case> listaReclamaciones = new List<Case>();
        Map<String, Object> camposReclamacion = new Map<String, Object>();  //Siendo Object tipo genérico
        camposReclamacion.put('Subject', 'TestRec');
        camposReclamacion.put('Origin', 'Backoffice');
        camposReclamacion.put('Status', 'SAC_001');
        camposReclamacion.put('SAC_StatusAuxiliar__c', 'SAC_001');
        camposReclamacion.put('SAC_GrupoLetrado__c', listGrupos[0].Id);

        //Se llama al método que devolverá el caso creado con los campos pasados
        Case casoReclamacion = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion);
        listaReclamaciones.add(casoReclamacion);

        Map<String, Object> camposReclamacion2 = new Map<String, Object>();  //Siendo Object tipo genérico
        camposReclamacion2.put('Subject', 'TestRec2');
        camposReclamacion2.put('Origin', 'Backoffice');
        camposReclamacion2.put('Status', 'SPV_AnalisisDecision');
        camposReclamacion2.put('SAC_StatusAuxiliar__c', 'SPV_AnalisisDecision');
        camposReclamacion2.put('OwnerId', usuario.Id);
        camposReclamacion2.put('SAC_GrupoLetrado__c', listGrupos[0].Id);

        Case casoReclamacion2 = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion2);
        listaReclamaciones.add(casoReclamacion2);

        //Y, una vez obtenidos los casos en una lista, se insertan
        //Database.insert(listaReclamaciones);
        SPV_DatabaseDML.insertListDML(listaReclamaciones, false);

        

        //Se añaden las pretensiones
        List<Case> listaPretensiones = new List<Case>();

        //Pretensión 1
        Map<String, Object> camposPretension = new Map<String, Object>();
        camposPretension.put('OwnerId', usuario.Id);
        camposPretension.put('SuppliedCompany', 'pret1');

        Case pretension1 = SPV_TestDataFactory.crearCaso('Pretension', camposPretension);
        listaPretensiones.add(pretension1);


        //Pretensión 2
        Map<String, Object> camposPretension2 = new Map<String, Object>();
        camposPretension2.put('SAC_Reclamacion__c', casoReclamacion.Id);
        camposPretension2.put('Status', casoReclamacion.Status);
        camposPretension2.put('SAC_StatusAuxiliar__c', casoReclamacion.Status);
        camposPretension2.put('Origin', casoReclamacion.Origin);
        camposPretension2.put('SAC_TiempoSLARegulatorio__c', 30);
        camposPretension2.put('SAC_TiempoSLALetradoAlta__c', 30);
        camposPretension2.put('CC_No_Identificado__c', true);
        camposPretension2.put('CC_IdentCliente__c', '0');
        camposPretension2.put('OwnerId', usuario.id);
        camposPretension2.put('SAC_EsPrincipal__c', true);

        Case pretension2 = SPV_TestDataFactory.crearCaso('Pretension', camposPretension2);
        listaPretensiones.add(pretension2);

        //Database.insert(listaPretensiones);
        SPV_DatabaseDML.insertListDML(listaPretensiones, false);

           //MCCs
           String mccTematicaRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
           String mccProdServRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
           String mccMotivoRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
           String mccDetalleRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('SAC_Detalle').getRecordTypeId();
           
           CC_MCC__c mccTematica = new CC_MCC__c(Name='Tematica', CC_Codigo_Externo__c='a', RecordTypeId=mccTematicaRecordTypeId, CC_Tipo_Cliente__c='SAC');
           //Database.insert(mccTematica);
           SPV_DatabaseDML.insertDML(mccTematica, false);
   
           CC_MCC__c mccProdServ = new CC_MCC__c(Name='ProdServ',CC_Tematica__c = mccTematica.id , CC_Codigo_Externo__c='b', RecordTypeId=mccProdServRecordTypeId, CC_Tipo_Cliente__c='SAC');
           //Database.insert(mccProdServ);
           SPV_DatabaseDML.insertDML(mccProdServ, false);
   
           CC_MCC__c mccMotivo = new CC_MCC__c(Name='Motivo',CC_Producto_Servicio__c = mccProdServ.id, CC_Codigo_Externo__c='c', RecordTypeId=mccMotivoRecordTypeId, CC_Tipo_Cliente__c='SAC');
           //Database.insert(mccMotivo);
           SPV_DatabaseDML.insertDML(mccMotivo, false);
   
           CC_MCC__c mccDetalle = new CC_MCC__c(Name='Detalle',CC_Motivo__c = mccMotivo.id, CC_Codigo_Externo__c='d', RecordTypeId=mccDetalleRecordTypeId, CC_Tipo_Cliente__c='SAC');
           //Database.insert(mccDetalle);
           SPV_DatabaseDML.insertDML(mccDetalle, false);
    }//Fin de makeData



    @isTest
    public static void tienePermisosTest(){
    
        Case reclamacion = [SELECT id, OwnerId FROM Case Where Subject = 'TestRec' LIMIT 1];
        User usuario = [SELECT id FROM User WHERE Username='useraadmin@test.com.testdata' AND isActive = true LIMIT 1];

        Boolean resultado= false;
        System.runAs(usuario){
            Test.startTest();
             resultado = SPV_LCMP_InsertarPretension.tienePermisos(reclamacion.id);
            Test.stopTest();
        }

        //Devuelve true porque una de las pretensiones de esa reclamación tiene como Owner el usuario 
        System.assertEquals(true, resultado, 'No tiene permisos para insertar una pretensión/consulta(Interacción).');

    }



  
    @isTest
    public static void insertarPretensionPrincipalTest(){
        Case casoReclamacion = [SELECT id, Status, Origin, SAC_PretensionPrincipal__c FROM Case WHERE Subject = 'TestRec2' LIMIT 1];
        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];

        System.runAs(usuario){
            Test.startTest();
            SPV_LCMP_InsertarPretension.insertarPretensionPrincipal(casoReclamacion.id, mccs);
            Test.stopTest();
        }
        Case casoReclamacionAct = [SELECT id, Status, Origin, SAC_PretensionPrincipal__c FROM Case WHERE Subject = 'TestRec2' LIMIT 1];
        Case pretension = [SELECT Id, SAC_Reclamacion__c FROM Case WHERE SAC_Reclamacion__c =:casoReclamacion.id];
        System.assertEquals(pretension.id, casoReclamacionAct.SAC_PretensionPrincipal__c, 'No se ha insertado la pretensión como principal.');
        System.assertEquals(pretension.SAC_Reclamacion__c, casoReclamacionAct.id, 'No se ha insertado la pretensión como principal.');


    }


    @isTest
    public static void insertarPretensionPrincipalTest2(){

        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];

        Case pretension = new Case();
        Map<String, Object> campospret = new Map<String, Object>();
        //campospret.put('SAC_Reclamacion__c', casoRelacionado.Id);
        campospret.put('Status', 'SAC_001'); 
        campospret.put('OwnerId', usuario.Id);

        pretension = SPV_TestDataFactory.crearCaso('Pretension', campospret);
        //Database.insert(pretension);
        SPV_DatabaseDML.insertDML(pretension, false);


        Case casoReclamacion = new Case();
        Map<String, Object> camposReclamacion = new Map<String, Object>(); 
        camposReclamacion.put('Subject', 'testRecla');
        camposReclamacion.put('Status', 'SAC_001');
        camposReclamacion.put('SAC_PretensionPrincipal__c', pretension.Id);
        //Se llama al método que devolverá el caso creado con los campos pasados
        casoReclamacion = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion);
        //Database.insert(casoReclamacion);
        SPV_DatabaseDML.insertDML(casoReclamacion, false);

        System.runAs(usuario){
            Test.startTest();
            SPV_LCMP_InsertarPretension.insertarPretensionPrincipal(casoReclamacion.id, mccs);
            Test.stopTest();
        }
        Case casoReclamacionAct = [SELECT id, Status, Origin, SAC_PretensionPrincipal__c FROM Case WHERE Subject = 'testRecla' LIMIT 1];
        Case pretensionRes = [SELECT Id, SAC_Reclamacion__c FROM Case WHERE SAC_Reclamacion__c =:casoReclamacion.id];
        System.assertEquals(pretensionRes.id, casoReclamacionAct.SAC_PretensionPrincipal__c, 'No se ha insertado la pretensión como principal.');
        System.assertEquals(pretensionRes.SAC_Reclamacion__c, casoReclamacionAct.id, 'No se ha insertado la pretensión como principal.');


    }


    @isTest
    static void insertarPretensionCasoRelacionado(){

        Test.startTest();
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];
        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        Boolean respuesta = false;

        Case casoRelacionado = new Case();
        Map<String, Object> camposReclamacion = new Map<String, Object>(); 
        camposReclamacion.put('Subject', 'testrelacionado');
        camposReclamacion.put('Status', 'Cerrado');

        //Se llama al método que devolverá el caso creado con los campos pasados
        casoRelacionado = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion);
        //Database.insert(casoRelacionado);
        SPV_DatabaseDML.insertDML(casoRelacionado, false);

        Case pretension = new Case();
        Map<String, Object> campospret = new Map<String, Object>();
        campospret.put('SAC_Reclamacion__c', casoRelacionado.Id);
        campospret.put('Status', 'SAC_001'); 
        campospret.put('OwnerId', usuario.Id);

        pretension = SPV_TestDataFactory.crearCaso('Pretension', campospret);
        //Database.insert(pretension);
        SPV_DatabaseDML.insertDML(pretension, false);

        casoRelacionado.SAC_PretensionPrincipal__c = pretension.Id;
        //Database.update(casoRelacionado);
        SPV_DatabaseDML.updateDML(casoRelacionado, false);

        Case casoPrincipal = new Case();
        Map<String, Object> camposReclamacion2 = new Map<String, Object>(); 
        camposReclamacion2.put('Subject', 'testNuevo');
        camposReclamacion2.put('Status', 'SAC_001');
        camposReclamacion2.put('SAC_CasoRelacionado__c', casoRelacionado.Id);
        casoPrincipal.SAC_CasoRelacionado__c = casoRelacionado.Id;
        
        casoPrincipal = SPV_TestDataFactory.crearCaso('Reclamacion', camposReclamacion2);
        //Database.insert(casoPrincipal);
        SPV_DatabaseDML.insertDML(casoPrincipal, false);

        System.runAs(usuario){
            respuesta = SPV_LCMP_InsertarPretension.insertarPretensiones(casoPrincipal.id, mccs);
      
        }

        System.assertEquals( true, respuesta, 'No se han insertado las pretensiones');

        Test.stoptest();
    }


    @isTest
    static void insertarPretensionesVueltaAltaTest(){
        Case casoReclamacion = [SELECT id, Status, Origin FROM Case WHERE Subject = 'TestRec' LIMIT 1];
        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        CC_MCC__c mccsRepetido = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle' LIMIT 1];
        mccs.add(mccsRepetido);
        Boolean respuesta = false;
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];
        Case pretension = [SELECT Id FROM Case WHERE SAC_Reclamacion__c = :casoReclamacion.Id LIMIT 1];



        System.runAs(usuario){
            Test.startTest();
            casoReclamacion.SPV_VueltaAlta__c = true;
            casoReclamacion.SAC_PretensionPrincipal__c = pretension.Id;
            //Database.update(casoReclamacion);
            SPV_DatabaseDML.updateDML(casoReclamacion, false);

            respuesta = SPV_LCMP_InsertarPretension.insertarPretensiones(casoReclamacion.id, mccs);
            Test.stopTest();
        }
        System.assertEquals( true, respuesta, 'No se han insertado las pretensiones');
    }

    @isTest
    static void insertarPretensionesAltaTest(){
        Case casoReclamacion = [SELECT id, Status, Origin FROM Case WHERE Subject = 'TestRec' LIMIT 1];
        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        CC_MCC__c mccsRepetido = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle' LIMIT 1];
        mccs.add(mccsRepetido);
        Boolean respuesta = false;
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];

        System.runAs(usuario){
            Test.startTest();
            respuesta = SPV_LCMP_InsertarPretension.insertarPretensiones(casoReclamacion.id, mccs);
            Test.stopTest();
        }
        System.assertEquals( true, respuesta, 'No se han insertado las pretensiones');
    }

    
    @isTest
    static void insertarPretensionesAnalisisTest(){
        List<CC_MCC__c> mccs = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle'];
        CC_MCC__c mccsRepetido = [SELECT id, Name FROM CC_MCC__c WHERE Name='Detalle' LIMIT 1];
        mccs.add(mccsRepetido);
        Boolean respuesta = false;
        Case reclamacion = [SELECT Id, OwnerId FROM Case WHERE subject = 'TestRec2' LIMIT 1];
        Case pretension = [SELECT Id, OwnerId FROM Case WHERE SuppliedCompany = 'pret1' LIMIT 1];
        String idRec = reclamacion.Id; 
        User usuario = [SELECT id FROM User WHERE Username = 'useraadmin@test.com.testdata' AND isActive = true Limit 1];

        System.runAs(usuario){
            Test.startTest();
            reclamacion.SAC_PretensionPrincipal__c = pretension.Id;
            //Database.update(reclamacion);
            SPV_DatabaseDML.updateDML(reclamacion, false);
            respuesta = SPV_LCMP_InsertarPretension.insertarPretensiones(reclamacion.id, mccs);
            Test.stopTest();
        }
		System.assertEquals( true, respuesta, 'No se han insertado las pretensiones');        
    }
    
    
}