force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_GrupoLetrado__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoLetrado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo Letrado</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Cases (Grupo Letrado)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/CC_Grupo_Colaborador_Contact__c.object-meta.xml
<CustomObject>
    <label>Colaborador</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Colaborador Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/fields/CC_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Colaboradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Colaboradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/fields/CC_Usuario__c.field-meta.xml
<CustomField>
    <fullName>CC_Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Email</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Colaboradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/SAC_ProductCase__c.object-meta.xml
<CustomObject>
    <label>Producto de reclamación</label>
    <nameField>
        <displayFormat>PRD-R-{00000}</displayFormat>
        <label>Nombre de Producto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de reclamación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ProductCase__c/fields/N_Contrato__c.field-meta.xml
<CustomField>
    <fullName>N_Contrato__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nº Contrato</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Descripcion__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_DisponemosDeContrato__c.field-meta.xml
<CustomField>
    <fullName>SAC_DisponemosDeContrato__c</fullName>
    <description>Campo para indicar si disponemos de contrato</description>
    <label>Disponemos de contrato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_FechaApertura__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaApertura__c</fullName>
    <description>Fecha de apertura del contrato</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha apertura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_FechaCancelacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaCancelacion__c</fullName>
    <description>Fecha de cancelación del contrato</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha cancelación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Negociar__c.field-meta.xml
<CustomField>
    <fullName>SAC_Negociar__c</fullName>
    <description>Campo para indicar si hay que negociar</description>
    <label>Negociar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Pretension__c.field-meta.xml
<CustomField>
    <fullName>SAC_Pretension__c</fullName>
    <label>Pretensión</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Productos de reclamación</relationshipLabel>
    <relationshipName>Productos_de_reclamacion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_TaeInicialContrato__c.field-meta.xml
<CustomField>
    <fullName>SAC_TaeInicialContrato__c</fullName>
    <description>Campo para indicar el tae inicial del contrato</description>
    <label>Tae inicial contrato</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_TaeMaximoAplicado__c.field-meta.xml
<CustomField>
    <fullName>SAC_TaeMaximoAplicado__c</fullName>
    <description>Campo para indicar el tae máximo aplicado</description>
    <label>Tae máximo aplicado</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Banca particulares</fullName>
            </value>
            <value>
                <fullName>Banca Personal</fullName>
            </value>
            <value>
                <fullName>Caixabank Now</fullName>
            </value>
            <value>
                <fullName>Cartera gestionada</fullName>
            </value>
            <value>
                <fullName>Contrato no aplica</fullName>
            </value>
            <value>
                <fullName>Contrato no localizado</fullName>
            </value>
            <value>
                <fullName>Decesos</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Dia a dia</fullName>
            </value>
            <value>
                <fullName>Disfrutar de la vida</fullName>
            </value>
            <value>
                <fullName>Domicil. recibos</fullName>
            </value>
            <value>
                <fullName>Dormir tranquilo</fullName>
            </value>
            <value>
                <fullName>Fondos</fullName>
            </value>
            <value>
                <fullName>Hipoteca</fullName>
            </value>
            <value>
                <fullName>Hogar</fullName>
            </value>
            <value>
                <fullName>Nómina</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Pensar en el futuro</fullName>
            </value>
            <value>
                <fullName>Pensión</fullName>
            </value>
            <value>
                <fullName>Planes de pensiones</fullName>
            </value>
            <value>
                <fullName>Préstamo</fullName>
            </value>
            <value>
                <fullName>Protección senior</fullName>
            </value>
            <value>
                <fullName>Rentas vitalicias</fullName>
            </value>
            <value>
                <fullName>Renting</fullName>
            </value>
            <value>
                <fullName>Salud</fullName>
            </value>
            <value>
                <fullName>Seguros ahorro</fullName>
            </value>
            <value>
                <fullName>ServiCuentas</fullName>
            </value>
            <value>
                <fullName>Seviam</fullName>
            </value>
            <value>
                <fullName>Sistemas seguridad</fullName>
            </value>
            <value>
                <fullName>Tarjeta crédito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAC_LCMP_ProductosPretensionWOSharing.cls
/*****************************************************************
 * Name: SAC_LCMP_ProductosPretensionWOSharing
 * Copyright © 2024  CaixaBank
 * 
 * Proposito: Clase controlador del componente sac_ProductosPretension
 * Clase test: SAC_LCMP_ProductosPretensionWOSharing_Test
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR         DATE         Description
 * 1.0            --              Iria ANPC     23/12/24        Creación
*****************************************************************/

public without sharing class SAC_LCMP_ProductosPretensionWOSharing {
    
    @AuraEnabled
    public static void createRecordWithoutSharing(String descripcion, String contrato, String tipo, Date fechaApertura, Date fechaCancelacion, Id pretensionId, Decimal taeInicial, Decimal taeMaximo, String negociar, String disponemosContrato) {
        // Get Pretensión
        Case pretension = [SELECT Id, SAC_Reclamacion__r.CC_Grupo_Colaborador__c, SAC_GrupoLetrado__c, SAC_Reclamacion__r.OwnerId FROM Case WHERE Id =: pretensionId];
        List<CC_Grupo_Colaborador_Contact__c> colaboradores = [SELECT Id FROM CC_Grupo_Colaborador_Contact__c WHERE CC_Usuario__c =: UserInfo.getUserId() AND (CC_Colaborador__c =: pretension.SAC_Reclamacion__r.CC_Grupo_Colaborador__c OR CC_Colaborador__c =: pretension.SAC_GrupoLetrado__c) LIMIT 1];
        if(colaboradores.isEmpty() || UserInfo.getUserId() != pretension.SAC_Reclamacion__r.OwnerId){
            throw new AuraHandledException('No tienes permisos para crear el registro');
        }else{
            SAC_ProductCase__c productCase = new SAC_ProductCase__c(
                SAC_Descripcion__c = descripcion,
                N_Contrato__c = contrato,
                SAC_Tipo__c = tipo,
                SAC_FechaApertura__c = fechaApertura,
                SAC_FechaCancelacion__c = fechaCancelacion,
                SAC_Pretension__c = pretensionId,
                SAC_TaeInicialContrato__c = taeInicial,
                SAC_TaeMaximoAplicado__c = taeMaximo,
                SAC_Negociar__c = negociar,
                SAC_DisponemosDeContrato__c = disponemosContrato
            );
            try {
                insert productCase;
            } catch (Exception e) {
                throw new AuraHandledException('Error al crear el registro: ' + e.getMessage());
            }
        }
    }
    
    @AuraEnabled
    public static void editRecordWithoutSharing(String productId, String descripcion, String contrato, String tipo, Date fechaApertura, Date fechaCancelacion, Id pretensionId, Decimal taeInicial, Decimal taeMaximo, String negociar, String disponemosContrato) {
        // Get Pretensión
        Case pretension = [SELECT Id, SAC_Reclamacion__r.CC_Grupo_Colaborador__c, SAC_GrupoLetrado__c, SAC_Reclamacion__r.OwnerId FROM Case WHERE Id =: pretensionId];
        List<CC_Grupo_Colaborador_Contact__c> colaboradores = [SELECT Id FROM CC_Grupo_Colaborador_Contact__c WHERE CC_Usuario__c =: UserInfo.getUserId() AND (CC_Colaborador__c =: pretension.SAC_Reclamacion__r.CC_Grupo_Colaborador__c OR CC_Colaborador__c =: pretension.SAC_GrupoLetrado__c) LIMIT 1];
        if(colaboradores.isEmpty() || UserInfo.getUserId() != pretension.SAC_Reclamacion__r.OwnerId){
            throw new AuraHandledException('No tienes permisos para editar el registro');
        }else{
            SAC_ProductCase__c productCase = [SELECT Id, SAC_Descripcion__c, N_Contrato__c, SAC_Tipo__c, SAC_FechaApertura__c, SAC_FechaCancelacion__c,
                                              SAC_TaeInicialContrato__c, SAC_TaeMaximoAplicado__c, SAC_Negociar__c, SAC_DisponemosDeContrato__c
                                              FROM SAC_ProductCase__c WHERE Id =: productId LIMIT 1];
            productCase.SAC_Descripcion__c = descripcion;
            productCase.N_Contrato__c = contrato;
            productCase.SAC_Tipo__c = tipo;
            productCase.SAC_FechaApertura__c = fechaApertura;
            productCase.SAC_FechaCancelacion__c = fechaCancelacion;
            productCase.SAC_TaeInicialContrato__c = taeInicial;
            productCase.SAC_TaeMaximoAplicado__c = taeMaximo;
            productCase.SAC_Negociar__c = negociar;
            productCase.SAC_DisponemosDeContrato__c = disponemosContrato;
            
            try {
                update productCase;
            } catch (Exception e) {
                throw new AuraHandledException('Error al actualizar el registro: ' + e.getMessage());
            }
        }
    }
}