force-app/main/default/objects/Case/fields/CC_Importe_Abonado__c.field-meta.xml
<CustomField>
    <fullName>CC_Importe_Abonado__c</fullName>
    <label>Importe abonado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Importe_Reclamado__c.field-meta.xml
<CustomField>
    <fullName>CC_Importe_Reclamado__c</fullName>
    <label>Importe reclamado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Oficina_Afectada_Lookup__c.field-meta.xml
<CustomField>
    <fullName>CC_Oficina_Afectada_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina afectada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Oficina Afectada)</relationshipLabel>
    <relationshipName>CasesLookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_CasoNegociado__c.field-meta.xml
<CustomField>
    <fullName>SAC_CasoNegociado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check para indicar cuando un caso a pasado por negociación y así poder controlar el cierre de los case milestone</description>
    <label>Caso negociado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_DetalleResultadoNegociacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_DetalleResultadoNegociacion__c</fullName>
    <label>Detalle resultado negociación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Factoría</fullName>
            </value>
            <value>
                <fullName>Falta de respuesta</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Préstamo usura – Acepta – TIN 10%</fullName>
            </value>
            <value>
                <fullName>Préstamo usura – Acepta – TIN 13%</fullName>
            </value>
            <value>
                <fullName>Préstamo usura – Acepta – TIN 6,5%</fullName>
            </value>
            <value>
                <fullName>Préstamo usura – Demanda – NO Pago Directo</fullName>
            </value>
            <value>
                <fullName>Rechazo expreso</fullName>
            </value>
            <value>
                <fullName>Revolving - Acepta - TAE 10,99%</fullName>
            </value>
            <value>
                <fullName>Revolving - Acepta - TAE 14,99%</fullName>
            </value>
            <value>
                <fullName>Revolving - Acepta - TAE 7,5%</fullName>
            </value>
            <value>
                <fullName>Revolving – Demanda – NO Pago Directo</fullName>
            </value>
            <value>
                <fullName>Revolving - Rechaza  - Cierre SR</fullName>
            </value>
            <value>
                <fullName>Revolving - Rechaza - Pago Directo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Importe_Resuelto__c.field-meta.xml
<CustomField>
    <fullName>SAC_Importe_Resuelto__c</fullName>
    <label>Importe resuelto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Importe_ResultadoNegociacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Importe_ResultadoNegociacion__c</fullName>
    <label>Importe ahorro negociación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_NegociacionFinalizada__c.field-meta.xml
<CustomField>
    <fullName>SAC_NegociacionFinalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que sirve para comprobar si la pretensión ha acabado su proceso de negociación</description>
    <label>Negociación finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_ProrrogaCounter__c.field-meta.xml
<CustomField>
    <fullName>SAC_ProrrogaCounter__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Contador que almacenará el numero de veces que la reclamación ha sido prorrogada</description>
    <label>Número Prórrogas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_RedaccionFinal__c.field-meta.xml
<CustomField>
    <fullName>SAC_RedaccionFinal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Listo para redacción final</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_ResultadoNegociacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_ResultadoNegociacion__c</fullName>
    <label>Resultado de negociación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acuerdo revocado</fullName>
            </value>
            <value>
                <fullName>Con acuerdo</fullName>
            </value>
            <value>
                <fullName>Con acuerdo parcial</fullName>
            </value>
            <value>
                <fullName>Sin acuerdo</fullName>
            </value>
            <value>
                <fullName>Sin respuesta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_SentidoResolucion__c.field-meta.xml
<CustomField>
    <fullName>SAC_SentidoResolucion__c</fullName>
    <description>Indica el sentido de la resolución: favorable, no favorable, favorable parcialmente etc.</description>
    <label>Sentido resolución</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_001</fullName>
                <label>A favor de la entidad</label>
            </value>
            <value>
                <fullName>SAC_002</fullName>
                <label>Favorable al cliente parcialmente</label>
            </value>
            <value>
                <fullName>SAC_003</fullName>
                <label>A favor del cliente</label>
            </value>
            <value>
                <fullName>SAC_004</fullName>
                <label>Inadmisión</label>
            </value>
            <value>
                <fullName>SAC_005</fullName>
                <label>Desistimiento</label>
            </value>
            <value>
                <fullName>SAC_006</fullName>
                <label>Allanamiento</label>
            </value>
            <value>
                <fullName>SAC_007</fullName>
                <label>Errónea</label>
            </value>
            <value>
                <fullName>SAC_008</fullName>
                <label>Incompetente</label>
            </value>
            <value>
                <fullName>SAC_009</fullName>
                <label>Sin pronunciamiento</label>
            </value>
            <value>
                <fullName>SPV_FavorableEntidad</fullName>
                <label>Favorable a Entidad</label>
            </value>
            <value>
                <fullName>SPV_DesfavorableEntidadTotal</fullName>
                <label>Desfavorable a Entidad Total</label>
            </value>
            <value>
                <fullName>SPV_DesfavorableEntidadParcial</fullName>
                <label>Desfavorable a Entidad Parcial</label>
            </value>
            <value>
                <fullName>SPV_Inadmitida</fullName>
                <label>Inadmitida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_StatusAuxiliar__c.field-meta.xml
<CustomField>
    <fullName>SAC_StatusAuxiliar__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status auxiliar</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_TipoConsumidor__c.field-meta.xml
<CustomField>
    <fullName>SAC_TipoConsumidor__c</fullName>
    <label>Consumidor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Si</fullName>
                <label>Sí</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Detalle__c.field-meta.xml
<CustomField>
    <fullName>SEG_Detalle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Detalle del MCC</description>
    <inlineHelpText>Detalle del MCC</inlineHelpText>
    <label>Detalle</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 3) AND 2</booleanFilter>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SAC Detalle</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Motivo__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Motivo__c</valueField>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Detalle</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Casos (MCC)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/SEG_Detalle__c.field-meta.xml
<CustomField>
    <fullName>SEG_Detalle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Detalle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Detalle</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Detalles</relationshipLabel>
    <relationshipName>SEG_MCC_Detalle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/SAC_Detalle.recordType-meta.xml
<RecordType>
    <fullName>SAC_Detalle</fullName>
    <active>true</active>
    <label>SAC_Detalle</label>
</RecordType>

force-app/main/default/classes/SAC_LCMP_CamposDetalleNegociacion_Test.cls
@isTest 
public with sharing class SAC_LCMP_CamposDetalleNegociacion_Test {
    @TestSetup
    static void makeData() {
        User usuario;

        Test.startTest();
        User usuarioAdmin = SAC_TestDataFactory.crearUsuarioAdministrador(1)[0];
        SAC_DatabaseDML.insertDML(usuarioAdmin, false);

        System.runAs(usuarioAdmin) {
            List<User> usuariosGenerales = SAC_TestDataFactory.crearUsuarioSACGeneral(1);
            usuariosGenerales[0].Username = 'Name12345@test.com';            
            usuario = usuariosGenerales[0];
            SAC_DatabaseDML.insertListDML(usuariosGenerales, false);

            PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
            PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
            permiSetAssi.AssigneeId = usuario.Id;
            permiSetAssi.PermissionSetId = permiSet.Id;
            SAC_DatabaseDML.insertDML(permiSetAssi, false);
        }
        //Cuentas
        Account cuenta = SAC_TestDataFactory.crearCuentas(1)[0];       
        Account ofi = SAC_TestDataFactory.crearCuentasOficina(1)[0];
        
        List<Account> listaCuentas = new List<Account>();
        listaCuentas.add(cuenta);
        listaCuentas.add(ofi);
        SAC_DatabaseDML.insertListDML(listaCuentas, false);
        Test.stopTest();

        //RECLAMACION
        Map<String, Object> camposRecl = new Map<String, Object>();
        camposRecl.put('Subject', 'TestRec');
        camposRecl.put('Origin', 'Otros');
        camposRecl.put('Status', 'SAC_007');
        camposRecl.put('OwnerId', usuario.Id);
        camposRecl.put('SAC_StatusAuxiliar__c', 'SAC_007');
        camposRecl.put('AccountId', cuenta.Id);
        camposRecl.put('SAC_ProrrogaCounter__c', 0);
        camposRecl.put('SuppliedEmail', 't.t@t.t');
        camposRecl.put('SAC_TipoConsumidor__c', 'Si');
        camposRecl.put('SAC_CasoNegociado__c', true);
        camposRecl.put('CC_Oficina_Afectada_Lookup__c', ofi.Id);
        
        Case casoReclamacion = SAC_TestDataFactory.crearCaso('Reclamacion', camposRecl);

        List<Case> casosReclamacion = new List<Case>();
        casosReclamacion.add(casoReclamacion);
        SAC_DatabaseDML.insertListDML(casosReclamacion, false);

        //Creacion MCC
        CC_MCC__c mcc = new CC_MCC__c();
        mcc.Name = 'MCC Test';
        mcc.RecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('SAC_Detalle').getRecordTypeId();
        SAC_DatabaseDML.insertDML(mcc, false);

        // PRETENSION
        Map<String, Object> camposPret = new Map<String, Object>();
        camposPret.put('Subject', 'TestPret');
        camposPret.put('SuppliedCompany', 'TestPret');
        camposPret.put('Origin', 'Otros');
        camposPret.put('Status', 'SAC_007');
        camposPret.put('SAC_StatusAuxiliar__c', 'SAC_007');
        camposPret.put('SAC_SentidoResolucion__c', 'SAC_002');
        camposPret.put('SAC_RedaccionFinal__c', true);
        camposPret.put('SAC_NegociacionFinalizada__c', true);
        camposPret.put('CC_Importe_Reclamado__c', 50);
        camposPret.put('SAC_Importe_Resuelto__c', 50);
        camposPret.put('CC_Importe_Abonado__c', 50);
        camposPret.put('SAC_Importe_ResultadoNegociacion__c', 50);
        camposPret.put('SAC_ResultadoNegociacion__c', 'Con acuerdo');
        camposPret.put('SAC_DetalleResultadoNegociacion__c', 'Factoría');
        camposPret.put('OwnerId', usuario.Id);
        camposPret.put('SAC_Reclamacion__c', casoReclamacion.Id);
        camposPret.put('AccountId', cuenta.Id);
        camposPret.put('SEG_Detalle__c', mcc.Id);
        
        Case pretension = SAC_TestDataFactory.crearCaso('Pretension', camposPret);
        
        List<Case> casosPretension = new List<Case>();
        casosPretension.add(pretension);
        SAC_DatabaseDML.insertListDML(casosPretension, false);
    }


    @isTest
    static void getNegociacionesPretensionTest(){
        Test.startTest();
        Case reclamacion = [SELECT Id, Status FROM Case WHERE Subject = 'TestRec'];

        List<Case> resultado;

        User usuario = [SELECT id FROM User WHERE Username = 'Name12345@test.com' AND isActive = true LIMIT 1];
        
		System.runAs(usuario){
            resultado = SAC_LCMP_CamposDetalleNegociacion.getNegociacionesPretension(reclamacion.Id);
        }
        Test.stopTest();

        Assert.areEqual(false, resultado.isEmpty(), 'No se han recuperado las pretensiones negociadas de la reclamación');
    }
}