force-app/main/default/objects/Case/fields/CC_Importe_Reclamado__c.field-meta.xml
<CustomField>
    <fullName>CC_Importe_Reclamado__c</fullName>
    <label>Importe reclamado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Importe_Resuelto__c.field-meta.xml
<CustomField>
    <fullName>SAC_Importe_Resuelto__c</fullName>
    <label>Importe resuelto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_ResultadoNegociacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_ResultadoNegociacion__c</fullName>
    <label>Resultado de negociación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acuerdo revocado</fullName>
            </value>
            <value>
                <fullName>Con acuerdo</fullName>
            </value>
            <value>
                <fullName>Con acuerdo parcial</fullName>
            </value>
            <value>
                <fullName>Sin acuerdo</fullName>
            </value>
            <value>
                <fullName>Sin respuesta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_StatusAuxiliar__c.field-meta.xml
<CustomField>
    <fullName>SAC_StatusAuxiliar__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status auxiliar</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/SAC_ParametrizacionSLATME__c.object-meta.xml
<CustomObject>
    <label>Parametrización SLA / TMO</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizaciones SLA / TMO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_Duracion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Duracion__c</fullName>
    <label>Duración(Días)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_Estados__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estados__c</fullName>
    <label>Estados</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_001</fullName>
                <label>Alta</label>
            </value>
            <value>
                <fullName>SAC_002</fullName>
                <label>Análisis</label>
            </value>
            <value>
                <fullName>SAC_003</fullName>
                <label>Redacción</label>
            </value>
            <value>
                <fullName>SAC_004</fullName>
                <label>Ejecución</label>
            </value>
            <value>
                <fullName>SAC_006</fullName>
                <label>Subsanación</label>
            </value>
            <value>
                <fullName>SAC_007</fullName>
                <label>Negociación</label>
            </value>
            <value>
                <fullName>SAC_009</fullName>
                <isActive>false</isActive>
                <label>Baja</label>
            </value>
            <value>
                <fullName>SAC_008</fullName>
                <isActive>false</isActive>
                <label>Derivación</label>
            </value>
            <value>
                <fullName>SAC_005</fullName>
                <isActive>false</isActive>
                <label>Inadmisión</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/SAC_TMECaso__c.object-meta.xml
<CustomObject>
    <label>TMO Caso</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de TMO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAC_TMECaso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_Caso__c.field-meta.xml
<CustomField>
    <fullName>SAC_Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>TME_Caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_Parametrizacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Parametrizacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parametrización</label>
    <referenceTo>SAC_ParametrizacionSLATME__c</referenceTo>
    <relationshipName>SAC_TME_Caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_TMECaso__c/fields/SAC_TMEDefinido__c.field-meta.xml
<CustomField>
    <fullName>SAC_TMEDefinido__c</fullName>
    <label>TMO Definido</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SAC_AsignarTMEs_Test.cls
@isTest
public with sharing class SAC_AsignarTMEs_Test {
    @isTest
    static void actualizacionCaso() {

        //Usuario SAC General
		User usuarioGeneral = SAC_TestDataFactory.crearUsuarioSACGeneral(1)[0];      
        Database.insert(usuarioGeneral);

        PermissionSet permiSet = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_General'];
        PermissionSetAssignment permiSetAssi = new PermissionSetAssignment();
        permiSetAssi.AssigneeId = usuarioGeneral.Id;
        permiSetAssi.PermissionSetId = permiSet.Id;
        Database.insert(permiSetAssi);

        //Usuario SAC Admin
		User usuarioAdmin = SAC_TestDataFactory.crearUsuarioSACGeneral(1)[0];
        usuarioAdmin.Username = 'usertestadmin@test.com.testSetup';      
        Database.insert(usuarioAdmin);

        PermissionSet permiSetAdmin = [SELECT Id FROM PermissionSet WHERE Name = 'SAC_Administrador'];
        PermissionSetAssignment permiSetAssiAdmin = new PermissionSetAssignment();
        permiSetAssiAdmin.AssigneeId = usuarioAdmin.Id;
        permiSetAssiAdmin.PermissionSetId = permiSetAdmin.Id;
        Database.insert(permiSetAssiAdmin);

        System.runAs(usuarioAdmin){
            List<CC_MCC__c> mccs = SAC_TestDataFactory.crearMCCs();
            Database.insert(mccs);
            List<SAC_ParametrizacionSLATME__c> listaParams = SAC_TestDataFactory.crearParamsSla('TME',3);
            listaParams[0].SAC_Duracion__c = 5; 
            listaParams[0].SAC_Estados__c='SAC_002';
            listaParams[1].SAC_Duracion__c = 10;
            listaParams[1].SAC_Estados__c='SAC_002;SAC_003';
            listaParams[2].SAC_Duracion__c = 15;
            listaParams[2].SAC_Estados__c='SAC_007';  
            Database.insert(listaParams);
        }
        
        System.runAs(usuarioGeneral){
            //Reclamacion
            Map<String, Object> camposRecl = new Map<String, Object>();
            camposRecl.put('Subject', 'TestRec');

            Case reclamacion = SAC_TestDataFactory.crearCaso('Reclamacion',camposRecl);
            Database.insert(reclamacion);

            //Pretension
            Map<String, Object> camposPret = new Map<String, Object>();
            camposPret.put('Subject', 'TestPret');
            camposPret.put('SAC_Reclamacion__c', reclamacion.Id);

            Case casoPretension = SAC_TestDataFactory.crearCaso('Pretension',camposPret);
            Database.insert(casoPretension);
        }

        Case caso = [SELECT Id FROM Case WHERE Subject = 'TestPret' LIMIT 1];

        List<SAC_TMECaso__c> tmeCreado = [SELECT Id, SAC_Parametrizacion__c, SAC_Caso__c, SAC_TMEDefinido__c, Name
                            FROM SAC_TMECaso__c 
                            WHERE SAC_Caso__c =: caso.Id];

        caso.Status = 'SAC_002';
        caso.SAC_StatusAuxiliar__c = caso.Status;

        User usuario = [SELECT id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND isActive = true LIMIT 1];
		System.runAs(usuario){
            Test.startTest();
            Database.update(caso);        
            
            Case casov2 = caso;

            List<SAC_TMECaso__c> tmeCreadov2 = [SELECT Id, SAC_Parametrizacion__c, SAC_Caso__c, SAC_TMEDefinido__c, Name
                                FROM SAC_TMECaso__c 
                                WHERE SAC_Caso__c =: caso.Id];

            casov2.Status = 'SAC_007';
            casov2.SAC_StatusAuxiliar__c = casov2.Status;

            SAC_Case_BU_TRHan.actualizarVariablesControl();
            Database.update(casov2);

            Case casov3 = casov2;

            List<SAC_TMECaso__c> tmeCreadov3 = [SELECT Id, SAC_Parametrizacion__c, SAC_Caso__c, SAC_TMEDefinido__c, Name
                FROM SAC_TMECaso__c 
                WHERE SAC_Caso__c =: casov2.Id];

            casov3.Status = 'SAC_002';
            casov3.SAC_StatusAuxiliar__c = casov3.Status;
            casov3.CC_Importe_Reclamado__c = 200;
            casov3.SAC_Importe_Resuelto__c = 100;
            casov3.SAC_ResultadoNegociacion__c = 'Con acuerdo';
            SAC_Case_BU_TRHan.actualizarVariablesControl();
            Database.update(casov3);

            system.assertNotEquals(tmeCreado, tmeCreadov2, 'No se han creado TMEs en la actualizacion');
            system.assertNotEquals(tmeCreadov2, tmeCreadov3, 'No se han creado TMEs en la actualizacion');
            Test.stopTest();
        }  
    }
}