force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CBK_Activity_Extension__c/CBK_Activity_Extension__c.object-meta.xml
<CustomObject>
    <label>Activity Extension</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CRM_Tarea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities Extension</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_Activity_Extension__c/fields/AV_ActivityId__c.field-meta.xml
<CustomField>
    <fullName>AV_ActivityId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Campo para guardar la id de la tarea o evento relacionado con la CRM tarea.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actividad relacionada</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CBK_Activity_Extension__c/fields/CC_Tipo_de_cita__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_de_cita__c</fullName>
    <description>Campo utilizado para la operativa Cita gestor y especificar si es por telefono o en persona.</description>
    <label>Tipo de cita</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cita telefónica</fullName>
            </value>
            <value>
                <fullName>Cita presencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CBK_Activity_Extension__c/recordTypes/CC_Task.recordType-meta.xml
<RecordType>
    <fullName>CC_Task</fullName>
    <active>true</active>
    <description>Activity extensions de CC</description>
    <label>CC Task</label>
</RecordType>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/CC_Buzones_Por_Defecto__mdt.object-meta.xml
<CustomObject>
    <label>Buzón por defecto</label>
    <pluralLabel>Buzones por defecto</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Direccion_Correo__c.field-meta.xml
<CustomField>
    <fullName>CC_Direccion_Correo__c</fullName>
    <label>Dirección de correo</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Mensajes_Mostrar__c.field-meta.xml
<CustomField>
    <fullName>CC_Mensajes_Mostrar__c</fullName>
    <description>Utilizado para mostrar mensajes largos</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mensajes a mostrar</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Settings__c/CC_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting reutilizable para NIC</description>
    <label>CC_Settings</label>
</CustomObject>

force-app/main/default/objects/CC_Settings__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Settings__c/fields/CC_Configuracion_1__c.field-meta.xml
<CustomField>
    <fullName>CC_Configuracion_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Configuracion_1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Settings__c/fields/CC_Configuracion_2__c.field-meta.xml
<CustomField>
    <fullName>CC_Configuracion_2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Configuracion_2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Settings__c/fields/CC_Configuracion_6__c.field-meta.xml
<CustomField>
    <fullName>CC_Configuracion_6__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Configuracion_6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/CC_TrazaInt__c.object-meta.xml
<CustomObject>
    <description>Trazas de integraciones</description>
    <label>Traza Integraciones</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interfaz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trazas Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/CC_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Procedencia__c</fullName>
    <description>Origen del email (Traslado colaborador o Remitir colaborador)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Operativa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/CC_Task.recordType-meta.xml
<RecordType>
    <fullName>CC_Task</fullName>
    <active>true</active>
    <description>Tarea (Contact Center)</description>
    <label>Tarea</label>
</RecordType>

force-app/main/default/classes/CC_WS_Alta_Citas.cls
public with sharing class CC_WS_Alta_Citas {
    public static Map<String, Object> altaCita(String numOficina, String numPer, String fechaSeleccionada, String franjaSeleccionada, String asunto, String recordId, String tipoCita) {
        Map<String, Object> resultado = new Map<String, Object>();

        Case casoAltaCita = [SELECT Id, CC_Idioma__c, ContactId, Contact.Email, OwnerId, Account.Name, CaseNumber FROM Case WHERE Id = :recordId LIMIT 1];
        CC_Lista_Valores__c listaValorTareaCita = [SELECT Id, CC_Activa__c, CC_Mensajes_Mostrar__c FROM CC_Lista_Valores__c WHERE Name = 'Texto cita o tarea existe' LIMIT 1];
        Boolean existenTareasCitas = CC_Activity.identificarTareasCitasExistentes( casoAltaCita, listaValorTareaCita);

        if (String.isBlank(numPer)) {
            CBK_Log.error('Numperso no informado');
        }else if(!existenTareasCitas){
            try {
                CC_Settings__c configuracion = CC_Settings__c.getValues('CC_Configuracion_Cita_Rapida');
                //Blob digest = Crypto.generateDigest('SHA-256', Blob.valueOf(numPer + 'asesorVentas1'));//se quita por la US1169531
                Blob digest = Crypto.generateDigest('SHA-512', Blob.valueOf(numPer));
                String branchHashId = EncodingUtil.convertToHex(digest);
                Map<String, String> requestHeaders = getRequestHeaders();
                
                asunto = (tipoCita == String.valueOf(42) ? ' Cita presencial' : ' Cita telefónica') + ' - ' + asunto;
                Map<String, String> bodyRequest = new Map<String, String>();
                bodyRequest.put('branchId', numOficina);
                bodyRequest.put('reasonId', '999');
                bodyRequest.put('reasonText', asunto);
                bodyRequest.put('waitingRoomDate', fechaSeleccionada);
                bodyRequest.put('device', configuracion.CC_Configuracion_6__c);
                bodyRequest.put('slotStartTime', franjaSeleccionada.substring(0, 5));
                bodyRequest.put('reservationType', configuracion.CC_Configuracion_2__c);
                //bodyRequest.put('customerInternalId', numPer); //se quita por la US1169531
                bodyRequest.put('customerInternalHashId', branchHashId);
                String jsonBody = JSON.serialize(bodyRequest);

                CBK_HttpServiceIntegration.RequestWapper integracion = new CBK_HttpServiceIntegration.RequestWapper();
                integracion.intSetting = 'CC_Alta_Cita';
                integracion.mHeaders = requestHeaders;
                integracion.body = jsonBody;
                
                HttpRequest request = CBK_HttpServiceIntegration.getRequest(integracion);

                HttpResponse response = CBK_HttpServiceIntegration.callHttpService(request, 'CC_WS_Alta_Citas', integracion.intSetting);
                
                if(response.getStatusCode() != 200 && response.getStatusCode() != 201) {
                    Map<String, Object> parsedError = new Map<String, Object>();
                    String detail = 'El servidor de Agendar Citas ha devuelto un error';
                    if (String.isNotBlank(response.getBody())) {
                        parsedError = (Map<String, Object>) JSON.deserializeUntyped(response.getbody());
                        detail = parsedError.containsKey('detail') ? (String) parsedError.get('detail') : 'El servidor de Agendar Citas ha devuelto un error';
                    }
                    CC_TrazaInt__c traza = CC_TrazaInt.generarTraza('CC_WS_Alta_Citas', request.getEndpoint(), String.valueOf(response.getStatusCode()), String.valueOf(request), detail, response.getBody(), false);
                    throw new AltaCitaCustomException(detail);
                } else {
                    String fechaConvertida = String.valueOf(Date.valueOf(fechaSeleccionada).day()) + '-' + 
                                            String.valueOf(Date.valueOf(fechaSeleccionada).month()) + '-' + 
                                            String.valueOf(Date.valueOf(fechaSeleccionada).year());
                    String mensaje = '';
                    Map<String, String> textosMap = new Map<String, String>();
                    List<CC_Lista_Valores__c> textos = [SELECT Name, CC_Mensajes_Mostrar__c FROM CC_Lista_Valores__c WHERE CC_Lista__r.Name = 'Textos operativa Derivar' AND CC_Activa__c = true];
                    for(CC_Lista_Valores__c texto : textos) {
                        textosMap.put(texto.Name, texto.CC_Mensajes_Mostrar__c);
                    }
                    if(tipoCita == '42') {
                        mensaje = textosMap.get('Toast cita rapida presencial').replace('XX:XX', franjaSeleccionada.substring(0, 5));
                        mensaje = mensaje.replace('XX', fechaConvertida);
                    } else {
                        mensaje = textosMap.get('Toast cita rapida telefonica').replace('XX:XX', franjaSeleccionada.substring(0, 5));
                        mensaje = mensaje.replace('XX', fechaConvertida);
                    }
                    resultado.put('mensaje', mensaje);
                    //Case casoAltaCita = [SELECT Id, CC_Idioma__c, ContactId, Contact.Email, OwnerId, Account.Name, CaseNumber FROM Case WHERE Id = :recordId LIMIT 1];
                    CC_Settings__c envioCorreoActivo = CC_Settings__c.getValues('CC_Configuracion_Cita_Rapida');

                    try {
                        crearTarea(casoAltaCita, asunto, fechaConvertida, franjaSeleccionada, tipoCita);
                        if(Boolean.valueOf(envioCorreoActivo.CC_Configuracion_1__c)) {
                            try {
                                enviarCorreo(casoAltaCita.CC_Idioma__c, recordId, casoAltaCita.ContactId, casoAltaCita.Contact.Email, fechaSeleccionada, franjaSeleccionada, asunto, tipoCita, casoAltaCita.Account.Name, casoAltaCita.caseNumber);
                                resultado.put('resultado', 'OK');
                            } catch (Exception e) {
                                resultado.put('resultado', 'KO');
                                resultado.put('resultadoMensaje', 'Ha habido un problema al enviar el correo');
                                CBK_Log.error(e);
                            }
                        } else {
                            resultado.put('resultado', 'OK');
                        }
                    } catch (Exception e) {
                        resultado.put('resultado', 'KO');
                        resultado.put('resultadoMensaje', 'Ha habido un problema al crear la tarea');
                        resultado.put('error', e);
                        CBK_Log.error(e);
                    }
                }
            } catch (Exception e) {
                resultado.put('resultado', 'KO');
                resultado.put('resultadoMensaje', 'Ha habido un problema con la integración');
                resultado.put('error', e);
                CBK_Log.error(e);
                throw new AuraException(e.getMessage());
            }
        }else{
            resultado.put('textoTareaCitaCreada', listaValorTareaCita.CC_Mensajes_Mostrar__c);
            resultado.put('existeTareaCitaCreada', true);
        }
        return resultado;
    }

    @AuraEnabled
    public static Map<String, Object> crearAltaCita(String numOficina, String numPer, String fechaSeleccionada, String franjaSeleccionada, String asunto, String recordId, String tipoCita) {
        return altaCita(numOficina, numPer, fechaSeleccionada, franjaSeleccionada, asunto, recordId, tipoCita);
    }

    private static void enviarCorreo(String idioma, String recordId, String contactId, String emailContact, String fechaSeleccionada, String franjaSeleccionada, String asunto, String tipoCita, String nombreCliente, String caseNumber) {
        Id idBuzonSalida = getBuzonSalidaId();
        List<Messaging.SingleEmailMessage> correos = new List<Messaging.SingleEmailMessage>();
        EmailTemplate plantilla = new EmailTemplate();

        if (idBuzonSalida == null) {
            throw new AuraHandledException('El buzón de salida no está configurado');
        }

        if(idioma == 'ca') {
            plantilla = [SELECT Subject, Id, HTMLValue FROM EmailTemplate WHERE DeveloperName = 'Plantilla_Cita_Rapida_ca' LIMIT 1];
        } else if(idioma == 'en') {
            plantilla = [SELECT Subject, Id, HTMLValue FROM EmailTemplate WHERE DeveloperName = 'Plantilla_Cita_Rapida_en' LIMIT 1];
        } else {
            plantilla = [SELECT Subject, Id, HTMLValue FROM EmailTemplate WHERE DeveloperName = 'Plantilla_Cita_Rapida_es' LIMIT 1];
        }

        if(fechaSeleccionada != null) {
            plantilla.HTMLValue = plantilla.HTMLValue.replace('(Fecha)', fechaSeleccionada);
        }
        if(franjaSeleccionada != null) {
            plantilla.HTMLValue = plantilla.HTMLValue.replace('(Hora)', franjaSeleccionada);
        }

        if(caseNumber != null) {
            plantilla.HTMLValue = plantilla.HTMLValue.replace('(caseNumber)', caseNumber);
        }

        if(tipoCita != null) {
            plantilla.HTMLValue = plantilla.HTMLValue.replace('(Tipo de cita)', tipoCita == String.valueOf(42) ? ' Cita presencial' : ' Cita telefónica');
        }
       
        if (emailContact != null) {
            Messaging.SingleEmailMessage renderStored = Messaging.renderStoredEmailTemplate(plantilla.Id, UserInfo.getUserId(), recordId);
            Messaging.SingleEmailMessage correo = new Messaging.SingleEmailMessage();
            String asuntoCorreo = renderStored.getSubject();
            asuntoCorreo += ' ' + (tipoCita == String.valueOf(42) ? ' Cita presencial' : ' Cita telefónica') + ' - ' + nombreCliente;
            correo.Subject = asuntoCorreo;
            correo.setHtmlBody(plantilla.HTMLValue);
            correo.setSaveAsActivity(true);
            correo.setWhatId(recordId);
            correo.setTargetObjectId(contactId);
            correo.setToAddresses(new List<String>{emailContact});
            correo.setOrgWideEmailAddressId(idBuzonSalida);
            correos.add(correo);
        }

        if (!correos.isEmpty()) {
            if (!Test.isRunningTest()) {
                Messaging.sendEmail(correos, false);
            } else {
                EmailMessage correoOrigen = new EmailMessage();
                correoOrigen.Subject = 'Prueba de envío de correo';     
                correoOrigen.CC_Procedencia__c = 'Responder Cliente';
                correoOrigen.FromAddress = 'prueba@ibm.com';
                correoOrigen.ToAddress = 'prueba@ibm.com';
                correoOrigen.Incoming = true;
                correoOrigen.ParentId = recordId;
                correoOrigen.RelatedToId = recordId;
                correoOrigen.Headers = '[{"value": "","name": "X-SFDC-Original-RCPT"}]';
                correoOrigen.HtmlBody = 'Cuerpo<br/>';
                insert correoOrigen;
            }
        }
    }

    private static void crearTarea(Case caso, String asunto, String fecha, String franja, String tipoCita) {
        String cita = tipoCita == String.valueOf(42) ? ' Cita presencial' : ' Cita telefónica';
        Task tarea = new Task();
        tarea.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'CC_Task');
        tarea.Subject = 'Cita gestor solicitada correctamente';
        tarea.Description = 'Se ha generado la cita correctamente.' + '\n' + '\n';
        tarea.Description += 'Asunto: ' + asunto + '\n';
        tarea.Description += 'Tipo de cita: ' + cita + '\n';
        tarea.Description += 'Fecha: ' + fecha + '\n';
        tarea.Description += 'Hora: ' + franja + '\n';
        tarea.Status = 'Completed';
        tarea.Priority = 'Normal';
        tarea.ActivityDate = date.today();
        tarea.WhatId = caso.Id;
        tarea.OwnerId = caso.OwnerId;
        tarea.Type = 'Cita rápida gestor';
        insert tarea;
        CBK_Activity_Extension__c tareaExtension = new CBK_Activity_Extension__c();
        tareaExtension.CC_Tipo_de_cita__c = tipoCita == String.valueOf(42) ? 'Cita presencial' : 'Cita telefónica';
        tareaExtension.AV_ActivityId__c = tarea.Id;
        insert tareaExtension;
    }
    
    private static Id getBuzonSalidaId() {
        String buzonDefecto = [SELECT CC_Direccion_Correo__c FROM CC_Buzones_Por_Defecto__mdt WHERE Label = 'Atención Cliente - ESP' AND CC_Activo__c = TRUE LIMIT 1]?.CC_Direccion_Correo__c;
        return [SELECT Id FROM OrgWideEmailAddress WHERE Address = :buzonDefecto LIMIT 1]?.Id;
    }

    private static Map<String, String> getRequestHeaders() {
		/* Ejemplo de headers:
			· Content-Type: application/json;charset=UTF-8
			· x-api-actor-simulated: CCSF 	(solo para previos)
			· HTTP-HEADER-ACTOR: CBCCSF 	(solo para previos)
		*/
		//Map<String, String> headers = new Map<String, String>{'HTTP-HEADER-ACTOR' => 'CBCCSF'};
        Map<String, String> headers = new Map<String, String>{'Content-Type' => 'application/json;charset=UTF-8'};
		if ([SELECT IsSandbox FROM Organization].IsSandbox) {
			for (CC_Lista_Valores__c lov : [SELECT Name, CC_Valor__c FROM CC_Lista_Valores__c
											WHERE CC_Lista__r.Name = 'Request headers específicos del sandbox'
											AND CC_Lista__r.CC_Activa__c = TRUE AND CC_Activa__c = TRUE]) {
				headers.put(lov.Name, lov.CC_Valor__c);
			}
		}
		return headers;
	}

    class AltaCitaCustomException extends Exception {}
}