force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/SPV_Reclamacion.recordType-meta.xml
<RecordType>
    <fullName>SPV_Reclamacion</fullName>
    <active>true</active>
    <businessProcess>SPV_ReclamacionSP</businessProcess>
    <description>Record type para las reclamaciones de Supervisores</description>
    <label>SPV Reclamacion</label>
</RecordType>

force-app/main/default/objects/ContentVersion/fields/SAC_Bloque__c.field-meta.xml
<CustomField>
    <fullName>SAC_Bloque__c</fullName>
    <description>Campo para clasificar los documentos en distintos bloques</description>
    <label>Bloque</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_Entrada</fullName>
                <default>true</default>
                <label>Entrada</label>
            </value>
            <value>
                <fullName>SAC_Tramitacion</fullName>
                <label>Tramitación</label>
            </value>
            <value>
                <fullName>SAC_Respuesta</fullName>
                <label>Respuesta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/SAC_StringRedaccion_fileupload__c.field-meta.xml
<CustomField>
    <fullName>SAC_StringRedaccion_fileupload__c</fullName>
    <description>Campo utlizado para poder identificar aquellos documentos que pertenecen a la resolución de la redaccón en el proyecto SAC</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Redacción</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/SAC_TipoAdjunto__c.field-meta.xml
<CustomField>
    <fullName>SAC_TipoAdjunto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que relaciona cada adjunto con el tipo de documento del que se trata (los tipos de documento se definen en el Maestro Temas)</description>
    <label>Tipo Adjunto</label>
    <referenceTo>SAC_MaestroTemas__c</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/SAC_ValidadoCV__c.field-meta.xml
<CustomField>
    <fullName>SAC_ValidadoCV__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si esta checkeado se le añadirá al título el casenumber y se podrá adjuntar en la etapa 1 y 3 de la redacción</description>
    <label>SAC_ValidadoCV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/SAC_DocumentoEnvio__c.object-meta.xml
<CustomObject>
    <label>Documento a enviar</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre de Documento a enviar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos a enviar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_Caso__c.field-meta.xml
<CustomField>
    <fullName>SAC_Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documentos a enviar</relationshipLabel>
    <relationshipName>Documentos_a_enviar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_DocPDF__c.field-meta.xml
<CustomField>
    <fullName>SAC_DocPDF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SAC_DocPDF</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_Documento__c.field-meta.xml
<CustomField>
    <fullName>SAC_Documento__c</fullName>
    <description>Campo que almacena la Id del ContentDocument del presente documento.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_Footer__c.field-meta.xml
<CustomField>
    <fullName>SAC_Footer__c</fullName>
    <description>Pie de página de cada página del pdf que creamos</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Footer</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_Header__c.field-meta.xml
<CustomField>
    <fullName>SAC_Header__c</fullName>
    <description>Encabezado para cada pagina del pdf que generamos</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Header</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>SAC_TipoDocumento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo Documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_URL__c.field-meta.xml
<CustomField>
    <fullName>SAC_URL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_DocumentoEnvio__c/fields/SAC_Version__c.field-meta.xml
<CustomField>
    <fullName>SAC_Version__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Version</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_ImagenDocumento__c/SAC_ImagenDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena las imágenes que contiene el documento de resolución del proyecto SAC</description>
    <label>Imagen Documento Resolución</label>
    <nameField>
        <displayFormat>IM-{0000000}</displayFormat>
        <label>Imagen Documento Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imagenes Documento Resolución</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ImagenDocumento__c/fields/SAC_Caso__c.field-meta.xml
<CustomField>
    <fullName>SAC_Caso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Caso con el que se relacionan las imágenes del documento</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Imagenes Documento Resolución</relationshipLabel>
    <relationshipName>Caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ImagenDocumento__c/fields/SAC_Imagen__c.field-meta.xml
<CustomField>
    <fullName>SAC_Imagen__c</fullName>
    <description>Campo text que almacena la imagen del documento</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Imagen</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_ImagenDocumento__c/recordTypes/SAC_ImagenDocumento.recordType-meta.xml
<RecordType>
    <fullName>SAC_ImagenDocumento</fullName>
    <active>true</active>
    <description>Record type para las imágenes del documento de resolución del proyecto SAC</description>
    <label>Imagen SAC</label>
</RecordType>

force-app/main/default/objects/SAC_MaestroTemas__c/SAC_MaestroTemas__c.object-meta.xml
<CustomObject>
    <description>Objeto maestro parametrizable de temas de marcas sobre las reclamaciones</description>
    <label>Maestro Temas</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maestro Temas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_MaestroTemas__c/fields/SAC_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>SAC_DeveloperName__c</fullName>
    <description>Campo para almacenar registros con un valor específico</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Developer Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SPV_LCMP_GeneracionDocumento.cls
public with sharing class SPV_LCMP_GeneracionDocumento {

    private static Set<String> objetos = new Set<String>{'SAC_ImagenDocumento__c'};
    private static Map<String, Map<String,Schema.RecordTypeInfo>> mapRTsObjects = SPV_Utils.getRecordTypesObjects(objetos);

    private static final Id RECTYPEIMAGENES = mapRTsObjects.get('SAC_ImagenDocumento__c').get('SAC_ImagenDocumento').getRecordTypeId();

    
    @AuraEnabled
    public static string getRuta(){
        try {
            String vfHostname = DomainCreator.getVisualforceHostname(null);
            return vfHostname;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string getRutaVS(){
        try {
            String vfHostname = DomainCreator.getVisualforceHostname(null);
            String ruta = 'https://' + vfHostname + '/apex/SPV_EditorHTMLPlantillas?id=';
            return ruta;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static string insertarimagen(String id, String imagen){
        try {
            SAC_ImagenDocumento__c imagenNueva = new SAC_ImagenDocumento__c();
            imagenNueva.SAC_Caso__c = id;
            imagenNueva.SAC_Imagen__c = imagen;
            imagenNueva.recordTypeId = RECTYPEIMAGENES;
            SPV_DatabaseDML.insertDML(imagenNueva,false);

            SAC_ImagenDocumento__c imagenInsertada = [SELECT Id, SAC_Imagen__c FROM SAC_ImagenDocumento__c WHERE RecordTypeId = :RECTYPEIMAGENES AND Id =: imagenNueva.id AND SAC_Caso__c = :id LIMIT 1];
            return imagenInsertada.SAC_Imagen__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void generarDocumento(String id, String nombreDocumento){
        try {
            String procedencia = 'generacionDocSPV';
            
            SAC_DocumentoEnvio__c docEnvio = [SELECT SAC_Caso__c, SAC_Documento__c, SAC_DocPDF__c, SAC_Version__c, Id
                                                FROM SAC_DocumentoEnvio__c 
                                                WHERE Id =: id and SAC_Documento__c = null AND SAC_TipoDocumento__c =:procedencia ORDER BY CreatedDate DESC LIMIT 1];

            String vfHostname = DomainCreator.getVisualforceHostname(null);
            String urlVF =  vfHostname + '/apex/SAC_DocumentoRedaccionPDF?id=' + docEnvio.Id;
    
            adjuntarPDFaCaso(urlVF, docEnvio.SAC_Caso__c , procedencia, nombreDocumento);

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    //metodo que extrae el numero de caso y el idioma en el que se va a generar el documento
    @AuraEnabled
    public static Map<String, Object> informacionCaso(String id) {
        try {
            String procedencia = 'generacionDocSPV';

            SAC_DocumentoEnvio__c docEnvio = [SELECT SAC_Caso__c, SAC_Documento__c, SAC_DocPDF__c, SAC_Version__c, Id
                                            FROM SAC_DocumentoEnvio__c 
                                            WHERE Id =: id 
                                            AND SAC_Documento__c = null 
                                            AND SAC_TipoDocumento__c =: procedencia 
                                            ORDER BY CreatedDate DESC 
                                            LIMIT 1];

            Case caso = [SELECT CaseNumber, CC_Idioma__c, RecordType.DeveloperName 
                        FROM Case 
                        WHERE Id = :docEnvio.SAC_Caso__c 
                        LIMIT 1];

            Map<String, Object> resultado = new Map<String, Object>();
            resultado.put('numeroCaso', caso.CaseNumber);
            resultado.put('idioma', caso.CC_Idioma__c);
            return resultado;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void adjuntarPDFaCaso(String url, Id parentId, String procedencia, String nombreDocumentoParametro){
        Case caso = [SELECT CaseNumber, CC_Idioma__c, recordType.DeveloperName FROM Case WHERE id =: parentId LIMIT 1];
        //String numCaso = caso.CaseNumber;
        //String numCaso = nombreDocumentoParametro;
        //String nombreDocumento;

        /*if(caso.CC_Idioma__c == 'es') { nombreDocumento = '  documento generado ESP'; }
        else if(caso.CC_Idioma__c == 'ca') { nombreDocumento = '  documento generado CAT '; }
        else if(caso.CC_Idioma__c == 'en') { nombreDocumento = '  documento generado ENG'; }
        else if(caso.CC_Idioma__c == 'va') { nombreDocumento = '  documento generado VAL'; }
        else if(caso.CC_Idioma__c == 'ga') { nombreDocumento = '  documento generado GAL'; }
        else if(caso.CC_Idioma__c == 'eu') { nombreDocumento = '  documento generado EUSK'; }
        else { nombreDocumento = ' documento generado DEFAULT'; }*/

        PageReference pageRef = new PageReference('https://' + url);          
        Blob body;
        if(Test.isRunningTest()){
            body = blob.valueOf('Unit.Test');
        }
        else{              
            body = pageRef.getContentAsPDF();                
        }

        List<ContentVersion> cvs = new List<ContentVersion>();
        // cvs = [SELECT Id, Title, ContentDocumentId, SAC_StringRedaccion_fileupload__c FROM ContentVersion WHERE FirstPublishLocationId =: parentId AND SAC_StringRedaccion_fileupload__c IN ('ResolucionRedaccion', 'ReenvioNuevoRedaccion')];

        // SAC_MaestroTemas__c maestro = new SAC_MaestroTemas__c();
        // if(caso.recordType.DeveloperName == 'SPV_Reclamacion') {
        //     maestro = [SELECT Id FROM SAC_MaestroTemas__c WHERE RecordTypeId = :RECTYPETIPOADJUNTOS AND SAC_DeveloperName__c = 'RESOLUCIONSPV' LIMIT 1];
        // }

        ContentVersion cv;
        Set<Id> idsCD = new Set<Id>(); 
        // if(!cvs.isEmpty()){
        //     for(ContentVersion tempCv : cvs){
        //         if(tempCv.SAC_StringRedaccion_fileupload__c == 'ResolucionRedaccion'){
        //         idsCD.add(tempCv.ContentDocumentId);
        //         }
        //     }
        //     List<ContentDocument> cds = [SELECT Id FROM ContentDocument WHERE Id IN: idsCD];
        //     SAC_DatabaseDML.deleteListDML(cds, false);
        // }
        cv = new ContentVersion(
            Title = nombreDocumentoParametro, 
            PathOnClient ='SampleTitle.pdf',
            VersionData = body,
            FirstPublishLocationId = parentId,
            SAC_Bloque__c = 'SAC_Tramitacion',
            SAC_ValidadoCV__c = false
        ); //SAC_StringRedaccion_fileupload__c = 'ResolucionRedaccion', SAC_TipoAdjunto__c = maestro.Id,

        SPV_DatabaseDML.insertDML(cv, false);
        

        SAC_DocumentoEnvio__c documento = [SELECT id FROM SAC_DocumentoEnvio__c WHERE SAC_Caso__c =:parentId AND SAC_Documento__c = null AND SAC_TipoDocumento__c =:procedencia ORDER BY CreatedDate DESC LIMIT 1]; 

        //Comentado para que al generar el documento no salga en docs
        // documento.SAC_Version__c = cv.Id;
        documento.SAC_Documento__c = cv.ContentDocumentId;
        documento.SAC_URL__c = url;

        SPV_DatabaseDML.updateDML(documento, false);   
                        
    }

    public string lexOrigin {get{ return URL.getOrgDomainUrl().toExternalForm().split('.my.')[0]+'.lightning.force.com';} set;}

    public string idCaso {get{ return ApexPages.currentPage().getParameters().get('id').escapeHtml4();} set;}

    public string cuerpoDocumento { get{ if(ApexPages.currentPage().getParameters().get('id') != null) {List<SAC_DocumentoEnvio__c> docGuardado = [SELECT Id, SAC_DocPDF__c, SAC_URL__c FROM SAC_DocumentoEnvio__c WHERE SAC_Caso__c =: ApexPages.currentPage().getParameters().get('id') AND SAC_TipoDocumento__c = 'generacionDocSPV' ORDER BY createdDate DESC LIMIT 1];if (docGuardado.size() > 0 && docGuardado[0].SAC_URL__c == null) {return docGuardado[0].SAC_DocPDF__c;}}return '';} set;}

    @AuraEnabled(cacheable=true)
    public static SAC_DocumentoEnvio__c comprobarDocumentoGuardado(String id){
        String procedencia = 'generacionDocSPV';
        
        List<SAC_DocumentoEnvio__c> docEnvio = [SELECT Id, SAC_URL__c, SAC_Header__c, SAC_Footer__c FROM SAC_DocumentoEnvio__c WHERE SAC_Caso__c  =: id AND SAC_TipoDocumento__c =:procedencia ORDER BY CreatedDate DESC LIMIT 1];

        if(!docEnvio.isEmpty()){
            return docEnvio[0];
        }else{
            return null;
        }
    }
}