force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OS_Departamento__c.field-meta.xml
<CustomField>
    <fullName>OS_Departamento__c</fullName>
    <description>Picklist con los posibles valores de Departamento</description>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AVALES</fullName>
            </value>
            <value>
                <fullName>BOS</fullName>
            </value>
            <value>
                <fullName>EFECTIVO</fullName>
            </value>
            <value>
                <fullName>EXPFIN</fullName>
            </value>
            <value>
                <fullName>FINCOMEX</fullName>
            </value>
            <value>
                <fullName>GESTORIAS</fullName>
            </value>
            <value>
                <fullName>GOC</fullName>
            </value>
            <value>
                <fullName>HOLABANK</fullName>
            </value>
            <value>
                <fullName>OPCOMEX</fullName>
            </value>
            <value>
                <fullName>UAC</fullName>
            </value>
            <value>
                <fullName>UAFE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/FRA_Cliente.recordType-meta.xml
<RecordType>
    <fullName>FRA_Cliente</fullName>
    <active>true</active>
    <businessProcess>FRA_Support_Process</businessProcess>
    <description>Record Type para proyecto HUB Fraude</description>
    <label>Cliente (FRA)</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <formula>IF( ( NOT(ISBLANK(CC_Fecha_Vigencia_Fin__c)) &amp;&amp; NOW() &gt;= CC_Fecha_Vigencia_Inicio__c &amp;&amp; NOW() &lt; CC_Fecha_Vigencia_Fin__c ) || ( ISBLANK(CC_Fecha_Vigencia_Fin__c) &amp;&amp; NOW() &gt;= CC_Fecha_Vigencia_Inicio__c ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Clasificacion_Completa_Formula__c.field-meta.xml
<CustomField>
    <fullName>CC_Clasificacion_Completa_Formula__c</fullName>
    <formula>LOWER(
    IF(
        RecordType.DeveloperName = &apos;CC_Motivo&apos;,
        CC_Producto_Servicio__r.CC_Tematica__r.Name + &apos; &apos; + CC_Producto_Servicio__r.Name + &apos; &apos; + Name,
        IF(
            RecordType.DeveloperName = &apos;CC_Producto_Servicio&apos;,
            CC_Tematica__r.Name + &apos; &apos; + Name,
            IF(
                RecordType.DeveloperName = &apos;SAC_Detalle&apos;,
                CC_Motivo__r.CC_Producto_Servicio__r.CC_Tematica__r.Name + &apos; &apos; + CC_Motivo__r.CC_Producto_Servicio__r.Name + &apos; &apos; + CC_Motivo__r.Name + &apos; &apos; + Name,
                IF(
                    RecordType.DeveloperName = &apos;SEG_Detalle&apos;,
                    CC_Motivo__r.CC_Producto_Servicio__r.CC_Tematica__r.Name + &apos; &apos; + CC_Motivo__r.CC_Producto_Servicio__r.Name + &apos; &apos; + CC_Motivo__r.Name + &apos; &apos; + Name,
				Name
                )
            )
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clasificación completa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Detalle__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalle__c</fullName>
    <description>Campo para poder indicar el detalle.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalle</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio_Formula__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio_Formula__c</fullName>
    <formula>CASE(RecordType.DeveloperName, &apos;CC_Motivo&apos;, CC_Producto_Servicio__r.Name, &apos;CC_Producto_Servicio&apos;, Name,CC_Motivo__r.CC_Producto_Servicio__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producto/Servicio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica_Formula__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica_Formula__c</fullName>
    <formula>CASE(RecordType.DeveloperName, &apos;CC_Motivo&apos;, CC_Producto_Servicio__r.CC_Tematica__r.Name, &apos;CC_Producto_Servicio&apos;, CC_Tematica__r.Name,CC_Motivo__r.CC_Producto_Servicio__r.CC_Tematica__r.Name)</formula>
    <label>Temática</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/OS_Departamento__c.field-meta.xml
<CustomField>
    <fullName>OS_Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AVALES</fullName>
            </value>
            <value>
                <fullName>BOS</fullName>
            </value>
            <value>
                <fullName>EFECTIVO</fullName>
            </value>
            <value>
                <fullName>EXPFIN</fullName>
            </value>
            <value>
                <fullName>FINCOMEX</fullName>
            </value>
            <value>
                <fullName>GESTORIAS</fullName>
            </value>
            <value>
                <fullName>GOC</fullName>
            </value>
            <value>
                <fullName>HOLABANK</fullName>
            </value>
            <value>
                <fullName>OPCOMEX</fullName>
            </value>
            <value>
                <fullName>UAC</fullName>
            </value>
            <value>
                <fullName>UAFE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/OS_Horario__c.field-meta.xml
<CustomField>
    <fullName>OS_Horario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Horario</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>MCCs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/OS_Horas_SLA__c.field-meta.xml
<CustomField>
    <fullName>OS_Horas_SLA__c</fullName>
    <label>Horas SLA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mismo dia</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>72</fullName>
            </value>
            <value>
                <fullName>92</fullName>
            </value>
            <value>
                <fullName>96</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/classes/FRA_MCC_Buscador_Controller_Test.cls
@isTest
public with sharing class FRA_MCC_Buscador_Controller_Test {
    @testSetup
    public static void testSetup(){
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            User usuario = new User();
            usuario.ProfileId = [SELECT Id FROM Profile WHERE Name = 'FRA_Usuario_Caixabank'].Id;
            usuario.UserRoleId = [SELECT Id FROM UserRole WHERE Name = 'FRA'].Id;
            usuario.FirstName = 'Fraude';
            usuario.LastName = 'Prueba';
            usuario.Alias = uniqueName.substring(18, 23);
            usuario.Email = uniqueName + '@test' + orgId + '.org';
            usuario.Username = uniqueName + '@test' + orgId + '.org';
            usuario.EmailEncodingKey = 'UTF-8';
            usuario.LanguageLocaleKey = 'es';
            usuario.LocaleSidKey = 'es_ES';
            usuario.TimezonesIdKey = 'Europe/Madrid';
            insert usuario;
    
            List<PermissionSetAssignment> psAssignments = new List<PermissionSetAssignment>();
            for (PermissionSet ps : [SELECT Id FROM PermissionSet WHERE Name IN ('FRA_PS_Operador')]) {
                PermissionSetAssignment psAssignment = new PermissionSetAssignment();
                psAssignment.AssigneeId = usuario.Id;
                psAssignment.PermissionSetId = ps.Id;
                psAssignments.add(psAssignment);
            }
            insert psAssignments;
        }
    }

    @isTest
    public static void testQuerySalesforceRecord() {
        Case casoFRA = new Case();
        casoFRA.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'FRA_Cliente');
        casoFRA.Subject = 'Caso Test FRA';
        insert casoFRA;

        String queryString = 'SELECT CC_Tematica_Formula__c, CC_Producto_Servicio_Formula__c, Name, CC_Detalle__c FROM CC_MCC__c WHERE CC_Clasificacion_Completa_Formula__c LIKE \'%Prod%\'';
        queryString += ' AND RecordType.DeveloperName = \'CC_Motivo\' AND CC_Activo__c = true';
        User usuario = [SELECT Id FROM User WHERE FirstName = 'Fraude' LIMIT 1];
        System.runAs(usuario){
            Test.startTest();
            Map<String, CC_MCC__c> mccRegistrosFRA = altaClasificacionPrueba('Cliente (FRA)', 'NomTematica1', 'NomProd1', 'NomMotiu1');
            List<sObject> resultadosCC = FRA_MCC_Buscador_Controller.querySalesforceRecord(casoFRA.Id, queryString, 15);
            System.assertEquals(mccRegistrosFRA.get('motivo').Id, resultadosCC[0].Id);
            Test.stopTest();
        }
    }

    @isTest
    public static void testActualizarCaso() {
        CC_MCC__c tematica = new CC_MCC__c();
        tematica.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematica.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        tematica.Name = 'Temática Test';
        tematica.CC_Codigo_Externo__c = 'TE-000001';
        insert tematica;

        CC_MCC__c productoServicio = new CC_MCC__c();
        productoServicio.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicio.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        productoServicio.Name = 'Producto/Servicio Test';
        productoServicio.CC_Tematica__c = tematica.Id;
        productoServicio.CC_Codigo_Externo__c = 'PR-000001';
        insert productoServicio;

        CC_MCC__c motivo = new CC_MCC__c();
        motivo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivo.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        motivo.Name = 'Motivo';
        motivo.CC_Producto_Servicio__c = productoServicio.Id;
        motivo.CC_Codigo_Externo__c = 'MO-000001';
        insert motivo;

        Case caso = new Case();
        caso.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'FRA_Cliente');
        caso.Subject = 'Caso Test';
        insert caso;
        
        FRA_MCC_Buscador_Controller.actualizarCaso(caso.Id, motivo.Id);
        Case casoQuery = [SELECT CC_MCC_Tematica__c, CC_MCC_ProdServ__c, CC_MCC_Motivo__c FROM Case WHERE Id = :caso.Id]; 
        User usuario = [SELECT Id FROM User WHERE FirstName = 'Fraude' LIMIT 1];
        System.runAs(usuario){
            Test.startTest();
            System.assertEquals(tematica.Id, casoQuery.CC_MCC_Tematica__c);
            System.assertEquals(productoServicio.Id, casoQuery.CC_MCC_ProdServ__c);
            System.assertEquals(motivo.Id, casoQuery.CC_MCC_Motivo__c);
            Test.stopTest();
        }    
    }

    @isTest
    public static void testGetTipificacion() {
        CC_MCC__c tematica = new CC_MCC__c();
        tematica.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematica.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        tematica.Name = 'Temática Test';
        tematica.CC_Codigo_Externo__c = 'TE-000001';
        insert tematica;

        CC_MCC__c productoServicio = new CC_MCC__c();
        productoServicio.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicio.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        productoServicio.Name = 'Producto/Servicio Test';
        productoServicio.CC_Tematica__c = tematica.Id;
        productoServicio.CC_Codigo_Externo__c = 'PR-000001';
        insert productoServicio;

        CC_MCC__c motivo = new CC_MCC__c();
        motivo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivo.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        motivo.Name = 'Motivo Test';
        motivo.CC_Producto_Servicio__c = productoServicio.Id;
        motivo.CC_Codigo_Externo__c = 'MO-000001';
        insert motivo;

        Case caso = new Case();
        caso.Subject = 'Caso Test';
        caso.CC_MCC_Tematica__c = tematica.Id;
        caso.CC_MCC_ProdServ__c = productoServicio.Id;
        caso.CC_MCC_Motivo__c = motivo.Id;
        insert caso;
      
        Case datosCaso = FRA_MCC_Buscador_Controller.getTipificacion(caso.Id);
        //El caracter '\u2192' es una flecha a la derecha (→)
        String tipificacion = datosCaso.CC_MCC_Tematica__r.Name + ' \u2192 '
                            + datosCaso.CC_MCC_ProdServ__r.Name + ' \u2192 '
                            + datosCaso.CC_MCC_Motivo__r.Name;

        User usuario = [SELECT Id FROM User WHERE FirstName = 'Fraude' LIMIT 1];
        System.runAs(usuario) {
            Test.startTest();
            System.assertNotEquals(null, datosCaso);
            System.assertEquals('Temática Test → Producto/Servicio Test → Motivo Test', tipificacion);
            Test.stopTest();
        }
    }

    @isTest
    public static void testCrearActividadRetipificacion() {
        CC_MCC__c tematica = new CC_MCC__c();
        tematica.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematica.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        tematica.Name = 'Temática Test';
        tematica.CC_Codigo_Externo__c = 'TE-000001';
        insert tematica;

        CC_MCC__c productoServicio = new CC_MCC__c();
        productoServicio.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicio.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        productoServicio.Name = 'Producto/Servicio Test';
        productoServicio.CC_Tematica__c = tematica.Id;
        productoServicio.CC_Codigo_Externo__c = 'PR-000001';
        insert productoServicio;

        CC_MCC__c motivo = new CC_MCC__c();
        motivo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivo.CC_Tipo_Cliente__c = 'Cliente (FRA)';
        motivo.Name = 'Motivo';
        motivo.CC_Producto_Servicio__c = productoServicio.Id;
        motivo.CC_Codigo_Externo__c = 'MO-000001';
        insert motivo;
        
        Case caso = new Case();
        caso.Subject = 'Caso Test';
        caso.CC_MCC_Tematica__c = tematica.Id;
        caso.CC_MCC_ProdServ__c = productoServicio.Id;
        caso.CC_MCC_Motivo__c = motivo.Id;
        insert caso;
       
        FRA_MCC_Buscador_Controller.crearActividadRetipificacion(caso.Id, tematica.Name, productoServicio.Name, motivo.Name,'');
        Case casoQuery = [SELECT CC_MCC_Tematica__c, CC_MCC_ProdServ__c, CC_MCC_Motivo__c FROM Case WHERE Id = :caso.Id];
        User usuario = [SELECT Id FROM User WHERE FirstName = 'Fraude' LIMIT 1];
        System.runAs(usuario) {
            Test.startTest();
            System.assertEquals(tematica.Id, casoQuery.CC_MCC_Tematica__c);
            System.assertEquals(productoServicio.Id, casoQuery.CC_MCC_ProdServ__c);
            System.assertEquals(motivo.Id, casoQuery.CC_MCC_Motivo__c);
            Test.stopTest();
        }
    }

    private static Map<String, CC_MCC__c> altaClasificacionPrueba(String tipoCliente, String nombreTematica, String nombreProducto, String nombreMotivo)  {
        Id businessHoursId;
        BusinessHours[] stdBusinessHours = [SELECT Id FROM BusinessHours WHERE Name = 'Default' AND IsActive = true];
        businessHoursId = stdBusinessHours[0].Id;
        if(stdBusinessHours.isEmpty()){
            businessHoursId = [SELECT Id FROM BusinessHours WHERE IsActive = true LIMIT 1].Id;
        }

        Map<String, CC_MCC__c> mccRegistros = new Map<String, CC_MCC__c>();

        CC_MCC__c tematica = new CC_MCC__c();
        tematica.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematica.CC_Tipo_Cliente__c = tipoCliente;
        tematica.Name = nombreTematica;
        tematica.OS_Departamento__c = 'UAC';
        tematica.CC_Codigo_Externo__c = 'TE-000001-' + nombreTematica;
        tematica.OS_Horas_SLA__c = '24' ;
        tematica.OS_Horario__C = businessHoursId;
        insert tematica;

        CC_MCC__c tematicaCOPS = new CC_MCC__c();
        tematicaCOPS.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematicaCOPS.CC_Tipo_Cliente__c = tipoCliente;
        tematicaCOPS.Name = nombreTematica;        
        tematicaCOPS.OS_Departamento__c = 'UAC';
        tematicaCOPS.CC_Codigo_Externo__c = 'TE-000002-' + nombreTematica;
        tematicaCOPS.OS_Horas_SLA__c = '24' ;
        tematicaCOPS.OS_Horario__C = businessHoursId;
        insert tematicaCOPS;

        CC_MCC__c tematicaCAM = new CC_MCC__c();
        tematicaCAM.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Tematica');
        tematicaCAM.CC_Tipo_Cliente__c = tipoCliente;
        tematicaCAM.Name = nombreTematica;
        tematicaCAM.OS_Departamento__c = 'UAC';
        tematicaCAM.CC_Codigo_Externo__c = 'TE-000003-' + nombreTematica;
        tematicaCAM.OS_Horas_SLA__c = '24' ;
        tematicaCAM.OS_Horario__C = businessHoursId;
        insert tematicaCAM;

        CC_MCC__c productoServicio = new CC_MCC__c();
        productoServicio.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicio.CC_Tipo_Cliente__c = tipoCliente;
        productoServicio.Name = nombreProducto;
        productoServicio.CC_Tematica__c = tematica.Id;
        productoServicio.CC_Codigo_Externo__c = 'PR-000001-' + nombreProducto;
        insert productoServicio;

        CC_MCC__c productoServicioCOPS = new CC_MCC__c();
        productoServicioCOPS.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicioCOPS.CC_Tipo_Cliente__c = tipoCliente;
        productoServicioCOPS.Name = nombreProducto;
        productoServicioCOPS.CC_Tematica__c = tematica.Id;
        productoServicioCOPS.CC_Codigo_Externo__c = 'PR-000002-' + nombreProducto;
        insert productoServicioCOPS;

        CC_MCC__c productoServicioCAM = new CC_MCC__c();
        productoServicioCAM.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Producto_Servicio');
        productoServicioCAM.CC_Tipo_Cliente__c = tipoCliente;
        productoServicioCAM.Name = nombreProducto;
        productoServicioCAM.CC_Tematica__c = tematica.Id;
        productoServicioCAM.CC_Codigo_Externo__c = 'PR-000003-' + nombreProducto;
        insert productoServicioCAM;

        CC_MCC__c motivo = new CC_MCC__c();
        motivo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivo.CC_Tipo_Cliente__c = tipoCliente;
        motivo.Name = nombreMotivo;
        motivo.CC_Producto_Servicio__c = productoServicio.Id;
        motivo.CC_Codigo_Externo__c = 'MO-000001-' + nombreMotivo;
        insert motivo;

        CC_MCC__c motivoCOPS = new CC_MCC__c();
        motivoCOPS.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivoCOPS.CC_Tipo_Cliente__c = tipoCliente;
        motivoCOPS.Name = nombreMotivo;
        motivoCOPS.CC_Producto_Servicio__c = productoServicio.Id;
        motivoCOPS.CC_Codigo_Externo__c = 'MO-000002-' + nombreMotivo;
        insert motivoCOPS;

        CC_MCC__c motivoCAM = new CC_MCC__c();
        motivoCAM.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');
        motivoCAM.CC_Tipo_Cliente__c = tipoCliente;
        motivoCAM.Name = nombreMotivo;
        motivoCAM.CC_Producto_Servicio__c = productoServicio.Id;
        motivoCAM.CC_Codigo_Externo__c = 'MO-000003-' + nombreMotivo;
        insert motivoCAM;

        mccRegistros.put('tematica', tematica);
        mccRegistros.put('tematicaCOPS', tematicaCOPS);
        mccRegistros.put('tematicaCAM', tematicaCAM);
        mccRegistros.put('productoServicio', productoServicio);
        mccRegistros.put('productoServicioCOPS', productoServicioCOPS);
        mccRegistros.put('productoServicioCAM', productoServicioCAM);
        mccRegistros.put('motivo', motivo);
        mccRegistros.put('motivoCOPS', motivoCOPS);
        mccRegistros.put('motivoCAM', motivoCAM);

        return mccRegistros;
    }
}