force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_CriterioBDEMateriaFuente__c.field-meta.xml
<CustomField>
    <fullName>SPV_CriterioBDEMateriaFuente__c</fullName>
    <description>Campo picklist que indica el criterio del BdE sobre materia y fuente de la pretensión</description>
    <inlineHelpText>Mencionar el criterio del BdE sobre esta materia y fuente (resoluciones anteriores, memoria del BdE, etc…)</inlineHelpText>
    <label>Criterio BdE sobre materia y fuente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_DecisionAlegaciones__c.field-meta.xml
<CustomField>
    <fullName>SPV_DecisionAlegaciones__c</fullName>
    <description>Campo picklist que muestra la decisión de alegaciones de la pretensión</description>
    <label>Decisión de alegaciones</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alegaciones</fullName>
            </value>
            <value>
                <fullName>Allanamiento</fullName>
            </value>
            <value>
                <fullName>Desistimiento</fullName>
            </value>
            <value>
                <fullName>Inadmisión</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_DecisionAllanamiento__c.field-meta.xml
<CustomField>
    <fullName>SPV_DecisionAllanamiento__c</fullName>
    <description>Campo picklist que indica la decisión de allanamiento de la pretensión</description>
    <label>Decisión de allanamiento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_Documentacion__c.field-meta.xml
<CustomField>
    <fullName>SPV_Documentacion__c</fullName>
    <description>Campo picklist que indica la documentación de la pretensión</description>
    <label>Documentación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Sí</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SPV_ObservacionesDecisionAlegaciones__c.field-meta.xml
<CustomField>
    <fullName>SPV_ObservacionesDecisionAlegaciones__c</fullName>
    <description>Campo texto que indica las observaciones de la decisión de alegaciones de la pretensión</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Observaciones decisión alegaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/SPV_Pretension.recordType-meta.xml
<RecordType>
    <fullName>SPV_Pretension</fullName>
    <active>true</active>
    <businessProcess>SPV_ReclamacionSP</businessProcess>
    <description>RecordType del objeto case para las pretensiones de Supervisores</description>
    <label>SPV Pretension</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SPV_Reclamacion.recordType-meta.xml
<RecordType>
    <fullName>SPV_Reclamacion</fullName>
    <active>true</active>
    <businessProcess>SPV_ReclamacionSP</businessProcess>
    <description>Record type para las reclamaciones de Supervisores</description>
    <label>SPV Reclamacion</label>
</RecordType>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email2__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email2__c</fullName>
    <description>Segundo email del grupo.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Para 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email3__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email3__c</fullName>
    <description>tercer email para el grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Para 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SAC_Email__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email__c</fullName>
    <description>Campo donde se guardaran los emails del grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Dirección de email al cual llegaran las consultas.</inlineHelpText>
    <label>Para</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_CasoEscalado__c.field-meta.xml
<CustomField>
    <fullName>SAC_CasoEscalado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relacionar los escalados de los casos</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Escalados</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Email2__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email2__c</fullName>
    <description>Campo para almacenar un email del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Email3__c.field-meta.xml
<CustomField>
    <fullName>SAC_Email3__c</fullName>
    <description>Campo para almacenar un email del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado en el que se encuentra la interacción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteRespuesta</fullName>
                <default>true</default>
                <label>Pendiente Respuesta</label>
            </value>
            <value>
                <fullName>SAC_Resuelta</fullName>
                <label>Resuelta</label>
            </value>
            <value>
                <fullName>SAC_Atendida</fullName>
                <label>Atendida</label>
            </value>
            <value>
                <fullName>SAC_Reescalada</fullName>
                <label>Re escalada</label>
            </value>
            <value>
                <fullName>SAC_Borrador</fullName>
                <label>Pendiente Respuesta -  Borrador</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadoSinAtender</fullName>
                <label>Finalizado sin atender</label>
            </value>
            <value>
                <fullName>SAC_Cancelado</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>SAC_Devuelto</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>SAC_PendienteRespuestaDefinitiva</fullName>
                <label>Pendiente Respuesta Definitiva</label>
            </value>
            <value>
                <fullName>SPV_PendienteEnviar</fullName>
                <label>Pendiente enviar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_GrupoColaborador__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoColaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo Colaborador</description>
    <label>Grupo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 6) OR (1 AND 2 AND 7) OR (3 AND 4) OR (3 AND 5) OR (4 AND 8) OR (5 AND 8) OR (3 AND 9) OR (1 AND 10)</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteConsultas__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consulta</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteEscalado__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV2</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV3</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_TieneUsuariosActivos__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_Externo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Letrados</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoSPV</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ConsultaSPV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Interacciones (Grupo)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relaciona el objeto interaccion con las reclamaciones</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SPV_Escalado.recordType-meta.xml
<RecordType>
    <fullName>SPV_Escalado</fullName>
    <active>true</active>
    <description>Record type para el escalado del proyecto SPV</description>
    <label>EscaladoSPV</label>
</RecordType>

force-app/main/default/objects/SPV_Formulario__c/SPV_Formulario__c.object-meta.xml
<CustomObject>
    <description>Representa un formulario asociado a una reclamación en supervisores.</description>
    <label>Formulario</label>
    <nameField>
        <displayFormat>FC-{0000000}</displayFormat>
        <label>Formulario Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formularios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPV_Formulario__c/fields/SPV_Caso__c.field-meta.xml
<CustomField>
    <fullName>SPV_Caso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Caso (Reclamación) a el que pertenece este formulario.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Formularios</relationshipLabel>
    <relationshipName>Formularios</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPV_Formulario__c/recordTypes/SPV_Formulario.recordType-meta.xml
<RecordType>
    <fullName>SPV_Formulario</fullName>
    <active>true</active>
    <description>Record Type del objeto SPV_Formulario para el proyecto supervisores.</description>
    <label>Formulario SPV</label>
</RecordType>

force-app/main/default/classes/SPV_LCMP_FormularioReclamaciones.cls
public with sharing class SPV_LCMP_FormularioReclamaciones {
    private static Set<String> objetos = new Set<String>{'SAC_Interaccion__c', 'Case','SPV_Formulario__c'};

    private static Map<String, Map<String,Schema.RecordTypeInfo>> mapRTsObjects = SPV_Utils.getRecordTypesObjects(objetos);

    private static final Id RECTYPERECLAMACION = mapRTsObjects.get('Case').get('SPV_Reclamacion').getRecordTypeId();
    private static final Id RECTYPEPRETENSION = mapRTsObjects.get('Case').get('SPV_Pretension').getRecordTypeId();
    private static final Id RECTYPEESCALADO = mapRTsObjects.get('SAC_Interaccion__c').get('SPV_Escalado').getRecordTypeId();
    private static final Id RECTYPEFORMULARIO = mapRTsObjects.get('SPV_Formulario__c').get('SPV_Formulario').getRecordTypeId();


    /*****************************************************************************
    * Proposito: Comprueba si hay algún formulario en la reclamación
    * 
    * Historial
    * -------
    * VERSION        USER_STORY       AUTHOR         DATE         Description
    * 1.0             US926182     Sergio Martín   18/06/24        Creación
    *****************************************************************************/
    @AuraEnabled(cacheable=true)
    public static String getFormularioExistente(String casoId) {
        if(Schema.sObjectType.SPV_Formulario__c.isAccessible()) {
            List<SPV_Formulario__c> listaFormularios = [SELECT Id FROM SPV_Formulario__c WHERE RecordTypeId = :RECTYPEFORMULARIO AND SPV_Caso__c = :casoId];
            if (!listaFormularios.isEmpty()) {
                return listaFormularios[0].id;
            }
        }
        return null;
    }


    /*********************************************************************************
    * Proposito: Recupera los campos deseados de las pretensiones de la reclamación
    * 
    * Historial
    * -------
    * VERSION        USER_STORY       AUTHOR         DATE         Description
    * 1.0             US926182     Sergio Martín   19/06/24        Creación
    ************************************************************************************/
    @AuraEnabled(cacheable=true)
    public static List<Case> getPretensionesReclamacion(String casoId) {
        List<Case> listaPretensiones = new List<Case>();
        if(Schema.sObjectType.Case.isAccessible()) {
            listaPretensiones = [SELECT Id, CaseNumber, Subject, SPV_CriterioBDEMateriaFuente__c, SPV_DecisionAlegaciones__c, SPV_ObservacionesDecisionAlegaciones__c, SPV_DecisionAllanamiento__c, SPV_Documentacion__c FROM Case WHERE RecordTypeId = :RECTYPEPRETENSION AND SAC_Reclamacion__c = :casoId];
        }
        return listaPretensiones;
    }


    /*************************************************************************
    * Proposito: Notificar al propietario del escalado que se ha modificado 
    *            el formulario e la reclamación
    * 
    * Historial
    * -------
    * VERSION        USER_STORY       AUTHOR         DATE         Description
    * 1.0             US929908     Sergio Martín   20/06/24        Creación
    * 1.1               ---         Raúl Santos    02/10/24        Modificación: Enviar alerta al owner si esta asignado, o al grupo si el owner es pte asignar
    *************************************************************************/
    @AuraEnabled
    public static void notificarCambioFicha(String casoId, String caseNumber) {

        if(Schema.sObjectType.SAC_Interaccion__c.isAccessible()) {
            List<SAC_Interaccion__c> listaEscalados = [SELECT Id, Name, SAC_CasoEscalado__c, OwnerId, SAC_Estado__c, SAC_GrupoColaborador__c, SAC_GrupoColaborador__r.SAC_Email__c, SAC_GrupoColaborador__r.SAC_Email2__c, SAC_GrupoColaborador__r.SAC_Email3__c
                                                         FROM SAC_Interaccion__c WHERE RecordTypeId = :RECTYPEESCALADO AND SAC_CasoEscalado__c = :casoId AND (SAC_Estado__c = 'SAC_PendienteRespuesta' OR SAC_Estado__c = 'SPV_PendienteEnviar') ORDER BY CreatedDate DESC LIMIT 1];

            List<Group> cola = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'SPV_PendienteAsignar' LIMIT 1];
            List<SAC_WrapperAlerta> listaWrapperAlerta = new List<SAC_WrapperAlerta>();

            if(!cola.isEmpty() && !listaEscalados.isEmpty()){
                for(SAC_Interaccion__c escalado : listaEscalados) {

                    //Preparar una alerta
                    SAC_WrapperAlerta wrapAlerta = new SAC_WrapperAlerta(escalado.SAC_CasoEscalado__c,
                                                                        'SPV_018',
                                                                        'La ficha de la reclamación ' + caseNumber + ' ha sido modificada, por favor revise antes de continuar con la resolución del escalado ' + escalado.Name,
                                                                        escalado.OwnerId,
                                                                        '',
                                                                        '',
                                                                        escalado.Id);
                                                                        wrapAlerta.enlaceParaEmail = URL.getSalesforceBaseUrl().toExternalForm() + '/' + escalado.Id;
                                                                        wrapAlerta.idGrupoColaborador = escalado.SAC_GrupoColaborador__c;
                                                                        wrapAlerta.proyecto = 'SPV';

                    //Alerta al grupo si esta pte asignar
                    if(escalado.OwnerId == cola[0].Id) {
                        List<String> listaEmails = new List<String>();  

                        if (escalado.SAC_GrupoColaborador__r.SAC_Email__c != null) {
                            listaEmails.add(escalado.SAC_GrupoColaborador__r.SAC_Email__c);
                        }
                        if (escalado.SAC_GrupoColaborador__r.SAC_Email2__c != null) {
                            listaEmails.add(escalado.SAC_GrupoColaborador__r.SAC_Email2__c);
                        }
                        if (escalado.SAC_GrupoColaborador__r.SAC_Email3__c != null) {
                            listaEmails.add(escalado.SAC_GrupoColaborador__r.SAC_Email3__c);
                        }
                                                                                                
                        wrapAlerta.listaEmailsGrupo = listaEmails;    
                    }

                    //Añadirla a la lista para posteriormente llamar al método
                    listaWrapperAlerta.add(wrapAlerta);
                }
            }

            //Si tenemos alertas que enviar, se llama al método que las envía
            if (!listaWrapperAlerta.isEmpty()) {
                SAC_Alertas.generarAlertas(listaWrapperAlerta);
            }
        }
    }
}