force-app/main/default/objects/Case/fields/SAC_AlertasPtes__c.field-meta.xml
<CustomField>
    <fullName>SAC_AlertasPtes__c</fullName>
    <description>Guarda el número de alertas pendientes que tiene la reclamación</description>
    <label>Alertas Ptes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Alerta__c/SAC_Alerta__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar registros de alertas que vienen parametrizadas por custom metadata types (Maestro de tipologías de alertas)</description>
    <label>Alerta</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Alerta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alertas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Alerta__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación a la que esta vinculada la alerta</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Alertas</relationshipLabel>
    <relationshipName>Alertas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Alerta__c/recordTypes/SPV_Alerta.recordType-meta.xml
<RecordType>
    <fullName>SPV_Alerta</fullName>
    <active>true</active>
    <description>Alertas de supervisores</description>
    <label>Alerta SPV</label>
</RecordType>

force-app/main/default/classes/SPV_AlertaAITRHan_Test.cls
@isTest
public with sharing class SPV_AlertaAITRHan_Test {
    @TestSetup
    static void makeData(){

        //Usuario SPV General
		User usuarioGeneral = SPV_TestDataFactory.crearUsuarioSPVGeneral(1)[0];
        Database.insert(usuarioGeneral);
        
        List<User> listaUsersAdmin = SPV_TestDataFactory.crearUsuarioAdministrador(1);
        Database.insert(listaUsersAdmin);
        
        Case reclamacion = new Case();

        System.runAs(usuarioGeneral){
            //Reclamacion
            Map<String, Object> camposRecl = new Map<String, Object>();
            camposRecl.put('Subject', 'TestRec');

            reclamacion = SPV_TestDataFactory.crearCaso('Reclamacion',camposRecl);
            Database.insert(reclamacion);
        }
        
        system.runAs(listaUsersAdmin[0]) {
            //Cambiar owner de la reclamación
            reclamacion.OwnerId = usuarioGeneral.Id;
            Database.update(reclamacion);
        }
    }
    @isTest
    static void sumarContadorAlertaTest() {
        Case reclamacion = [SELECT Id, SAC_AlertasPtes__c FROM Case];
        SAC_Alerta__c alerta = new SAC_Alerta__c(
                SAC_Reclamacion__c = reclamacion.Id,
                RecordTypeId = Schema.SObjectType.SAC_Alerta__c.getRecordTypeInfosByDeveloperName().get('SPV_Alerta').getRecordTypeId()
            );

        User usuario = [SELECT id FROM User WHERE Username = 'usertest0@testSPV.com.testSetup' AND isActive = true LIMIT 1];
		System.runAs(usuario){
            Test.startTest();
            Database.insert(alerta);
            Test.stopTest();
        }

        Case reclamacionResult = [SELECT Id, SAC_AlertasPtes__c FROM Case LIMIT 1];

        System.assertEquals(1, reclamacionResult.SAC_AlertasPtes__c, 'No se ha añadido la alerta al contador de alertas pendientes');
    }
}