force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/SAC_ProductCase__c.object-meta.xml
<CustomObject>
    <label>Producto de reclamación</label>
    <nameField>
        <displayFormat>PRD-R-{00000}</displayFormat>
        <label>Nombre de Producto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de reclamación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Descripcion__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Descripción</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SAC_ProductCase__c/fields/SAC_Pretension__c.field-meta.xml
<CustomField>
    <fullName>SAC_Pretension__c</fullName>
    <label>Pretensión</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Productos de reclamación</relationshipLabel>
    <relationshipName>Productos_de_reclamacion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SAC_LCMP_ProductosPretensionWOShar_Test.cls
/*****************************************************************
 * Name: SAC_LCMP_ProductosPretensionWOSharing
 * Copyright © 2024  CaixaBank
 * 
 * Proposito: Clase test de SAC_LCMP_ProductosPretensionWOSharing
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR         DATE         Description
 * 1.0            --              Iria ANPC     24/12/24        Creación
*****************************************************************/
@isTest
public class SAC_LCMP_ProductosPretensionWOShar_Test {
    @TestSetup
    static void makeData(){
        // User
        List<User> listaUsuarios = SAC_TestDataFactory.crearUsuarioSACGeneral(1);
        SAC_DatabaseDML.insertListDML(listaUsuarios, false);

        PermissionSet ps = [select id from PermissionSet where  PermissionSet.Label ='SAC_General'];
        PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId = ps.id, AssigneeId = listaUsuarios[0].id);
        SAC_DatabaseDML.insertDML(psa, false);

        System.runAs(listaUsuarios[0]) {
            // Reclamacion
            Map<String, Object> camposRecl = new Map<String, Object>();
            camposRecl.put('Subject', 'TestRecl');
            
            Case reclamacion = SAC_TestDataFactory.crearCaso('Reclamacion',camposRecl);
            SAC_DatabaseDML.insertDML(reclamacion, false);

            Map<String, Object> camposPretl = new Map<String, Object>();
            camposPretl.put('Subject', 'TestPretl');
            
            Case pretension = SAC_TestDataFactory.crearCaso('Pretension',camposPretl);
            pretension.SAC_Reclamacion__c = reclamacion.Id;
            SAC_DatabaseDML.insertDML(pretension, false);

            SAC_ProductCase__c producto  = new SAC_ProductCase__c();
            producto.SAC_Pretension__c = pretension.Id;
            producto.SAC_Descripcion__c = 'Descripcion test';
            SAC_DatabaseDML.insertDML(producto, false);
        }
    }
    
    @isTest
    static void createProductWithoutPermission() {
        User usuario = [SELECT Id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND IsActive = true LIMIT 1];
        Case pretension = [SELECT Id FROM Case WHERE Subject = 'TestPretl' LIMIT 1];
        
        System.runAs(usuario) {
            try{
            SAC_LCMP_ProductosPretensionWOSharing.createRecordWithoutSharing('Descripción', '12345', 'Dental', System.today(), System.today(), pretension.Id, 10, 10, null, null);
            //System.assertNotEquals(null, productos, 'No se han recuperado los productos de pretension');
            }catch(Exception e){
                
            }
        }
    }
    
    @isTest
    static void editProductWithoutPermission() {
        User usuario = [SELECT Id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND IsActive = true LIMIT 1];
        Case pretension = [SELECT Id FROM Case WHERE Subject = 'TestPretl' LIMIT 1];
        SAC_ProductCase__c product = [SELECT Id FROM SAC_ProductCase__c WHERE SAC_Pretension__c =: pretension.Id];
        System.runAs(usuario) {
            try{
                SAC_LCMP_ProductosPretensionWOSharing.editRecordWithoutSharing(product.Id, 'Descripción Edit', '12345', 'Dental', System.today(), System.today(), pretension.Id, 10, 10, null, null);
                //System.assertNotEquals(null, productos, 'No se han recuperado los productos de pretension');
            }catch(Exception e){
                
            }
        }
    }
    
    @isTest
    static void createProductWithPermission() {
        User usuario = [SELECT Id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND IsActive = true LIMIT 1];
        Case pretension = [SELECT Id FROM Case WHERE Subject = 'TestPretl' LIMIT 1];
        
        System.runAs(usuario) {
            try{
            SAC_LCMP_ProductosPretensionWOSharing.createRecordWithoutSharing('Descripción', '12345', 'Dental', System.today(), System.today(), pretension.Id, 10, 10, null, null);
            //System.assertNotEquals(null, productos, 'No se han recuperado los productos de pretension');
            }catch(Exception e){
                
            }
        }
    }
    
    @isTest
    static void editProductWithPermission() {
        User usuario = [SELECT Id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND IsActive = true LIMIT 1];
        Case pretension = [SELECT Id FROM Case WHERE Subject = 'TestPretl' LIMIT 1];
        SAC_ProductCase__c product = [SELECT Id FROM SAC_ProductCase__c WHERE SAC_Pretension__c =: pretension.Id];
        System.runAs(usuario) {
            try{
                SAC_LCMP_ProductosPretensionWOSharing.editRecordWithoutSharing(product.Id, 'Descripción Edit', '12345', 'Dental', System.today(), System.today(), pretension.Id, 10, 10, null, null);
                //System.assertNotEquals(null, productos, 'No se han recuperado los productos de pretension');
            }catch(Exception e){
                
            }
        }
    }
}