force-app/main/default/objects/Case/fields/SEG_ClasificacionRapida__c.field-meta.xml
<CustomField>
    <fullName>SEG_ClasificacionRapida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Clasificación rápida del caso</description>
    <label>Clasificación Rápida</label>
    <referenceTo>SEG_ClasificacionRapida__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Grupo__c.field-meta.xml
<CustomField>
    <fullName>SEG_Grupo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo asignado al caso</description>
    <label>Grupo de trabajo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo colaborador, Grupo Operativo Segmentos</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Cases (Grupo)</relationshipLabel>
    <relationshipName>SEG_Grupo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Numero_de_centro__c.field-meta.xml
<CustomField>
    <fullName>SEG_Numero_de_centro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre de centro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Número de centro)</relationshipLabel>
    <relationshipName>SEG_Numero_de_centro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Organizacion__c.field-meta.xml
<CustomField>
    <fullName>SEG_Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEG_Organizacion_Segmentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Zona__c.field-meta.xml
<CustomField>
    <fullName>SEG_Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SEG_Organizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SEG_Zona_Segmentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/SEG_ClasificacionRapida__c.object-meta.xml
<CustomObject>
    <label>Clasificación Rápida</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clasificación Rápida</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Organizacion__c.field-meta.xml
<CustomField>
    <fullName>SEG_Organizacion__c</fullName>
    <label>Organización</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banca Corporativa</fullName>
            </value>
            <value>
                <fullName>Centro Empresas</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>Financiación Estructurada</fullName>
            </value>
            <value>
                <fullName>Centro Soporte Especialistas</fullName>
            </value>
            <value>
                <fullName>PYMES</fullName>
            </value>
            <value>
                <fullName>Banca Internacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEG_Contratos__c/SEG_Contratos__c.object-meta.xml
<CustomObject>
    <label>Contratos</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Número Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_Contratos__c/fields/SEG_Estado__c.field-meta.xml
<CustomField>
    <fullName>SEG_Estado__c</fullName>
    <description>Firmado: Para poder modificar el estado del contrato a firmado el usuario ha de incluir en documentos firmados de dicho registro un PDF.
No Firmado: Es el estado en el que el sistema realiza las reclamaciones automáticas definidas.
Reclamaciones agotadas: Estado una vez finalizadas todas las reclamaciones definidas en el proceso y que hará que el sistema realice el envío a gestor o a cola de trabajo definida.
No reclamar: Es el estado que el usuario escoge cuando el cliente indica que irá físicamente a la oficina a firmarlo por ejemplo.</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Firmado</fullName>
            </value>
            <value>
                <fullName>No firmado</fullName>
                <default>true</default>
                <label>No firmado</label>
            </value>
            <value>
                <fullName>No reclamar</fullName>
            </value>
            <value>
                <fullName>Reclamaciones agotadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEG_Contratos__c/fields/SEG_NombreCuenta__c.field-meta.xml
<CustomField>
    <fullName>SEG_NombreCuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Nombre del cliente relacionado con el contrato.</description>
    <label>Nombre de la cuenta</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El cliente que esta intentando asociar no existe.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente, Centro CaixaBank, Cliente, Cliente (Segmentos)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_Contratos__c/fields/SEG_SR_Seguimiento__c.field-meta.xml
<CustomField>
    <fullName>SEG_SR_Seguimiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso Seguimiento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_Contratos__c/fields/SEG_Zona__c.field-meta.xml
<CustomField>
    <fullName>SEG_Zona__c</fullName>
    <description>Zona del cliente.</description>
    <formula>TEXT(SEG_NombreCuenta__r.SEG_Zona__c)</formula>
    <label>Zona</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SEG_Contratos_AU_TRHan.cls
/**
*   @description SEG_Contratos_AU_TRHan
*/
public with sharing class SEG_Contratos_AU_TRHan  extends CC_TriggerHandlerBase {

    public override void mainEntry(CC_TriggerParameters tp) {
		process((List<SEG_Contratos__c>)tp.newList, (List<SEG_Contratos__c>)tp.oldList, (Map<ID, SEG_Contratos__c>)tp.newMap, (Map<ID, SEG_Contratos__c>)tp.oldMap);
	}
    private void process(List<SEG_Contratos__c> newList, List<SEG_Contratos__c> oldList, Map<ID, SEG_Contratos__c> newMap, Map<ID, SEG_Contratos__c> oldMap) {

        // Procesar las posibles nuevas marcas del contrato.
        Set<Id> listadoMarcasCuenta = new Set<Id>();
        Set<Id> listadoCuentasReclamacionesAgotadas = new Set<Id>();
        for (Id contratoId : newMap.keySet())
        {
            SEG_Contratos__c contratoNew = newMap.get(contratoId);
            SEG_Contratos__c contratoOld = oldMap.get(contratoId);

            if (contratoNew.SEG_Estado__c != contratoOld.SEG_Estado__c && 
                (contratoOld.SEG_Estado__c == 'Reclamaciones Agotadas' || contratoNew.SEG_Estado__c == 'Reclamaciones Agotadas'))
            {
                listadoCuentasReclamacionesAgotadas.add(contratoNew.SEG_NombreCuenta__c);
                listadoCuentasReclamacionesAgotadas.add(contratoOld.SEG_NombreCuenta__c);
            }
            listadoMarcasCuenta.add(contratoNew.SEG_NombreCuenta__c);
            listadoMarcasCuenta.add(contratoOld.SEG_NombreCuenta__c);
        }
        // Gestión de las marcas del cliente.
        if (!listadoMarcasCuenta.isEmpty())
        {
            SEG_Contratos_BI_TRHan.actualizarMarcasReclamaciones (listadoMarcasCuenta, listadoCuentasReclamacionesAgotadas);
        }

        // Procesar las excepciones del contrato.
        getExcepcionesContrato (newMap, oldMap);
    }

    /**
     * @description Gestión de excepciones de contratos.
     * @param newMap Mapa new del contexto del trigger.
     * @param oldMap Mapa old del contexto del trigger.
     */
    private void getExcepcionesContrato (Map<Id,SEG_Contratos__c> newMap, Map<Id,SEG_Contratos__c> oldMap)
    {
        List<Id> listaContratos = new List<Id>();
        for (Id contratoId : newMap.keySet())
        {
            SEG_Contratos__c contratoNew = newMap.get(contratoId);
            SEG_Contratos__c contratoOld = oldMap.get(contratoId);

            // Comprobar cambios que han de evaluar excepciones
            if (contratoNew.SEG_SR_Seguimiento__r?.SEG_Organizacion__c <> contratoOld.SEG_SR_Seguimiento__r?.SEG_Organizacion__c 
                || contratoNew.SEG_SR_Seguimiento__r?.SEG_Zona__c <> contratoOld.SEG_SR_Seguimiento__r?.SEG_Zona__c
                || contratoNew.SEG_SR_Seguimiento__r?.SEG_ClasificacionRapida__c <> contratoOld.SEG_SR_Seguimiento__r?.SEG_ClasificacionRapida__c 
                || contratoNew.SEG_SR_Seguimiento__r?.SEG_Grupo__c <> contratoOld.SEG_SR_Seguimiento__r?.SEG_Grupo__c
                || contratoNew.SEG_SR_Seguimiento__r?.SEG_Numero_de_centro__c <> contratoOld.SEG_SR_Seguimiento__r?.SEG_Numero_de_centro__c 
                || contratoNew.SEG_NombreCuenta__c <> contratoOld.SEG_NombreCuenta__c) 
            {
                listaContratos.add(contratoNew.Id);
            } 
        }

        // Gestionar las excepciones de los contratos.
        if (!listaContratos.isEmpty())
        {
            SEG_ExcepcionesHandler.calcularExcepcionesCasosYContratos(0, null, false, listaContratos);
        }
    }
 }