force-app/main/default/objects/Case/fields/SEG_Case_Owner__c.field-meta.xml
<CustomField>
    <fullName>SEG_Case_Owner__c</fullName>
    <formula>IF(
ISBLANK(Owner:User.Id), /* If blank, it&apos;s a queue */
Owner:Queue.QueueName,
Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName
)</formula>
    <label>Propietario</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_ClasificacionRapida__c.field-meta.xml
<CustomField>
    <fullName>SEG_ClasificacionRapida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Clasificación rápida del caso</description>
    <label>Clasificación Rápida</label>
    <referenceTo>SEG_ClasificacionRapida__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_N_operaciones_del_caso__c.field-meta.xml
<CustomField>
    <fullName>SEG_N_operaciones_del_caso__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Nº oper. del caso</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Organizacion__c.field-meta.xml
<CustomField>
    <fullName>SEG_Organizacion__c</fullName>
    <label>Organización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SEG_Organizacion_Segmentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_TipoClasificacion__c.field-meta.xml
<CustomField>
    <fullName>SEG_TipoClasificacion__c</fullName>
    <description>Tipo de clasificación para el caso en Segmentos.</description>
    <label>Tipo de clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regla de clasificación</fullName>
            </value>
            <value>
                <fullName>Cognitive sin adjuntos</fullName>
            </value>
            <value>
                <fullName>Cognitive con adjuntos</fullName>
            </value>
            <value>
                <fullName>Robot no clasificado</fullName>
            </value>
            <value>
                <fullName>No se ha podido clasificar</fullName>
            </value>
            <value>
                <fullName>Clasificado Manualmente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Zona__c.field-meta.xml
<CustomField>
    <fullName>SEG_Zona__c</fullName>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SEG_Organizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SEG_Zona_Segmentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/CC_InterfaceSettings__mdt.object-meta.xml
<CustomObject>
    <description>Configuración de integraciones</description>
    <label>Configuración interfaz</label>
    <pluralLabel>Configuración interfases</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_Certificado__c.field-meta.xml
<CustomField>
    <fullName>CC_Certificado__c</fullName>
    <description>Certificado necesario en la integración</description>
    <inlineHelpText>Certificado necesario en la integración</inlineHelpText>
    <label>Certificado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/CC_TrazaInt__c.object-meta.xml
<CustomObject>
    <description>Trazas de integraciones</description>
    <label>Traza Integraciones</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interfaz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trazas Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_DetalleError__c.field-meta.xml
<CustomField>
    <fullName>CC_DetalleError__c</fullName>
    <description>Detalle error producido</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Detalle error producido</inlineHelpText>
    <label>Detalle error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FechaFin__c.field-meta.xml
<CustomField>
    <fullName>CC_FechaFin__c</fullName>
    <description>Fecha de finalización de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Fecha de finalización de la integración</inlineHelpText>
    <label>Fecha Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>CC_FechaInicio__c</fullName>
    <description>Fecha inicio de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Fecha inicio de la integración</inlineHelpText>
    <label>Fecha Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FinOK__c.field-meta.xml
<CustomField>
    <fullName>CC_FinOK__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de finalización correcta de la integración</description>
    <inlineHelpText>Indicador de finalización correcta de la integración</inlineHelpText>
    <label>Finalizado OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_Identificador__c.field-meta.xml
<CustomField>
    <fullName>CC_Identificador__c</fullName>
    <description>Identificador asociado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Identificador asociado</inlineHelpText>
    <label>Identificador</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_MensajeEntrada__c.field-meta.xml
<CustomField>
    <fullName>CC_MensajeEntrada__c</fullName>
    <description>Mensaje de entrada</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mensaje de entrada</inlineHelpText>
    <label>Entrada</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_MensajeSalida__c.field-meta.xml
<CustomField>
    <fullName>CC_MensajeSalida__c</fullName>
    <description>Mensaje de salida de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mensaje de salida de la integración</inlineHelpText>
    <label>Salida</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_TipoError__c.field-meta.xml
<CustomField>
    <fullName>CC_TipoError__c</fullName>
    <description>Tipo error producido</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tipo error producido</inlineHelpText>
    <label>Tipo error</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/SEG_ClasificacionRapida__c.object-meta.xml
<CustomObject>
    <label>Clasificación Rápida</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clasificación Rápida</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Canaldeentrada__c.field-meta.xml
<CustomField>
    <fullName>SEG_Canaldeentrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Canal BPO</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>WebService</fullName>
            </value>
            <value>
                <fullName>Paquetería</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Teléfono</label>
            </value>
            <value>
                <fullName>Muro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Nombre_CR_Cognitive__c.field-meta.xml
<CustomField>
    <fullName>SEG_Nombre_CR_Cognitive__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Nombre CR Cognitive</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Organizacion__c.field-meta.xml
<CustomField>
    <fullName>SEG_Organizacion__c</fullName>
    <label>Organización</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banca Corporativa</fullName>
            </value>
            <value>
                <fullName>Centro Empresas</fullName>
            </value>
            <value>
                <fullName>Instituciones</fullName>
            </value>
            <value>
                <fullName>Financiación Estructurada</fullName>
            </value>
            <value>
                <fullName>Centro Soporte Especialistas</fullName>
            </value>
            <value>
                <fullName>PYMES</fullName>
            </value>
            <value>
                <fullName>Banca Internacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Producto__c.field-meta.xml
<CustomField>
    <fullName>SEG_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Se debe añadir un Producto del Tipo Segmentos.</errorMessage>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Tipo_Cliente__c</field>
            <operation>equals</operation>
            <value>Segmentos, Segmentos FFEE, Segmentos CSE, Segmentos BC CE INST, Cliente (COPS), Empleado (COPS), Cliente (COPS)/Empleado (COPS)</value>
        </filterItems>
        <filterItems>
            <field>$Source.SEG_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Clasificación Rápida (Producto)</relationshipLabel>
    <relationshipName>SEG_ClasificacionRapida_Producto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_ClasificacionRapida__c/fields/SEG_Tematica__c.field-meta.xml
<CustomField>
    <fullName>SEG_Tematica__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (1 AND 4 AND 5)</booleanFilter>
        <errorMessage>El negocio de la CR debe concordar con el tipo cliente del MCC.</errorMessage>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Tipo_Cliente__c</field>
            <operation>equals</operation>
            <value>Segmentos</value>
        </filterItems>
        <filterItems>
            <field>$Source.CBK_Negocio__c</field>
            <operation>equals</operation>
            <value>Segmentos</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Tipo_Cliente__c</field>
            <operation>equals</operation>
            <value>Cliente (COPS)/Empleado (COPS) , Cliente (COPS), Empleado (COPS)</value>
        </filterItems>
        <filterItems>
            <field>$Source.CBK_Negocio__c</field>
            <operation>equals</operation>
            <value>Cops</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Clasificación Rápida</relationshipLabel>
    <relationshipName>SEG_ClasificacionRapida_Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_ExcepcionesCR__c/SEG_ExcepcionesCR__c.object-meta.xml
<CustomObject>
    <description>Junction object con plantillas (NO excepciones) de SEGMENTOS.</description>
    <label>Plantillas CR</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>ID Excepciones CR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plantillas CR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_ExcepcionesCR__c/fields/SEG_ClasificacionRapida__c.field-meta.xml
<CustomField>
    <fullName>SEG_ClasificacionRapida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clasificación Rápida</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SEG_ClasificacionRapida__c.CBK_Negocio__c</field>
            <operation>equals</operation>
            <value>Segmentos</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SEG_ClasificacionRapida__c</referenceTo>
    <relationshipLabel>Plantillas CR</relationshipLabel>
    <relationshipName>SEG_ClasificacionRapida</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SEG_CognitiveCR.cls
/**
*   @description SEG_CognitiveCR - Clase para la obtención de clasificaciones rápidas de Casos a partir de la conexión por WS con Cognitive.
*/ 
public with sharing class SEG_CognitiveCR {
    @future(callout=true)
    public static void getCRCognitive(id casoid) { 
  
        //List<ContentVersion> listFiles;
        //List<ContentVersion> listFiles = getFilesCase(casoid); //Obtención de los adjuntos del caso.
        //CC_InterfaceSettings__mdt oConfig = getConfig('SEG_COGNITIVE'); //Obtención de la configuración del WS a partir de la metadata.

        CC_TrazaInt__c oTraza = new CC_TrazaInt__c(); //Creación de la traza para control de WS
        oTraza.Name = 'Cognitive_Segmentos';
        oTraza.CC_FechaInicio__c = datetime.now();


        Case casoSeg = new Case();
        casoSeg = [SELECT id, SEG_ClasificacionRapida__c, SEG_ClasificacionRapida__r.Name,SEG_Case_Owner__c, Subject,Description,CreatedDate,SEG_Zona__c,SEG_Organizacion__c,CaseNumber, SEG_N_operaciones_del_caso__c FROM Case WHERE id=:casoid];
        
        oTraza.CC_Identificador__c = casoSeg.CaseNumber;

        if(casoSeg != null && casoSeg.SEG_ClasificacionRapida__c == null && casoSeg.SEG_Case_Owner__c == 'SEG_BO'){ //US583083 - Se añade una comprovación para evitar que Cognitive reclasifique casos que ya se hayan clasificado manualmente.
            SEG_sendToCognitive sendCase = new SEG_sendToCognitive();
            sendCase.subject = casoSeg.Subject;
    
            if(casoSeg.Description != null){
                sendCase.body = casoSeg.Description.replaceAll('\r\n|\n|\r',' ');  
            }else{
                sendCase.body = '';
            }
    
            sendCase.date_time = casoSeg.CreatedDate.format('yyyy-MM-dd HH:mm:ss', 'Europe/Madrid'); //"2017-12-23 16:30:21" yyyy-MM-dd 
            sendCase.zone = casoSeg.SEG_Zona__c;
            sendCase.organisation=casoSeg.SEG_Organizacion__c;
            sendCase.sr=casoSeg.CaseNumber;
            sendCase.origin='BCorp';
            sendCase.total_attach = '0';
    
            /*if(listFiles != null){
                sendCase.total_attach = String.valueOf(listFiles.size());
            }*/
    
            List<SEG_sendToCognitive.cls_attachs> attachments = new List<SEG_sendToCognitive.cls_attachs>();
            sendCase.attachs = attachments;

            /*for(ContentVersion cv:listFiles) {
                SEG_sendToCognitive.cls_attachs attachmentFile = new SEG_sendToCognitive.cls_attachs();
                attachmentFile.Name = cv.Title+'.'+cv.FileExtension;
                attachmentFile.binary = String.valueOf(cv.versiondata);
                attachmentFile.extension = cv.FileExtension;
                attachmentFile.size = cv.ContentSize;
                attachments.add(attachmentFile);
            }
    
            sendCase.attachs = attachments;
            */
    
            String jsonToCognitive = JSON.serialize(sendCase);
            jsonToCognitive=jsonToCognitive.replace('date_time', 'date-time');
            jsonToCognitive=jsonToCognitive.replace('total_attach', 'total-attach');

            // Custom Setting
            String intSetting = 'SEG_COGNITIVE';
            
            try {

                // Crear HEADER
                Map<String,string> mHeaders =  new  Map<String,string>();
                mHeaders.put('Content-Type', 'application/json;charset=UTF-8');

                CBK_HttpServiceIntegration.RequestWapper requestWrp = new CBK_HttpServiceIntegration.RequestWapper();
                requestWrp.body = jsonToCognitive;
                requestWrp.intSetting = intSetting;
                requestWrp.method = 'POST';
                requestWrp.mHeaders = mHeaders;
                requestWrp.mUriParams = null;
                requestWrp.mQueryParams = null;

                HttpRequest request = CBK_HttpServiceIntegration.getRequest(requestWrp);
                //request.setClientCertificateName(oConfig.CC_Certificado__c);

                HttpResponse response = CBK_HttpServiceIntegration.callHttpService(request, intSetting, intSetting);
                
                oTraza.CC_MensajeEntrada__c = String.valueOf(jsonToCognitive);
    
                if (response != null && response.getStatusCode() == 200) {
                    Integer maxSize = 32767;
                    SEG_receiveFromCognitive results = new SEG_receiveFromCognitive();
                    
                    if (response.getBody() != null && response.getBody().length() < maxSize) {
                        oTraza.CC_MensajeSalida__c = response.getBody();
                    } else if(response.getBody() != null) {
                        oTraza.CC_MensajeSalida__c = response.getBody().substring(0, maxSize);
                    }
                    
                    oTraza.CC_FechaFin__c = datetime.now();
                    oTraza.CC_FinOK__c = true;
                    
                    results = SEG_receiveFromCognitive.parse(response.getBody());
    
                    Case casoControlCR = [SELECT Subject, SEG_ClasificacionRapida__c, SEG_ClasificacionRapida__r.Name, SEG_Case_Owner__c FROM Case WHERE id=:casoid];
                    
                    if(casoControlCR != null && (casoControlCR.SEG_ClasificacionRapida__c != null || casoControlCR.SEG_Case_Owner__c != 'SEG_BO') || (Test.isRunningTest() && casoControlCR.Subject.equalsIgnoreCase('TEST Caso Owner'))){
                        //US583083 - Se inserta en chatter un registro indicando que se ha indicado una CR manualmente durante la consulta a Cognitive.
                        FeedItem feed = new FeedItem();
                        feed.ParentId = casoid; 
                        if (casoControlCR.SEG_Case_Owner__c != 'SEG_BO') {
                            feed.Body = 'Cognitive: Se ha asignado un propietario previa consulta a Cognitive con lo que no se ha aplicado la CR indicada.'; 
                        } else {
                            feed.Body = 'Cognitive: El caso ya se encontraba clasificado manualmente por lo que no se ha podido aplicar Cognitive.'; 
                        }
                        
                        insert feed;

                        //Traza - No se asigna la clasificación al estar ya indicada manualmente.
                        oTraza.CC_FechaFin__c = datetime.now();
                        oTraza.CC_FinOK__c = true;
                        oTraza.CC_TipoError__c = 'Excepcion de asignacion';
                        oTraza.CC_DetalleError__c = 'El caso no ha sido clasificado por cognitive';
                    } else if(results != null && String.isNotBlank(results.category)) {
                        if(results.category=='Robot No Clasificado') { //Cognitive indica que no ha encontrado ninguna clasificacción en base a los datos indicados.
                            casoSeg.SEG_TipoClasificacion__c='Robot no clasificado';
                        } else {
                            FeedItem feed = new FeedItem();
                            feed.Type = 'TextPost';
                            feed.ParentId = casoid;
                            List<SEG_ClasificacionRapida__c> crCognitive = new List<SEG_ClasificacionRapida__c>([select id,name,SEG_Nombre_CR_Cognitive__c,SEG_Canaldeentrada__c, SEG_Tematica__c,SEG_Producto__c,SEG_Motivo__c,SEG_Detalle__c,SEG_Prioridad__c, SEG_CRAuditoria__c from SEG_ClasificacionRapida__c where SEG_Nombre_CR_Cognitive__c =:results.category AND SEG_Inactiva__c=false AND SEG_Organizacion__c includes(:casoSeg.SEG_Organizacion__c)]);
                            if(crCognitive != null && crCognitive.size()>0){
                                
                                casoSeg.SEG_ClasificacionRapida__c=crCognitive[0].id;
                                casoSeg.CC_MCC_Tematica__c = crCognitive[0].SEG_Tematica__c;
                                casoSeg.CC_MCC_ProdServ__c = crCognitive[0].SEG_Producto__c;
                                casoSeg.CC_MCC_Motivo__c = crCognitive[0].SEG_Motivo__c;
                                casoSeg.SEG_Detalle__c = crCognitive[0].SEG_Detalle__c;
                                casoSeg.Priority = crCognitive[0].SEG_Prioridad__c;
                                casoSeg.SEG_N_operaciones_del_caso__c = 1;
                                casoSeg.SEG_TipoClasificacion__c='Cognitive sin adjuntos';

                                feed.Body = 'Cognitive: ' + results.Category; 
                            } else {
                                //Traza - La CR indicada por Cognitive no existe en Salesforce.
                                oTraza.CC_FechaFin__c = datetime.now();
                                oTraza.CC_FinOK__c = false;
                                oTraza.CC_TipoError__c = 'CR No existente.';
                                oTraza.CC_DetalleError__c = 'No existe CR en Salesforce activa con Nombre Cognitive: ' + results.category +  '  y Organización: ' + casoSeg.SEG_Organizacion__c;

                                feed.Body = 'Cognitive: No existe CR en Salesforce activa con Nombre Cognitive: ' + results.category +  '  y Organización: ' + casoSeg.SEG_Organizacion__c; 
                            }
                            insert feed;
                        }
                        //Update caso
                        Database.SaveResult sr = Database.update(casoSeg, false);
                        if (sr.isSuccess()) {
                            Map<String,String> resutAutoasignar = SEG_Case_Operativas_Controller.autoAsignarGrupo(casoSeg.Id);
                            CBK_Log.error('SEG_Cognitive resutAutoasignar: ' + resutAutoasignar);
                        } else {
                            String erroresActualizacion = 'SEG_Cognitive Datasave Error ';
                            for(Database.Error err : sr.getErrors()) {
                                erroresActualizacion += ' - Error: ' + err.getStatusCode() + ' - ' + err.getMessage();
                            }
                            CBK_log.debug(erroresActualizacion, LoggingLevel.ERROR);
                            FeedItem feed = new FeedItem();
                            feed.Type = 'TextPost';
                            feed.ParentId = casoid;
                            feed.Body = 'Cognitive: No se ha podido relalizar la actualización correcta del caso.'; 
                        }                                                                      
                    }  
                } else {
                    //Traza - Error con la conexión al ws
                    oTraza.CC_FechaFin__c = datetime.now();
                    oTraza.CC_FinOK__c = false;
                    oTraza.CC_TipoError__c = 'Error comunicaciones.';
                    oTraza.CC_DetalleError__c = response.getStatusCode() + ':' + response.getBody();
                }
            } catch (Exception e) {
                //Traza - Error de Apex
                CBK_Log.error(e, 'Error durante la comunicación con Cognitive');
                oTraza.CC_FechaFin__c = datetime.now();
                oTraza.CC_FinOK__c = false;
                oTraza.CC_TipoError__c = 'Error comunicaciones.';
                oTraza.CC_DetalleError__c = e.getMessage();
            }
        } else if(casoSeg != null){
            //US583083 - Se inserta en chatter un registro indicando que el caso ya tenía clasificación al contactar con cognitive.
            FeedItem feed = new FeedItem();
            feed.ParentId = casoid; 
            feed.Type = 'TextPost';
            if(casoSeg.SEG_Case_Owner__c != 'SEG_BO'){
                feed.Body = 'Cognitive: Se ha asignado un propietario previa consulta a Cognitive con lo que no se ha aplicado la CR indicada.'; 
            } else {
                feed.Body = 'Cognitive: El caso ya se encontraba clasificado manualmente por lo que no se ha podido aplicar Cognitive.'; 
            }

            insert feed;

            //Traza - No se asigna la clasificación al estar ya indicada manualmente.
            oTraza.CC_FechaFin__c = datetime.now();
            oTraza.CC_FinOK__c = true;
            oTraza.CC_TipoError__c = 'Excepcion de asignacion';
            oTraza.CC_DetalleError__c = 'El caso no ha sido clasificado por cognitive';
        }
        
        insert oTraza;       
    } 
    /*
    //Verión antigua con los adjuntos comentados.
    private static List<ContentVersion> getFilesCase(Id casoId)
    {
        List<ContentVersion> listFiles = new List<ContentVersion>();
        listFiles = [select id, versiondata,Title,FileExtension,ContentSize,FirstPublishLocationId from ContentVersion where FirstPublishLocationId=:casoId];
        List<ContentDocumentLink> contentDocLinkList = new List<ContentDocumentLink>([SELECT ContentDocumentId, LinkedEntityId  FROM ContentDocumentLink where LinkedEntityId in ( SELECT Id FROM Case where id=: casoId) and LinkedEntity.Type='Case']);
        Set<Id> contentDocLinkIds = new Set<Id>();
        for (ContentDocumentLink contentLink:contentDocLinkList){
            contentDocLinkIds.add(contentLink.ContentDocumentId);
        }
        List<ContentVersion> listFiles = new List<ContentVersion>();
        listFiles = [select ContentDocumentId,Title,FileExtension,Description,VersionData,ContentSize from ContentVersion where ContentDocumentId in:contentDocLinkIds];
        return listFiles;
    }
    */
    /*
     20/02/2023 - Se comenta la versión del método con los adjuntos activos a petición de Adela hasta que se decida subir el desarrollo
    private static List<ContentVersion> getFilesCase(Id casoId) {
        List<ContentDocumentLink> contentDocLinkList = new List<ContentDocumentLink>([SELECT ContentDocumentId, LinkedEntityId, ContentDocument.FileType, ContentDocument.ContentSize  FROM ContentDocumentLink WHERE LinkedEntityId =: casoId AND LinkedEntity.Type ='Case']);
        Set<Id> contentDocLinkIds = new Set<Id>();
        SEG_Parametros__mdt tamanoMaxCog = SEG_Parametros__mdt.getInstance('SEG_TamanoMaxArchivosCog');
        for (ContentDocumentLink contentLink : contentDocLinkList){
            if(contentLink.ContentDocument.FileType != 'PNG' && contentLink.ContentDocument.FileType != 'JPEG' && contentLink.ContentDocument.FileType != 'JPG'){
                contentDocLinkIds.add(contentLink.ContentDocumentId);
            } else if (contentLink.ContentDocument.ContentSize > 0 && tamanoMaxCog != null && contentLink.ContentDocument.ContentSize <= Integer.valueOf(tamanoMaxCog.SEG_Valor__c)) {
                contentDocLinkIds.add(contentLink.ContentDocumentId);
            }
        }
        List<ContentVersion> listFiles = new List<ContentVersion>();
        if (!contentDocLinkIds.isEmpty()) {
            listFiles = [SELECT Id, ContentDocumentId,Title,FileExtension,Description,VersionData,ContentSize, FirstPublishLocationId FROM ContentVersion WHERE ContentDocumentId in:contentDocLinkIds];
        }
        
        return listFiles;
    }*/
}