force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Orden__c.field-meta.xml
<CustomField>
    <fullName>CC_Orden__c</fullName>
    <label>Orden</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Valor.recordType-meta.xml
<RecordType>
    <fullName>CC_Valor</fullName>
    <active>true</active>
    <label>Valor</label>
</RecordType>

force-app/main/default/classes/CSBD_ServicioGenesysFuncionApex.cls
public with sharing class CSBD_ServicioGenesysFuncionApex {

    @AuraEnabled(cacheable=true)
    public static List<String> getServicioGenesysFuncionOptions() {
        return CSBD_Utils.listaCampo(
            [SELECT CC_Valor__c FROM CC_Lista_Valores__c
                WHERE RecordType.DeveloperName = 'CC_Valor'
                AND CC_Lista__r.Name = 'CSBD: Configuración de rellamadas'
                AND CC_Activa__c = true
                AND Name = 'Opción para el campo Función de Servicio Genesys'
                ORDER BY CC_Orden__c ASC],
            'CC_Valor__c'
        );
    }
}