force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha inicio vigencia</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/FRA_MotivoDestino__c.field-meta.xml
<CustomField>
    <fullName>FRA_MotivoDestino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que informa el MCC destino para la tabla de equivalencias</description>
    <label>Motivo destino</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El MCC seleccionado debe tener Record Type &apos;C - Motivo&apos; y tipo cliente &apos;Cliente (FRA)&apos;</errorMessage>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Tipo_Cliente__c</field>
            <operation>equals</operation>
            <value>Cliente (FRA)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Listas de valores (Motivo destino)</relationshipLabel>
    <relationshipName>Listas_de_valores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/FRA_MotivoOrigen__c.field-meta.xml
<CustomField>
    <fullName>FRA_MotivoOrigen__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que informa el MCC origen para la tabla de equivalencias</description>
    <label>Motivo origen</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
        <errorMessage>El MCC seleccionado debe tener Record Type &apos;C - Motivo&apos;, tipo cliente &apos;Cliente&apos; y ámbito derivación caixabank e imagin igual a &apos;Caso a Fraude&apos;</errorMessage>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Tipo_Cliente__c</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Ambito_Tareas_Caixa__c</field>
            <operation>equals</operation>
            <value>Caso a Fraude, Phising/Smishing/Malware</value>
        </filterItems>
        <filterItems>
            <field>CC_MCC__c.CC_Ambito_Tareas_Imagin__c</field>
            <operation>equals</operation>
            <value>Caso a Fraude, Phising/Smishing/Malware</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Listas de valores</relationshipLabel>
    <relationshipName>Listas_de_valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/FRA_TablaEquivalenciasDerivacion_CC_FRAUDE.recordType-meta.xml
<RecordType>
    <fullName>FRA_TablaEquivalenciasDerivacion_CC_FRAUDE</fullName>
    <active>true</active>
    <description>Record Type para la creación de registros para definir las equivalencias entre el MCC de un caso de CC, y el MCC de un caso de FRAUDE</description>
    <label>Tabla equivalencias derivación CC a FRAUDE</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Ambito_Tareas_Caixa__c.field-meta.xml
<CustomField>
    <fullName>CC_Ambito_Tareas_Caixa__c</fullName>
    <description>Campo utilizado para controlar a quien se manda la tarea del gestor en las cuentas caixa</description>
    <label>Ámbito derivación Caixa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Amenazas empleados</fullName>
            </value>
            <value>
                <fullName>Amenazas suicidios</fullName>
            </value>
            <value>
                <fullName>Argos General</fullName>
            </value>
            <value>
                <fullName>Argos Xpays</fullName>
            </value>
            <value>
                <fullName>Bizum Fraude</fullName>
            </value>
            <value>
                <fullName>CaixaBank Talks</fullName>
            </value>
            <value>
                <fullName>Cajeros</fullName>
            </value>
            <value>
                <fullName>Cajeros Incidencias</fullName>
            </value>
            <value>
                <fullName>Cambio de gestor</fullName>
            </value>
            <value>
                <fullName>Cambio de oficina</fullName>
            </value>
            <value>
                <fullName>Caso a Fraude</fullName>
            </value>
            <value>
                <fullName>CSBD 3N</fullName>
            </value>
            <value>
                <fullName>CSBD Contratar</fullName>
            </value>
            <value>
                <fullName>CSBD No Contratar</fullName>
            </value>
            <value>
                <fullName>Documentación</fullName>
            </value>
            <value>
                <fullName>No clientes</fullName>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Oficina física</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Phising/Smishing/Malware</fullName>
            </value>
            <value>
                <fullName>Testamentaría</fullName>
            </value>
            <value>
                <fullName>Ventas</fullName>
            </value>
            <value>
                <fullName>Vidacaixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Fecha de inicio de vigencia</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio vigencia</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/classes/FRA_ListaValores_TRHan_Test.cls
@isTest
public with sharing class FRA_ListaValores_TRHan_Test {

    @TestSetup
    static void makeData(){

        Id perfilAdministradorId = [SELECT Id FROM Profile
									WHERE Name IN ('System Administrator', 'Administrador del sistema') LIMIT 1].Id;

        User usuario = new User();
        usuario.FirstName = 'Agente';
        usuario.LastName = 'Uno';
        usuario.Alias='AUno';
        usuario.Email = 'agente2@invalid.comtest';
        usuario.Username= 'agente1@caixa.comtest_cc_fraude';
        usuario.ProfileId = perfilAdministradorId;
        usuario.EmailEncodingkey='UTF-8';
        usuario.LanguageLocaleKey='en_US';
        usuario.LocalesIdKey='en_US';
        usuario.TimezonesIdKey='Europe/Berlin';

        insert new List<User>{usuario};
    }

    @isTest
    public static void crearEquivalenciaTest() {

        User usuario = [SELECT Id FROM User WHERE Username = 'agente1@caixa.comtest_cc_fraude' LIMIT 1];

        System.runAs(usuario) {

            Id recordTypeIdMotivo = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');

            CC_MCC__c mccMotivo = new CC_MCC__c();
            mccMotivo.Name = 'Test Motivo CC para lista valores';
            mccMotivo.CC_Tipo_Cliente__c = 'Cliente';
            mccMotivo.CC_Fecha_Vigencia_Inicio__c = date.today();
            mccMotivo.RecordTypeId = recordTypeIdMotivo;
            mccMotivo.CC_Ambito_Tareas_Caixa__c = 'Caso a Fraude';
            mccMotivo.CC_Codigo_Externo__c = 'MO-000001';
            insert mccMotivo;

            CC_MCC__c mccMotivo2 = new CC_MCC__c();
            mccMotivo2.Name = 'Test motivo FRAUDE para lista valores';
            mccMotivo2.CC_Tipo_Cliente__c = 'Cliente (FRA)';
            mccMotivo2.CC_Fecha_Vigencia_Inicio__c = date.today();
            mccMotivo2.RecordTypeId = recordTypeIdMotivo;
            mccMotivo2.CC_Codigo_Externo__c = 'MO-000002';
            insert mccMotivo2;

            Id tablaEquivalenciasRecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'FRA_TablaEquivalenciasDerivacion_CC_FRAUDE');

            CC_Lista_Valores__c equivalencia = new CC_Lista_Valores__c();
            equivalencia.Name = 'Tets equivalencia MCC CC FRAUDE';
            equivalencia.RecordTypeId = tablaEquivalenciasRecordTypeId;
            equivalencia.FRA_MotivoOrigen__c = mccMotivo.Id;
            equivalencia.FRA_MotivoDestino__c = mccMotivo2.Id;
            insert equivalencia;

            System.assert(equivalencia.Id != null, 'Error al insertar la equivalencia');
        }
    }

    @isTest
    public static void crearEquivalenciaTest2() {

        User usuario = [SELECT Id FROM User WHERE Username = 'agente1@caixa.comtest_cc_fraude' LIMIT 1];

        System.runAs(usuario) {

            Id recordTypeIdMotivo = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_MCC__c', 'CC_Motivo');

            CC_MCC__c mccMotivo = new CC_MCC__c();
            mccMotivo.Name = 'Test Motivo CC para lista valores';
            mccMotivo.CC_Tipo_Cliente__c = 'Cliente';
            mccMotivo.CC_Fecha_Vigencia_Inicio__c = date.today();
            mccMotivo.RecordTypeId = recordTypeIdMotivo;
            mccMotivo.CC_Ambito_Tareas_Caixa__c = 'Caso a Fraude';
            mccMotivo.CC_Codigo_Externo__c = 'MO-000001';
            insert mccMotivo;

            CC_MCC__c mccMotivo3 = new CC_MCC__c();
            mccMotivo3.Name = 'Test Motivo CC para lista valores2';
            mccMotivo3.CC_Tipo_Cliente__c = 'Cliente';
            mccMotivo3.CC_Fecha_Vigencia_Inicio__c = date.today();
            mccMotivo3.RecordTypeId = recordTypeIdMotivo;
            mccMotivo3.CC_Ambito_Tareas_Caixa__c = 'Caso a Fraude';
            mccMotivo3.CC_Codigo_Externo__c = 'MO-000003';
            insert mccMotivo3;

            CC_MCC__c mccMotivo2 = new CC_MCC__c();
            mccMotivo2.Name = 'Test motivo FRAUDE para lista valores';
            mccMotivo2.CC_Tipo_Cliente__c = 'Cliente (FRA)';
            mccMotivo2.CC_Fecha_Vigencia_Inicio__c = date.today();
            mccMotivo2.RecordTypeId = recordTypeIdMotivo;
            mccMotivo2.CC_Codigo_Externo__c = 'MO-000002';
            insert mccMotivo2;

            Id tablaEquivalenciasRecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'FRA_TablaEquivalenciasDerivacion_CC_FRAUDE');

            CC_Lista_Valores__c equivalencia = new CC_Lista_Valores__c();
            equivalencia.Name = 'Tets equivalencia MCC CC FRAUDE';
            equivalencia.RecordTypeId = tablaEquivalenciasRecordTypeId;
            equivalencia.FRA_MotivoOrigen__c = mccMotivo.Id;
            equivalencia.FRA_MotivoDestino__c = mccMotivo2.Id;
            insert equivalencia;

            equivalencia.FRA_MotivoOrigen__c = mccMotivo3.Id;
            update equivalencia;

            System.assert(equivalencia.Id != null, 'Error al insertar la equivalencia');
        }
    }
}