force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Accion__c/SAC_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto juntion entre el Maestro de acciones y el objeto Case creando una relación acción-reclamación/pretensión, para el proyecto de SAC Reclamaciones.</description>
    <label>Acción</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado de la acción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteEnviar</fullName>
                <default>true</default>
                <label>Pendiente enviar</label>
            </value>
            <value>
                <fullName>SAC_PendienteAsignar</fullName>
                <label>Pendiente asignar</label>
            </value>
            <value>
                <fullName>SAC_EnGestion</fullName>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadaIncompleta</fullName>
                <label>Finalizada incompleta</label>
            </value>
            <value>
                <fullName>SAC_StandBy</fullName>
                <label>Stand By</label>
            </value>
            <value>
                <fullName>SAC_PendienteRevision</fullName>
                <label>Pendiente revisión de GGH</label>
            </value>
            <value>
                <fullName>SAC_Devuelta</fullName>
                <label>Devuelta</label>
            </value>
            <value>
                <fullName>SAC_PteReenvio</fullName>
                <label>Pendiente reenvío a GGH</label>
            </value>
            <value>
                <fullName>SAC_Descartada</fullName>
                <label>Descartada</label>
            </value>
            <value>
                <fullName>SAC_Abierto</fullName>
                <isActive>false</isActive>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>SAC_Cerrado</fullName>
                <isActive>false</isActive>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_FechaVencimientoInicial__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaVencimientoInicial__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha vto inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Acciones de ejecución (Reclamación)</relationshipLabel>
    <relationshipName>SAC_AccionesCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/recordTypes/SAC_MaestroDeTareas.recordType-meta.xml
<RecordType>
    <fullName>SAC_MaestroDeTareas</fullName>
    <active>true</active>
    <description>Acciones que ya están predefinidas</description>
    <label>Maestro de tareas</label>
</RecordType>

force-app/main/default/objects/SAC_Accion__c/recordTypes/SAC_OtrasTareas.recordType-meta.xml
<RecordType>
    <fullName>SAC_OtrasTareas</fullName>
    <active>true</active>
    <description>Creación de nuevas tareas</description>
    <label>Otras Tareas</label>
</RecordType>

force-app/main/default/objects/SAC_Accion__c/recordTypes/SPV_Acciones.recordType-meta.xml
<RecordType>
    <fullName>SPV_Acciones</fullName>
    <active>true</active>
    <description>Record Type para la creación de tareas en SPV</description>
    <label>SPV Acciones</label>
</RecordType>

force-app/main/default/objects/SAC_Accion__c/recordTypes/SPV_MaestroDeTareas.recordType-meta.xml
<RecordType>
    <fullName>SPV_MaestroDeTareas</fullName>
    <active>true</active>
    <description>Maestro de tareas de supervisores</description>
    <label>SPV Maestro de tareas</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_CasoEscalado__c.field-meta.xml
<CustomField>
    <fullName>SAC_CasoEscalado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relacionar los escalados de los casos</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Escalados</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Conclusion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Conclusion__c</fullName>
    <description>Conclusión del escalado</description>
    <label>Conclusión</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_Autorizado</fullName>
                <label>Autorizado</label>
            </value>
            <value>
                <fullName>SAC_AutorizadoConModificaciones</fullName>
                <label>Autorizado con modificaciones</label>
            </value>
            <value>
                <fullName>SAC_Denegado</fullName>
                <label>Denegado</label>
            </value>
            <value>
                <fullName>SAC_DevolverNivelAnterior</fullName>
                <label>Devolver escalado al nivel anterior</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado en el que se encuentra la interacción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteRespuesta</fullName>
                <default>true</default>
                <label>Pendiente Respuesta</label>
            </value>
            <value>
                <fullName>SAC_Resuelta</fullName>
                <label>Resuelta</label>
            </value>
            <value>
                <fullName>SAC_Atendida</fullName>
                <label>Atendida</label>
            </value>
            <value>
                <fullName>SAC_Reescalada</fullName>
                <label>Re escalada</label>
            </value>
            <value>
                <fullName>SAC_Borrador</fullName>
                <label>Pendiente Respuesta -  Borrador</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadoSinAtender</fullName>
                <label>Finalizado sin atender</label>
            </value>
            <value>
                <fullName>SAC_Cancelado</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>SAC_Devuelto</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>SAC_PendienteRespuestaDefinitiva</fullName>
                <label>Pendiente Respuesta Definitiva</label>
            </value>
            <value>
                <fullName>SPV_PendienteEnviar</fullName>
                <label>Pendiente enviar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_GrupoColaborador__c.field-meta.xml
<CustomField>
    <fullName>SAC_GrupoColaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo Colaborador</description>
    <label>Grupo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 6) OR (1 AND 2 AND 7) OR (3 AND 4) OR (3 AND 5) OR (4 AND 8) OR (5 AND 8) OR (3 AND 9) OR (1 AND 10)</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteConsultas__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Consulta</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_PermiteEscalado__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV2</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoNV3</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_TieneUsuariosActivos__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.SAC_Externo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Letrados</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>EscaladoSPV</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ConsultaSPV</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Interacciones (Grupo)</relationshipLabel>
    <relationshipName>Interacciones1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relaciona el objeto interaccion con las reclamaciones</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Titulo__c</fullName>
    <description>Título del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_Consulta.recordType-meta.xml
<RecordType>
    <fullName>SAC_Consulta</fullName>
    <active>true</active>
    <description>Consulta a datos de otros Departamentos</description>
    <label>Consulta</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_Escalado.recordType-meta.xml
<RecordType>
    <fullName>SAC_Escalado</fullName>
    <active>true</active>
    <description>Record type para el escalado</description>
    <label>EscaladoNV2</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_EscaladoNV3.recordType-meta.xml
<RecordType>
    <fullName>SAC_EscaladoNV3</fullName>
    <active>true</active>
    <description>Escalados de nivel 3</description>
    <label>EscaladoNV3</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SPV_Consulta.recordType-meta.xml
<RecordType>
    <fullName>SPV_Consulta</fullName>
    <active>true</active>
    <description>Record type para la consulta del proyecto SPV</description>
    <label>ConsultaSPV</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SPV_Escalado.recordType-meta.xml
<RecordType>
    <fullName>SPV_Escalado</fullName>
    <active>true</active>
    <description>Record type para el escalado del proyecto SPV</description>
    <label>EscaladoSPV</label>
</RecordType>

force-app/main/default/classes/SAC_LCMP_AsuntosPendientes.cls
/*****************************************************************
 * Name: SAC_LCMP_AsuntosPendientes
 * Copyright © 2021  CaixaBank
 * 
 * Proposito: Controlador del componente sAC_AsuntosPendientes
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR         DATE         Description
 * 1.0              US308697     Marcela Neira   24/03/2022      Creación
 * 1.1              US1208226     Raúl Santos    24/04/2025      Modificación: reutilizar para el proyecto SPV  
*****************************************************************/
public with sharing class SAC_LCMP_AsuntosPendientes {  

    private static Set<String> objetos = new Set<String>{'SAC_Interaccion__c','SAC_Accion__c'};
    private static Map<String, Map<String,Schema.RecordTypeInfo>> mapRTsObjects = SAC_Utils.getRecordTypesObjects(objetos);
    
    final static Id RECTYPECONSULTA = mapRTsObjects.get('SAC_Interaccion__c').get('SAC_Consulta').getRecordTypeId();
    final static Id RECTYPEESCALADONV2 = mapRTsObjects.get('SAC_Interaccion__c').get('SAC_Escalado').getRecordTypeId();
    final static Id RECTYPEESCALADONV3 = mapRTsObjects.get('SAC_Interaccion__c').get('SAC_EscaladoNV3').getRecordTypeId();
    final static Id RECTYPEOTRATAREA = mapRTsObjects.get('SAC_Accion__c').get('SAC_OtrasTareas').getRecordTypeId();
    final static Id RECTYPEMAESTROTAREA = mapRTsObjects.get('SAC_Accion__c').get('SAC_MaestroDeTareas').getRecordTypeId();
  
    final static Id RECTYPECONSULTA_SPV = mapRTsObjects.get('SAC_Interaccion__c').get('SPV_Consulta').getRecordTypeId();
    final static Id RECTYPEESCALADO_SPV = mapRTsObjects.get('SAC_Interaccion__c').get('SPV_Escalado').getRecordTypeId();
    final static Id RECTYPEOTRATAREA_SPV = mapRTsObjects.get('SAC_Accion__c').get('SPV_Acciones').getRecordTypeId();
    final static Id RECTYPEMAESTROTAREA_SPV = mapRTsObjects.get('SAC_Accion__c').get('SPV_MaestroDeTareas').getRecordTypeId();


    @AuraEnabled
    public static AsuntosPendientesWrapper comprobarAsuntos(String idCaso) {
        
        List<SAC_Interaccion__c> listaEscalados = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultas = new List<SAC_Interaccion__c>();
        String mensaje;

        try {
            List<SAC_Accion__c> listaTareas = [SELECT id, Name, CreatedDate, SAC_Estado__c, SAC_FechaVencimientoInicial__c 
                                                FROM SAC_Accion__c 
                                                WHERE RecordTypeId IN (:RECTYPEOTRATAREA, :RECTYPEMAESTROTAREA, :RECTYPEOTRATAREA_SPV, :RECTYPEMAESTROTAREA_SPV) AND SAC_Reclamacion__c =:idCaso AND (SAC_Estado__c <> 'SAC_Finalizada' AND SAC_Estado__c <> 'SAC_FinalizadaIncompleta'  AND SAC_Estado__c <> 'SAC_Descartada')];

            List<SAC_Interaccion__c> listaInteracciones = [SELECT Id, Name, SAC_Estado__c, CreatedDate, SAC_Conclusion__c, SAC_CasoEscalado__c, RecordTypeId,
                                                        SAC_GrupoColaborador__r.Name, SAC_Titulo__c
                                                        FROM SAC_Interaccion__c 
                                                        WHERE RecordTypeId IN (:RECTYPECONSULTA, :RECTYPEESCALADONV2, :RECTYPEESCALADONV3, :RECTYPECONSULTA_SPV, :RECTYPEESCALADO_SPV) AND (SAC_CasoEscalado__c =: idCaso OR SAC_Reclamacion__c =: idCaso) AND (SAC_Estado__c = 'SAC_PendienteRespuesta' OR SAC_Estado__c = 'SAC_PendienteRespuestaDefinitiva')];

            for(SAC_Interaccion__c interaccion: listaInteracciones){
                if(interaccion.RecordTypeId == RECTYPEESCALADONV2 || interaccion.RecordTypeId == RECTYPEESCALADONV3 || interaccion.RecordTypeId == RECTYPEESCALADO_SPV){
                    listaEscalados.add(interaccion);
                }else if(interaccion.RecordTypeId == RECTYPECONSULTA || interaccion.RecordTypeId == RECTYPECONSULTA_SPV){
                    listaConsultas.add(interaccion);
                }
            }

            if(listaTareas.isEmpty() && listaConsultas.isEmpty() && listaEscalados.isEmpty()){
                mensaje='No tiene asuntos pendientes';
            }else {
                mensaje='OK';
            }

            AsuntosPendientesWrapper  apw = new AsuntosPendientesWrapper(listaTareas, listaEscalados , listaConsultas, mensaje);
            return  apw;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**************************************************************************
     * Proposito: Clase wrapper para los asuntos pendientes
     * 
     * Historial
     * -------
     * VERSION        USER_STORY       AUTHOR         DATE         Description
     * 1.0             US308697     Marcela Neira   24/03/2022      Creación
    **************************************************************************/  

    public class AsuntosPendientesWrapper{
        @AuraEnabled public List<SAC_Accion__c> listaTareas {get; set;}
        @AuraEnabled public List<SAC_Interaccion__c> listaEscalados {get; set;}
        @AuraEnabled public List<SAC_Interaccion__c> listaConsultas {get; set;}
        @AuraEnabled public String mensaje {get; set;}

        public AsuntosPendientesWrapper(List<SAC_Accion__c> listaTareasC, List<SAC_Interaccion__c> listaEscaladosC, List<SAC_Interaccion__c> listaConsultasC, String mensajeC){
            listaTareas = listaTareasC;
            listaEscalados = listaEscaladosC;
            listaConsultas = listaConsultasC;
            mensaje = mensajeC;
        }
    }
}