force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/OS_Negocio__c.field-meta.xml
<CustomField>
    <fullName>OS_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CSI_Bankia</fullName>
            </value>
            <value>
                <fullName>GRR</fullName>
            </value>
            <value>
                <fullName>HDT</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>SEGMENTOS</fullName>
            </value>
            <value>
                <fullName>SPV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Plantilla__c/CC_Grupo_Colaborador_Plantilla__c.object-meta.xml
<CustomObject>
    <label>Grupo Colaborador Plantilla</label>
    <nameField>
        <displayFormat>GCP-{0000}</displayFormat>
        <label>Grupo Colaborador Plantilla Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grupo Colaborador Plantillas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador_Plantilla__c/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Plantillas</relationshipLabel>
    <relationshipName>Grupo_Colaborador_Plantillas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Plantilla__c/fields/CC_Plantilla_Name__c.field-meta.xml
<CustomField>
    <fullName>CC_Plantilla_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plantilla</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CC_Grupo_Colaborador_Plantilla.cls
public with sharing class CC_Grupo_Colaborador_Plantilla {
    @AuraEnabled
    public static List<EmailTemplate> getPlantillas(Id grupoId, String carpetaOperativa) {
        List<EmailTemplate> opcionesPlantilla = new List<EmailTemplate>();
        String carpeta = carpetaOperativa + '_es';

        Id parentId = [SELECT Id FROM Folder WHERE DeveloperName = :carpeta LIMIT 1].Id;
        
        List<String> plantillasRegistradas = new List<String>();
        for (CC_Grupo_Colaborador_Plantilla__c plantilla : [SELECT CC_Plantilla_Name__c FROM CC_Grupo_Colaborador_Plantilla__c WHERE CC_Grupo_Colaborador__c = :grupoId]) {
            plantillasRegistradas.add(plantilla.CC_Plantilla_Name__c);
        }

        List<EmailTemplate> plantillas = [SELECT Name,DeveloperName FROM EmailTemplate WHERE FolderId = :parentId AND Name NOT IN :plantillasRegistradas ORDER BY Name ASC];
        for (EmailTemplate plantilla : plantillas) {
            opcionesPlantilla.add(plantilla);
        }
        
        return opcionesPlantilla;
    }
    @AuraEnabled
    public static List<Folder> getOperativas(String grupo) {        
        List<CC_Grupo_Colaborador__c> grupoColaborador = [SELECT OS_Negocio__c FROM CC_Grupo_Colaborador__c WHERE Id = :grupo];

        Id parentId;
        String carpetaNegocio = '';
        List<Folder> carpetas = new List<Folder>();

        if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'COPS') {
            carpetaNegocio = 'OS_Operativas';
            
        }else if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'CSI_Bankia') {
            carpetaNegocio = 'CC_Operativas_CSI_Bankia';
            
        }else if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'CAM') {
            carpetaNegocio = 'AM_Operativas';
            
        }else if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'HDT') {
            carpetaNegocio = 'HDT_Operativas';
        
        }
        else if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'SACH') { 
            carpetaNegocio = 'SACH_Operativas';  
        }       
        else if (grupoColaborador.size() > 0 && grupoColaborador[0].OS_Negocio__c == 'GRR') { 
           carpetaNegocio = 'GRR_Operativas';  
        }     
        else {
            carpetaNegocio = 'CC_Operativas';            
        }
        
        List<Folder> listadoCarpetas = [SELECT Id FROM Folder WHERE DeveloperName = :carpetaNegocio LIMIT 1];
        parentId = listadoCarpetas[0].Id;
        carpetas = [SELECT Name,DeveloperName FROM Folder WHERE TYPE = 'EmailTemplate' AND ParentId = :parentId AND (DeveloperName like '%Trasladar%' OR DeveloperName like '%Remitir%')];
        
        return carpetas;
    }
    @AuraEnabled
    public static void guardar(CC_Grupo_Colaborador_Plantilla__c plantilla){
        insert plantilla;        
    }
}