force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SEG_Tipologia__c.field-meta.xml
<CustomField>
    <fullName>SEG_Tipologia__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CSO</fullName>
            </value>
            <value>
                <fullName>Firmas</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>CSO FFEE</fullName>
            </value>
            <value>
                <fullName>BO FFEE</fullName>
            </value>
            <value>
                <fullName>CSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/CC_Grupo_Colaborador_Contact__c.object-meta.xml
<CustomObject>
    <label>Colaborador</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Colaborador Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador_Contact__c/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Colaboradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SEG_Grupo_Colaborador_BU_TRHan_Test.cls
@isTest
public class SEG_Grupo_Colaborador_BU_TRHan_Test {

    @isTest
    public static void executeTrigger() 
    {
        CC_Grupo_Colaborador__c grupoColaboradorA = SEG_TestHelper.createGrupoColaborador('BO_TESTApex1', 'SEGMENTOS', 'BO');
        User userA = SEG_TestHelper.createUser('UsA');
        CC_Grupo_Colaborador_Contact__c colaboradorA = SEG_TestHelper.createColaborador(grupoColaboradorA, 'Escritura', userA);
        grupoColaboradorA.SEG_Tipologia__c='MCC';
        update grupoColaboradorA;
        
        // Si se hace el update, es correcto.
        System.assert(grupoColaboradorA.Id != null);
        
        List<CC_Grupo_Colaborador__c> grupoUpdate = [SELECT Id FROM CC_Grupo_Colaborador__c WHERE Name = 'BO_TESTApex1' AND SEG_Tipologia__c = 'MCC'];
        System.assert(grupoUpdate.size()>0);        
    }
}