force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/recordTypes/SAC_GrupoResponsableAccion.recordType-meta.xml
<RecordType>
    <fullName>SAC_GrupoResponsableAccion</fullName>
    <active>true</active>
    <description>Equipo responsable de la gestión de las acciones para el Proyecto de SAC Reclamaciones</description>
    <label>Grupo Responsable de la acción</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado en el que se encuentra la interacción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteRespuesta</fullName>
                <default>true</default>
                <label>Pendiente Respuesta</label>
            </value>
            <value>
                <fullName>SAC_Resuelta</fullName>
                <label>Resuelta</label>
            </value>
            <value>
                <fullName>SAC_Atendida</fullName>
                <label>Atendida</label>
            </value>
            <value>
                <fullName>SAC_Reescalada</fullName>
                <label>Re escalada</label>
            </value>
            <value>
                <fullName>SAC_Borrador</fullName>
                <label>Pendiente Respuesta -  Borrador</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadoSinAtender</fullName>
                <label>Finalizado sin atender</label>
            </value>
            <value>
                <fullName>SAC_Cancelado</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>SAC_Devuelto</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>SAC_PendienteRespuestaDefinitiva</fullName>
                <label>Pendiente Respuesta Definitiva</label>
            </value>
            <value>
                <fullName>SPV_PendienteEnviar</fullName>
                <label>Pendiente enviar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Oficina__c.field-meta.xml
<CustomField>
    <fullName>SAC_Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interacciones</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Pregunta__c.field-meta.xml
<CustomField>
    <fullName>SAC_Pregunta__c</fullName>
    <description>Pregunta a realizar</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Pregunta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_Consulta.recordType-meta.xml
<RecordType>
    <fullName>SAC_Consulta</fullName>
    <active>true</active>
    <description>Consulta a datos de otros Departamentos</description>
    <label>Consulta</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_Escalado.recordType-meta.xml
<RecordType>
    <fullName>SAC_Escalado</fullName>
    <active>true</active>
    <description>Record type para el escalado</description>
    <label>EscaladoNV2</label>
</RecordType>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_EscaladoNV3.recordType-meta.xml
<RecordType>
    <fullName>SAC_EscaladoNV3</fullName>
    <active>true</active>
    <description>Escalados de nivel 3</description>
    <label>EscaladoNV3</label>
</RecordType>

force-app/main/default/classes/SAC_Interaccion_AU_TRHan.cls
public with sharing class SAC_Interaccion_AU_TRHan extends CC_TriggerHandlerBase{
    public override void mainEntry(CC_TriggerParameters tp) {
        process((List<SAC_Interaccion__c>) tp.newList, (Map<Id, SAC_Interaccion__c>) tp.newMap, (List<SAC_Interaccion__c>) tp.oldList, (Map<Id, SAC_Interaccion__c>) tp.oldMap);
    }    
    private void process(List<SAC_Interaccion__c> listNewObj, Map<Id, SAC_Interaccion__c> mapNewObj, List<SAC_Interaccion__c> listOldObj, Map<Id, SAC_Interaccion__c> mapOldObj){
        //obtener record type  
        Id recTypeEscaladoNv2 = Schema.SObjectType.SAC_Interaccion__c.getRecordTypeInfosByDeveloperName().get('SAC_Escalado').getRecordTypeId();
        Id recTypeEscaladoNv3 = Schema.SObjectType.SAC_Interaccion__c.getRecordTypeInfosByDeveloperName().get('SAC_EscaladoNV3').getRecordTypeId();
        Id recTypeConsulta = Schema.SObjectType.SAC_Interaccion__c.getRecordTypeInfosByDeveloperName().get('SAC_Consulta').getRecordTypeId();
        Id recTypeGrupoResAccion = Schema.SObjectType.CC_Grupo_Colaborador__c.getRecordTypeInfosByDeveloperName().get('SAC_GrupoResponsableAccion').getRecordTypeId();
        String estadoBorradorInterraccion = 'SAC_Borrador';
        String estadoPendienteRespuestaDefinitivaInteraccion = 'SAC_PendienteRespuestaDefinitiva';

        List<SAC_Interaccion__c> listaEscaladosNV2yNV3 = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultaOficinas = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultaInterna = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaInteracciones = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultaRespondida = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultaPendienteRespuesta = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultaPendienteRespuestaDefinitiva = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaCerrarTME = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaReabrirTME = new List<SAC_Interaccion__c>();
        List<SAC_Interaccion__c> listaConsultasConOficina = new List<SAC_Interaccion__c>();

        //Recorremos la lista de interacciones
        for (SAC_Interaccion__c consulta : listNewObj) {
            
            //listaConsulta.add(consulta);
            if (consulta.RecordTypeId == recTypeEscaladoNv2 || consulta.RecordTypeId == recTypeEscaladoNv3) {
                listaEscaladosNV2yNV3.add(consulta);
            }

            if(consulta.RecordTypeId == recTypeConsulta){
                //no es una funcionalidad unica para escalados, puede ser aplicada también para consultas

                if(consulta.SAC_Pregunta__c != mapOldObj.get(consulta.Id).SAC_Pregunta__c 
                    && String.isBlank(mapOldObj.get(consulta.Id).SAC_Pregunta__c)
                ){
                    listaConsultaOficinas.add(consulta);
                    //Añadir a una lista las consultas que tengan una oficina informada para posteriormente llamar al método que envía el correo electronico de la pregunta realizada
                    if (String.isNotBlank(consulta.SAC_Oficina__c)) {
                        listaConsultasConOficina.add(consulta);
                    }
                }
                if (mapOldObj.get(consulta.id).SAC_Estado__c != consulta.SAC_Estado__c && consulta.SAC_Estado__c == 'SAC_Resuelta') {
                    listaConsultaRespondida.add(consulta);
                }
                if (mapOldObj.get(consulta.Id).SAC_Estado__c != consulta.SAC_Estado__c && consulta.SAC_Estado__c == 'SAC_PendienteRespuesta') {
                    listaConsultaPendienteRespuesta.add(consulta);
                }
                if (mapOldObj.get(consulta.Id).SAC_Estado__c != consulta.SAC_Estado__c && consulta.SAC_Estado__c == 'SAC_PendienteRespuestaDefinitiva') {
                    listaConsultaPendienteRespuestaDefinitiva.add(consulta);
                }
            }

            if(consulta.SAC_Estado__c != estadoBorradorInterraccion){
                listaCerrarTME.add(consulta);
            }
            if(consulta.SAC_Estado__c == estadoPendienteRespuestaDefinitivaInteraccion){
                listaReabrirTME.add(consulta);
            }
        }

      

        if (!listaEscaladosNV2yNV3.isEmpty()) {
            SAC_Interaccion.crearTaskEscaladoAtendido(listaEscaladosNV2yNV3, mapOldObj);
            //SAC_Interaccion.cerrarTME(listaEscaladosNV2yNV3, mapOldObj);
            SAC_Notificacion.notificarEscaladoAtendido(listaEscaladosNV2yNV3, mapOldObj);
        }
        if(!listaCerrarTME.isEmpty()){
            SAC_Interaccion.cerrarTME(listaCerrarTME, mapOldObj);
        }
        if(!listaReabrirTME.isEmpty()){
            SAC_Interaccion.reabrirTME(listaCerrarTME, mapOldObj);
        }
        if (!listaConsultasConOficina.isEmpty()) {
            SAC_Interaccion.enviarEmailConsultaInterna(listaConsultasConOficina);
        }
        if(!listaConsultaOficinas.isEmpty()){
            //SAC_Interaccion.cambiaEstado(listaConsultasConGrupo); ahora se hace en el BU
            SAC_Interaccion.insertarTME(listaConsultaOficinas);
        }
        if (!listaConsultaRespondida.isEmpty()) {
            SAC_Notificacion.alertaConsultaRespondida(listaConsultaRespondida);
        }
        if (!listaConsultaPendienteRespuesta.isEmpty()) {
            SAC_Interaccion.scheduleAlertaConsulta24h(listaConsultaPendienteRespuesta);
        }
        if (!listaConsultaPendienteRespuestaDefinitiva.isEmpty()) {
            SAC_Interaccion.reprogramarAlertaConsulta(listaConsultaPendienteRespuestaDefinitiva);
        }
    }
}