force-app/main/default/objects/CBK_SCH_PendingProcess__c/CBK_SCH_PendingProcess__c.object-meta.xml
<CustomObject>
    <label>CBK SCH PendingProcess</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Schedule Pendig Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CBK SCH PendingProcess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CSBD_Gestor_Oportunidad__c/CSBD_Gestor_Oportunidad__c.object-meta.xml
<CustomObject>
    <label>Gestor Oportunidad</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre Gestor Oportunidad</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gestores Oportunidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSBD_Gestor_Oportunidad__c/fields/CSBD_Estado__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
            </value>
            <value>
                <fullName>Fuera horario comercial</fullName>
            </value>
            <value>
                <fullName>Fuera horario contacto</fullName>
            </value>
            <value>
                <fullName>Pendiente de asignar</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSBD_Gestor_Oportunidad__c/fields/CSBD_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Gestores Oportunidad</relationshipLabel>
    <relationshipName>Gestores_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSBD_ParametrosBatch__c/CSBD_ParametrosBatch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Parámetros de tiempo entre ejecuciones y número de registros por ejecución para batch.</description>
    <label>CSBD - Parametros batch</label>
</CustomObject>

force-app/main/default/objects/CSBD_ParametrosBatch__c/fields/CSBD_RegistrosPorLote__c.field-meta.xml
<CustomField>
    <fullName>CSBD_RegistrosPorLote__c</fullName>
    <label>Registros por lote</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CSBD_ParametrosBatch__c/fields/CSBD_TiempoIntervalos__c.field-meta.xml
<CustomField>
    <fullName>CSBD_TiempoIntervalos__c</fullName>
    <label>Tiempo intervalos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Estado__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>Activa</fullName>
                <default>true</default>
                <label>Activa</label>
            </value>
            <value>
                <fullName>Pendiente Interno</fullName>
            </value>
            <value>
                <fullName>Pendiente Cita</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Pendiente Cliente</fullName>
            </value>
            <value>
                <fullName>Con Venta</fullName>
                <isActive>false</isActive>
                <label>Con Venta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CSBD_CMB.recordType-meta.xml
<RecordType>
    <fullName>CSBD_CMB</fullName>
    <active>true</active>
    <businessProcess>CSBD_Sales_Process_Simple</businessProcess>
    <label>CMB</label>
</RecordType>

force-app/main/default/classes/CSBD_BatchJob_Motor_Test.cls
@isTest
public class CSBD_BatchJob_Motor_Test {

    @TestSetup
    public static void crearDatosPrueba() {
        User usuarioGestor = CSBD_Usuarios.usuarioGestor();

        Opportunity oportunidad = new Opportunity();
        oportunidad.RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByDeveloperName().get('CSBD_CMB').getRecordTypeId();
        oportunidad.Name = 'Oportunidad Test';
        oportunidad.StageName = 'Solicitud';
        oportunidad.CSBD_Estado__c = 'Cerrada';
        insert oportunidad;

        OpportunityShare oppshare = new OpportunityShare();
        oppshare.UserOrGroupId = [SELECT Id FROM User WHERE FirstName = 'GestorCSBD' AND Profile.Name = 'CSBD Gestor' LIMIT 1].Id;
        oppshare.OpportunityId = oportunidad.Id;
        oppshare.OpportunityAccessLevel = 'Edit';
        insert oppshare;


        
       List<CSBD_Gestor_Oportunidad__c> listaGestorOportunidad = new List<CSBD_Gestor_Oportunidad__c>();

        for (Integer i = 0; i < 100; i++) {
            CSBD_Gestor_Oportunidad__c gestorOportunidad = new CSBD_Gestor_Oportunidad__c();
            gestorOportunidad.Name = 'Gestor oportunidad ' + (i + 1); // Asignar un nombre único
            gestorOportunidad.CSBD_Oportunidad__c = oportunidad.Id;
            gestorOportunidad.CSBD_Estado__c = 'Fuera horario comercial';
            listaGestorOportunidad.add(gestorOportunidad);
        }
        insert listaGestorOportunidad;  
        
    
        
        CSBD_ParametrosBatch__c parametrosBatch = new CSBD_ParametrosBatch__c();
		parametrosBatch.CSBD_RegistrosPorLote__c = 10; 
		parametrosBatch.CSBD_TiempoIntervalos__c = 5;
		insert parametrosBatch;

    }

   

    @isTest
    public static void test() {
        User usuarioGestor = [SELECT Id FROM User WHERE FirstName = 'GestorCSBD' AND Profile.Name = 'CSBD Gestor' LIMIT 1];

        System.runAs ( usuarioGestor ) {
            Test.startTest();
            CSBD_BatchJob_Motor batchTest = new CSBD_BatchJob_Motor();
            Database.executeBatch(batchTest);
            Test.stopTest();

            List<CBK_SCH_PendingProcess__c> pP= [select id, Schedule_Time__c from CBK_SCH_PendingProcess__c where ClassName__c = 'CBK_SCH_CSBD_ScheduleBatchGestorOppty'];
            List<CSBD_Gestor_Oportunidad__c> gestorOportunidad = [SELECT Id, OwnerId, CSBD_Estado__c FROM CSBD_Gestor_Oportunidad__c WHERE CSBD_Estado__c =: 'Pendiente de asignar'];
            
            System.assertEquals(!pP.isEmpty(), true);
            System.assertEquals(!gestorOportunidad.isEmpty(), true);
        }
    }
    
   
}