force-app/main/default/objects/Case/recordTypes/SEG_Cliente.recordType-meta.xml
<RecordType>
    <fullName>SEG_Cliente</fullName>
    <active>true</active>
    <businessProcess>SEG_Clientes</businessProcess>
    <label>Cliente (SEG)</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SEG_Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>SEG_Seguimiento</fullName>
    <active>true</active>
    <businessProcess>SEG_Clientes</businessProcess>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/CC_Caracteristica__c/CC_Caracteristica__c.object-meta.xml
<CustomObject>
    <label>Característica</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Características</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Caracteristica__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/objects/CC_Caracteristica__c/recordTypes/SEG_Caracteristicacaso.recordType-meta.xml
<RecordType>
    <fullName>SEG_Caracteristicacaso</fullName>
    <active>true</active>
    <label>Característica de un caso</label>
</RecordType>

force-app/main/default/objects/SEG_MarcasCSO__c/SEG_MarcasCSO__c.object-meta.xml
<CustomObject>
    <label>Marcas CSO</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Marcas CSO ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marcas CSO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_MarcasCSO__c/fields/SEG_Marca__c.field-meta.xml
<CustomField>
    <fullName>SEG_Marca__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marca</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Caracteristica__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SEG_Caracteristicacaso</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Caracteristica__c</referenceTo>
    <relationshipLabel>Marcas CSO</relationshipLabel>
    <relationshipName>Marcas_CSO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_MarcasCSO__c/fields/SEG_MarcasCSO__c.field-meta.xml
<CustomField>
    <fullName>SEG_MarcasCSO__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <label>Marcas CSO</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SEG_MarcasCSO__c/fields/SEG_ServiciosCSO__c.field-meta.xml
<CustomField>
    <fullName>SEG_ServiciosCSO__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicios CSO</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SEG_ServiciosCSO__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Marca</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SEG_ServiciosCSO__c</referenceTo>
    <relationshipLabel>Marcas de un caso</relationshipLabel>
    <relationshipName>Marcas_CSO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_Marcasdeuncaso__c/SEG_Marcasdeuncaso__c.object-meta.xml
<CustomObject>
    <label>Marcas de un caso</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Marcas de un caso ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marcas de un caso</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_Marcasdeuncaso__c/fields/SEG_Caracteristica__c.field-meta.xml
<CustomField>
    <fullName>SEG_Caracteristica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Característica</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Caracteristica__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SEG_Caracteristicacaso</value>
        </filterItems>
        <filterItems>
            <field>CC_Caracteristica__c.OS_Negocio__c</field>
            <operation>equals</operation>
            <value>SEGMENTOS</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Caracteristica__c</referenceTo>
    <relationshipLabel>Marcas de un caso</relationshipLabel>
    <relationshipName>Marcas_de_un_caso1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_Marcasdeuncaso__c/fields/SEG_Caso__c.field-meta.xml
<CustomField>
    <fullName>SEG_Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SEG_Cliente, SEG_Seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Marcas de un caso</relationshipLabel>
    <relationshipName>Marcas_de_un_caso1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_ServiciosCSO__c/SEG_ServiciosCSO__c.object-meta.xml
<CustomObject>
    <label>Servicios CSO</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios CSO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_ServiciosCSO__c/recordTypes/Marca.recordType-meta.xml
<RecordType>
    <fullName>Marca</fullName>
    <active>true</active>
    <label>Marca</label>
</RecordType>

force-app/main/default/classes/SEG_Marca_Case_AI_TRHan.cls
/**
 *   @description SEG_Marca_Case_AI_TRHan
*/
public with sharing class SEG_Marca_Case_AI_TRHan extends CC_TriggerHandlerBase {
	public override void mainEntry(CC_TriggerParameters tp)
	{
		// Quedarnos solo marcas asociadas a casos de segmento
		Set<Id> caseIds = new Set<Id>();
		Set<Id> caracteIds = new Set<Id>();
		for (SEG_Marcasdeuncaso__c marcaCase : (List<SEG_Marcasdeuncaso__c>) tp.newList) {
			caseIds.add(marcaCase.SEG_Caso__c);
			caracteIds.add(marcaCase.SEG_Caracteristica__c);
		}
		Set<Id> recordTypesSeg = new Set<Id> ();
		Id recordTypeSEG = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SEG_Cliente').getRecordTypeId();
		Id recordTypeSeguimiento = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SEG_Seguimiento').getRecordTypeId();
		Id recordTypeMarcasCaso = Schema.SObjectType.CC_Caracteristica__c.getRecordTypeInfosByDeveloperName().get('SEG_Caracteristicacaso').getRecordTypeId();
		recordTypesSeg.add(recordTypeSEG);
		recordTypesSeg.add(recordTypeSEG);
		Map<Id, Case> mapCases = new Map<Id, Case> ([Select Id From Case Where RecordTypeId IN :recordTypesSeg and Id IN :caseIds]);
		Map<Id, CC_Caracteristica__c> mapCaractCase = new Map<Id, CC_Caracteristica__c> ([Select Id, RecordTypeId From CC_Caracteristica__c Where RecordTypeId = :recordTypeMarcasCaso and Id IN :caracteIds]);
		List<Id> lstMarcaCaseSeg = new List<Id> ();
		for (SEG_Marcasdeuncaso__c marcaCase : (List<SEG_Marcasdeuncaso__c>) tp.newList)
		{
			if (mapCases.containsKey(marcaCase.SEG_Caso__c) && mapCaractCase.containsKey(marcaCase.SEG_Caracteristica__c)) {
				lstMarcaCaseSeg.add(marcaCase.Id);
			}
		}
		if (lstMarcaCaseSeg.size() > 0)
		{
			process(lstMarcaCaseSeg, (List<SEG_Marcasdeuncaso__c>) tp.newList, (Map<Id, SEG_Marcasdeuncaso__c>) tp.newMap, (List<SEG_Marcasdeuncaso__c>) tp.oldList, (Map<Id, SEG_Marcasdeuncaso__c>) tp.oldMap);
		}
	}

	private void process(List<Id> lstMarcaCaseSeg, List<SEG_Marcasdeuncaso__c> listNewObj, Map<Id, SEG_Marcasdeuncaso__c> mapNewObj, List<SEG_Marcasdeuncaso__c> listOldObj, Map<Id, SEG_Marcasdeuncaso__c> mapOldObj)
	{
		crearFotoFacturacion(lstMarcaCaseSeg, mapNewObj);
	}
	private void crearFotoFacturacion(List<Id> lstMarcaCaseSeg, Map<Id, SEG_Marcasdeuncaso__c> mapNewObj) {
		Map<Id, List<SEG_Marcasdeuncaso__c>> caseMarcas = new Map<Id, List<SEG_Marcasdeuncaso__c>> ();
		List<Id> lstCaseIds = new List<Id> ();
		Set<Id> idsMarcas = new Set<Id>();

		for (Id marcaCaseId : lstMarcaCaseSeg) {
			if(mapNewObj.containsKey(marcaCaseId)){
				idsMarcas.add(mapNewObj.get(marcaCaseId).SEG_Caracteristica__c);
			}	
		}

		if(!idsMarcas.isEmpty()){
			List<SEG_MarcasCSO__c> lstMarcasCSO = [SELECT Id, SEG_Marca__c, SEG_ServiciosCSO__c FROM SEG_MarcasCSO__c WHERE SEG_Marca__c IN :idsMarcas];
			Map<Id, String> mapMarcaConCSO = new Map<Id, String>();
			for (SEG_MarcasCSO__c marcaCSO : lstMarcasCSO) {
				if(marcaCSO.SEG_Marca__c != null && marcaCSO.SEG_ServiciosCSO__c != null){
					mapMarcaConCSO.put(marcaCSO.SEG_Marca__c, marcaCSO.SEG_ServiciosCSO__c);
				}
			}
			if(!mapMarcaConCSO.isEmpty()){
				for (Id marcaCaseId : lstMarcaCaseSeg) {
					if(mapNewObj.containsKey(marcaCaseId) && mapMarcaConCSO.containsKey(mapNewObj.get(marcaCaseId).SEG_Caracteristica__c) && mapMarcaConCSO.get(mapNewObj.get(marcaCaseId).SEG_Caracteristica__c) != null){
						if(caseMarcas.containsKey(mapNewObj.get(marcaCaseId).SEG_Caso__c)){
							caseMarcas.get(mapNewObj.get(marcaCaseId).SEG_Caso__c).add(mapNewObj.get(marcaCaseId));
						}else{
							caseMarcas.put(mapNewObj.get(marcaCaseId).SEG_Caso__c, new List<SEG_Marcasdeuncaso__c>{mapNewObj.get(marcaCaseId)});
						}
						lstCaseIds.add(mapNewObj.get(marcaCaseId).SEG_Caso__c);
					}
				}
				if (lstCaseIds.size() > 0) {
					SEG_FotoFacturacionHandler ffHandler = new SEG_FotoFacturacionHandler(lstCaseIds, SEG_FotoFacturacionHandler.Operativa.Marca, caseMarcas);
					System.enqueueJob(ffHandler);
					//ffHandler.createFF();
				}
			}
		}
	}
}