force-app/main/default/objects/SEG_Gestor_Grupo__c/SEG_Gestor_Grupo__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la información para agrupar gestores de empresas y asignarles un grupo resolutor</description>
    <label>Gestor-Grupo</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestores-Grupos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_Gestor_Grupo__c/fields/SEG_GrupoOperativa__c.field-meta.xml
<CustomField>
    <fullName>SEG_GrupoOperativa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo Operativa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo Operativo Segmentos</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Gestores-Grupos</relationshipLabel>
    <relationshipName>Gestores_Grupos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SEG_Gestor_Grupo__c/fields/SEG_IDGestor__c.field-meta.xml
<CustomField>
    <fullName>SEG_IDGestor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ID Gestor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SEG_Grupo_Gestor_BU_TRHan.cls
public with sharing class SEG_Grupo_Gestor_BU_TRHan extends CC_TriggerHandlerBase{
    public override void mainEntry(CC_TriggerParameters tp) {
        process((List<SEG_Gestor_Grupo__c>)tp.newList, (Map<Id, SEG_Gestor_Grupo__c>) tp.oldMap);
    }
    
    private void process(List<SEG_Gestor_Grupo__c> listNewObj, Map<Id, SEG_Gestor_Grupo__c> mapOldObj) {
        grupoGestor(listNewObj,mapOldObj);	       
	}   

    public static void grupoGestor(List<SEG_Gestor_Grupo__c> listNewObj, Map<Id, SEG_Gestor_Grupo__c> mapOldObj) {
        for (SEG_Gestor_Grupo__c grupoGestor : listNewObj) {
            if(grupoGestor.SEG_IDGestor__c != mapOldObj.get(grupoGestor.Id).SEG_GrupoOperativa__c && !String.isBlank(grupoGestor.SEG_GrupoOperativa__c)){
                grupoGestor.SEG_IDGestor__c = grupoGestor.SEG_GrupoOperativa__c;
            }
        }
    }
}