force-app/main/default/objects/CC_Caracteristica__c/CC_Caracteristica__c.object-meta.xml
<CustomObject>
    <label>Característica</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Características</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Caracteristica__c/fields/CC_Activo__c.field-meta.xml
<CustomField>
    <fullName>CC_Activo__c</fullName>
    <formula>IF( ( NOT(ISBLANK(CC_Fecha_vigencia_fin__c)) &amp;&amp; NOW() &gt;= CC_Fecha_vigencia_inicio__c &amp;&amp; NOW() &lt; CC_Fecha_vigencia_fin__c ) || ( ISBLANK(CC_Fecha_vigencia_fin__c) &amp;&amp; NOW() &gt;= CC_Fecha_vigencia_inicio__c ), true, false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica__c/fields/OS_Negocio__c.field-meta.xml
<CustomField>
    <fullName>OS_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CSBD</fullName>
            </value>
            <value>
                <fullName>CSI_Bankia</fullName>
            </value>
            <value>
                <fullName>HDT</fullName>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>SEGMENTOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/CC_Caracteristica_Detalle__c.object-meta.xml
<CustomObject>
    <label>Característica Detalle</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Característica Detalles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/fields/CC_Caracteristica__c.field-meta.xml
<CustomField>
    <fullName>CC_Caracteristica__c</fullName>
    <label>Característica</label>
    <referenceTo>CC_Caracteristica__c</referenceTo>
    <relationshipLabel>Asignaciones</relationshipLabel>
    <relationshipName>CC_Caracteristica_Detalles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/fields/CC_Centro_CaixaBank__c.field-meta.xml
<CustomField>
    <fullName>CC_Centro_CaixaBank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centro CaixaBank</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Centros CaixaBank</relationshipLabel>
    <relationshipName>CC_Caracteristica_Detalles_Centros</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/fields/CC_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (cuenta personal)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>CC_Caracteristica_Detalles_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/fields/CC_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CC_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (cuenta personal)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cuentas clientes</relationshipLabel>
    <relationshipName>CC_Cuentas_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Caracteristica_Detalle__c/fields/CC_Empleado__c.field-meta.xml
<CustomField>
    <fullName>CC_Empleado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empleado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Empleados</relationshipLabel>
    <relationshipName>CC_Caracteristica_Detalles_Empleados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CC_Caracteristica_Detalle_AI_TRHan.cls
public with sharing class CC_Caracteristica_Detalle_AI_TRHan  extends CC_TriggerHandlerBase{
    
    public override void mainEntry(CC_TriggerParameters tp) {
		  process((List<CC_Caracteristica_Detalle__c>)tp.newList, (Map<Id, CC_Caracteristica_Detalle__c>)tp.newMap);
	}

	private void process(List<CC_Caracteristica_Detalle__c> listNewObj, Map<Id, CC_Caracteristica_Detalle__c> mapNewObj) {
        updateContactOrAccountRelated(mapNewObj);
	}

    private void updateContactOrAccountRelated(Map<Id, CC_Caracteristica_Detalle__c> mapNewObj) {
		Map<Id,Contact> mapContactsToUpdateById = new Map<Id,Contact>();
        Map<Id,Account> mapAccountsToUpdateById = new Map<Id,Account>();
        //Exraigo los detalles junto con los campos CC_Tiene_Caracteristica_Detalle__c de contact y account relacionados, pero solo si la Caracteristica está activa
        List<CC_Caracteristica_Detalle__c> lstCaracteristicaDetalle = [SELECT Id, CC_Caracteristica__c, 
                                                                        CC_Cliente__c, CC_Cliente__r.CC_Tiene_Caracteristica_Detalle__c, 
                                                                        CC_Empleado__c, CC_Empleado__r.CC_Tiene_Caracteristica_Detalle__c,
                                                                        CC_Cuenta__c, CC_Cuenta__r.CC_Tiene_Caracteristica_Detalle__c,
                                                                        CC_Centro_CaixaBank__c , CC_Centro_CaixaBank__r.CC_Tiene_Caracteristica_Detalle__c
                                                                      FROM CC_Caracteristica_Detalle__c 
                                                                      WHERE Id IN :mapNewObj.keySet() 
                                                                      AND CC_Caracteristica__r.CC_Activo__c = true AND CC_Caracteristica__r.OS_Negocio__c = 'CC'];
        for(CC_Caracteristica_Detalle__c detalle : lstCaracteristicaDetalle) {
            //Control de que las nuevas cuentas o contactos tengan el campo CC_Tiene_Caracteristica_Detalle__c a true, sino los actualizo
            if (detalle.CC_Cliente__c != null && !detalle.CC_Cliente__r.CC_Tiene_Caracteristica_Detalle__c) {
                Contact c = new Contact(Id = detalle.CC_Cliente__c);
                c.CC_Tiene_Caracteristica_Detalle__c = true;
                mapContactsToUpdateById.put(detalle.CC_Cliente__c,c);
            }
            if (detalle.CC_Empleado__c != null && !detalle.CC_Empleado__r.CC_Tiene_Caracteristica_Detalle__c) {
                Contact c = new Contact(Id = detalle.CC_Empleado__c);
                c.CC_Tiene_Caracteristica_Detalle__c = true;
                mapContactsToUpdateById.put(detalle.CC_Empleado__c,c);
            }
            if (detalle.CC_Cuenta__c != null && !detalle.CC_Cuenta__r.CC_Tiene_Caracteristica_Detalle__c) {
                Account a = new Account(Id = detalle.CC_Cuenta__c);
                a.CC_Tiene_Caracteristica_Detalle__c = true;
                mapAccountsToUpdateById.put(detalle.CC_Cuenta__c,a);
            }
            if (detalle.CC_Centro_CaixaBank__c != null && !detalle.CC_Centro_CaixaBank__r.CC_Tiene_Caracteristica_Detalle__c) {
                Account a = new Account(Id = detalle.CC_Centro_CaixaBank__c);
                a.CC_Tiene_Caracteristica_Detalle__c = true;
                mapAccountsToUpdateById.put(detalle.CC_Centro_CaixaBank__c,a);
            }
              
        }
        // Actualizo los contactos y cuentas que no tengan ya el valor a true
        if(!mapContactsToUpdateById.isEmpty()) {
            update mapContactsToUpdateById.values();
        }
        if(!mapAccountsToUpdateById.isEmpty()) {
            update mapAccountsToUpdateById.values();
        }
	}
}