force-app/main/default/objects/Account/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/Case/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de resolución</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/CC_Buzones_Por_Defecto__mdt.object-meta.xml
<CustomObject>
    <label>Buzón por defecto</label>
    <pluralLabel>Buzones por defecto</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Direccion_Correo__c.field-meta.xml
<CustomField>
    <fullName>CC_Direccion_Correo__c</fullName>
    <label>Dirección de correo</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Parametrizaciones_Consultas_Operativa__c/CC_Parametrizaciones_Consultas_Operativa__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings con las parametrizaciones de las tematicas/canales de resolución/colas</description>
    <label>CC_Parametrizaciones_Consultas_Operativa</label>
</CustomObject>

force-app/main/default/objects/CC_Parametrizaciones_Consultas_Operativa__c/fields/CC_Canal_resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_resolucion__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Canal resolucion</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Parametrizaciones_Consultas_Operativa__c/fields/CC_Cola__c.field-meta.xml
<CustomField>
    <fullName>CC_Cola__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cola</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Parametrizaciones_Consultas_Operativa__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tematica</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Parametrizaciones_Consultas_Operativa__c/fields/CC_Tematica_CAT__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica_CAT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tematica CAT</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Inactivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Inactivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Matricula__c.field-meta.xml
<CustomField>
    <fullName>CC_Matricula__c</fullName>
    <description>Campo Matricula del empleado.
Cuando un empleado esté activo este campo será de 8 caracteres con el código U01 del empleado.
Cuando un empleado no se encuentre activo este campo será de 31 caracteras con el siguiente formato:
MATRICULA + - + YYYYMMDDHHMMSS + &quot;-INVALID&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Matrícula</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/classes/CC_Formulario_Consultas_Operativas_Test.cls
@isTest
public with sharing class CC_Formulario_Consultas_Operativas_Test {
   
    @TestSetup static void customSetting(){
        CC_Parametrizaciones_Consultas_Operativa__c setting = new CC_Parametrizaciones_Consultas_Operativa__c();
		setting.Name = 'Test Setting';
		setting.CC_Canal_resolucion__c = 'Tarjetas y Comercios';
        setting.CC_Cola__c = 'CC_ConsForm_Tarjetas_Comercios';
        setting.CC_Tematica__c = 'Tarjetas';
        setting.CC_Tematica_CAT__c ='Targetes';
		insert setting;

        Account cuenta = new Account();
        cuenta.Name = 'Cuenta01';
        
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_CentroCaixaBank');
        insert cuenta; 	
                
        Contact contacto = new Contact();
        contacto.Email = 'jorge.andres.argente.guillen@ibm.com';
        contacto.CC_Inactivo__c = false;
        contacto.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Empleado');
        contacto.LastName = 'Plata';
        contacto.AccountId = cuenta.Id;
        contacto.CC_Matricula__c = 'U0152396';
        insert contacto;
        
        
        
        List<String> developerNamesPlantillas = new List<String>{'CC_ConsultasOperativasCanalFormulario_Entrada_CAS','CC_ConsultasOperativasCanalFormulario_Entrada_CAT'};
		List<EmailTemplate> plantillas = [SELECT Id, Name FROM EmailTemplate WHERE DeveloperName IN :developerNamesPlantillas];
        List<EmailTemplate> plantillasAInsertar = new List<EmailTemplate>();
        if (plantillas.isEmpty()) {
            
            EmailTemplate plantilla1CAS= new EmailTemplate();
            plantilla1CAS.Developername = 'CC_ConsultasOperativasCanalFormulario_Entrada_CAS';
            plantilla1CAS.HTMLValue= 'hola prueba 2';
            plantilla1CAS.Subject = 'plantilla1CAS';
            plantilla1CAS.FolderId = UserInfo.getUserId();
            plantilla1CAS.TemplateType = 'Text';        
            plantilla1CAS.name = 'CC_ConsultasOperativasCanalFormulario_Entrada_CAS';
            plantilla1CAS.IsActive = true;
            plantillasAInsertar.Add(plantilla1CAS);

            
            EmailTemplate plantilla1CAT= new EmailTemplate();
            plantilla1CAT.Developername = 'CC_ConsultasOperativasCanalFormulario_Entrada_CAT';
            plantilla1CAT.HTMLValue= 'hola prueba 2';
            plantilla1CAT.Subject = 'plantilla1CAT';
            plantilla1CAT.FolderId = UserInfo.getUserId();
            plantilla1CAT.TemplateType = 'Text';        
            plantilla1CAT.name = 'CC_ConsultasOperativasCanalFormulario_Entrada_CAT';
            plantilla1CAT.IsActive = true;
            plantillasAInsertar.Add(plantilla1CAT);
            
            System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            	insert plantillasAInsertar;
        	}
        }
    }
     
    @isTest
    public static void testCreacionCasoCastellano() {        
        
        //Crear un InboundEnvelope e InboundEmail de entrada
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        Messaging.InboundEmail.Header header = new Messaging.InboundEmail.Header();
        List<String> lstCcAdd = new List<String>();
        String buzonFormularioConsultasOperativas = [SELECT CC_Direccion_Correo__c FROM CC_Buzones_Por_Defecto__mdt WHERE DeveloperName = 'CC_Formulario_Consultas_operativas_ESP' LIMIT 1].CC_Direccion_Correo__c;
		List<String> lstToAdd = new List<String>();
        lstToAdd.add('email1@test.com');
        lstToAdd.add(buzonFormularioConsultasOperativas);
        
        //Setup header for the email
        List<EmailServicesAddress> emailServicesList= [SELECT LocalPart, EmailDomainName FROM EmailServicesAddress WHERE FunctionId IN (SELECT Id FROM EmailServicesFunction WHERE FunctionName = 'CC_Formulario_Consultas') LIMIT 1];
        String headerValueStr;
        EmailServicesAddress headerValue= new EmailServicesAddress();
        if (!EmailServicesList.isEmpty()) {
            headerValue=emailServicesList[0];
            headerValueStr = headervalue.LocalPart + '@' + headervalue.EmailDomainName;       
        } else {
            headerValueStr = 'Prueba@IBM';    
        }
        header.value = headerValueStr;
        header.name = 'X-SFDC-Original-RCPT';

		/*header.value = 'hello';
        header.name = 'HEADER DE PRUEBA';*/
        envelope.fromAddress = 'correo@prueba.com';
        envelope.toAddress = buzonFormularioConsultasOperativas;
        correo.subject = 'Asunto';
        correo.fromAddress = 'correo@prueba.com';
        correo.toAddresses = lstToAdd;
        correo.ccAddresses = lstCcAdd;
        correo.htmlBody = 'Lunes 27/12/2021 09:30:00<br><br>nU01: U0152396<br><br>Nombre empleado: MIGUEL BRAVO GUTIERREZ<br><br>Email empleado: jorge.andres.argente.guillen@ibm.com<br><br>Selecciona la temática: Tarjetas<br><br>Detalla tu consulta: Extracto fiscal 2022 PRUEBA<br><br>>Cognitive id: 123456789<br>';
		correo.headers = new List<Messaging.InboundEmail.Header>{header};

        // add an Binary attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('my attachment text');
        attachment.fileName = 'textfileone.txt';
        attachment.mimeTypeSubType = 'text/plain';
        correo.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
        
		// add an Text atatchment
		Messaging.InboundEmail.TextAttachment attachmenttext = new Messaging.InboundEmail.TextAttachment();
        attachmenttext.body = 'my attachment text';
        attachmenttext.fileName = 'textfiletwo3.txt';
        attachmenttext.mimeTypeSubType = 'texttwo/plain';
        correo.textAttachments = new Messaging.inboundEmail.TextAttachment[] { attachmenttext };

       
        Test.startTest();
        CC_Formulario_Consultas_Operativas emailServiceConsultasoperativas = new CC_Formulario_Consultas_Operativas();
       	emailServiceConsultasoperativas.handleInboundEmail(correo, envelope);

        Case caso = [SELECT Id FROM Case WHERE Subject = 'Asunto'];    
        Test.stopTest();
        
        System.assertEquals(2, [SELECT Count() FROM EmailMessage WHERE ParentId = :caso.Id]);
    }
    
     @isTest
    public static void testCrearCasoCatalan() {

        //Crear un InboundEnvelope e InboundEmail de entrada
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        Messaging.InboundEmail.Header header = new Messaging.InboundEmail.Header();
        List<String> lstCcAdd = new List<String>();
        String buzonFormularioConsultasOperativas = [SELECT CC_Direccion_Correo__c FROM CC_Buzones_Por_Defecto__mdt WHERE DeveloperName = 'CC_Formulario_Consultas_operativas_ESP' LIMIT 1].CC_Direccion_Correo__c;
		List<String> lstToAdd = new List<String>();
        lstToAdd.add('email1@test.com');
        lstToAdd.add(buzonFormularioConsultasOperativas);
        
        //Setup header for the email
        List<EmailServicesAddress> emailServicesList= [SELECT LocalPart, EmailDomainName FROM EmailServicesAddress WHERE FunctionId IN (SELECT Id FROM EmailServicesFunction WHERE FunctionName = 'CC_Formulario_Consultas') LIMIT 1];
        String headerValueStr;
        EmailServicesAddress headerValue= new EmailServicesAddress();
        if (!EmailServicesList.isEmpty()) {
            headerValue=emailServicesList[0];
            headerValueStr = headervalue.LocalPart + '@' + headervalue.EmailDomainName;       
        } else {
            headerValueStr = 'Prueba@IBM';    
        }
        header.value = headerValueStr;
        header.name = 'X-SFDC-Original-RCPT';

		/*header.value = 'hello';
        header.name = 'HEADER DE PRUEBA';*/
        envelope.fromAddress = 'correo@prueba.com';
        envelope.toAddress = buzonFormularioConsultasOperativas;
        correo.subject = 'Asumpte';
        correo.fromAddress = 'correo@prueba.com';
        correo.toAddresses = lstToAdd;
        correo.ccAddresses = lstCcAdd;
        correo.htmlBody = 'Lunes 27/12/2021 09:30:00<br><br>nU01: U0152396<br><br>Nom empleat: MIGUEL BRAVO GUTIERREZ<br><br>Email empleat: jorge.andres.argente.guillen@ibm.com<br><br>Selecciona la temàtica: Targetes<br><br>Detalla la teva consulta: Extracto fiscal 2022 PRUEBA<br><br>Cognitive id: 123456789<br>';
		correo.headers = new List<Messaging.InboundEmail.Header>{header};

        Test.startTest();
        CC_Formulario_Consultas_Operativas emailServiceConsultasoperativas = new CC_Formulario_Consultas_Operativas();
       	emailServiceConsultasoperativas.handleInboundEmail(correo, envelope);     
        Test.stopTest();
                
        Case caso = [SELECT Id FROM Case WHERE Subject =  'Asumpte'];

        System.assertEquals(2, [SELECT Count() FROM EmailMessage WHERE ParentId = :caso.Id]);
    }
    
    
    
}