force-app/main/default/objects/Account/recordTypes/CC_Colaborador.recordType-meta.xml
<RecordType>
    <fullName>CC_Colaborador</fullName>
    <active>true</active>
    <label>CC_Colaborador</label>
</RecordType>

force-app/main/default/objects/CBK_MCC_Knowledge__c/CBK_MCC_Knowledge__c.object-meta.xml
<CustomObject>
    <description>Objeto para poder relacionar el MCC con los artículos de la Knowledge</description>
    <label>MCC Knowledge</label>
    <nameField>
        <displayFormat>MCC-Knowledge-{000000}</displayFormat>
        <label>MCC Knowledge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MCC Knowledge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_MCC_Knowledge__c/fields/CBK_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>CBK_Knowledge__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Knowledge</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Knowledge__kav.PublishStatus</field>
            <operation>equals</operation>
            <value>Publicado</value>
        </filterItems>
        <filterItems>
            <field>Knowledge__kav.PublishStatus</field>
            <operation>equals</operation>
            <value>Published</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Knowledge__kav</referenceTo>
    <relationshipLabel>MCC Knowledge</relationshipLabel>
    <relationshipName>CBK_MCC_Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CBK_MCC_Knowledge__c/fields/CBK_MCC__c.field-meta.xml
<CustomField>
    <fullName>CBK_MCC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MCC</label>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Artículos</relationshipLabel>
    <relationshipName>CBK_MCC_Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Canal_Operativo__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Operativo__c</fullName>
    <label>Canal Operativo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>App BrokerNow</fullName>
            </value>
            <value>
                <fullName>App CaixaBankPay</fullName>
            </value>
            <value>
                <fullName>App CaixaBankSign</fullName>
            </value>
            <value>
                <fullName>App CBKNow</fullName>
            </value>
            <value>
                <fullName>App Imagin</fullName>
            </value>
            <value>
                <fullName>App imaginKids</fullName>
            </value>
            <value>
                <fullName>App imaginTeens</fullName>
            </value>
            <value>
                <fullName>Cajero</fullName>
            </value>
            <value>
                <fullName>Cajero ATM NOW</fullName>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Otras App</fullName>
            </value>
            <value>
                <fullName>Plataforma virtual</fullName>
            </value>
            <value>
                <fullName>Portal CBK</fullName>
            </value>
            <value>
                <fullName>Portal Wivai</fullName>
                <label>Portal Facilitea</label>
            </value>
            <value>
                <fullName>RRSS</fullName>
            </value>
            <value>
                <fullName>Servicios Centrales</fullName>
            </value>
            <value>
                <fullName>Sin canal</fullName>
            </value>
            <value>
                <fullName>SmartPhone</fullName>
            </value>
            <value>
                <fullName>Web CBKNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Fecha de inicio de vigencia</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio vigencia</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Causa.recordType-meta.xml
<RecordType>
    <fullName>CC_Causa</fullName>
    <active>true</active>
    <label>Causa</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/CC_Colaborador.recordType-meta.xml
<RecordType>
    <fullName>CC_Colaborador</fullName>
    <active>true</active>
    <label>Colaborador</label>
</RecordType>

force-app/main/default/objects/Knowledge__kav/fields/CBK_Codigo_Externo_Causa__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_Externo_Causa__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código externo Causa</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CBK_Codigo_Externo_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_Externo_Motivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código externo Motivo</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CBK_Codigo_Externo_Producto__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_Externo_Producto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código externo Producto</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CBK_Codigo_Externo_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_Externo_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código externo Temática</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CC_Fecha_Caducidad__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Caducidad__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha de caducidad</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CC_Fecha_Inicio_Publicacion__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Inicio_Publicacion__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha de inicio de publicación</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CC_Responsable_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Responsable_Externo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Responsable</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Colaborador</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Knowledge</relationshipLabel>
    <relationshipName>Knowledge</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CC_MCC_Knowledge_AI_TRHan_Test.cls
@isTest
public class CC_MCC_Knowledge_AI_TRHan_Test {

    @isTest
    public static void testAI(){
        Account cuenta = new Account();
        cuenta.Name = 'PRUEBA TEST Cristina';
        cuenta.RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Colaborador').getRecordTypeId();
        insert cuenta;

        Id profileId = [SELECT Id FROM Profile WHERE Name = 'CC_Usuario_CaixaBank'].Id;
        User usuario = new User(
            Alias = 'TEST',
            Email = 'testpruebamcc@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'testLastName',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es',
            TimeZoneSidKey = 'Europe/Berlin',
            UserName = 'Testpruebamcc@test.com',
            ProfileId = profileId
        );
        insert usuario;
        
        Contact contacto = new Contact();
        contacto.FirstName = 'Cris';
        contacto.LastName = 'Prueba';
        contacto.Email = 'mp@test.com';
        contacto.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Colaborador').getRecordTypeId();
        contacto.AccountId = cuenta.Id;
		insert contacto;
        
        Datetime fecha = Datetime.now();
        Datetime fechaInicio = fecha.addHours(2);
        Datetime fechaCaducidad = fecha.addHours(10);

        Knowledge__kav articulo = new Knowledge__kav(); 
        articulo.URLName = 'Apex-Test' + System.now().getTime();
        articulo.Title = 'Articulo test cris';
        articulo.CC_Fecha_Inicio_Publicacion__c = fechaInicio;
        articulo.CC_Fecha_Caducidad__c = fechaCaducidad;
        articulo.CC_Responsable_Externo__c = contacto.Id;
        articulo.ValidationStatus = 'Validado';
        insert articulo; 
        articulo = [SELECT Id, CBK_Codigo_Externo_Causa__c, CBK_Codigo_Externo_Motivo__c, CBK_Codigo_Externo_Producto__c, CBK_Codigo_Externo_Tematica__c 
                    FROM Knowledge__kav WHERE Title = 'Articulo test cris'];
        Id idArticulo = articulo.Id;
        Map<Id, KnowledgeArticleVersion> obtenidoIdQuery = new Map<Id, KnowledgeArticleVersion>([SELECT Id, KnowledgeArticleId 
                                            FROM KnowledgeArticleVersion WHERE Id =: idArticulo]);

        CC_MCC__c mccTematica = new CC_MCC__c();
        Id recordTypeIdTematica = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
        mccTematica.RecordTypeId = recordTypeIdTematica;
        mccTematica.Name = 'Tematica Test AI';
        mccTematica.CC_Tipo_Cliente__c = 'Cliente';
        mccTematica.CC_Codigo_Externo__c = 'TE-000789';
        mccTematica.CC_Fecha_Vigencia_Inicio__c = fecha;
        mccTematica.CC_Canal_Operativo__c = 'Sin canal';
        insert mccTematica;
        
        CC_MCC__c mccProducto = new CC_MCC__c();
        Id recordTypeIdProducto = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
        mccProducto.RecordTypeId = recordTypeIdProducto;
        mccProducto.Name = 'Producto Test AI';
        mccProducto.CC_Tipo_Cliente__c = 'Cliente';
        mccProducto.CC_Codigo_Externo__c = 'PR-000789';
        mccProducto.CC_Fecha_Vigencia_Inicio__c = fecha;
        insert mccProducto;

        CC_MCC__c mccMotivo = new CC_MCC__c();
        Id recordTypeIdMotivo = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
        mccMotivo.RecordTypeId = recordTypeIdMotivo;
        mccMotivo.Name = 'Motivo Test AI';
        mccMotivo.CC_Tipo_Cliente__c = 'Cliente';
        mccMotivo.CC_Codigo_Externo__c = 'MO-000789';
        mccMotivo.CC_Fecha_Vigencia_Inicio__c = fecha;
        insert mccMotivo;

        CC_MCC__c mccCausa = new CC_MCC__c();
        Id recordTypeIdCausa = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Causa').getRecordTypeId();
        mccCausa.RecordTypeId = recordTypeIdCausa;
        mccCausa.Name = 'Causa Test AI';
        mccCausa.CC_Tipo_Cliente__c = 'Cliente';
        mccCausa.CC_Codigo_Externo__c = 'CA-000789';
        mccCausa.CC_Fecha_Vigencia_Inicio__c = fecha;
        insert mccCausa;

        Test.startTest();
        List<CBK_MCC_Knowledge__c> relaciones = new List<CBK_MCC_Knowledge__c>();
        CBK_MCC_Knowledge__c relacionTematica = new CBK_MCC_Knowledge__c();
        CBK_MCC_Knowledge__c relacionProducto = new CBK_MCC_Knowledge__c();
        CBK_MCC_Knowledge__c relacionMotivo = new CBK_MCC_Knowledge__c();
        CBK_MCC_Knowledge__c relacionCausa = new CBK_MCC_Knowledge__c();
        insert relacionTematica;
        insert relacionProducto;
        insert relacionMotivo;
        insert relacionCausa;
        CC_MCC_Knowledge_AI_TRHan.publishArticle((String)obtenidoIdQuery.get(idArticulo).KnowledgeArticleId);
        relacionTematica.OwnerId = usuario.Id;
        relacionTematica.CBK_MCC__c = mccTematica.Id;
        relacionTematica.CBK_Knowledge__c = articulo.Id;      
        relaciones.add(relacionTematica);
        CC_MCC_Knowledge_AI_TRHan.process(relaciones);

        relaciones.clear();
        relacionProducto.OwnerId = usuario.Id;
        relacionProducto.CBK_MCC__c = mccProducto.Id;
        relacionProducto.CBK_Knowledge__c = articulo.Id;
        relaciones.add(relacionProducto);
        CC_MCC_Knowledge_AI_TRHan.process(relaciones);

        relaciones.clear();
        relacionMotivo.OwnerId = usuario.Id;
        relacionMotivo.CBK_MCC__c = mccMotivo.Id;
        relacionMotivo.CBK_Knowledge__c = articulo.Id;
        relaciones.add(relacionMotivo);
        CC_MCC_Knowledge_AI_TRHan.process(relaciones);


        relacionMotivo.OwnerId = usuario.Id;
        relacionMotivo.CBK_MCC__c = mccMotivo.Id;
        relacionMotivo.CBK_Knowledge__c = articulo.Id;
        relaciones.add(relacionMotivo);
        CC_MCC_Knowledge_AI_TRHan.process(relaciones);

        relaciones.clear();
        relacionCausa.OwnerId = usuario.Id;
        relacionCausa.CBK_MCC__c = mccCausa.Id;
        relacionCausa.CBK_Knowledge__c = articulo.Id;
        relaciones.add(relacionCausa);
        CC_MCC_Knowledge_AI_TRHan.process(relaciones);
        Test.stopTest();


        articulo = [SELECT Id, CBK_Codigo_Externo_Causa__c, CBK_Codigo_Externo_Motivo__c, CBK_Codigo_Externo_Producto__c, CBK_Codigo_Externo_Tematica__c, PublishStatus 
        FROM Knowledge__kav WHERE Title = 'Articulo test cris'];

        //Comprobaciones para saber si se ha creado bien
        System.assertEquals('TE-000789 -', articulo.CBK_Codigo_Externo_Tematica__c, 'El código externo de temática no se ha guardado correctamente');
        System.assertEquals('Online', articulo.PublishStatus, 'El artículo no se publica');
        
    }
}