force-app/main/default/objects/Account/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/Case/fields/CC_Admin__c.field-meta.xml
<CustomField>
    <fullName>CC_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que hace bypass a las validation rules que lo tengan en cuenta.</description>
    <label>CC_Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Buzon_Salida__c.field-meta.xml
<CustomField>
    <fullName>CC_Buzon_Salida__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Buzón de salida (interno)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Contacto__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Contacto__c</fullName>
    <description>Campo para indicar que tipo de contacto tiene el caso.</description>
    <label>Tipo de contacto</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_TipoContacto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_URL_Encuesta_3N__c.field-meta.xml
<CustomField>
    <fullName>CC_URL_Encuesta_3N__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>URL Encuesta 3N</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/OS_Empleado.recordType-meta.xml
<RecordType>
    <fullName>OS_Empleado</fullName>
    <active>true</active>
    <businessProcess>OS_Support_Process</businessProcess>
    <label>Empleado (COPS)</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Fecha de inicio de vigencia</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio vigencia</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/OS_No_Enviar_Encuestas__c.field-meta.xml
<CustomField>
    <fullName>OS_No_Enviar_Encuestas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No enviar encuesta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/classes/OS_Encuesta_Test.cls
@isTest(SeeAllData=true)
//Se usa el seeAllData porque el objeto Survey no se puede crear/editar en un test
public class OS_Encuesta_Test {

    public static Id mccProductoServicioRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
    public static Id mccMotivoRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
    public static Id ccMCCTematica = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
    public static Id recordTypeIdAccountCentroCaixaBank = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_CentroCaixaBank').getRecordTypeId(); 
    public static Id recordTypeIdContactCCEmpleado = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
    public static Id recordTypeIdCaseOSEmpleado = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('OS_Empleado').getRecordTypeId();

    @isTest
    static void enviarEncuesta() {      
        Account cuenta = new Account();
        cuenta.Name = 'Cuenta Test Cliente';
        cuenta.RecordTypeId = recordTypeIdAccountCentroCaixaBank;
        insert cuenta;

        Contact contacto = new Contact();
        contacto.LastName = 'Test contacto';
        contacto.Email = 'test@test.es';
        contacto.RecordTypeId = recordTypeIdContactCCEmpleado;
        contacto.AccountId = cuenta.Id;
        insert contacto;

        CC_MCC__c mccTematica = new CC_MCC__c();
		mccTematica.Name = 'MCC Tematica';
        mccTematica.CC_Tipo_Cliente__c = 'Empleado';
        mccTematica.CC_Fecha_Vigencia_Inicio__c = Date.today();
        mccTematica.RecordTypeId = ccMCCTematica;
        mccTematica.CC_Codigo_Externo__c = 'TE-000001' + String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccTematica.OS_No_Enviar_Encuestas__c = false;
		insert mccTematica;

        Id recordTypeIdProducto = mccProductoServicioRecordTypeId;
        CC_MCC__c mccProducto = new CC_MCC__c();
        mccProducto.Name = 'MCC Producto';
        mccProducto.CC_Tipo_Cliente__c = 'Empleado';
        mccProducto.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccProducto.RecordTypeId = recordTypeIdProducto;
        mccProducto.CC_Tematica__c = mccTematica.Id;
        mccProducto.CC_Codigo_Externo__c = 'PR-000001'+ String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccProducto.OS_No_Enviar_Encuestas__c = false;
        insert mccProducto; 
        
        Id recordTypeIdMotivo = mccMotivoRecordTypeId;
       	CC_MCC__c mccMotivo = new CC_MCC__c();
        mccMotivo.Name = 'MCCMotivo';
        mccMotivo.CC_Tipo_Cliente__c = 'Empleado';
        mccMotivo.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccMotivo.RecordTypeId = recordTypeIdMotivo;
        mccMotivo.CC_Tematica__c = mccTematica.Id;
        mccMotivo.CC_Producto_Servicio__c = mccProducto.Id;
        mccMotivo.CC_Codigo_Externo__c = 'MO-000001' + + String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccMotivo.OS_No_Enviar_Encuestas__c = false;
        insert mccMotivo;
        
        Case caso = new Case();
        caso.Subject = 'Caso de prueba';
        caso.CC_Idioma__c = 'es';
        caso.recordtypeId = recordTypeIdCaseOSEmpleado;
        caso.Origin = 'Email';
        caso.CC_Canal_Procedencia__c = 'Buzón KYC Renewal';
        //caso.CC_Tipo_Contacto__c = 'Formación';
        caso.Status = 'Activo';
        caso.ContactId = contacto.Id;
        caso.AccountId = cuenta.Id;
        caso.CC_MCC_Tematica__c = mccTematica.Id;
        caso.CC_MCC_ProdServ__c = mccProducto.Id;
        caso.CC_MCC_Motivo__c = mccMotivo.Id ;
        caso.CC_Buzon_Salida__c = 'buzon.servicedesk.devcops5@gmail.com';
        insert caso;

        EmailTemplate plantilla = new EmailTemplate();
        plantilla.FolderId = UserInfo.getUserId();
        plantilla.Name = 'OS Encuesta Offline';
        plantilla.DeveloperName = 'OS_Encuesta_Offline';
        plantilla.TemplateType = 'Text';
        plantilla.isactive = true;
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert plantilla;
        }

        Test.startTest();
        List<Id> lista = new List<Id>();
        lista.add(caso.Id);
        OS_Encuesta.enviarEncuesta(lista);
        Test.stopTest();

        String nombre = 'Encuesta para el caso ' + [SELECT CaseNumber FROM Case WHERE Id = :caso.Id].CaseNumber;
        Case elCasoCreado = [SELECT Id, CC_Admin__c FROM Case WHERE Id = :caso.Id];
        System.assertEquals(true, elCasoCreado.CC_Admin__c);
        System.assertEquals(nombre, [SELECT Name FROM SurveyInvitation WHERE Name = :nombre].Name);
    }

    @isTest
    static void enviarEncuesta2() { 
        Account cuenta = new Account();
        cuenta.Name = 'Cuenta Test Cliente2';
        cuenta.RecordTypeId = recordTypeIdAccountCentroCaixaBank;
        insert cuenta;

        Contact contacto = new Contact();
        contacto.LastName = 'Test contacto2';
        contacto.Email = 'testoliver@test.es';
        contacto.RecordTypeId = recordTypeIdContactCCEmpleado;
        contacto.AccountId = cuenta.Id;
        insert contacto;

        CC_MCC__c mccTematica = new CC_MCC__c();
		mccTematica.Name = 'MCC Tematica';
        mccTematica.CC_Tipo_Cliente__c = 'Empleado';
        mccTematica.CC_Fecha_Vigencia_Inicio__c = Date.today();
        mccTematica.RecordTypeId = ccMCCTematica;
        mccTematica.CC_Codigo_Externo__c = 'TE-000001' + String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccTematica.OS_No_Enviar_Encuestas__c = false;
		insert mccTematica;

        Id recordTypeIdProducto = mccProductoServicioRecordTypeId;
        CC_MCC__c mccProducto = new CC_MCC__c();
        mccProducto.Name = 'MCC Producto';
        mccProducto.CC_Tipo_Cliente__c = 'Empleado';
        mccProducto.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccProducto.RecordTypeId = recordTypeIdProducto;
        mccProducto.CC_Tematica__c = mccTematica.Id;
        mccProducto.CC_Codigo_Externo__c = 'PR-000001'+ String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccProducto.OS_No_Enviar_Encuestas__c = false;
        insert mccProducto; 
        
       	CC_MCC__c mccMotivo = new CC_MCC__c();
        mccMotivo.Name = 'MCCMotivo';
        mccMotivo.CC_Tipo_Cliente__c = 'Empleado';
        mccMotivo.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccMotivo.RecordTypeId = mccMotivoRecordTypeId;
        mccMotivo.CC_Tematica__c = mccTematica.Id;
        mccMotivo.CC_Producto_Servicio__c = mccProducto.Id;
        mccMotivo.CC_Codigo_Externo__c = 'MO-000001' + + String.valueOf(System.now()).left(3); //añadimos variable de tiempo porque con el see all data el ExternalId puede estar repetido
        mccMotivo.OS_No_Enviar_Encuestas__c = false;
        insert mccMotivo;

        Case caso2 = new Case();
        caso2.Subject = 'Caso de prueba2';
        caso2.CC_Idioma__c = 'es';
        caso2.recordtypeId = recordTypeIdCaseOSEmpleado;
        caso2.Origin = 'Email';
        caso2.CC_Canal_Procedencia__c = 'Buzón Comercio Exterior';
        //caso.CC_Tipo_Contacto__c = 'Formación';
        caso2.Status = 'Activo';
        caso2.ContactId = contacto.Id;
        caso2.AccountId = cuenta.Id;
        caso2.CC_Tematica__c = 'UAC ExportOnline';
        caso2.CC_MCC_Tematica__c = mccTematica.Id;
        caso2.CC_MCC_ProdServ__c = mccProducto.Id;
        caso2.CC_MCC_Motivo__c = mccMotivo.Id;
        caso2.EntitlementID = null;
        //caso2.CC_Buzon_Salida__c = 'buzon.servicedesk.devcops2@gmail.com';
        insert caso2;

        EmailTemplate plantilla = new EmailTemplate();
        plantilla.FolderId = UserInfo.getUserId();
        plantilla.Name = 'OS Encuesta Offline';
        plantilla.DeveloperName = 'OS_Encuesta_Offline';
        plantilla.TemplateType = 'Text';
        plantilla.isactive = true;
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            insert plantilla;
        }

        Test.startTest();

        List<Id> idCasos = new List<Id>();
        idCasos.add(caso2.Id);
        OS_Encuesta.enviarEncuesta(idCasos);
        Test.stopTest();

        String nombre2 = 'Encuesta para el caso ' + [SELECT CaseNumber FROM Case WHERE Id = :caso2.Id].CaseNumber;
        Case elCasoCreado2 = [SELECT Id, CC_Admin__c, CC_URL_Encuesta_3N__c FROM Case WHERE Id = :caso2.Id];
        
        SurveyInvitation invitacionCreada = [SELECT Name, InvitationLink FROM SurveyInvitation WHERE Name = :nombre2 LIMIT 1];
        System.assertEquals(nombre2, invitacionCreada.Name);
        System.assertEquals(invitacionCreada.InvitationLink, elCasoCreado2.CC_URL_Encuesta_3N__c);
        //System.assertEquals(true, elCasoCreado2.CC_Admin__c);
    }
}