force-app/main/default/objects/CC_Agrupador__c/CC_Agrupador__c.object-meta.xml
<CustomObject>
    <label>Agrupador</label>
    <nameField>
        <displayFormat>GRP-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Estado__c.field-meta.xml
<CustomField>
    <fullName>CC_Estado__c</fullName>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activo</fullName>
                <default>true</default>
                <label>Activo</label>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Pendiente Revision</fullName>
                <label>Pendiente revisión solución</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>CC_Titulo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa</fullName>
    <active>true</active>
    <label>Comunicación Informativa</label>
</RecordType>

force-app/main/default/classes/CC_Com_Informativa_Scheduled_Test.cls
@isTest
public class CC_Com_Informativa_Scheduled_Test {
	@isTest
    public static void planificar() {
        
        //Alta de datos para la prueba
        CC_Agrupador__c comunicacionInformativa = new CC_Agrupador__c();
        comunicacionInformativa.RecordTypeId = Schema.SObjectType.CC_Agrupador__c.getRecordTypeInfosByDeveloperName().get('CC_Comunicacion_Informativa').getRecordTypeId();
        comunicacionInformativa.CC_Estado__c = 'Activo';
        comunicacionInformativa.CC_Titulo__c = 'Título';
        insert comunicacionInformativa;
        
        //Ejecución de la prueba
        Test.startTest();
        CC_Comunicacion_Informativa_Scheduled.planificar();
        Test.stopTest();
        
        //Evaluación del resultado de la prueba
        //TODO
    }
    
}