force-app/main/default/objects/AV_Simulador__c/AV_Simulador__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para parametrizar los simuladores</description>
    <label>Simulador</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_Simulador__c/fields/AV_Color__c.field-meta.xml
<CustomField>
    <fullName>AV_Color__c</fullName>
    <description>Campo para almacenar el color del botón en formato hexadecimal</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Color</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AV_Simulador__c/fields/AV_PEA__c.field-meta.xml
<CustomField>
    <fullName>AV_PEA__c</fullName>
    <description>Utilizado para almacenar las PEAS</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PEA</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AV_Simulador__c/fields/AV_Producto__c.field-meta.xml
<CustomField>
    <fullName>AV_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto relacionado con el simulador</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Simuladores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_Simulador__c/fields/AV_URL_PEA__c.field-meta.xml
<CustomField>
    <fullName>AV_URL_PEA__c</fullName>
    <label>URL/PEA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>URL</fullName>
            </value>
            <value>
                <fullName>PEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_PEA__c.field-meta.xml
<CustomField>
    <fullName>AV_PEA__c</fullName>
    <description>PEA</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PEA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_PF__c.field-meta.xml
<CustomField>
    <fullName>AV_PF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF asociado a la oportunidad</description>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.AV_Nivel__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Product2.AV_ExternalID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (PF)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_Producto__c.field-meta.xml
<CustomField>
    <fullName>AV_Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto de la oportunidad</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_PEA__c.field-meta.xml
<CustomField>
    <fullName>AV_PEA__c</fullName>
    <description>Clave/identificador del punto de acceso</description>
    <encryptionScheme>None</encryptionScheme>
    <label>PEA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AV_peaLink_Controller_Test.cls
@isTest
private class AV_peaLink_Controller_Test {

    @TestSetup
	static void setup() {
        User userGestor = AV_TestHelper.createUser('AV_Usuario_CaixaBank');
        AV_TestHelper.insertPermissionSet(userGestor.Id, 'AV_Simuladores');
        AV_TestHelper.insertPermissionSet(userGestor.Id, 'AV_CustomMetadata');

        User usuario =[Select Id from User where Profile.Name = 'API Only' and Alias = 'AV-TF9' and IsActive = true limit 1];
        
        System.runAs(usuario) {
            Account customerTest = AV_TestHelper.createCustomer();
            Opportunity opp= AV_TestHelper.createOpportunity(customerTest);
            Product2 product = [SELECT Id FROM Product2 WHERE Id =: opp.AV_PF__c];
            AV_Simulador__c simulador = new AV_Simulador__c();
                simulador.name = 'pruebaSimulador';
                simulador.AV_Color__c = '#557FB8';
                simulador.AV_URL_PEA__c = 'PEA';
                simulador.AV_PEA__c = 'https://google.es';
                simulador.AV_Producto__c = product.Id;

                insert simulador;
        }
	}

    @isTest
    static void getURLsTest() {
        User us1=[SELECT id FROM User WHERE Alias = 'tsAlias'];
        List<AV_peaLink_Controller.LabelURL> listURLs = new List<AV_peaLink_Controller.LabelURL>();
                
        Test.startTest();
        System.runAs(us1){
            listURLs = AV_peaLink_Controller.getURLs('AV_0004');
        Test.stopTest();
        }

        System.assertNotEquals(null, listURLs, 'url is null');
    }

    @isTest
    static void getCurrentPEATest() {
        User us1=[SELECT id FROM User WHERE Alias = 'tsAlias'];
        AV_Simulador__c simulador = [SELECT Id FROM AV_Simulador__c WHERE Name = 'pruebaSimulador'];
        String idSimulador = simulador.Id;
        String currentPEA = '';
                Test.startTest();
                System.runAs(us1){
                    currentPEA = AV_peaLink_Controller.getCurrentPEA(idSimulador);
                
                Test.stopTest();
                }
                System.assertNotEquals(null, currentPEA, 'currentPEA is null');
            }

    @isTest
    static void updateSimuladorTest() {
        User us1=[SELECT id FROM User WHERE Alias = 'tsAlias'];
        AV_Simulador__c simulador = [SELECT Id FROM AV_Simulador__c WHERE Name = 'pruebaSimulador'];
        String urlNew = 'testURLUpdate';  
        Test.startTest();
        System.runAs(us1){
            AV_peaLink_Controller.updateSimulador(simulador.Id, urlNew);
        
        Test.stopTest();
        }
        System.assertNotEquals(null, urlNew, 'urlNew is null');

    }
}