force-app/main/default/objects/Account/fields/AV_AhorroEInversion__c.field-meta.xml
<CustomField>
    <fullName>AV_AhorroEInversion__c</fullName>
    <description>Importe de ahorro e inversión del cliente</description>
    <label>Ahorro e Inversión</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_EAPGestor__c.field-meta.xml
<CustomField>
    <fullName>AV_EAPGestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EAP Gestor</description>
    <label>EAP/Gestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (AV_EAPGestor)</relationshipLabel>
    <relationshipName>AccountsGestor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_Financiacion__c.field-meta.xml
<CustomField>
    <fullName>AV_Financiacion__c</fullName>
    <description>Importe de financiación del cliente</description>
    <label>Financiación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_Ingresos__c.field-meta.xml
<CustomField>
    <fullName>AV_Ingresos__c</fullName>
    <formula>MAX( AV_IngresosPension__c , AV_IngresosPersonales__c , AV_IngresosProfesionales__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ingresos</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_OficinaPrincipal__c.field-meta.xml
<CustomField>
    <fullName>AV_OficinaPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oficina principal del cliente</description>
    <label>Oficina Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (AV_OficinaPrincipal)</relationshipLabel>
    <relationshipName>AccountsOficina</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_Rentabilidad__c.field-meta.xml
<CustomField>
    <fullName>AV_Rentabilidad__c</fullName>
    <description>Importe de rentabilidad del cliente</description>
    <label>Rentabilidad</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/AV_Birthdate__c.field-meta.xml
<CustomField>
    <fullName>AV_Birthdate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha nacimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/AV_CustomerId__c.field-meta.xml
<CustomField>
    <fullName>AV_CustomerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número identificación</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AV_CheckExistsCustomers_Controller.cls
public  without sharing class AV_CheckExistsCustomers_Controller {

    @AuraEnabled
	public static CustomerList getCustomers(String leadId){
		//CustomerList cl = new CustomerList();
		Lead l  = [SELECT Id, AV_CustomerId__c, FirstName, LastName, AV_Birthdate__c FROM Lead WHERE Id = :leadId];
		if (l.AV_Birthdate__c != null &&  l.AV_CustomerId__c != null) {
		String birthdate = String.valueOfGmt(l.AV_Birthdate__c);
		birthdate = birthdate.substring(0,10);
        //Aqui sacar los Accounts
		String avQuery = 'SELECT Id, Name, AV_Financiacion__c, AV_Ingresos__c, AV_AhorroEInversion__c, AV_Rentabilidad__c, PersonMobilePhone, AV_OficinaPrincipal__r.Name, AV_OficinaPrincipal__c, AV_EAPGestor__r.Name, AV_EAPGestor__c  FROM Account WHERE CC_Numero_Documento__c = ' + '\''+l.AV_CustomerId__c+'\' AND PersonBirthdate = '+birthdate; 
			return new CustomerList((List<Account>) Database.query(avQuery));
		}
		return null;
	}

	public class CustomerList {
		@AuraEnabled
		public List<SObject> recordList;

		public CustomerList(List<SObject> recordList) {
			this.recordList = recordList;
		}

		public void add(CustomerList ol) {
			this.recordList.addAll(ol.recordList);
		}
	}
}