force-app/main/default/objects/Account/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AV_ExperienceBusiness__c/AV_ExperienceBusiness__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la información de las Experiencias de la estructura comercial relacionadas con el negocio</description>
    <label>Experiencia-Negocio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Experiencia-Negocio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiencia-Negocio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ExperienceBusiness__c/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/AV_ProductClient__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la información relaciona de los productos contratados por el cliente.
Almacena la tenencia y potencialidad de los PF del cliente.</description>
    <label>ProductoFicha-Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto-Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductoFicha-Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cliente relacionado</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProductoFicha-Cliente</relationshipLabel>
    <relationshipName>ProductoFicha_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_ImportePreconcedido__c.field-meta.xml
<CustomField>
    <fullName>AV_ImportePreconcedido__c</fullName>
    <description>Importe del preconcedido para el producto ficha del cliente</description>
    <label>Importe Preconcedido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Potencialidad__c.field-meta.xml
<CustomField>
    <fullName>AV_Potencialidad__c</fullName>
    <description>Valor de potencialidad del PF</description>
    <label>Potencialidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
                <label>Potencial</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Sin potencial</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>No informado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_ProductoFicha__c.field-meta.xml
<CustomField>
    <fullName>AV_ProductoFicha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF relacionado</description>
    <label>Producto Ficha</label>
    <referenceTo>AV_ProductExperience__c</referenceTo>
    <relationshipLabel>ProductoFicha-Cliente</relationshipLabel>
    <relationshipName>ProductoFicha_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Target__c.field-meta.xml
<CustomField>
    <fullName>AV_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de mejora de prima</description>
    <label>Mejora de prima</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_TenenciaProducto__c.field-meta.xml
<CustomField>
    <fullName>AV_TenenciaProducto__c</fullName>
    <description>Valor de tenencia del PF</description>
    <label>Situación Actual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>No tiene Producto</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Tiene Producto</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tuvo Producto</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>No interesado/a en el producto</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>No tiene + Info de otras entidades</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Tiene + Info de otras entidades</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Tuvo + Info en otras entidades</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>No apto + Info de otras entidades</label>
            </value>
            <value>
                <fullName>AV_IcoTieneParcial</fullName>
                <isActive>false</isActive>
                <label>Tiene y puede tener más producto/s</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_TieneOportunidad__c.field-meta.xml
<CustomField>
    <fullName>AV_TieneOportunidad__c</fullName>
    <description>Lista de valores que indica si tiene oportunidad, si se puede ofrecer o si ha sido rechazado por el cliente.</description>
    <label>Tiene Oportunidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OFERT</fullName>
                <label>Producto a ofertar</label>
            </value>
            <value>
                <fullName>OPORT</fullName>
                <label>Oportunidad</label>
            </value>
            <value>
                <fullName>RECHZ</fullName>
                <label>Producto rechazado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/AV_ProductExperience__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la relación entre PF y Experiencia</description>
    <label>ProductoFicha-Experiencia</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductoFicha-Experiencia</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de si está activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_ExperienciaNegocio__c.field-meta.xml
<CustomField>
    <fullName>AV_ExperienciaNegocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Experiencia (Negocio) relacionado con el PF</description>
    <label>Experiencia Negocio</label>
    <referenceTo>AV_ExperienceBusiness__c</referenceTo>
    <relationshipLabel>ProductoFicha-Experiencia</relationshipLabel>
    <relationshipName>ProductoFicha_Experiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_ProductoFicha__c.field-meta.xml
<CustomField>
    <fullName>AV_ProductoFicha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF relacionado</description>
    <label>Producto Ficha</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ProductoFicha-Experiencia</relationshipLabel>
    <relationshipName>ProductoFicha_Experiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador de CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_Profesional__c.field-meta.xml
<CustomField>
    <fullName>AV_Profesional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de si es profesional</description>
    <label>Profesional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AV_FichaProductosCController_Test.cls
/**********************************************************************************************************************
 Name:	  AV_FichaProductosCController_Test
 Copyright © 2019  CaixaBank
=======================================================================================================================
Proposito: Clase Test para AV_FichaProductosComponentController
=======================================================================================================================
Historial
---------------------
	VERSION		USER_STORY			AUTHOR				DATE				Description
	1.0			Test				Carolina Alonso	   	09/03/2020		  	Init version
	1.1			Test				Carolina Alonso	   	12/05/2020		  	Update coverage
	1.2			Test				Carolina Alonso	   	20/05/2020		  	Update coverage; getOpportunityNumber and 
																			getClientName methods.
	1.3			Test				Esperanza Conde		29/07/2020			Modified test method about target and Preconcedido
	1.4			Test				Esperanza Conde		30/09/2020			Update coverage
	1.5			Fix					Sandra Gómez		26/08/2021			Fix product opportunity
	1.6			US276250			Víctor Santiago		15/10/2021			Added second call to getInitData because of
																			asynchronous update (future)
***********************************************************************************************************************/
@isTest
public with sharing class AV_FichaProductosCController_Test {
   
	@isTest
	public static void testAccountWithoutExperienceBusiness() {
		AV_TestHelper.activateLogger();
		Account acc = AV_TestHelper.createCustomer();

		Test.startTest();

		List<AV_FichaProductosComponentController.Response> responseList = new List<AV_FichaProductosComponentController.Response>();
		AV_FichaProductosComponentController.getInitData(acc.Id);
		Test.stopTest();

		//Second call to getInitData is mandatory for retrieving the data that a future method updated to the database in the first call.
		responseList = AV_FichaProductosComponentController.getInitData(acc.Id);
		System.assertEquals(null, responseList);
	}
	
	@isTest
	public static void testAccountWithoutPFExperience() {
		AV_TestHelper.activateLogger();
		Account acc = AV_TestHelper.createCustomer();
		AV_ExperienceBusiness__c exp = AV_TestHelper.createExperienciaNegocio();

		Test.startTest();

		List<AV_FichaProductosComponentController.Response> responseList = new List<AV_FichaProductosComponentController.Response>();
		AV_FichaProductosComponentController.getInitData(acc.Id);
		Test.stopTest();

		//Second call to getInitData is mandatory for retrieving the data that a future method updated to the database in the first call.
		responseList = AV_FichaProductosComponentController.getInitData(acc.Id);
		System.assertEquals(null, responseList);
	}

	@isTest
	public static void testAccountWithTenenciaPotencialidadAndOpp() {
		AV_TestHelper.activateLogger();
		Account acc = AV_TestHelper.createCustomer();
		
		AV_ExperienceBusiness__c exp = AV_TestHelper.createExperienciaNegocio();

		Product2 prodPF = AV_TestHelper.createProduct(null,null);
		Product2 producto = AV_TestHelper.createProduct(prodPF,'20');
		producto.AV_Profesional__c = false;
		producto.AV_Activo__c = true;
		update producto;

		AV_ProductExperience__c prodExp = AV_TestHelper.createPFExperience();
		prodExp.AV_Activo__c = true;
		prodExp.AV_ProductoFicha__c = producto.Id; 
		prodExp.AV_ExperienciaNegocio__c = exp.Id;
        prodExp.AV_ExternalId__c = 'BPA001_50077';
		update prodExp;
		
		AV_ProductClient__c prodCliente = AV_TestHelper.createPFCliente();
        prodCliente.AV_ProductoFicha__c = prodExp.Id;
        prodCliente.AV_Cliente__c = acc.Id;
        prodCliente.AV_TieneOportunidad__c = 'OPORT';
        prodCliente.AV_TenenciaProducto__c = '1';
        prodCliente.AV_Potencialidad__c = 'S';
		update prodCliente;
        
        String userId = '13550';
		String commercialProductId = producto.Id;


		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AV_MockCallout_Test('CLI_CUSTOMMERPRODDATA','OK'));
		AV_FichaCliente_Integration.CommercialProductsResponse commercialProductResponse = AV_FichaCliente_Integration.getCommercialProducts(userId);		
		List<AV_FichaProductosComponentController.Response> responseList = new List<AV_FichaProductosComponentController.Response>();
        AV_FichaProductosComponentController.getInitData(acc.Id);
		Test.stopTest();
		
		//Second call to getInitData is mandatory for retrieving the data that a future method updated to the database in the first call.
		responseList = AV_FichaProductosComponentController.getInitData(acc.Id);
		System.assertEquals(1, responseList.size());
	}
	
	@isTest
	public static void testAccountWithTargetAndpreconcedido() {
		AV_TestHelper.activateLogger();
		Account acc = AV_TestHelper.createCustomer();
		String userId = '13550';
		AV_ExperienceBusiness__c exp = AV_TestHelper.createExperienciaNegocio();

		Product2 prodPF = AV_TestHelper.createProduct(null,null);
		Product2 producto = AV_TestHelper.createProduct(prodPF,'20');
		producto.AV_Profesional__c = false;
		producto.AV_Activo__c = true;
		update producto;

		AV_ProductExperience__c prodExp = AV_TestHelper.createPFExperience();
		prodExp.AV_Activo__c = true;
		prodExp.AV_ProductoFicha__c = producto.Id; 
		prodExp.AV_ExperienciaNegocio__c = exp.Id;
        prodExp.AV_ExternalId__c = 'BPA001_50077';
		update prodExp;
		
		AV_ProductClient__c prodCliente = AV_TestHelper.createPFCliente();
        prodCliente.AV_ProductoFicha__c = prodExp.Id;
        prodCliente.AV_Cliente__c = acc.Id;
        prodCliente.AV_ImportePreconcedido__c = 123123.12;
        prodCliente.AV_Target__c = true;
		update prodCliente;


		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AV_MockCallout_Test('CLI_CUSTOMMERPRODDATA','OK'));
		AV_FichaCliente_Integration.CommercialProductsResponse commercialProductResponse = AV_FichaCliente_Integration.getCommercialProducts(userId);		
		List<AV_FichaProductosComponentController.Response> responseList = new List<AV_FichaProductosComponentController.Response>();
        AV_FichaProductosComponentController.getInitData(acc.Id);
		Test.stopTest();

		//Second call to getInitData is mandatory for retrieving the data that a future method updated to the database in the first call.
		responseList = AV_FichaProductosComponentController.getInitData(acc.Id);
		System.assertEquals(1, responseList.size());
	}
	
	@isTest
	public static void testGetOpportunityNumber() {
		AV_TestHelper.activateLogger();
		
		Account acc = AV_TestHelper.createCustomer();
		
        Pricebook2 pb = new Pricebook2();
		pb.Name = 'Standard Price Book';
		insert pb;
        
		Opportunity opp = AV_TestHelper.createOpportunity(acc);

		Test.startTest();
		Product2 prodPF= [SELECT Id FROM Product2 LIMIT 1];
		List<Opportunity> listOpp = new List<Opportunity>();
		listOpp = AV_FichaProductosComponentController.getOpportunityNumber((String)acc.Id, (String)prodPF.Id);
		System.assertEquals(1, listOpp.size());
		
		Test.stopTest();
	}

	@isTest
	public static void testGetClientName() {
		AV_TestHelper.activateLogger();
		
		Account acc = AV_TestHelper.createCustomer();
		
		String nameAcc = [SELECT Name FROM Account where ID =: acc.Id LIMIT 1].Name;
		
        Pricebook2 pb = new Pricebook2();
		pb.Name = 'Standard Price Book';
		insert pb;
        
		Opportunity opp = AV_TestHelper.createOpportunity(acc);

		Test.startTest();

		String clientName = '';
		clientName = AV_FichaProductosComponentController.getClientName((String)acc.Id);
		System.assertEquals(nameAcc, clientName);
		
		Test.stopTest();
	} 
    
    @isTest
	public static void testproducts() {
		AV_TestHelper.activateLogger();
		Account acc = AV_TestHelper.createCustomer();
		String userId = '13550';
		AV_ExperienceBusiness__c exp = AV_TestHelper.createExperienciaNegocio();

		Product2 prodPF = AV_TestHelper.createProduct(null,null);
		Product2 producto = AV_TestHelper.createProduct(prodPF,'20');
		producto.AV_Profesional__c = false;
		producto.AV_Activo__c = true;
		update producto;

		AV_ProductExperience__c prodExp = AV_TestHelper.createPFExperience();
		prodExp.AV_Activo__c = true;
		prodExp.AV_ProductoFicha__c = producto.Id; 
		prodExp.AV_ExperienciaNegocio__c = exp.Id;
        prodExp.AV_ExternalId__c = 'BPA001_50046';
		update prodExp;
		
		AV_ProductClient__c prodCliente = AV_TestHelper.createPFCliente();
        prodCliente.AV_ProductoFicha__c = prodExp.Id;
        prodCliente.AV_Cliente__c = acc.Id;
        prodCliente.AV_ImportePreconcedido__c = 123123.12;
        prodCliente.AV_Target__c = true;
        prodCliente.AV_ExternalId__c = '50046';
		update prodCliente;
		AV_FichaCliente_Integration.Products product = new AV_FichaCliente_Integration.Products();
        AV_FichaCliente_Integration.DataKeyValue proCode= new  AV_FichaCliente_Integration.DataKeyValue('50046','');
        product.productCode = proCode;
        AV_FichaCliente_Integration.DataKeyValue sta= new  AV_FichaCliente_Integration.DataKeyValue('BPA001','');
        product.state = sta;
        product.order = 2;
        product.preconceived = 2;
        product.isTarget = true;
        product.isPotential = true;
        AV_FichaCliente_Integration.DataKeyValue oppData= new  AV_FichaCliente_Integration.DataKeyValue(prodCliente.AV_ExternalId__c,'');
        product.oportunity = oppData;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AV_MockCallout_Test('CLI_CUSTOMMERPRODDATA','OK'));
		AV_FichaCliente_Integration.CommercialProductsResponse commercialProductResponse = AV_FichaCliente_Integration.getCommercialProducts(userId);		
		List<AV_FichaProductosComponentController.Response> responseList = new List<AV_FichaProductosComponentController.Response>();
        AV_FichaProductosComponentController.getInitData(acc.Id);
        List<AV_FichaCliente_Integration.Products> listproduct = new List<AV_FichaCliente_Integration.Products>();
        listproduct.add(product);
        Map<String, AV_FichaCliente_Integration.Products> mapExpPFCustomer = new Map<String, AV_FichaCliente_Integration.Products>();
        mapExpPFCustomer.put(prodCliente.AV_ExternalId__c, product);
        List<AV_ProductClient__c> listPFCustomerViaIntegration = new List<AV_ProductClient__c>();
		listPFCustomerViaIntegration.add(prodCliente);
		Map<String, AV_ProductExperience__c> mapExternalIdExperience = new Map<String, AV_ProductExperience__c>();
		mapExternalIdExperience = AV_FichaProductosComponentController.createMapExperience(acc.AV_NumPerso__c, mapExpPFCustomer.keySet());
        AV_FichaProductosComponentController.updatePF(acc.Id, acc.AV_NumPerso__c, mapExpPFCustomer, listPFCustomerViaIntegration, mapExternalIdExperience);
		Test.stopTest();

		//Second call to getInitData is mandatory for retrieving the data that a future method updated to the database in the first call.
		responseList = AV_FichaProductosComponentController.getInitData(acc.Id);
		System.assertEquals(1, responseList.size());
	}

}