force-app/main/default/objects/Account/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_Negocio__c.field-meta.xml
<CustomField>
    <fullName>AV_Negocio__c</fullName>
    <description>Negocio del cliente (multivalor)</description>
    <label>Negocio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ExperienceBusiness__c/AV_ExperienceBusiness__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la información de las Experiencias de la estructura comercial relacionadas con el negocio</description>
    <label>Experiencia-Negocio</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Experiencia-Negocio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiencia-Negocio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ExperienceBusiness__c/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AV_ExperienceBusiness__c/fields/AV_Negocio__c.field-meta.xml
<CustomField>
    <fullName>AV_Negocio__c</fullName>
    <description>Negocio asociado con la experiencia de la estructura comercial</description>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/AV_ProductClient__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la información relaciona de los productos contratados por el cliente.
Almacena la tenencia y potencialidad de los PF del cliente.</description>
    <label>ProductoFicha-Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto-Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductoFicha-Cliente</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cliente relacionado</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ProductoFicha-Cliente</relationshipLabel>
    <relationshipName>ProductoFicha_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_ImportePreconcedido__c.field-meta.xml
<CustomField>
    <fullName>AV_ImportePreconcedido__c</fullName>
    <description>Importe del preconcedido para el producto ficha del cliente</description>
    <label>Importe Preconcedido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Negocio__c.field-meta.xml
<CustomField>
    <fullName>AV_Negocio__c</fullName>
    <description>Negocio del Producto Ficha y Cliente</description>
    <label>Negocio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_ProductoFicha__c.field-meta.xml
<CustomField>
    <fullName>AV_ProductoFicha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF relacionado</description>
    <label>Producto Ficha</label>
    <referenceTo>AV_ProductExperience__c</referenceTo>
    <relationshipLabel>ProductoFicha-Cliente</relationshipLabel>
    <relationshipName>ProductoFicha_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductClient__c/fields/AV_Target__c.field-meta.xml
<CustomField>
    <fullName>AV_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de mejora de prima</description>
    <label>Mejora de prima</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/AV_ProductExperience__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la relación entre PF y Experiencia</description>
    <label>ProductoFicha-Experiencia</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Producto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductoFicha-Experiencia</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de si está activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_ExperienciaNegocio__c.field-meta.xml
<CustomField>
    <fullName>AV_ExperienciaNegocio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Experiencia (Negocio) relacionado con el PF</description>
    <label>Experiencia Negocio</label>
    <referenceTo>AV_ExperienceBusiness__c</referenceTo>
    <relationshipLabel>ProductoFicha-Experiencia</relationshipLabel>
    <relationshipName>ProductoFicha_Experiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_ProductExperience__c/fields/AV_ProductoFicha__c.field-meta.xml
<CustomField>
    <fullName>AV_ProductoFicha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF relacionado</description>
    <label>Producto Ficha</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ProductoFicha-Experiencia</relationshipLabel>
    <relationshipName>ProductoFicha_Experiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador de CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_Activo__c.field-meta.xml
<CustomField>
    <fullName>AV_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de activo</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_Profesional__c.field-meta.xml
<CustomField>
    <fullName>AV_Profesional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de si es profesional</description>
    <label>Profesional</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AV_LinkArgumentario_Controller_Test.cls
/**********************************************************************************************************************
Name:	  AV_LinkArgumentario_Controller_Test
Copyright © 2020  CaixaBank
=======================================================================================================================
Proposito: Unit test to AV_LinkArgumentario_Controller 
=======================================================================================================================
Historial
---------------------
VERSION		USER_STORY		AUTHOR				DATE			Description
1.0			Test Class		Gonzalo Ávila 	    03/04/2024		Init version
***********************************************************************************************************************/
@isTest
public with sharing class AV_LinkArgumentario_Controller_Test {
    @TestSetup
	static void setup() {
        User userGcf = [Select Id from User where Profile.Name = 'API Only' and Alias = 'AV-TF9' and IsActive = true limit 1];
        User usuCli = [Select Id from User where Profile.Name = 'API Only' and Alias = 'FC-TF9' and IsActive = true limit 1];
        User userGestor = AV_TestHelper.createUser('AV_Usuario_CaixaBank','U01545454', 'AV_SistematicaComercial');
        

        AV_TestHelper.insertNeededPermissions(userGestor);
        
        Account acc;
		Contact cnt;
        	System.runAs(usuCli) {
                cnt = AV_TestHelper.createEmployee(AV_TestHelper.createCaixaCenter(),userGestor,userGestor.AV_ExternalID__c);
				acc = AV_TestHelper.createCustomer();
                
           }

        System.runAs(userGcf){
					AV_ExperienceBusiness__c exp = AV_TestHelper.createExperienciaNegocioSinInsert();
					exp.AV_ExternalID__c = 'BPA004';
					exp.AV_Negocio__c = 'BPA';
					insert exp;
					Product2 prodPF = AV_TestHelper.createProduct(null,null);
					Product2 producto = AV_TestHelper.createProductSinInsert(prodPF,'20',null);
					producto.AV_Profesional__c = false;
					producto.AV_Activo__c = true;
					insert producto;
		
					AV_ProductExperience__c prodExp = AV_TestHelper.createPFExperienceSinInsert();
					prodExp.AV_Activo__c = true;
					prodExp.AV_ProductoFicha__c = producto.Id; 
					prodExp.AV_ExperienciaNegocio__c = exp.Id;
					prodExp.AV_ExternalId__c = 'BPA004_50077';
					insert prodExp;
					
					AV_ProductClient__c prodCliente = AV_TestHelper.createPFClienteSinInsert();
					prodCliente.AV_ProductoFicha__c = prodExp.Id;
					prodCliente.AV_Cliente__c = acc.Id;
					prodCliente.AV_ImportePreconcedido__c = 123123.12;
					prodCliente.AV_Target__c = true;
					prodCliente.AV_ExternalID__c = '50046';
					prodCliente.AV_Activo__c = true;
					insert prodCliente;
					Opportunity opp = AV_TestHelper.createOpportunityWithProduct(acc,cnt,prodPF,null,null,null);


        }
	}

    @isTest
    public static void testgetProductData(){
        User us1=[SELECT id FROM User WHERE Alias = 'AV-TF9'];
        Opportunity opp = [Select Id FROM Opportunity WHERE AV_ExternalID__c = '00000001'];
        
        Test.startTest();
        System.runAs(us1){
            Product2 data = AV_LinkArgumentario_Controller.getProductData(opp.id);
        System.assert(data != null);
        Test.stopTest();
        }
    }
}