force-app/main/default/objects/Account/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_ToDelete__c.field-meta.xml
<CustomField>
    <fullName>AV_ToDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_Book__c/AV_Book__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene el detalle de las carteras de los gestores</description>
    <label>Cartera</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_BookMember__c/AV_BookMember__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene las carteras que están asociadas al cliente</description>
    <label>Cartera Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Cartera Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras Cliente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_BookMember__c/fields/AV_Cartera__c.field-meta.xml
<CustomField>
    <fullName>AV_Cartera__c</fullName>
    <description>Cartera asociada</description>
    <label>Cartera</label>
    <referenceTo>AV_Book__c</referenceTo>
    <relationshipLabel>Carteras Cliente</relationshipLabel>
    <relationshipName>Carteras_Cliente</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <description>Cliente asociado a la cartera</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carteras Cliente</relationshipLabel>
    <relationshipName>Carteras_Cliente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AV_DeleteRecordsCartCliBatch_Test.cls
/**********************************************************************************************************************
 Name:      AV_DeleteRecordsCartCliBatch_test
 Copyright © 2020  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito: Test de la clase AV_DeleteRecordsCartCliBatch
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
   VERSION        USER_STORY       AUTHOR           DATE                Description
   1.0            App FSC          Maria Telleria   23/04/2020          Init version
   1.1			  App FSC		   Sandra Gómez		04/11/2020			Refactor
   1.3		    FIX11070844	    Oscar Moreno		22/07/2024	        Insert System.enqueueJob(new AV_DeleteRecordsCartCliBatchQueueable()); 


***********************************************************************************************************************/
@isTest
private class AV_DeleteRecordsCartCliBatch_Test {

	/**
	 * Create 10 BookManagement Members with the field  To Delete checked.
	 */
	@TestSetup
	static void setup() {
		AV_TestHelper.activateLogger();

		AV_Book__c book=new AV_Book__c(name='Test');
		insert book;
		Account cliente=new Account(name='Test');
		insert cliente;
		// Insert 10 Book Members
		List<AV_BookMember__c> bookmemb = new List<AV_BookMember__c>();
		for (Integer i=0;i<10;i++) {
			bookmemb.add(new AV_BookMember__c(name='TestBorrado'+i, AV_ToDelete__c = true, AV_Cartera__c = book.id, AV_Cliente__c = cliente.id));
		}
		insert bookmemb;
	}

	/**
	 * Execute the Batch class (AV_DeleteRecordsCartCliBatch) and check if the book members created in te previous method are deleted.
	 */
	@isTest
	static void executeBatchDeleteRecord() {
		System.assertEquals(10, [select count() from AV_BookMember__c where AV_ToDelete__c = true]);
		Test.startTest();
		AV_DeleteRecordsCartCliBatch obj = new AV_DeleteRecordsCartCliBatch();
		DataBase.executeBatch(obj);
		System.enqueueJob(new AV_DeleteRecordsCartCliBatchQueueable()); 
		Test.stopTest();
		// Check if the inserted Book members are deleted correctly
		System.assertEquals(0, [select count() from AV_BookMember__c where AV_ToDelete__c = true]);
	}
	
}