force-app/main/default/objects/Account/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Es cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_ToDelete__c.field-meta.xml
<CustomField>
    <fullName>AV_ToDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIBE_BookCenter__c.field-meta.xml
<CustomField>
    <fullName>CIBE_BookCenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oficina Carterización del cliente</description>
    <label>Oficina carterización</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Oficina Carterización)</relationshipLabel>
    <relationshipName>AccountsBookCenter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember/fields/CIBE_IsAutomatic__c.field-meta.xml
<CustomField>
    <fullName>CIBE_IsAutomatic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsAutomatic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_Book__c/AV_Book__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene el detalle de las carteras de los gestores</description>
    <label>Cartera</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_Book__c/fields/AV_Centro__c.field-meta.xml
<CustomField>
    <fullName>AV_Centro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro de la cartera</description>
    <label>Centro</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carteras</relationshipLabel>
    <relationshipName>Carteras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_BookManagementMember__c/AV_BookManagementMember__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene la relación entre las carteras y los gestores</description>
    <label>Cartera Gestor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Cartera Gestor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras Gestor</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_BookManagementMember__c/fields/AV_Cartera__c.field-meta.xml
<CustomField>
    <fullName>AV_Cartera__c</fullName>
    <description>Cartera asociada</description>
    <label>Cartera</label>
    <referenceTo>AV_Book__c</referenceTo>
    <relationshipLabel>Carteras Gestor</relationshipLabel>
    <relationshipName>Carteras_Gestor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AV_BookManagementMember__c/fields/AV_CarteraActiva__c.field-meta.xml
<CustomField>
    <fullName>AV_CarteraActiva__c</fullName>
    <description>Muestra la cartera que esta activa</description>
    <formula>TEXT(AV_Cartera__r.AV_Activa__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cartera Activa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AV_BookManagementMember__c/fields/AV_EmpleadoGestor__c.field-meta.xml
<CustomField>
    <fullName>AV_EmpleadoGestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gestor asociado a la cartera</description>
    <label>Empleado Gestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Carteras Gestor</relationshipLabel>
    <relationshipName>Carteras_Gestor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AV_BookManagementMember__c/fields/CIBE_NegocioCartera__c.field-meta.xml
<CustomField>
    <fullName>CIBE_NegocioCartera__c</fullName>
    <formula>TEXT(AV_Cartera__r.AV_Negocio__c)</formula>
    <label>Negocio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/AV_BookMember__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene las carteras que están asociadas al cliente</description>
    <label>Cartera Cliente</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Cartera Cliente Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras Cliente</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AV_BookMember__c/fields/AV_Cartera__c.field-meta.xml
<CustomField>
    <fullName>AV_Cartera__c</fullName>
    <description>Cartera asociada</description>
    <label>Cartera</label>
    <referenceTo>AV_Book__c</referenceTo>
    <relationshipLabel>Carteras Cliente</relationshipLabel>
    <relationshipName>Carteras_Cliente</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/fields/AV_CarteraActiva__c.field-meta.xml
<CustomField>
    <fullName>AV_CarteraActiva__c</fullName>
    <description>Indicador de cartera activa</description>
    <formula>TEXT(AV_Cartera__r.AV_Activa__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cartera Activa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/fields/AV_CarteraPrincipal__c.field-meta.xml
<CustomField>
    <fullName>AV_CarteraPrincipal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de cartera principal</description>
    <label>Cartera Principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/fields/AV_Cliente__c.field-meta.xml
<CustomField>
    <fullName>AV_Cliente__c</fullName>
    <description>Cliente asociado a la cartera</description>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Carteras Cliente</relationshipLabel>
    <relationshipName>Carteras_Cliente</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/fields/CIBE_NegocioCartera__c.field-meta.xml
<CustomField>
    <fullName>CIBE_NegocioCartera__c</fullName>
    <description>negocio</description>
    <formula>TEXT(AV_Cartera__r.AV_TipoCartera__c)</formula>
    <label>Negocio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AV_BookMember__c/recordTypes/AV_CarteraCliente.recordType-meta.xml
<RecordType>
    <fullName>AV_CarteraCliente</fullName>
    <active>true</active>
    <label>Cartera Cliente</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AV_UsuarioAsociado__c.field-meta.xml
<CustomField>
    <fullName>AV_UsuarioAsociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Asociado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CIBE_BookMemberTriggerHelper.cls
/**********************************************************************************************************************
Name:	  CIBE_BookMemberTriggerHelper
Copyright © 2022  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito: Clase auxiliar de los Triggers de Cartera Cliente
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
	VERSION		USER_STORY			AUTHOR				DATE				Description
	1.0			US392789            Jose Maria		    04/10/2022			Init version
    1.0                             Bea                 27/01/2023          Create setBookCenter method
***********************************************************************************************************************/
public with sharing class CIBE_BookMemberTriggerHelper {

    /**
     *  @param description: Check the record types, de field delete and if is active
     *  @param listNews: list of new records
     */
    public static List<AV_BookMember__c> checkGeneralRT(List<AV_BookMember__c> listNews){
        Set<Id> setIdsRt = getAllRT();
        Set<String> negocioValues = new Set<String>{'COR', 'CIB', 'INS', 'EMP', 'PRO', 'MIC', 'INT', 'MOR', 'FIN', 'TES', 'CMX', 'RIE'};
        Set<String> tipoNegValues = new Set<String>{'ETR'};
        List<AV_BookMember__c> listData = new List<AV_BookMember__c>();
        for(AV_BookMember__c dataNew : listNews){
            if((setIdsRt).contains(dataNew.RecordTypeId)
                && dataNew.AV_CarteraActiva__c == 'S'
                && (negocioValues.contains(dataNew.CIBE_NegocioCartera__c)
                || (!String.IsBlank(dataNew.AV_ExternalID__c) && tipoNegValues.contains(dataNew.AV_ExternalID__c.substring(16, 19))))) {
                listData.add(dataNew);
            }
        }
        return listData;
    }
    
    /**
     *  @param description: Get all the ID's of the RT
     */
    public static Set<Id> getAllRT(){
        Set<String> setLabelsRt = new Set<String>{'AV_CarteraCliente'};
        return AV_AppUtilities.getRecordTypeIdsInSet(setLabelsRt);
    }

    /**
     *  @param description: Method that insert accountTeamMember if its necesary
     *  @param listBookMembers: get trigger insert values
     */
    public static void insertBookMember(List<AV_BookMember__c> listBookMembers) {
        Set<Id> setIdsClient = new Set<Id>();
        Set<String> setIdsCarteras = new Set<String>();
        for(AV_BookMember__c bm : listBookMembers){
            if(!bm.AV_ToDelete__c && String.isNotBlank(bm.AV_Cartera__c) && String.isNotBlank(bm.AV_Cliente__c)){
                setIdsCarteras.add(bm.AV_Cartera__c);
                setIdsClient.add(bm.AV_Cliente__c);
            }
        }

        if(!setIdsCarteras.isEmpty() && !setIdsClient.isEmpty()) {
            Map<String,String> mapBookMMB = new Map<String,String>();
            if(Schema.AV_BookManagementMember__c.SObjectType.getDescribe().isAccessible()){
                for(AV_BookManagementMember__c bmm : [SELECT Id, Name, AV_Cartera__c, AV_ToDelete__c, AV_EmpleadoGestor__c FROM AV_BookManagementMember__c WHERE AV_Cartera__c IN :setIdsCarteras AND AV_CarteraActiva__c = 'S' AND AV_ToDelete__c = false]){
                    mapBookMMB.put(bmm.AV_Cartera__c, bmm.AV_EmpleadoGestor__c);
                }
            }

            if(!mapBookMMB.isEmpty()){
                Map<String, String> mapUser = new Map<String, String>();
                if(Schema.Contact.SObjectType.getDescribe().isAccessible()){
                    for(Contact cont : [SELECT Id, AV_UsuarioAsociado__c FROM Contact WHERE Id IN :mapBookMMB.values()]){
                        mapUser.put(cont.Id, cont.AV_UsuarioAsociado__c);
                    }
                }
            
                if(!mapUser.isEmpty()){
                    Map<String, AccountTeamMember> mapAccTeamM = new Map<String, AccountTeamMember>();
                    if(Schema.AccountTeamMember.SObjectType.getDescribe().isAccessible()){
                        for(AccountTeamMember accTeamM : [SELECT Id, UserId, AccountId FROM AccountTeamMember WHERE UserId = :mapUser.values() AND AccountId = :setIdsClient]) {
                            mapAccTeamM.put((accTeamM.AccountId + '_' + accTeamM.UserId), accTeamM);
                        }
                    }

                    List<AccountTeamMember> listAccTM = new List<AccountTeamMember>();
                    for(AV_BookMember__c bm : listBookMembers){
                        if(String.isNotBlank(bm.AV_Cliente__c)
                            && mapBookMMB.containsKey(bm.AV_Cartera__c)
                            && mapUser.containsKey(mapBookMMB.get(bm.AV_Cartera__c))
                            && String.isNotBlank(mapUser.get(mapBookMMB.get(bm.AV_Cartera__c)))
                            && !mapAccTeamM.containsKey((bm.AV_Cliente__c + '_' + mapUser.get(mapBookMMB.get(bm.AV_Cartera__c))))) {
                            AccountTeamMember accTeamMember = new AccountTeamMember();
                            accTeamMember.UserId = mapUser.get(mapBookMMB.get(bm.AV_Cartera__c)); 
                            accTeamMember.AccountId = bm.AV_Cliente__c;
                            accTeamMember.AccountAccessLevel = CIBE_AppConstants.READ;
                            accTeamMember.OpportunityAccessLevel = CIBE_AppConstants.NONE;
                            accTeamMember.CaseAccessLevel = CIBE_AppConstants.READ;
                            accTeamMember.ContactAccessLevel = CIBE_AppConstants.EDIT;
                            accTeamMember.CIBE_IsAutomatic__c = true;
                            accTeamMember.TeamMemberRole = CIBE_AppConstants.PARTICIPANTE;
                            listAccTM.add(accTeamMember);
                        }
                    }

                    if(!listAccTM.isEmpty() && Schema.AccountTeamMember.SObjectType.getDescribe().isCreateable()){
                        Database.SaveResult [] inrs = Database.insert(listAccTM, false);

                        boolean hasError = false;
                        Map<String, String> msjs = new Map<String, String>();
                        List<Object> objs = new List<Object>();
                        for (Integer i = 0; i < listAccTM.size(); i++) {
                            Database.SaveResult sr = inrs[i];
                            if(!sr.isSuccess() && !sr.getErrors().isEmpty()) {
                                msjs.put(listAccTM[i].AccountId + '_' + listAccTM[i].UserId, ((String)sr.getErrors()[0].getMessage()));
                                objs.add(listAccTM[i]);
                                hasError = true;
                            }
                        }
                        if(hasError) {
                            CBK_Log.error(msjs, objs);
                        }
                    }
                }
            }
        }
    }

    /**
     *  @param description: Method that de accountTeamMember if its necesary
     *  @param listNewBM: get trigger update values
	 */
    public static void updateBookMember(List<AV_BookMember__c> listNewBM) {
        Set<String> setIdsCartDelete = new Set<String>();
        Set<String> setIdsClientDelete = new Set<String>();
        for(AV_BookMember__c bm : listNewBM){
            if(bm.AV_ToDelete__c && String.isNotBlank(bm.AV_Cartera__c) && String.isNotBlank(bm.AV_Cliente__c)) {
                setIdsCartDelete.add(bm.AV_Cartera__c);
                setIdsClientDelete.add(bm.AV_Cliente__c);
            }
        }

        if(!setIdsCartDelete.isEmpty() && !setIdsClientDelete.isEmpty()) {
            Map<String,String> mapBookMMB = new Map<String,String>();
            if(Schema.AV_BookManagementMember__c.SObjectType.getDescribe().isAccessible()){
                for(AV_BookManagementMember__c bmm : [SELECT Id, AV_Cartera__c, AV_EmpleadoGestor__c FROM AV_BookManagementMember__c WHERE AV_Cartera__c IN :setIdsCartDelete]){
                    mapBookMMB.put(bmm.AV_Cartera__c, bmm.AV_EmpleadoGestor__c);
                }
            }

            if(!mapBookMMB.isEmpty()){
                List<Id> listUser =new List<Id>();
                if(Schema.Contact.SObjectType.getDescribe().isAccessible()){
                    for(Contact cont : [SELECT Id, AV_UsuarioAsociado__c FROM Contact WHERE Id IN :mapBookMMB.values() ANd AV_UsuarioAsociado__c != null]){
                        listUser.add(cont.AV_UsuarioAsociado__c);
                    }
                }

                if(!listUser.isEmpty()){
                    List<AccountTeamMember> listAccTeamM = new List<AccountTeamMember>();
                    if(Schema.AccountTeamMember.SObjectType.getDescribe().isAccessible()){
                        listAccTeamM = [SELECT Id FROM AccountTeamMember WHERE CIBE_IsAutomatic__c = true AND UserId = :listUser AND AccountId = :setIdsClientDelete];
                    }

                    if(!listAccTeamM.isEmpty() && Schema.AccountTeamMember.SObjectType.getDescribe().isDeletable()){
                        Database.DeleteResult[] dels = Database.delete(listAccTeamM, false);

                        boolean hasError = false;
                        Map<String, String> msjs = new Map<String, String>();
                        List<Object> objs = new List<Object>();
                        for (Integer i = 0; i < listAccTeamM.size(); i++) {
                            Database.DeleteResult dr = dels[i];
                            if(!dr.isSuccess() && !dr.getErrors().isEmpty()) {
                                msjs.put(listAccTeamM[i].Id, ((String)dr.getErrors()[0].getMessage()));
                                objs.add(listAccTeamM[i]);
                                hasError = true;
                            }
                        }
                        if(hasError) {
                            CBK_Log.error(msjs, objs);
                        }
                    }
                }
            }
        }
    }

    public static void setBookCenter(List<AV_BookMember__c> listBookMembers) {
        Map<Id, Id> bookMemberToClient = new Map<Id, Id>();
        for (AV_BookMember__c bm : listBookMembers) {
            if(bm.AV_CarteraPrincipal__c && String.isNotBlank(bm.AV_Cliente__c)) {
                bookMemberToClient.put(bm.Id, bm.AV_Cliente__c);
            }
        }
        if(!bookMemberToClient.isEmpty()) {
            List<AV_BookMember__c> bookMembers = new List<AV_BookMember__c>();
            if(Schema.sObjectType.AV_BookMember__c.isAccessible()
                && Schema.SObjectType.AV_BookMember__c.fields.AV_Cliente__c .isAccessible()
                && Schema.SObjectType.AV_BookMember__c.fields.AV_Cartera__c .isAccessible()
                && Schema.SObjectType.AV_BookMember__c.fields.AV_CarteraPrincipal__c .isAccessible()) {
                bookMembers = [SELECT Id, AV_Cliente__c, AV_Cartera__c, AV_Cartera__r.AV_Centro__c FROM AV_BookMember__c WHERE Id = :bookMemberToClient.keySet() AND AV_Cliente__c != null AND AV_Cartera__c != null AND AV_CarteraPrincipal__c = true];
            }

            Map<Id, Account> clients = new Map<Id, Account>();
            if(Schema.sObjectType.Account.isAccessible()
                && Schema.SObjectType.Account.fields.CIBE_BookCenter__c .isAccessible()) {
                clients = new Map<Id, Account>([SELECT Id, CIBE_BookCenter__c FROM Account WHERE id IN :bookMemberToClient.values()]);
            }
            
            List<Account> toUpdate = new List<Account>();
            for(AV_BookMember__c bm : bookMembers) {   
                if(bm.AV_Cartera__r.AV_Centro__c != null && clients.containsKey(bm.AV_Cliente__c) && clients.get(bm.AV_Cliente__c).CIBE_BookCenter__c != bm.AV_Cartera__r.AV_Centro__c) {
                    clients.get(bm.AV_Cliente__c).CIBE_BookCenter__c = bm.AV_Cartera__r.AV_Centro__c;
                    if(!toUpdate.contains(clients.get(bm.AV_Cliente__c))){
                        toUpdate.add(clients.get(bm.AV_Cliente__c)); 
                    }
                }
            }
            if(!toUpdate.isEmpty() && Schema.sObjectType.Account.isUpdateable()) {
                Database.SaveResult [] inrs = Database.update(toUpdate, false);

                boolean hasError = false;
                Map<String, String> msjs = new Map<String, String>();
                List<Object> objs = new List<Object>();
                for (Integer i = 0; i < toUpdate.size(); i++) {
                    Database.SaveResult sr = inrs[i];
                    if(!sr.isSuccess() && !sr.getErrors().isEmpty()) {
                        msjs.put(toUpdate[i].Id, ((String)sr.getErrors()[0].getMessage()));
                        objs.add(toUpdate[i]);
                        hasError = true;
                    }
                }
                if(hasError) {
                    CBK_Log.error(msjs, objs);
                }
            }
        }
    } 
}