force-app/main/default/objects/Account/fields/AV_EAPGestor__c.field-meta.xml
<CustomField>
    <fullName>AV_EAPGestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EAP Gestor</description>
    <label>EAP/Gestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (AV_EAPGestor)</relationshipLabel>
    <relationshipName>AccountsGestor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_DominioMail__c.field-meta.xml
<CustomField>
    <fullName>SEG_DominioMail__c</fullName>
    <description>Dominio del e-mail asociado a la empresa</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dominio de e-mail</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_Empleado_gestor_Segmentos__c.field-meta.xml
<CustomField>
    <fullName>SEG_Empleado_gestor_Segmentos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empleado gestor (Segmentos)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cuentas (Empleado gestor (Segmentos))</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_Gestor_Comercial_Actual__c.field-meta.xml
<CustomField>
    <fullName>SEG_Gestor_Comercial_Actual__c</fullName>
    <description>Campo para comprobar si un Account tiene Caracterización Segmentos o no.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Gestor Comercial Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_GestorOperativaNacional__c.field-meta.xml
<CustomField>
    <fullName>SEG_GestorOperativaNacional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestor Operativa Nacional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Gestor Operativa Nacional)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_GestorOperativaNacionalActual__c.field-meta.xml
<CustomField>
    <fullName>SEG_GestorOperativaNacionalActual__c</fullName>
    <description>Campo que guarda el nombre del Gestor Operativa Nacional para poder usarse como filtro en el Caso</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Campo que guarda el nombre del Gestor Operativa Nacional para poder usarse como filtro en el Caso</inlineHelpText>
    <label>Gestor Operativa Nacional Actual</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_No_enviar_Acuse_Recibo_Empresa__c.field-meta.xml
<CustomField>
    <fullName>SEG_No_enviar_Acuse_Recibo_Empresa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No enviar Acuse Recibo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CC_ClienteSEG.recordType-meta.xml
<RecordType>
    <fullName>CC_ClienteSEG</fullName>
    <active>true</active>
    <description>Record Type para clientes manuales de Segmentos</description>
    <label>Cliente (Segmentos)</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CC_Colaborador.recordType-meta.xml
<RecordType>
    <fullName>CC_Colaborador</fullName>
    <active>true</active>
    <label>CC_Colaborador</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SEG_No_enviar_Acuse_Recibo__c.field-meta.xml
<CustomField>
    <fullName>SEG_No_enviar_Acuse_Recibo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No enviar Acuse Recibo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/CC_Colaborador.recordType-meta.xml
<RecordType>
    <fullName>CC_Colaborador</fullName>
    <active>true</active>
    <label>Colaborador</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/classes/SEG_Account_BI_TRHan_Test.cls
@isTest
public class SEG_Account_BI_TRHan_Test{
    //User operativo = SEG_Usuarios.usuarioOperativo();
    //User supervisor = SEG_Usuarios.usuarioSupervisor();

    /*@isTest
    public static void nuevoColaborador() {
        User supervisor = SEG_Usuarios.usuarioSupervisor();

        // Alta de datos para la prueba
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_Colaborador').getRecordTypeId();
        Account acc = new Account(RecordTypeId=rtId);
        acc.Name = 'Prueba';
        System.runAs (supervisor) {
            Test.startTest();
                    insert acc;
            Test.stopTest();
            
            // Evaluación del resultado de la prueba
            Account accInsertado = [SELECT Id FROM Account WHERE Id = :acc.Id];
            if (accInsertado != null) {
                System.assertNotEquals(accInsertado.Id, null);
            }
        }
    }*/

    //Test para la inserción de cuentas que deban rellenar el campo gestor comercial
    @isTest
    public static void actualizacionGestorComercial() {
        User supervisor = SEG_Usuarios.usuarioSupervisor();

        System.runAs ( new User(Id = UserInfo.getUserId()) ) {

            // Alta de datos para la prueba
            Contact contactoSEG = new Contact();
            contactoSEG.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
            contactoSEG.FirstName = 'Yaiza';
            contactoSEG.LastName = 'Contacto 2';
            contactoSEG.Email = 'testasdas@test.com';
            contactoSEG.SEG_No_enviar_Acuse_Recibo__c = false;
            insert contactoSEG;

            Contact contactoSEG2 = new Contact();
            contactoSEG2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
            contactoSEG2.FirstName = 'Yaiza';
            contactoSEG2.LastName = 'Contacto 2';
            contactoSEG2.Email = 'testasdas@test.com';
            contactoSEG2.SEG_No_enviar_Acuse_Recibo__c = false;
            insert contactoSEG2;

            Account cuentaSEG1 = new Account();
            cuentaSEG1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();
            cuentaSEG1.Name = 'Empresa segmentos 2';
            cuentaSEG1.SEG_DominioMail__c = '@cuentaSEG2';
            cuentaSEG1.CC_Numero_Documento__c = '11111111F';
            cuentaSEG1.AV_EAPGestor__c = contactoSEG.Id;
            cuentaSEG1.SEG_Empleado_gestor_Segmentos__c = contactoSEG2.Id;
            cuentaSEG1.SEG_No_enviar_Acuse_Recibo_Empresa__c = false;

        
            Test.startTest();
                insert cuentaSEG1;
            Test.stopTest();
            
            // Evaluación del resultado de la prueba
            Account accInsertado = [SELECT Id, SEG_Gestor_Comercial_Actual__c FROM Account WHERE Id = :cuentaSEG1.Id];
            if (accInsertado != null) {
                System.assertNotEquals(accInsertado.SEG_Gestor_Comercial_Actual__c, null);
            }
        }
    }

    //Test para la inserción de cuentas que deban rellenar el campo gestor comercial
    @isTest
    public static void actualizacionGestorComercial2() {
        User supervisor = SEG_Usuarios.usuarioSupervisor();

        // Alta de datos para la prueba
        Contact contactoSEG = new Contact();
        contactoSEG.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
        contactoSEG.FirstName = 'Yaiza';
        contactoSEG.LastName = 'Contacto 2';
        contactoSEG.Email = 'testasdas@test.com';
        contactoSEG.SEG_No_enviar_Acuse_Recibo__c = false;
        insert contactoSEG;

        Contact contactoSEG2 = new Contact();
        contactoSEG2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
        contactoSEG2.FirstName = 'Yaiza';
        contactoSEG2.LastName = 'Contacto 2';
        contactoSEG2.Email = 'testasdas@test.com';
        contactoSEG2.SEG_No_enviar_Acuse_Recibo__c = false;
        insert contactoSEG2;

        Account cuentaSEG1 = new Account();
        cuentaSEG1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClienteSEG').getRecordTypeId();
        cuentaSEG1.Name = 'Empresa segmentos 2';
        cuentaSEG1.SEG_DominioMail__c = '@cuentaSEG2';
        cuentaSEG1.CC_Numero_Documento__c = '11111111F';
        cuentaSEG1.AV_EAPGestor__c = contactoSEG.Id;
        cuentaSEG1.SEG_Empleado_gestor_Segmentos__c = contactoSEG2.Id;
        cuentaSEG1.SEG_No_enviar_Acuse_Recibo_Empresa__c = true;

        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Test.startTest();
                    insert cuentaSEG1;
            Test.stopTest();
            
            // Evaluación del resultado de la prueba
            Account accInsertado = [SELECT Id, SEG_Gestor_Comercial_Actual__c FROM Account WHERE Id = :cuentaSEG1.Id];
            if (accInsertado != null) {
                System.assertNotEquals(accInsertado.SEG_Gestor_Comercial_Actual__c, null);
            }
        }
    }

        //Test para la inserción de cuentas que deban rellenar el campo gestor comercial
        @isTest
        public static void actualizacionGestorComercial3() {
            User supervisor = SEG_Usuarios.usuarioSupervisor();

            // Alta de datos para la prueba
            Contact contactoSEG = new Contact();
            contactoSEG.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
            contactoSEG.FirstName = 'Yaiza';
            contactoSEG.LastName = 'Contacto 2';
            contactoSEG.Email = 'testasdas@test.com';
            contactoSEG.SEG_No_enviar_Acuse_Recibo__c = false;
            insert contactoSEG;
    
            Contact contactoSEG2 = new Contact();
            contactoSEG2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
            contactoSEG2.FirstName = 'Yaiza';
            contactoSEG2.LastName = 'Contacto 2';
            contactoSEG2.Email = 'testasdas@test.com';
            contactoSEG2.SEG_No_enviar_Acuse_Recibo__c = false;
            insert contactoSEG2;
    
            Account cuentaSEG1 = new Account();
            cuentaSEG1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClienteSEG').getRecordTypeId();
            cuentaSEG1.Name = 'Empresa segmentos 2';
            cuentaSEG1.SEG_DominioMail__c = '@cuentaSEG2';
            cuentaSEG1.CC_Numero_Documento__c = '11111111F';
            cuentaSEG1.AV_EAPGestor__c = contactoSEG.Id;
            cuentaSEG1.SEG_Empleado_gestor_Segmentos__c = contactoSEG2.Id;
            cuentaSEG1.SEG_No_enviar_Acuse_Recibo_Empresa__c = false;
    
            System.runAs ( new User(Id = UserInfo.getUserId()) ) {
                Test.startTest();
                        insert cuentaSEG1;
                Test.stopTest();
                
                // Evaluación del resultado de la prueba
                Account accInsertado = [SELECT Id, SEG_Gestor_Comercial_Actual__c FROM Account WHERE Id = :cuentaSEG1.Id];
                if (accInsertado != null) {
                    System.assertNotEquals(accInsertado.SEG_Gestor_Comercial_Actual__c, null);
                }
            }
        }

    //Test para la inserción de cuentas que deban rellenar el campo Gestor Operativa Nacional
    @isTest
    public static void actualizacionGestorOperativaNacionalTest() {
        User supervisor = SEG_Usuarios.usuarioSupervisor();
        
        // Alta de datos para la prueba
        Contact contactoSEG = new Contact();
        contactoSEG.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
        contactoSEG.FirstName = 'Test';
        contactoSEG.LastName = 'Test Apellido';
        contactoSEG.Email = 'testapellido@test.com';
        contactoSEG.SEG_No_enviar_Acuse_Recibo__c = false;
        insert contactoSEG;

        Account cuentaSEG1 = new Account();
        cuentaSEG1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();
        cuentaSEG1.Name = 'Empresa segmentos 3';
        cuentaSEG1.SEG_DominioMail__c = '@cuentaSEG3';
        cuentaSEG1.CC_Numero_Documento__c = '222222222F';
        cuentaSEG1.SEG_GestorOperativaNacional__c = contactoSEG.Id;
        cuentaSEG1.SEG_No_enviar_Acuse_Recibo_Empresa__c = false;
    
        System.runAs(new User(Id = UserInfo.getUserId())){
            Test.startTest();
                insert cuentaSEG1;
            Test.stopTest();
        }
        // Evaluación del resultado de la prueba
        Account accInsertado = [SELECT Id, SEG_GestorOperativaNacionalActual__c FROM Account WHERE Id = :cuentaSEG1.Id];
        if (accInsertado != null) {
            System.assertNotEquals(accInsertado.SEG_GestorOperativaNacionalActual__c, null);
        }
    }
}