force-app/main/default/objects/Account/fields/AV_EAPGestor__c.field-meta.xml
<CustomField>
    <fullName>AV_EAPGestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>EAP Gestor</description>
    <label>EAP/Gestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (AV_EAPGestor)</relationshipLabel>
    <relationshipName>AccountsGestor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AV_Idioma__c.field-meta.xml
<CustomField>
    <fullName>AV_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002</fullName>
                <label>Castellano</label>
            </value>
            <value>
                <fullName>001</fullName>
                <label>Catalán</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Euskera</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>Euskera/castellano</label>
            </value>
            <value>
                <fullName>006</fullName>
                <label>Valenciano</label>
            </value>
            <value>
                <fullName>004</fullName>
                <label>Gallego</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>Inglés</label>
            </value>
            <value>
                <fullName>012</fullName>
                <label>Alemán</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>Arabe</label>
            </value>
            <value>
                <fullName>022</fullName>
                <label>Búlgaro</label>
            </value>
            <value>
                <fullName>028</fullName>
                <label>Checo</label>
            </value>
            <value>
                <fullName>020</fullName>
                <label>Chino</label>
            </value>
            <value>
                <fullName>024</fullName>
                <label>Danés</label>
            </value>
            <value>
                <fullName>000</fullName>
                <label>Desconocido</label>
            </value>
            <value>
                <fullName>030</fullName>
                <label>Eslovaco</label>
            </value>
            <value>
                <fullName>026</fullName>
                <label>Finés</label>
            </value>
            <value>
                <fullName>011</fullName>
                <label>Francés</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>Griego</label>
            </value>
            <value>
                <fullName>016</fullName>
                <label>Holandés</label>
            </value>
            <value>
                <fullName>031</fullName>
                <label>Húngaro</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>Italiano</label>
            </value>
            <value>
                <fullName>027</fullName>
                <label>Japonés</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>Noruego</label>
            </value>
            <value>
                <fullName>017</fullName>
                <label>Polaco</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>Portugués</label>
            </value>
            <value>
                <fullName>018</fullName>
                <label>Rumano</label>
            </value>
            <value>
                <fullName>023</fullName>
                <label>Ruso</label>
            </value>
            <value>
                <fullName>015</fullName>
                <label>Sueco</label>
            </value>
            <value>
                <fullName>032</fullName>
                <label>Turco</label>
            </value>
            <value>
                <fullName>CastellanoDeprecated</fullName>
                <isActive>false</isActive>
                <label>CastellanoDeprecated</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EV_LastModifiedDateAC__c.field-meta.xml
<CustomField>
    <fullName>EV_LastModifiedDateAC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>EV_LastModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>false</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/EV_AccountTriggerHelper_Test.cls
@isTest
public with sharing class EV_AccountTriggerHelper_Test {
    @TestSetup
	static void makeData(){
		Account personAccount = EV_TestHelper.createCustomer();
	}


	@isTest
	public static void updateLastModifiedDateTest() {
		//Set<String> selectFieldsAccount = new Set<String>{'Id', 'CC_Numero_Documento__c', 'EV_LastModifiedDateAC__c,AV_Idioma__c,AV_EAPGestor__c'};

		Account customer = [SELECT Id, CC_Numero_Documento__c, EV_LastModifiedDateAC__c, AV_Idioma__c, AV_EAPGestor__c FROM Account where AV_NumPerso__c = '123'];
		Map<Id, Account> mapOld = new Map<Id, Account>{customer.Id => customer};
		List<Account> listNew = new List<Account>();
		customer.CC_Numero_Documento__c = '48133896Z';
		
		//update customer;
		listNew.add(customer);
		Test.startTest();
		//EV_AccountTriggerHelper.updateLastModifiedDate(listNew, mapOld);
		update customer;
		
		System.assertEquals('48133896Z', customer.CC_Numero_Documento__c);
		Test.stopTest();
		
	}
	

}