force-app/main/default/objects/Account/fields/AV_IndicadoresClientes__c.field-meta.xml
<CustomField>
    <fullName>AV_IndicadoresClientes__c</fullName>
    <description>obtener los indicadores de los clientes, para todos los tipos de clientes</description>
    <label>Indicadores de cliente</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ImaginTeen</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AgroBank</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Entidades Sociales</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Orden religiosa</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>DayOne</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Partido politico</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>HolaBank</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>InTouch</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Turismo</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Accionista CaixaBank</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>ImaginBank</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Real State</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Autonomo</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>ICO (Contigo mas que nunca)</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>NEG-BPE</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Comercializacion seguros Bankia</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Universo Consumo</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>Intouch Premier</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Food&amp;Drinks</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>MyBox</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Pharma</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>FeelGood</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>Senior</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Cliente sin consentimientos GDPR</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>Funcionarios y empleados públicos</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Universo Comunidades</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Universo Financiación Empresarial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Motivo_Derivacion__c.field-meta.xml
<CustomField>
    <fullName>CC_Motivo_Derivacion__c</fullName>
    <description>Motivo de la derivación KPI Agente</description>
    <label>Motivo de la derivación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por KO autenticación</fullName>
            </value>
            <value>
                <fullName>Por limitación de protocolo</fullName>
            </value>
            <value>
                <fullName>Resto derivación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_EnvioParcial__c.field-meta.xml
<CustomField>
    <fullName>SAC_EnvioParcial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check para informar del envío parcial de una pretensión</description>
    <label>Envío parcial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CBK_Activity_Extension__c/CBK_Activity_Extension__c.object-meta.xml
<CustomObject>
    <label>Activity Extension</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>CRM_Tarea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities Extension</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_Activity_Extension__c/fields/AV_ActivityId__c.field-meta.xml
<CustomField>
    <fullName>AV_ActivityId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Campo para guardar la id de la tarea o evento relacionado con la CRM tarea.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Actividad relacionada</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor2__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Valor.recordType-meta.xml
<RecordType>
    <fullName>CC_Valor</fullName>
    <active>true</active>
    <label>Valor</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Ambito_Tareas_Caixa__c.field-meta.xml
<CustomField>
    <fullName>CC_Ambito_Tareas_Caixa__c</fullName>
    <description>Campo utilizado para controlar a quien se manda la tarea del gestor en las cuentas caixa</description>
    <label>Ámbito derivación Caixa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Amenazas empleados</fullName>
            </value>
            <value>
                <fullName>Amenazas suicidios</fullName>
            </value>
            <value>
                <fullName>Argos General</fullName>
            </value>
            <value>
                <fullName>Argos Xpays</fullName>
            </value>
            <value>
                <fullName>Bizum Fraude</fullName>
            </value>
            <value>
                <fullName>CaixaBank Talks</fullName>
            </value>
            <value>
                <fullName>Cajeros</fullName>
            </value>
            <value>
                <fullName>Cajeros Incidencias</fullName>
            </value>
            <value>
                <fullName>Cambio de gestor</fullName>
            </value>
            <value>
                <fullName>Cambio de oficina</fullName>
            </value>
            <value>
                <fullName>Caso a Fraude</fullName>
            </value>
            <value>
                <fullName>CSBD 3N</fullName>
            </value>
            <value>
                <fullName>CSBD Contratar</fullName>
            </value>
            <value>
                <fullName>CSBD No Contratar</fullName>
            </value>
            <value>
                <fullName>Documentación</fullName>
            </value>
            <value>
                <fullName>No clientes</fullName>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Oficina física</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Phising/Smishing/Malware</fullName>
            </value>
            <value>
                <fullName>Testamentaría</fullName>
            </value>
            <value>
                <fullName>Ventas</fullName>
            </value>
            <value>
                <fullName>Vidacaixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Ambito_Tareas_Imagin__c.field-meta.xml
<CustomField>
    <fullName>CC_Ambito_Tareas_Imagin__c</fullName>
    <description>Campo utilizado para controlar a quien se manda la tarea del gestor en las cuentas imagin</description>
    <label>Ámbito derivación Imagin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Amenazas empleados</fullName>
            </value>
            <value>
                <fullName>Amenazas suicidios</fullName>
            </value>
            <value>
                <fullName>Argos General</fullName>
            </value>
            <value>
                <fullName>Argos Xpays</fullName>
            </value>
            <value>
                <fullName>Bizum Fraude</fullName>
            </value>
            <value>
                <fullName>CaixaBank Talks</fullName>
            </value>
            <value>
                <fullName>Cajeros</fullName>
            </value>
            <value>
                <fullName>Cajeros Incidencias</fullName>
            </value>
            <value>
                <fullName>Cambio de gestor</fullName>
            </value>
            <value>
                <fullName>Cambio de oficina</fullName>
            </value>
            <value>
                <fullName>Caso a Fraude</fullName>
            </value>
            <value>
                <fullName>CSBD 3N</fullName>
            </value>
            <value>
                <fullName>CSBD Contratar</fullName>
            </value>
            <value>
                <fullName>CSBD No Contratar</fullName>
            </value>
            <value>
                <fullName>Documentación</fullName>
            </value>
            <value>
                <fullName>Hub Imagin</fullName>
            </value>
            <value>
                <fullName>No clientes</fullName>
            </value>
            <value>
                <fullName>Oficina</fullName>
            </value>
            <value>
                <fullName>Oficina física</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Phising/Smishing/Malware</fullName>
            </value>
            <value>
                <fullName>Testamentaría</fullName>
            </value>
            <value>
                <fullName>Ventas</fullName>
            </value>
            <value>
                <fullName>Vidacaixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_Calculo_KPI_Tareas.cls
public with sharing class CC_Calculo_KPI_Tareas {

    private static Map<Case, Task> recuperarDatosCalculoKPI(List<Task> tareas, Set<String> tipoTareas) {

        // Extraer los IDs de casos de las tareas
        Set<Id> casoIds = new Set<Id>();
        for(Task tarea : tareas) {
            if(tarea.WhatId != null && tarea.WhatId.getSObjectType().getDescribe().getName() == 'Case' && tipoTareas.contains(tarea.Type)) {
                casoIds.add(tarea.WhatId);
            }
        }
        if(!casoIds.isEmpty()){
        // Recuperamos solo los casos
            Map<Id, Case> casosMap = new Map<Id, Case>([SELECT 
                            Id,
                            Subject, 
                            OwnerId, 
                            Account.AV_IndicadoresClientes__c, 
                            CC_Motivo_Derivacion__c, 
                            ContactId, 
                            CC_MCC_Motivo__r.CC_Ambito_Tareas_Imagin__c, 
                            CC_MCC_Motivo__r.CC_Ambito_Tareas_Caixa__c, 
                            SAC_EnvioParcial__c
                            FROM Case 
                        WHERE Id IN :casoIds]);

            // Crear mapa final
            Map<Case, Task> casos = new Map<Case, Task>();
            for(Id casoId : casosMap.keySet()) {
                for (Task tarea : tareas){
                    if(tarea.WhatId == casoId) {
                        casos.put(casosMap.get(casoId), tarea); //Se calculará el KPI a traves de la primera tarea que se procese para el caso (Bulk)
                        break;
                    }
                }
            }
            return casos;
        } else {
            return null;
        }
    }

    public static void rellenarKPI(List<Task> tareas){
        //Recogemos los tipos de tareas que se van a rellenar
        Set<String> tipoTareas = new Set<String>();

        List<CC_Lista_Valores__c> valoresOtrasOperativas = new List<CC_Lista_Valores__c>();
        List<CC_Lista_Valores__c> valoresDerivar = new List<CC_Lista_Valores__c>();
        
        List<CC_Lista_Valores__c> valores = [SELECT Id, Name, CC_Tipo_Tarea__c, CC_Valor__c, CC_Valor2__c, CC_AmbitoNull__c, CC_Lista__c, CC_Lista__r.Name FROM CC_Lista_Valores__c 
                WHERE CC_Lista__r.Name = 'Ámbitos cálculo KPI Derivar' 
                OR CC_Lista__r.Name = 'Ámbitos cálculo KPI Otras Operativas'
        ];

        for(CC_Lista_Valores__c valor : valores){
            tipoTareas.add(valor.CC_Tipo_Tarea__c);
            if(valor.CC_Lista__r.Name == 'Ámbitos cálculo KPI Derivar'){
                valoresDerivar.add(valor);
            } else if(valor.CC_Lista__r.Name == 'Ámbitos cálculo KPI Otras Operativas'){
                valoresOtrasOperativas.add(valor);
            }
        }

        System.debug('valores: ' + valores);

        //ESTRUCURA DE KPI - OPCION 1 - LOV
        //lISTA PRINCIPAL CON 2 LISTAS DE VALORES (VALORES DERIVAR Y VALORES OTRAS OPERATIVAS)
        //lISTA VALORES DERIVAR: CONTIENE LOS VALORES DE KPI RELACIONADOS CON EL AMBITO DE DERIVAR - ES NECESARIO QUE SE FIJE EN EL AMBITO TAREAS 
        //LISTA VALORES OTRAS OPERATIVAS: CONTIENE LOS VALORES DE KPI RELACIONADOS CON EL AMBITO DE OTRAS OPERATIVAS - NECESARIO QUE SE FIJE EN EL AMBITO TAREAS 
        //  SINO EN OTROS CAMPOS RELACIONADOS CON ESTE, POR EJEMPLO, CON EL CAMPO CC_ENTERCERNIVEL__C, O SIMPLEMENTE EN EL PROPIO CAMPO TIPO DE TAREA

        //Recuperamos los valores de los KPI
        Map<Case, Task> casos = recuperarDatosCalculoKPI(tareas, tipoTareas);
                
        //ESTRUCURA DE KPI - OPCION 2 - CUSTOM SETTINGS - CUSTOM METADATA
        //LOS VALORES DEL KPI SE ALMACENAN EN UN CUSTOM SETTING DE TIPO JERARQUICO O CUSTOM METADATA
        //3 CAMPOS:
        //1. Operativa del KPI
        //2. Valor del KPI (valor a asignar)
        //3. Tipo de KPI (tipo de la tarea)

        //List<CC_KPI_Tareas__mdt> kpiSettings = [SELECT Id, CC_Operativa__c, CC_Valor__c, CC_Tipo_Tarea__c, CC_AmbitoNull__c FROM CC_KPI_Tareas__mdt];

        //List<Task> tareasAMarcar = new List<Task>();

        if(casos != null && !casos.isEmpty()){
            for(Case caso : casos.keySet()){
                if(caso.SAC_EnvioParcial__c){
                    String ambitoActivo = caso.Account.AV_IndicadoresClientes__c != null && caso.Account.AV_IndicadoresClientes__c.contains('28') ? caso.CC_MCC_Motivo__r.CC_Ambito_Tareas_Imagin__c : caso.CC_MCC_Motivo__r.CC_Ambito_Tareas_Caixa__c;
                    String valorKPI = getLOV('Derivar', ambitoActivo, valoresDerivar, casos.get(caso).Type);
                    caso.CC_Motivo_Derivacion__c = valorKPI != null && valorKPI != '' ? valorKPI : caso.CC_Motivo_Derivacion__c;
                    caso.SAC_EnvioParcial__c = false;
                } else if (!caso.SAC_EnvioParcial__c){
                    String valorKPI = getLOV('Otras Operativas', null, valoresOtrasOperativas, casos.get(caso).Type);
                    caso.CC_Motivo_Derivacion__c = valorKPI != null && valorKPI != '' ? valorKPI : caso.CC_Motivo_Derivacion__c; 
                }
                //if(caso.CC_Motivo_Derivacion__c != null){
                //    tareasAMarcar.add(casos.get(caso));
                //}
            }

            /*if(!tareasAMarcar.isEmpty()){
                marcarTareaKPI(tareasAMarcar);
            }*/
            System.debug('caso motivo derivacion: ' + JSON.serializePretty(casos.keySet()));
            update new List<Case>(casos.keySet());
        }
    }

    private static String getLOV (String operativa, String ambitoActivo, List<CC_Lista_Valores__c> valores, String tipoTarea){

        //VAlOR DE EJEMPLO
        // 1. OPERATIVA = Derivar
        // 2. AMBITO ACTIVO = DOCUMENTACION
        // 3. VALORES POSIBLES DE CC_VALOR = Documentación, Solicitud Documentación, Gestionado con soporte
        // 4. TIPO DE TAREA (CC_TIPO_TAREA) = Solicitud Documentación
        // 5. VALOR DE RETORNO = Documentación

        if(operativa == null || valores == null || tipoTarea == null){
            return null;
        }

        for(CC_Lista_Valores__c valor : valores){
            if(valor.CC_Tipo_Tarea__c != tipoTarea) continue;

            if(operativa == 'Derivar'){
                if(valor.CC_Lista__r.Name == 'Ámbitos cálculo KPI Derivar' && (valor.CC_Valor__c == ambitoActivo || valor.CC_AmbitoNull__c == true) && valor.CC_Tipo_Tarea__c == tipoTarea){
                    return valor.CC_Valor2__c;
                }
            } else if (operativa == 'Otras Operativas'){
                if(valor.CC_Lista__r.Name == 'Ámbitos cálculo KPI Otras Operativas' && valor.CC_Tipo_Tarea__c == tipoTarea){
                    return valor.CC_Valor2__c;
                }
            }
        }

        return null;
    }

    //Creo que ya no es necesario marcar la tarea, ya que la tarea se rellena al crearse directamente y siempre será la ultima aunque no se complete la operativa
    /*private static void marcarTareaKPI(List<Task> tareas){
        // Recuperar extensiones existentes para todas las tareas
        Map<Id, CBK_Activity_Extension__c> extensiones = new Map<Id, CBK_Activity_Extension__c>();
        for(CBK_Activity_Extension__c ext : [SELECT Id, AV_ActivityId__c, CC_Tarea_Derivar__c 
                                            FROM CBK_Activity_Extension__c 
                                            WHERE AV_ActivityId__c IN :tareas]){
            extensiones.put(ext.AV_ActivityId__c, ext);
        }
        
        // Lista para almacenar extensiones a crear/actualizar
        List<CBK_Activity_Extension__c> paraUpsert = new List<CBK_Activity_Extension__c>();
        
        // Procesar cada tarea
        for(Task tarea : tareas){
            // Si la tarea ya tiene extensión
            if(extensiones.containsKey(tarea.Id)){
                CBK_Activity_Extension__c ext = extensiones.get(tarea.Id);
                // Solo actualizar si no tiene fecha asignada
                if(ext.CC_Tarea_Derivar__c == null){
                    ext.CC_Tarea_Derivar__c = CBK_UtilsDate.todaySYS();
                    paraUpsert.add(ext);
                }
            } else {
                // Crear nueva extensión si no existe
                paraUpsert.add(new CBK_Activity_Extension__c(
                    AV_ActivityId__c = tarea.Id,
                    CC_Tarea_Derivar__c = CBK_UtilsDate.todaySYS()
                ));
            }
        }
        
        // Ejecutar upsert si hay registros para procesar
        if(!paraUpsert.isEmpty()) upsert paraUpsert;
    }*/
}