force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de centro</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>NumPerso de la cuenta</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso proporcionado en la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>NumPerso proporcionado en la creación del caso</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SACH_Cliente.recordType-meta.xml
<RecordType>
    <fullName>SACH_Cliente</fullName>
    <active>true</active>
    <businessProcess>SACH_Support_Process</businessProcess>
    <label>Cliente (SACH)</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Fecha de inicio de vigencia</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio vigencia</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerson</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <formula>Account.CC_Numero_Oficina__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número Oficina</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerso</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/SACH_Parametros__c/SACH_Parametros__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting para todo lo referente a SACH para la configuración de datos.</description>
    <label>SACH_Parametros</label>
</CustomObject>

force-app/main/default/objects/SACH_Parametros__c/fields/SACH_Parametro_1__c.field-meta.xml
<CustomField>
    <fullName>SACH_Parametro_1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parametro_1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SACH_WS_AltaCasoPromor_v1_test.cls
@isTest
public with sharing class SACH_WS_AltaCasoPromor_v1_test {

    @testSetup
    static void data(){
          //Usuario SAC General
		User usuarioGeneral = SACH_TestDataFactory.crearUsuarioaSACH(1)[0];      
        Database.insert(usuarioGeneral);

        Id recordTypeIdTematica = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
        CC_MCC__c mccTematica = new CC_MCC__c();
		mccTematica.Name = 'Ahorro a la vista';
        mccTematica.CC_Tipo_Cliente__c = 'Cliente (SACH)';
        mccTematica.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccTematica.RecordTypeId = recordTypeIdTematica;
        mccTematica.CC_Codigo_Externo__c = 'TE-00000112';
        insert mccTematica;
        
        Id recordTypeIdProducto = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
        CC_MCC__c mccProducto = new CC_MCC__c();
        mccProducto.Name = 'Cuenta corriente'; 
        mccProducto.CC_Tipo_Cliente__c = 'Cliente (SACH)';
        mccProducto.CC_Fecha_Vigencia_Inicio__c = date.today();
        mccProducto.RecordTypeId = recordTypeIdProducto;
        mccProducto.CC_Tematica__c = mccTematica.Id;
        mccProducto.CC_Codigo_Externo__c = 'PR-00000121';
        insert mccProducto;
        
        Id recordTypeIdMotivo = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
        CC_MCC__c mccMotivo = new CC_MCC__c();
        mccMotivo.Name = 'Apertura sin autorización';
        mccMotivo.CC_Tipo_Cliente__c = 'Cliente (SACH)';
        mccMotivo.CC_Fecha_Vigencia_Inicio__c = date.today().addDays(7);
        mccMotivo.RecordTypeId = recordTypeIdMotivo;
        mccMotivo.CC_Tematica__c = mccTematica.Id;
        mccMotivo.CC_Producto_Servicio__c = mccProducto.Id;
        mccMotivo.CC_Codigo_Externo__c = 'MO-0000012';
        insert mccMotivo;

         // Insertar RecordTypes para Account y Contact si es necesario o asegurarse de que existen
         Id rtAccountCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_ClientePA');
         Id rtContactCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
 
         // Crear y insertar Account de prueba
         Account testAccount = new Account(LastName = 'Test Account',RecordTypeId = rtAccountCliente);
         insert testAccount;
         
         // Crear y insertar Contact de prueba
         Contact testContact = new Contact(RecordTypeId = rtContactCliente, LastName = 'Test Contact', AV_NumPerso__c = '14336032');
         insert testContact;

         SACH_Parametros__c params = new SACH_Parametros__c();
        params.Name = 'SACH_Promor';
        params.SACH_Parametro_1__c = 'https://google.com';
        insert params;
    }


    @isTest
    static void registrarCasoPromor_Test() {

        User usuario = [SELECT id FROM User WHERE Username = 'useratest0@test.com.testSetup' AND isActive = true LIMIT 1];
        System.runAs(usuario){


        Account cuenta = new Account();
        //cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClientePA').getRecordTypeId();
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_CentroCaixaBank');
        cuenta.Name = 'account temp';
        cuenta.CC_Numero_Oficina__c = '00256';
        insert cuenta;

        Id clientePAId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClientePA').getRecordTypeId();
        Id clienteId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();

        Id rtAccountCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_ClientePA');
        Account cuentaA = new Account();
        cuentaA.RecordTypeId = rtAccountCliente;
        cuentaA.LastName = 'Cuenta personal test A';
        insert cuentaA;

        Id rtAccountCliente2 = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_Cliente');
        Account cuentaB = new Account();
        cuentaB.RecordTypeId = rtAccountCliente2;
        cuentaB.Name = 'Cuenta personal test B';
        insert cuentaB;

        Id rtContactCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
       
        Contact contacto1 = new Contact();
        contacto1.RecordTypeId = rtContactCliente;
        contacto1.AccountId = cuentaB.Id;
        contacto1.FirstName = 'Contacto';
        contacto1.LastName = '01';
        contacto1.CC_NumPerso__c = '14336032';
        //contacto1.AV_NumPerso__c = '25345561';
        contacto1.CC_Idioma__c = 'ca';
        contacto1.Email = 'correo@gmail.com';
        contacto1.Phone = '973242323';
        insert contacto1;

        // Creamos un objeto RestRequest simulado
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/AltaCasoPromorv1';
        request.httpMethod = 'POST';
        
        // Crear una instancia de RestResponse
        RestResponse res = new RestResponse();
        // Establecer valores en la instancia de RestResponse
        res.statusCode = 200;
        res.responseBody = Blob.valueOf('{"message": "Success"}');
        res.addHeader('Content-Type', 'application/json');

        List<SACH_WS_AltaCasoPromor_v1.Input> inputsAccepted = new List<SACH_WS_AltaCasoPromor_v1.Input>();

        // Creamos un objeto de entrada simulado
        SACH_WS_AltaCasoPromor_v1.Input input = new SACH_WS_AltaCasoPromor_v1.Input();
        input.demanda = 'Demanda de prueba';
        input.iddemanda = '1234567890';
        input.contrato = 12345;
        input.oficinagestora = '00256';
        input.pacto = '299';
        input.numperso = '00DAC020';
        
        // Crear la lista de actividades
        List<SACH_WS_AltaCasoPromor_v1.Actividad> actividades = new List<SACH_WS_AltaCasoPromor_v1.Actividad>();

         // Crear una actividad de ejemplo
         SACH_WS_AltaCasoPromor_v1.Actividad actividad = new SACH_WS_AltaCasoPromor_v1.Actividad();
         actividad.codactividad = '58';
         actividad.comentarios = 'Prueba';
            
          // Crear la lista de adjuntos para la actividad
        List<SACH_WS_AltaCasoPromor_v1.Adjunto> adjuntos = new List<SACH_WS_AltaCasoPromor_v1.Adjunto>();

          // Crear adjuntos de ejemplo y añadirlos a la lista
          SACH_WS_AltaCasoPromor_v1.Adjunto adjunto1 = new SACH_WS_AltaCasoPromor_v1.Adjunto();
          adjunto1.nombreadjunto = 'prueba nombre adjunto1a';
          adjunto1.tipodocumento = 'tipodedocumento prueba1a';
          adjunto1.iddocumento = '123456789';
          adjuntos.add(adjunto1);

          SACH_WS_AltaCasoPromor_v1.Adjunto adjunto2 = new SACH_WS_AltaCasoPromor_v1.Adjunto();
          adjunto2.nombreadjunto = 'prueba nombre adjunto2a';
          adjunto2.tipodocumento = 'tipodedocumento prueba2a';
          adjunto2.iddocumento = '000000000';
          adjuntos.add(adjunto2);

          SACH_WS_AltaCasoPromor_v1.Adjunto adjunto3 = new SACH_WS_AltaCasoPromor_v1.Adjunto();
        adjunto3.nombreadjunto = 'prueba nombre adjunto3a';
        adjunto3.tipodocumento = 'tipodedocumento prueba3a';
        adjunto3.iddocumento = '111111111';
        adjuntos.add(adjunto3);

        // Asignar la lista de adjuntos a la actividad
        actividad.adjuntos = adjuntos;

         // Añadir la actividad a la lista de actividades
         actividades.add(actividad);

         // Asignar la lista de actividades al input
        input.actividades = actividades;
        inputsAccepted.add(input);


        /*
        input.comentario1 = 'Comentario 1';
        input.comentario2 = 'Comentario 2';
        input.comentario3 = 'Comentario 3';
        input.comentario4 = 'Comentario 4';*/

          // Creamos un número de persona ficticio
          
          Id idRecordTypeSACH = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SACH_Cliente').getRecordTypeId();
        
       Contact contactonuevo = [SELECT AV_NumPerso__c,Id,CC_NumPerso__c,RecordTypeId FROM Contact WHERE AccountId = :cuentaB.Id];
        //contactonuevo.AV_NumPerso__c = '25345561';
        //contactonuevo.RecordTypeId = rtContactCliente;
        //update contactonuevo;

         // Crear y insertar Contact de prueba
         //Contact testContact = new Contact(RecordTypeId = rtContactCliente, LastName = 'Test Contacto nuevo', AV_NumPerso__c = '25345561');
         //insert testContact;
        
         Case caso = new Case();
         caso.RecordTypeId = idRecordTypeSACH;
         caso.ContactId = contactonuevo.Id;
         caso.Subject = 'comprobacionContactoAI';    
        insert caso;

        // Convertimos el objeto de entrada en JSON y lo añadimos al cuerpo de la solicitud
        String requestBody = JSON.serialize(input);
        request.requestBody = Blob.valueOf(requestBody);
        

         // Asignar la instancia de RestResponse al contexto de la llamada REST
         RestContext.response = res;

        // Establecemos la solicitud simulada en el contexto de REST
        RestContext.request = request;
        //insert inputsAccepted;

        // Ejecutamos el método de registro del caso
        Test.startTest();
            //SACH_WS_AltaCasoPromor_v1.Output output = SACH_WS_AltaCasoPromor_v1.registrarCasoPromor(input);
            SACH_WS_AltaCasoPromor_v1.Output output = SACH_WS_AltaCasoPromor_v1.registrarCasoPromor();
        Test.stopTest();

        // Verificamos los resultados esperados
        System.assertEquals('OK', output.resultado);
        System.assertNotEquals(null, output.caseId);

        }
    }

    /*

    @isTest
    static void registrarCasoPromor2_Test() {

        User usuario = [SELECT id FROM User WHERE Username = 'useratest0@test.com.testSetup' AND isActive = true LIMIT 1];
        System.runAs(usuario){


        Account cuenta = new Account();
        //cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClientePA').getRecordTypeId();
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_CentroCaixaBank');
        cuenta.Name = 'account temp';
        cuenta.CC_Numero_Oficina__c = '09000';
        insert cuenta;

        Id clientePAId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClientePA').getRecordTypeId();
        Id clienteId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();

        Id rtAccountCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_ClientePA');
        Account cuentaA = new Account();
        cuentaA.RecordTypeId = rtAccountCliente;
        cuentaA.LastName = 'Cuenta personal test A';
        insert cuentaA;

        Id rtAccountCliente2 = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_Cliente');
        Account cuentaB = new Account();
        cuentaB.RecordTypeId = rtAccountCliente2;
        cuentaB.Name = 'Cuenta personal test B';
        insert cuentaB;

        Id rtContactCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
       
        Contact contacto1 = new Contact();
        contacto1.RecordTypeId = rtContactCliente;
        contacto1.AccountId = cuentaB.Id;
        contacto1.FirstName = 'Contacto';
        contacto1.LastName = '01';
        contacto1.CC_NumPerso__c = '14336032';
        //contacto1.AV_NumPerso__c = '25345561';
        contacto1.CC_Idioma__c = 'ca';
        contacto1.Email = 'correo@gmail.com';
        contacto1.Phone = '973242323';
        insert contacto1;

        // Creamos un objeto RestRequest simulado
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/AltaCasoPromorv1';
        request.httpMethod = 'POST';

        // Creamos un objeto de entrada simulado
        SACH_WS_AltaCasoPromor_v1.Input input = new SACH_WS_AltaCasoPromor_v1.Input();
        input.demanda = 'Demanda de prueba';
        input.contrato = 12345;
        input.oficinagestora = '09000';
        input.pacto = 'Pacto cumplido';
        input.numperso = '12345677';
        /*
        input.comentario1 = 'Comentario 1';
        input.comentario2 = 'Comentario 2';
        input.comentario3 = 'Comentario 3';
        input.comentario4 = 'Comentario 4';

          // Creamos un número de persona ficticio
          
          Id idRecordTypeSACH = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SACH_Cliente').getRecordTypeId();
        
       Contact contactonuevo = [SELECT AV_NumPerso__c,Id,CC_NumPerso__c,RecordTypeId FROM Contact WHERE AccountId = :cuentaB.Id];
        //contactonuevo.AV_NumPerso__c = '25345561';
        //contactonuevo.RecordTypeId = rtContactCliente;
        //update contactonuevo;

         // Crear y insertar Contact de prueba
         //Contact testContact = new Contact(RecordTypeId = rtContactCliente, LastName = 'Test Contacto nuevo', AV_NumPerso__c = '25345561');
         //insert testContact;
        
         Case caso = new Case();
         caso.RecordTypeId = idRecordTypeSACH;
         caso.ContactId = contactonuevo.Id;
         caso.Subject = 'comprobacionContactoAI';    
        insert caso;

        // Convertimos el objeto de entrada en JSON y lo añadimos al cuerpo de la solicitud
        String requestBody = JSON.serialize(input);
        request.requestBody = Blob.valueOf(requestBody);

        // Establecemos la solicitud simulada en el contexto de REST
        RestContext.request = request;

        // Ejecutamos el método de registro del caso
        Test.startTest();
            SACH_WS_AltaCasoPromor_v1.Output output = SACH_WS_AltaCasoPromor_v1.registrarCasoPromor(input);
        Test.stopTest();

        // Verificamos los resultados esperados
        System.assertEquals('KO', output.resultado);
        System.assertNotEquals(null, output.caseId);
        }
    }*/

    @isTest
    static void registrarCasoPromor_conCasoAsociado_Test() {
        User usuario = [SELECT id FROM User WHERE Username = 'useratest0@test.com.testSetup' AND isActive = true LIMIT 1];
        System.runAs(usuario){

          Account cuenta = new Account();
          //cuenta.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClientePA').getRecordTypeId();
          cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_CentroCaixaBank');
          cuenta.Name = 'account temp';
          cuenta.CC_Numero_Oficina__c = '00256';
          insert cuenta;


        Id rtContactCliente = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
        //Account cuenta = [SELECT Id, PersonContactId FROM Account WHERE recordType.developerName = 'CC_ClientePA'];
         // Crear y insertar Contact de prueba
         Contact testContact = new Contact(RecordTypeId = rtContactCliente, LastName = 'Test Contactdsfsdf', AV_NumPerso__c = '14336033');
         insert testContact;
        
        Id idRecordTypeSACH = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SACH_Cliente').getRecordTypeId();
        Case caso1 = new Case();
        caso1.RecordTypeId = idRecordTypeSACH;
        //caso1.AccountId = cuenta.Id;
        caso1.Status = 'Cerrado';
        caso1.ContactId = testContact.Id;
        caso1.Subject = 'comprobacionContactoAI';    
       insert caso1;

       Contact contactoIdentificado = SACH_Identificacion_Auto.identificarNUMPERSO('00DAC021');
	   List<Case> lstcasos = [SELECT Id FROM Case WHERE RecordType.DeveloperName = 'SACH_Cliente' AND ContactId = :contactoIdentificado.Id LIMIT 1];
	

       Case casoo = [SELECT Id FROM Case WHERE RecordTypeId = :idRecordTypeSACH];
         // Creamos un objeto RestRequest simulado
         RestRequest request = new RestRequest();
         request.requestURI = '/services/apexrest/AltaCasoPromorv1';
         request.httpMethod = 'POST';
      

         // Creamos un objeto de entrada simulado
        SACH_WS_AltaCasoPromor_v1.Input input = new SACH_WS_AltaCasoPromor_v1.Input();
        input.demanda = 'Demanda de prueba';
        input.contrato = 12345;
        input.oficinagestora = '09000';
        input.pacto = 'Pacto cumplido';
        input.numperso = '00DAC021';
        /*
        input.comentario1 = 'Comentario 1';
        input.comentario2 = 'Comentario 2';
        input.comentario3 = 'Comentario 3';
        input.comentario4 = 'Comentario 4';*/

          // Convertimos el objeto de entrada en JSON y lo añadimos al cuerpo de la solicitud
          String requestBody = JSON.serialize(input);
          request.requestBody = Blob.valueOf(requestBody);
         
          // Establecemos la solicitud simulada en el contexto de REST
         RestContext.request = request;
          
         // Crear una instancia de RestResponse
        RestResponse res = new RestResponse();
        // Establecer valores en la instancia de RestResponse
        res.statusCode = 200;
        res.responseBody = Blob.valueOf('{"message": "Success"}');
        res.addHeader('Content-Type', 'application/json');
        RestContext.response = res;


       // Ejecutamos el método de registro del caso
       Test.startTest();
        //SACH_WS_AltaCasoPromor_v1.Output output = SACH_WS_AltaCasoPromor_v1.registrarCasoPromor(input);
        SACH_WS_AltaCasoPromor_v1.Output output = SACH_WS_AltaCasoPromor_v1.registrarCasoPromor();
       Test.stopTest();

       // Verificamos los resultados esperados
       System.assertEquals('KO', output.resultado);
       System.assertNotEquals(null, output.caseId);
        }
    }
}