force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Identificador__c.field-meta.xml
<CustomField>
    <fullName>CC_Identificador__c</fullName>
    <formula>IF(RecordType.DeveloperName == &apos;CC_CentroCaixaBank&apos;, CC_Numero_Oficina_Empresa__c, CC_Numero_Documento__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identificador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>NumPerso de la cuenta</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso proporcionado en la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>NumPerso proporcionado en la creación del caso</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Status_Autorizacion__c.field-meta.xml
<CustomField>
    <fullName>CC_Status_Autorizacion__c</fullName>
    <description>Se utiliza este campo para guardar el estado de la autenticación que viene desde la llamada</description>
    <label>Status Autorización</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>UNAUTHORIZED</fullName>
            </value>
            <value>
                <fullName>TIMEOUT</fullName>
            </value>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>INPROGRESS</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>NOT_IDENTIFIED</fullName>
            </value>
            <value>
                <fullName>IS_MINOR</fullName>
            </value>
            <value>
                <fullName>IS_A_COMPANY</fullName>
            </value>
            <value>
                <fullName>NOT_DIGITAL_OR_BLOCKED</fullName>
            </value>
            <value>
                <fullName>NOTIFICATIONS_OFF</fullName>
            </value>
            <value>
                <fullName>SIN ESTADO</fullName>
                <default>true</default>
                <label>SIN ESTADO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/CC_Comunicaciones__c.object-meta.xml
<CustomObject>
    <description>Entidad para poder guardar comunicaciones con el cliente, otp, sms, etc...</description>
    <label>Comunicaciones</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Comunicaciones Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comunicaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CC_Case__c.field-meta.xml
<CustomField>
    <fullName>CC_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Comunicaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CC_Codigo_Error__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Error__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código error</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CC_Estado__c.field-meta.xml
<CustomField>
    <fullName>CC_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Cancelada por agente</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>Denegado</fullName>
            </value>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>No autorizado</fullName>
            </value>
            <value>
                <fullName>OTP No recibida</fullName>
            </value>
            <value>
                <fullName>Pdte. Envío</fullName>
            </value>
            <value>
                <fullName>Pdte. Validar</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CC_Respuesta_OTP__c.field-meta.xml
<CustomField>
    <fullName>CC_Respuesta_OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Respuesta OTP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CC_Ticket__c.field-meta.xml
<CustomField>
    <fullName>CC_Ticket__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>N.º Ticket</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/fields/CSBD_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad para la que se ha realizado la autenticación segura</description>
    <label>Oportunidad</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>startsWith</operation>
            <value>CSBD_</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Autenticaciones</relationshipLabel>
    <relationshipName>CSBD_Autenticaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Comunicaciones__c/recordTypes/CC_OTPSMS.recordType-meta.xml
<RecordType>
    <fullName>CC_OTPSMS</fullName>
    <active>true</active>
    <description>RecordType para crear un nuevo OTPSMS</description>
    <label>OTPSMS</label>
</RecordType>

force-app/main/default/objects/CC_InterfaceSettings__mdt/CC_InterfaceSettings__mdt.object-meta.xml
<CustomObject>
    <description>Configuración de integraciones</description>
    <label>Configuración interfaz</label>
    <pluralLabel>Configuración interfases</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_TrazaEntrada__c.field-meta.xml
<CustomField>
    <fullName>CC_TrazaEntrada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador si se guarda el mensaje de entrada de la integración</description>
    <inlineHelpText>Indicador si se guarda el mensaje de entrada de la integración</inlineHelpText>
    <label>Traza Entrada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_TrazaSalida__c.field-meta.xml
<CustomField>
    <fullName>CC_TrazaSalida__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador si se guarda el mensaje de respuesta de la integración</description>
    <inlineHelpText>Indicador si se guarda el mensaje de respuesta de la integración</inlineHelpText>
    <label>Traza Salida</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/CC_TrazaInt__c.object-meta.xml
<CustomObject>
    <description>Trazas de integraciones</description>
    <label>Traza Integraciones</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Interfaz</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trazas Integraciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_DetalleError__c.field-meta.xml
<CustomField>
    <fullName>CC_DetalleError__c</fullName>
    <description>Detalle error producido</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Detalle error producido</inlineHelpText>
    <label>Detalle error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FechaFin__c.field-meta.xml
<CustomField>
    <fullName>CC_FechaFin__c</fullName>
    <description>Fecha de finalización de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Fecha de finalización de la integración</inlineHelpText>
    <label>Fecha Fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FechaInicio__c.field-meta.xml
<CustomField>
    <fullName>CC_FechaInicio__c</fullName>
    <description>Fecha inicio de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Fecha inicio de la integración</inlineHelpText>
    <label>Fecha Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_FinOK__c.field-meta.xml
<CustomField>
    <fullName>CC_FinOK__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicador de finalización correcta de la integración</description>
    <inlineHelpText>Indicador de finalización correcta de la integración</inlineHelpText>
    <label>Finalizado OK</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_Identificador__c.field-meta.xml
<CustomField>
    <fullName>CC_Identificador__c</fullName>
    <description>Identificador asociado</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Identificador asociado</inlineHelpText>
    <label>Identificador</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_MensajeEntrada__c.field-meta.xml
<CustomField>
    <fullName>CC_MensajeEntrada__c</fullName>
    <description>Mensaje de entrada</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mensaje de entrada</inlineHelpText>
    <label>Entrada</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_MensajeSalida__c.field-meta.xml
<CustomField>
    <fullName>CC_MensajeSalida__c</fullName>
    <description>Mensaje de salida de la integración</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Mensaje de salida de la integración</inlineHelpText>
    <label>Salida</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_TrazaInt__c/fields/CC_TipoError__c.field-meta.xml
<CustomField>
    <fullName>CC_TipoError__c</fullName>
    <description>Tipo error producido</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Tipo error producido</inlineHelpText>
    <label>Tipo error</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_EstadoAutenticacion__c.field-meta.xml
<CustomField>
    <fullName>CSBD_EstadoAutenticacion__c</fullName>
    <label>Estado de la autenticación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABORTED</fullName>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>DENIED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>EXPIRED</fullName>
            </value>
            <value>
                <fullName>INPROGRESS</fullName>
            </value>
            <value>
                <fullName>IS_A_COMPANY</fullName>
            </value>
            <value>
                <fullName>IS_MINOR</fullName>
            </value>
            <value>
                <fullName>NOT_DIGITAL_OR_BLOCKED</fullName>
            </value>
            <value>
                <fullName>NOT_IDENTIFIED</fullName>
            </value>
            <value>
                <fullName>NOTIFICATIONS_OFF</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>SIN ESTADO</fullName>
                <default>true</default>
                <label>SIN ESTADO</label>
            </value>
            <value>
                <fullName>TIMEOUT</fullName>
            </value>
            <value>
                <fullName>UNAUTHORIZED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Idioma_Solicitud__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Idioma_Solicitud__c</fullName>
    <label>Idioma solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CC_WS_Envio_OTP.cls
public with sharing class CC_WS_Envio_OTP {

	//@future(callout=true)
	public static List<CC_Comunicaciones__c> CC_WS_Envio_OTP(Set<Id> idAutenticaciones) {
		List<CC_Comunicaciones__c> autenticaciones = [SELECT CC_Case__c, CC_Case__r.CC_Idioma__c, //Name, CC_Case__r.CC_NumPerso__c
														CC_Case__r.Account.CC_NumPerso__c, CC_Case__r.Account.AV_NumPerso__c,
														CSBD_Opportunity__c, CSBD_Opportunity__r.CSBD_Idioma_Solicitud__c,
														CSBD_Opportunity__r.Account.CC_NumPerso__c, CSBD_Opportunity__r.Account.AV_NumPerso__c
														FROM CC_Comunicaciones__c WHERE Id IN :idAutenticaciones]; //AND RecordType.DeveloperName = 'CC_OTPSMS'];

		CC_InterfaceSettings__mdt cfgIntegracion = CC_MetodosUtiles.getInterfazConfigBody('CC_Envio_OTP');
		if (cfgIntegracion != null) {
			List<CC_TrazaInt__c> trazas = new List<CC_TrazaInt__c>();
			List<Case> casos = new List<Case>();
            List<Opportunity> oportunidades = new List<Opportunity>();

			for (CC_Comunicaciones__c autenticacion : autenticaciones) {
				CC_TrazaInt__c traza = new CC_TrazaInt__c(Name = 'CC_Envio_OTP', CC_Identificador__c = autenticacion.Id);

                Id recordId = autenticacion.CC_Case__c ?? autenticacion.CSBD_Opportunity__c;
                String tipoObjeto = recordId.getSObjectType().getDescribe().getName();

				//Comprobar que tenemos el numperso informado para poder realizar el envío
				String numperso = autenticacion.CC_Case__r.Account.CC_NumPerso__c;
				numperso = numperso ?? autenticacion.CC_Case__r.Account.AV_NumPerso__c;
				numperso = numperso ?? autenticacion.CSBD_Opportunity__r.Account.CC_NumPerso__c;
				numperso = numperso ?? autenticacion.CSBD_Opportunity__r.Account.AV_NumPerso__c;
                if (String.isBlank(numperso)) { //Sin NUMPERSO informado
					traza.CC_FinOK__c = false;
					traza.CC_TipoError__c = 'Datos entrada no informados.';
					traza.CC_DetalleError__c = 'NUMPERSO no informado. Comunicación: ' + autenticacion.Id;
				} else {
					try {
						String requestBody = getRequestBody(cfgIntegracion, autenticacion, numperso);
						if (cfgIntegracion.CC_TrazaEntrada__c) {
							traza.CC_MensajeEntrada__c = requestBody;
						}

						traza.CC_FechaInicio__c = Datetime.now();
						HttpResponse httpResponse = new Http().send(getRequest(cfgIntegracion, requestBody));
						traza.CC_FechaFin__c = Datetime.now();

						// httpResponse.setStatusCode(200);//DPK comentar
						// httpResponse.setBody('{"ticket":"20240828123912408   00000007BCCOTP01","KeyBlock":{"publicClusterKey":"","publicIndexKey":""},"PhoneBlock":{"prefix":34,"phoneNumber":0,"phoneNumberO":"*****0346"}}');//DPK comentar
						// Parse the JSON httpResponse

						Boolean responseOk = httpResponse.getStatusCode() == 200;
                        traza.CC_FinOK__c = responseOk;
						if ((cfgIntegracion.CC_TrazaSalida__c || Test.isRunningTest())) {
							traza.CC_MensajeSalida__c = httpResponse.getBody();
						}

                        if (tipoObjeto == 'Case') {
                            Case caso = new Case(Id = recordId);
                            caso.CC_Status_Autorizacion__c = responseOk ? 'INPROGRESS' : 'ERROR';
                            casos.add(caso);
                        } else if (tipoObjeto == 'Opportunity') {
                            Opportunity oportunidad = new Opportunity(Id = recordId);
                            oportunidad.CSBD_EstadoAutenticacion__c = responseOk ? 'INPROGRESS' : 'ERROR';
                            oportunidades.add(oportunidad);
                        }

						System.debug('autenticacion.CC_Fecha_Envio__c = Datetime.now()');
						autenticacion.CC_Fecha_Envio__c = System.now();
						autenticacion.CC_Respuesta_OTP__c = (httpResponse.getBody() ?? '').left(255);
						if (responseOk) {
							autenticacion.CC_Estado__c = 'Pdte. Validar';
							autenticacion.CC_Codigo_Error__c = '00000';
							autenticacion.CC_Ticket__c = getResponseTicket(httpResponse.getBody());
						} else {
							Map<String, String> errores = getResponseErrores(httpResponse.getBody());
							autenticacion.CC_Estado__c = 'Error';
							autenticacion.CC_Resultado_Validacion__c = 'OTP errónea';
                            autenticacion.CC_Codigo_Error__c = errores.get('errorCode');
                            autenticacion.CC_Mensaje_Error__c = (errores.get('errorMessage') ?? '').left(255);

							traza.CC_TipoError__c = 'Error petición.';
							traza.CC_DetalleError__c = httpResponse.getStatus() + ' (' + httpResponse.getStatusCode() + ')';
						}
					} catch (Exception e) {
						traza.CC_FinOK__c = false;
						traza.CC_TipoError__c = 'Error comunicaciones.';
						traza.CC_DetalleError__c = e.getMessage();
					}
				}
				trazas.add(traza);
			}

			if (cfgIntegracion.CC_TrazaActiva__c || Test.isRunningTest()) {
                Database.insert(trazas, false);
            }
			Database.update(autenticaciones, false);
			Database.update(casos, false);
			Database.update(oportunidades, false);
		}
		return autenticaciones;
	}

	private static String getRequestBody(CC_InterfaceSettings__mdt cfgIntegracion, CC_Comunicaciones__c autenticacion, String numperso) {
		String eventDataClave = autenticacion.Id;
		Datetime ahora = System.now();
		eventDataClave += String.valueOf(ahora.year()) + ahora.month() + ahora.day();
		eventDataClave += ahora.hour()+ ahora.minute() + ahora.second() + ahora.millisecond();

		String idioma = autenticacion.CC_Case__r.CC_Idioma__c ?? autenticacion.CSBD_Opportunity__r.CSBD_Idioma_Solicitud__c;
		String eventDataIdioma = 'IDI00001003' + (idioma == 'es' ? '002' : idioma == 'ca' ? '001' : '003');

		//eventDataNumperso = eventDataNumperso + decimalToHex(decimal.valueOf(autenticacion.CC_Case__r.Account.CC_NumPerso__c));
		String eventDataNumperso = 'PER00002008' + decimalToHex(decimal.valueOf(numperso)).leftPad(8, '0');

		String requestBody = cfgIntegracion.CC_Body__c;
		requestBody = requestBody.replace('##dateTime##', getTimestamp());
		requestBody = requestBody.replace('##eventData##', 'CLAU0O01050' + eventDataClave.leftPad(50, ' ') + eventDataIdioma + eventDataNumperso + '99999999');
		requestBody = requestBody.replace('##personId##', numperso);
		return requestBody;
	}

	private static String getTimestamp() {
		Datetime ahora = System.now();
		String timestamp = String.valueOf(ahora.year());
		String mes = String.valueOf(ahora.month());
		timestamp += '-' + (mes.length() == 1 ? '0' + mes : mes);
		String dia = String.valueOf(ahora.day());
		timestamp += '-' + (dia.length() == 1 ? '0' + dia : dia);
		String hora = String.valueOf(ahora.hour());
		timestamp += '-' + (hora.length() == 1 ? '0' + hora : hora);
		String minutos = String.valueOf(ahora.minute());
		timestamp += '.' + (minutos.length() == 1 ? '0' + minutos : minutos);
		String segundos = String.valueOf(ahora.second());
		timestamp += '.' + (segundos.length() == 1 ? '0' + segundos : segundos);
		timestamp += '.' + String.valueOf(ahora.millisecond());
		return timestamp;
	}

	private static HttpRequest getRequest(CC_InterfaceSettings__mdt cfgIntegracion, String body) {
		HttpRequest httpRequest = new HttpRequest();
		if (!Test.isRunningTest()) {
			httpRequest.setClientCertificateName(cfgIntegracion.CC_Certificado__c);
		}
		httpRequest.setEndpoint(cfgIntegracion.CC_EndPoint__c);
		httpRequest.setMethod(cfgIntegracion.CC_TipoPeticion__c);
		Map<String, String> headers = getRequestHeaders();
		for (String header : headers.keySet()) {
			httpRequest.setHeader(header, headers.get(header));
		}

		httpRequest.setBody(body);
		return httpRequest;
	}

	private static Decimal modulus(Decimal dividend, Decimal divisor) {
		Decimal d = dividend.divide(divisor, 0, RoundingMode.FLOOR);
		return dividend - (d * divisor);
	}

	private static String decimalToHex(Decimal d) {
		String digits = '0123456789abcdef';
		String hex = '';
		while (d > 0) {
			Decimal digit = modulus(d, 16); // rightmost digit
			hex = digits.substring(digit.intValue(), digit.intValue() + 1) + hex; // string concatenation
			d = d.divide(16, 0, RoundingMode.FLOOR);
		}
		return hex;
	}

	private static String getResponseTicket(String httpRequestBody) {
        System.JSONParser parserSR = System.JSON.createParser(httpRequestBody);
        while (parserSR.nextToken() != null){
			if ((parserSR.getCurrentToken() == JSONToken.FIELD_NAME) && (parserSR.getText() == 'ticket')) {
				parserSR.nextToken();
				return parserSR.getText();
			}
		}
        return '';
    }

	private static Map<String, String> getResponseErrores(String httpRequestBody) {
        System.JSONParser parserSR = System.JSON.createParser(httpRequestBody);
        Map<String, String> errores = new Map<String, String>();
        while (parserSR.nextToken() != null) {
            if ((parserSR.getCurrentToken() == JSONToken.FIELD_NAME) && (parserSR.getText() == 'errorCode')) {
                parserSR.nextToken();
                errores.put('errorCode', parserSR.getText());
            }
            if ((parserSR.getCurrentToken() == JSONToken.FIELD_NAME) && (parserSR.getText() == 'errorMessage')) {
                parserSR.nextToken();
                errores.put('errorMessage', parserSR.getText());
            }
        }
		if (String.isNotBlank(errores.get('errorCode')) || String.isNotBlank(errores.get('errorMessage'))) {
			return errores;
		}

        parserSR = System.JSON.createParser(httpRequestBody);
        while (parserSR.nextToken() != null) {
            if ((parserSR.getCurrentToken() == JSONToken.FIELD_NAME) && (parserSR.getText() == 'code')) {
                parserSR.nextToken();
                errores.put('errorCode', parserSR.getText());
            }
            if ((parserSR.getCurrentToken() == JSONToken.FIELD_NAME) && (parserSR.getText() == 'summary')) {
                parserSR.nextToken();
                errores.put('errorMessage', parserSR.getText());
            }
        }
        return errores;
    }

	private static Map<String, String> getRequestHeaders() {
		/* Ejemplo de headers:
			· Content-Type: application/json;charset=UTF-8
			· x-api-actor-simulated: CCSF 	(solo para previos)
			· HTTP-HEADER-ACTOR: CBCCSF 	(solo para previos)
		*/
		Map<String, String> headers = new Map<String, String>{'Content-Type' => 'application/json;charset=UTF-8'};
		if ([SELECT IsSandbox FROM Organization].IsSandbox) {
			for (CC_Lista_Valores__c lov : [SELECT Name, CC_Valor__c FROM CC_Lista_Valores__c
											WHERE CC_Lista__r.Name = 'Request headers específicos del sandbox'
											AND CC_Lista__r.CC_Activa__c = TRUE AND CC_Activa__c = TRUE]) {
				headers.put(lov.Name, lov.CC_Valor__c);
			}
		}
		return headers;
	}
}