force-app/main/default/objects/Account/fields/AV_NumeroCentroCaixaBank__c.field-meta.xml
<CustomField>
    <fullName>AV_NumeroCentroCaixaBank__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de centro Caixa Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_OficinaGestoraId__c.field-meta.xml
<CustomField>
    <fullName>CC_OficinaGestoraId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oficina gestora del cliente</description>
    <inlineHelpText>Oficina gestora del cliente</inlineHelpText>
    <label>Oficina gestora</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oficinas gestoras</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_SuppliedNIF__c.field-meta.xml
<CustomField>
    <fullName>CC_SuppliedNIF__c</fullName>
    <description>Servicio web creación casos. Documento de identidad proporcionado.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Documento de identidad proporcionado.</inlineHelpText>
    <label>NIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_NombreContacto__c.field-meta.xml
<CustomField>
    <fullName>SAC_NombreContacto__c</fullName>
    <description>Nombre del contacto de la reclamación SAC</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Persona de contacto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reclamación padre de la pretensión</description>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pretensiones relacionadas</relationshipLabel>
    <relationshipName>Pretensiones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/SAC_Consulta.recordType-meta.xml
<RecordType>
    <fullName>SAC_Consulta</fullName>
    <active>true</active>
    <businessProcess>SAC_Consulta</businessProcess>
    <description>Consulta COPS</description>
    <label>Consulta</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AV_UsuarioAsociado__c.field-meta.xml
<CustomField>
    <fullName>AV_UsuarioAsociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Asociado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_OficinaGestoraId__c.field-meta.xml
<CustomField>
    <fullName>CC_OficinaGestoraId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina gestora</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oficinas gestoras</relationshipLabel>
    <relationshipName>CC_OficinaGestora</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/SAC_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto juntion entre el Maestro de acciones y el objeto Case creando una relación acción-reclamación/pretensión, para el proyecto de SAC Reclamaciones.</description>
    <label>Acción</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Comentarios__c.field-meta.xml
<CustomField>
    <fullName>SAC_Comentarios__c</fullName>
    <description>Apartado para los comentarios.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Comentarios</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Descripcion__c</fullName>
    <description>Descripción de la acción.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado de la acción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteEnviar</fullName>
                <default>true</default>
                <label>Pendiente enviar</label>
            </value>
            <value>
                <fullName>SAC_PendienteAsignar</fullName>
                <label>Pendiente asignar</label>
            </value>
            <value>
                <fullName>SAC_EnGestion</fullName>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadaIncompleta</fullName>
                <label>Finalizada incompleta</label>
            </value>
            <value>
                <fullName>SAC_StandBy</fullName>
                <label>Stand By</label>
            </value>
            <value>
                <fullName>SAC_PendienteRevision</fullName>
                <label>Pendiente revisión de GGH</label>
            </value>
            <value>
                <fullName>SAC_Devuelta</fullName>
                <label>Devuelta</label>
            </value>
            <value>
                <fullName>SAC_PteReenvio</fullName>
                <label>Pendiente reenvío a GGH</label>
            </value>
            <value>
                <fullName>SAC_Descartada</fullName>
                <label>Descartada</label>
            </value>
            <value>
                <fullName>SAC_Abierto</fullName>
                <isActive>false</isActive>
                <label>Abierto</label>
            </value>
            <value>
                <fullName>SAC_Cerrado</fullName>
                <isActive>false</isActive>
                <label>Cerrado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_FechaVencimiento__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaVencimiento__c</fullName>
    <description>Deprecated</description>
    <formula>CreatedDate +  SAC_PlazoMaximo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha vto inicial deprecated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_FechaVencimientoInicial__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaVencimientoInicial__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha vto inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_FechaVencimientoProrroga__c.field-meta.xml
<CustomField>
    <fullName>SAC_FechaVencimientoProrroga__c</fullName>
    <description>Guardará la fecha de vencimiento después de sumar los días de prórroga.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha vto prórroga</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Oficina__c.field-meta.xml
<CustomField>
    <fullName>SAC_Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Acciones</relationshipLabel>
    <relationshipName>Acciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_PlazoMaximo__c.field-meta.xml
<CustomField>
    <fullName>SAC_PlazoMaximo__c</fullName>
    <description>Plazo máximo (duración en días) (TME)</description>
    <label>Plazo máximo(Días)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reclamación</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Acciones de ejecución (Reclamación)</relationshipLabel>
    <relationshipName>SAC_AccionesCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/SAC_Interaccion__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar consultas a otros departamentos</description>
    <label>Interacción</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interacciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Estado__c.field-meta.xml
<CustomField>
    <fullName>SAC_Estado__c</fullName>
    <description>Estado en el que se encuentra la interacción</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAC_PendienteRespuesta</fullName>
                <default>true</default>
                <label>Pendiente Respuesta</label>
            </value>
            <value>
                <fullName>SAC_Resuelta</fullName>
                <label>Resuelta</label>
            </value>
            <value>
                <fullName>SAC_Atendida</fullName>
                <label>Atendida</label>
            </value>
            <value>
                <fullName>SAC_Reescalada</fullName>
                <label>Re escalada</label>
            </value>
            <value>
                <fullName>SAC_Borrador</fullName>
                <label>Pendiente Respuesta -  Borrador</label>
            </value>
            <value>
                <fullName>SAC_Finalizada</fullName>
                <label>Finalizada</label>
            </value>
            <value>
                <fullName>SAC_FinalizadoSinAtender</fullName>
                <label>Finalizado sin atender</label>
            </value>
            <value>
                <fullName>SAC_Cancelado</fullName>
                <label>Cancelado</label>
            </value>
            <value>
                <fullName>SAC_Devuelto</fullName>
                <label>Devuelto</label>
            </value>
            <value>
                <fullName>SAC_PendienteRespuestaDefinitiva</fullName>
                <label>Pendiente Respuesta Definitiva</label>
            </value>
            <value>
                <fullName>SPV_PendienteEnviar</fullName>
                <label>Pendiente enviar</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Fecha_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>SAC_Fecha_Vencimiento__c</fullName>
    <description>Fecha actual + el número de días definido en el grupo</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha Vencimiento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Oficina__c.field-meta.xml
<CustomField>
    <fullName>SAC_Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interacciones</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Pregunta__c.field-meta.xml
<CustomField>
    <fullName>SAC_Pregunta__c</fullName>
    <description>Pregunta a realizar</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Pregunta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para relaciona el objeto interaccion con las reclamaciones</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Consultas</relationshipLabel>
    <relationshipName>Interacciones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Reclamante__c.field-meta.xml
<CustomField>
    <fullName>SAC_Reclamante__c</fullName>
    <description>Reclamante del caso al que pertenece esta interacción</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Reclamante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Respuesta__c.field-meta.xml
<CustomField>
    <fullName>SAC_Respuesta__c</fullName>
    <description>Respuesta a la pregunta realizada</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Respuesta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/fields/SAC_Titulo__c.field-meta.xml
<CustomField>
    <fullName>SAC_Titulo__c</fullName>
    <description>Título del escalado</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAC_Interaccion__c/recordTypes/SAC_Consulta.recordType-meta.xml
<RecordType>
    <fullName>SAC_Consulta</fullName>
    <active>true</active>
    <description>Consulta a datos de otros Departamentos</description>
    <label>Consulta</label>
</RecordType>

force-app/main/default/classes/SAC_LCMP_ConsultasTareas.cls
/*****************************************************************
 * Name: SAC_LCMP_ConsultasTareas
 * Copyright © 2021  CaixaBank
 * 
 * Proposito: Controlador componente
 *              
 *   LWC asociado: sAC_ConsultasTareas
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR         DATE         Description
 * 1.0            US380275      Marcela Neira    02/06/22      Creación Clase
*****************************************************************/
public without sharing class SAC_LCMP_ConsultasTareas {
    
    @AuraEnabled(cacheable=true)
    public static AsuntosWrapper getActionConsultaOffice (){
        Id recTypeConsulta = Schema.SObjectType.SAC_Interaccion__c.getRecordTypeInfosByDeveloperName().get('SAC_Consulta').getRecordTypeId();

        id userId = userInfo.getUserId();
        /* SAC_Titulo__c, SAC_Descripcion__c, SAC_PlazoMaximo__c, SAC_FechaVencimientoInicial__c, SAC_FechaVencimientoProrroga__c, */
        List <SAC_Accion__c> lstTareas = [SELECT Id, RecordType.Name, toLabel(SAC_Estado__c), SAC_Reclamacion__r.CaseNumber, Owner.Name, SAC_Comentarios__c,
                                        SAC_Reclamacion__r.SAC_NombreContacto__c, SAC_Reclamacion__r.CC_SuppliedNIF__c, SAC_FechaVencimiento__c, SAC_Oficina__r.CC_Numero_Oficina__pc, SAC_Oficina__r.AV_NumeroCentroCaixaBank__c
                                        FROM SAC_Accion__c 
                                        WHERE  SAC_Reclamacion__r.CaseNumber != null AND Owner.Name != null AND SAC_Estado__c in ('SAC_PendienteAsignar', 'SAC_EnGestion', 'SAC_StandBy') 
                                        AND SAC_Oficina__c in (select AccountId from contact where AV_UsuarioAsociado__c =: userId )]; /*CC_OficinaGestoraId__c*/

        /* SAC_Titulo__c, toLabel(SAC_Estado__c) */
        List <SAC_Interaccion__c> lstConsultas = [SELECT Id, SAC_Pregunta__c, Owner.Name, SAC_Reclamacion__r.CaseNumber, SAC_Respuesta__c,
                                                SAC_Reclamante__c, SAC_Reclamacion__r.CC_SuppliedNIF__c, SAC_Fecha_Vencimiento__c, SAC_Oficina__r.CC_Numero_Oficina__pc, SAC_Oficina__r.AV_NumeroCentroCaixaBank__c
                                                FROM SAC_Interaccion__c 
                                                WHERE RecordTypeId = :recTypeConsulta AND (SAC_Estado__c = 'SAC_PendienteRespuesta' OR SAC_Estado__c = 'SAC_PendienteRespuestaDefinitiva') AND SAC_Reclamacion__r.CaseNumber != null AND Owner.Name != null AND
                                                SAC_Oficina__c in (select AccountId from contact where AV_UsuarioAsociado__c =: userId )];

        if(!lstTareas.isEmpty()){for (SAC_Accion__c tarea : lstTareas) {if(String.isNotBlank(tarea.SAC_Comentarios__c)){tarea.SAC_Comentarios__c = tarea.SAC_Comentarios__c.replaceAll('<[/a-zAZ0-9]*>','');}}}

        if(!lstConsultas.isEmpty()){for (SAC_Interaccion__c consulta : lstConsultas){if(String.isNotBlank(consulta.SAC_Pregunta__c)){consulta.SAC_Pregunta__c = consulta.SAC_Pregunta__c.replaceAll('<[/a-zAZ0-9]*>','');}if(String.isNotBlank(consulta.SAC_Respuesta__c)){consulta.SAC_Respuesta__c = consulta.SAC_Respuesta__c.replaceAll('<[/a-zAZ0-9]*>','');}}}
               
        AsuntosWrapper asuntos = new AsuntosWrapper(lstConsultas, lstTareas);
        return asuntos;
    }

    
    @AuraEnabled(cacheable=true)
    public static String getURLHomeOficinas() {
        return URL.getSalesforceBaseUrl().toExternalForm() +'/lightning/app/c__SAC_HomeOficinas/n/Home_Oficina';
    }

    public class AsuntosWrapper {

        @AuraEnabled public List <SAC_Interaccion__c> lstConsultas {get; set;}
        @AuraEnabled public List <SAC_Accion__c> lstTareas {get; set;}

        public AsuntosWrapper(List <SAC_Interaccion__c> lstConsultasC, List <SAC_Accion__c> lstTareasC){
            lstConsultas = lstConsultasC;
            lstTareas = lstTareasC;
        }
    }
}