force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Motivo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Motivo del caso</description>
    <inlineHelpText>Motivo del caso</inlineHelpText>
    <label>Motivo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>C - Motivo</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_ProdServ__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Producto_Servicio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <description>Número de documento de identidad proporcionado para la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Número de documento de identidad proporcionado para la creación del caso</inlineHelpText>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Buz_n_de_la_zona__c.field-meta.xml
<CustomField>
    <fullName>SEG_Buz_n_de_la_zona__c</fullName>
    <description>Buzon de la Zona del Caso</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Buzón de la Zona del Caso</inlineHelpText>
    <label>Buzón de la zona</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_sincronizado_con_TaskConnect__c.field-meta.xml
<CustomField>
    <fullName>SEG_sincronizado_con_TaskConnect__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox que indica si el Caso está sincronizado con TaskConnect</description>
    <label>Sincronizado con TaskConnect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SEG_Link_TF9__mdt/SEG_Link_TF9__mdt.object-meta.xml
<CustomObject>
    <description>Custom setting que contiene los parametros de la url del link operativo tf9, muestra si esta activo, y la sección donde queremos mostrar se tiene que mostrar.</description>
    <label>SEG_Link_TF9</label>
    <pluralLabel>SEG_Link_TF9s</pluralLabel>
</CustomObject>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_Activo__c.field-meta.xml
<CustomField>
    <fullName>SEG_Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Comprobación para ver si es Activo</description>
    <label>SEG_Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_Link_Name__c.field-meta.xml
<CustomField>
    <fullName>SEG_Link_Name__c</fullName>
    <description>Campo para establecer la URL a través de texto.</description>
    <label>Link_Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_Orden__c.field-meta.xml
<CustomField>
    <fullName>SEG_Orden__c</fullName>
    <description>Orden</description>
    <label>SEG_Orden</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_Seccion__c.field-meta.xml
<CustomField>
    <fullName>SEG_Seccion__c</fullName>
    <description>Sección</description>
    <label>SEG_Seccion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_trazadoNif__c.field-meta.xml
<CustomField>
    <fullName>SEG_trazadoNif__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Trazado para saber si un NIF es necesario en el Link.</description>
    <label>SEG_trazadoNif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SEG_Link_TF9__mdt/fields/SEG_VisibleDinamica__c.field-meta.xml
<CustomField>
    <fullName>SEG_VisibleDinamica__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para comrpobar si ellink pertenece a MCC</description>
    <label>VisibleDinamica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SEG_Link_TF9_Controller.cls
public with sharing class SEG_Link_TF9_Controller {

    public class LinkOperativo {
        @AuraEnabled
		public String label;
        @AuraEnabled
        public String url;
        @AuraEnabled
        public String nif;
        @AuraEnabled
        public Boolean trazadoNif;
        @AuraEnabled
        public String caseNumber;

        public LinkOperativo(String label, String url, String nif, Boolean trazadoNif, String caseNumber) {
            this.label = label;
            this.url = url;
            this.nif = nif;
            this.trazadoNif = trazadoNif;
            this.caseNumber = caseNumber;
        }
	}


    @AuraEnabled
    public static List<LinkOperativo> getLinks(String seccion, Id customerId) {
        //Metodo Apex al cual se le envia el nombre d eun objeto y un ID
        //Busca la cuenta relacionada al Id y genera un Link a TF9 donde se muestran los datos de la cuenta
        List<LinkOperativo> linksOperativos = new List<LinkOperativo>();
        if (seccion.equalsIgnoreCase('Case')) { //Se obtiene el Id de la cuenta si el lwc está en la página de un caso
            Case caso = [SELECT AccountId, CaseNumber, Account.AV_NumPerso__c, Account.Name, Account.CC_Numero_Documento__c, SEG_sincronizado_con_TaskConnect__c, CC_MCC_ProdServ__r.SEG_Links_Relacionados__c, CC_MCC_Motivo__r.SEG_Links_Relacionados__c, CC_MCC_Tematica__r.SEG_Links_Relacionados__c, SEG_Buz_n_de_la_zona__c FROM Case WHERE Id = :customerId];//Añadir traerse el nuevo campo de los MCC
            for (SEG_Link_TF9__mdt linkOperativoCmdt : [SELECT SEG_Link_Name__c, SEG_VisibleDinamica__c, Label, SEG_Orden__c, SEG_Seccion__c, SEG_trazadoNif__c, QualifiedApiName FROM SEG_Link_TF9__mdt
            WHERE SEG_Activo__c = TRUE
            AND SEG_Seccion__c LIKE :('%' + seccion + '%') ORDER BY SEG_Orden__c ASC]) {
                // Concatenar todos los niveles de MCC para el containts y crear String concatenado
                String mccs = (caso.CC_MCC_ProdServ__r?.SEG_Links_Relacionados__c ?? '') + 
                                       (caso.CC_MCC_Motivo__r?.SEG_Links_Relacionados__c ?? '') + 
                                       (caso.CC_MCC_Tematica__r?.SEG_Links_Relacionados__c ?? '');
                
                if ((linkOperativoCmdt.QualifiedApiName == 'SEG_Emision_Avales_Nacionales' && caso.SEG_sincronizado_con_TaskConnect__c)
                    || (linkOperativoCmdt.SEG_VisibleDinamica__c && mccs.contains(linkOperativoCmdt.label))
                    || (linkOperativoCmdt.SEG_VisibleDinamica__c == false && linkOperativoCmdt.QualifiedApiName != 'SEG_Emision_Avales_Nacionales')) {
                    String url = linkOperativoCmdt.SEG_Link_Name__c;                                         
                    url = url.replace('{n}', caso?.Account?.AV_NumPerso__c ?? '');
                    url = url.replace('{nif}', caso?.Account?.CC_Numero_Documento__c ?? '');
                    url = url.replace('{f}%20{l}', caso?.Account?.Name ?? '');
                    url = url.replaceAll( '\\s+', '%20');
                    url = url.replace('{caseN}', caso.caseNumber ?? '');
                    url = url.replace('{b}', caso.SEG_Buz_n_de_la_zona__c ?? '');
                        
                    linksOperativos.add(new LinkOperativo(linkOperativoCmdt.Label, url, caso?.Account?.CC_Numero_Documento__c ?? '', linkOperativoCmdt.SEG_trazadoNif__c, caso.caseNumber ?? ''));
                }
            }
        }
        return linksOperativos;
    }

    @AuraEnabled
    public static void insertarChatter(String seccion,Id customerId, String title, String nif, Boolean trazadoNif){
        
        if (seccion.equalsIgnoreCase('Case')) { 

            FeedItem feed = new FeedItem();
            feed.ParentId = customerId;
            feed.Type = 'TextPost';
            
            if(trazadoNif){
                feed.Body = 'Enlace a ' + title + ' NIF ' + nif;
            } else {
                feed.Body = 'Enlace a ' + title;
            }

            Database.insert(feed, true);
        }
    }
}