force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/CC_InterfaceSettings__mdt.object-meta.xml
<CustomObject>
    <description>Configuración de integraciones</description>
    <label>Configuración interfaz</label>
    <pluralLabel>Configuración interfases</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Interfaz activa</description>
    <inlineHelpText>Interfaz activa</inlineHelpText>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_Certificado__c.field-meta.xml
<CustomField>
    <fullName>CC_Certificado__c</fullName>
    <description>Certificado necesario en la integración</description>
    <inlineHelpText>Certificado necesario en la integración</inlineHelpText>
    <label>Certificado</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_ContentType__c.field-meta.xml
<CustomField>
    <fullName>CC_ContentType__c</fullName>
    <description>Content type de la petición</description>
    <inlineHelpText>Content type de la petición</inlineHelpText>
    <label>Content Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>CC_EndPoint__c</fullName>
    <description>End point del servicio</description>
    <inlineHelpText>End point del servicio</inlineHelpText>
    <label>End Point</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_InterfaceSettings__mdt/fields/CC_TipoPeticion__c.field-meta.xml
<CustomField>
    <fullName>CC_TipoPeticion__c</fullName>
    <description>Tipo de petición del servicio (GET / POST)</description>
    <inlineHelpText>Tipo de petición del servicio (GET / POST)</inlineHelpText>
    <label>Tipo petición</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Lista_Valores.recordType-meta.xml
<RecordType>
    <fullName>CC_Lista_Valores</fullName>
    <active>true</active>
    <label>Lista de valores</label>
</RecordType>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Valor.recordType-meta.xml
<RecordType>
    <fullName>CC_Valor</fullName>
    <active>true</active>
    <label>Valor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerson</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Actualizacion_Datos_Riesgo__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Actualizacion_Datos_Riesgo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Actualización datos riesgo (interno)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Limite_Compra_Estrella__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Compra_Estrella__c</fullName>
    <label>Importe disponible Compra Estrella</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Limite_Prestamos_Canales__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Prestamos_Canales__c</fullName>
    <label>Importe disponible  préstamos canales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Limite_Prestamos_Oficinas__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Prestamos_Oficinas__c</fullName>
    <label>Importe disponible préstamos oficinas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Limite_Tarjetas_Canales__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Tarjetas_Canales__c</fullName>
    <label>Importe disponible tarjetas canales</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CSBD_Limite_Tarjetas_Oficinas__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Tarjetas_Oficinas__c</fullName>
    <label>Importe disponible tarjetas oficinas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Contact_2__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Contact_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segundo contacto</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Segundo contacto)</relationshipLabel>
    <relationshipName>Opportunity2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Contact__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Limite_Compra_Estrella__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Compra_Estrella__c</fullName>
    <label>Importe disponible Wivai OP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Limite_Prestamos_Canales__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Prestamos_Canales__c</fullName>
    <label>Importe disponible préstamos canales OP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Limite_Prestamos_Oficinas__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Prestamos_Oficinas__c</fullName>
    <label>Importe disponible préstamos oficinas OP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Limite_Tarjetas_Canales__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Tarjetas_Canales__c</fullName>
    <label>Importe disponible tarjetas canales OP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Limite_Tarjetas_Oficinas__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Limite_Tarjetas_Oficinas__c</fullName>
    <label>Importe disponible tarjetas oficinas OP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Now_NIF__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Now_NIF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>NIF</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CSBD_Prestamo.recordType-meta.xml
<RecordType>
    <fullName>CSBD_Prestamo</fullName>
    <active>true</active>
    <businessProcess>CSBD_Sales_Process_Prestamos</businessProcess>
    <label>Consumo</label>
</RecordType>

force-app/main/default/classes/CSBD_SIR_Test.cls
@isTest
public class CSBD_SIR_Test {

    @TestSetup
    private static void altaDatosPrueba() {
        //Alta de las parametrizaciones que necesita el trigger BI de oportunidades
        CC_Lista_Valores__c listaValores = new CC_Lista_Valores__c();
        listaValores.RecordTypeId = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByDeveloperName().get('CC_Lista_Valores').getRecordTypeId();
        listaValores.Name = 'CSBD: Días cierre oportunidad por defecto';
        listaValores.CC_Activa__c = true;
        insert listaValores;

        CC_Lista_Valores__c valor = new CC_Lista_Valores__c();
        valor.RecordTypeId = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByDeveloperName().get('CC_Valor').getRecordTypeId();
        valor.CC_Lista__c = listaValores.Id;
        valor.Name = 'Préstamo';
        valor.CC_Valor__c = '1';
        listaValores.CC_Activa__c = true;
        insert valor;

        Pricebook2 listaPrecios = new Pricebook2();
        listaPrecios.Name = 'CSBD Price Book';
        listaPrecios.Description = 'CSBD Price Book';
        listaPrecios.IsActive = true;
        insert listaPrecios;
    }

    @isTest
    public static void actualizarDatosRiesgoClientesOportunidades() {
        System.runAs(CSBD_TestDataFactory.usuarioAdministrador()) {
            Map<String, Object> cuentaContacto = CSBD_TestDataFactory.crearCuentaContacto('46979396X', new Map<String, Object>{'AV_NumPerso__c' => '21444982'});
            Account cuenta = (Account)cuentaContacto.get('cuenta');
            Contact contacto1 = (Contact)cuentaContacto.get('contacto');
            Contact contacto2 = CSBD_TestDataFactory.crearContacto(new Map<String, Object>{'AccountId' => cuenta.Id, 'AV_NumPerso__c' => '21444983'});

            System.runAs(CSBD_TestDataFactory.usuarioGestor()) {
                //Preparación de respuestas de prueba de los servicios web guardadas como static resources
                MultiStaticResourceCalloutMock multiMock = new MultiStaticResourceCalloutMock();
                String endpointSirCalcLimites = obtenerParametrosIntegracion('CSBD_SIR_CalcLimites')?.CC_EndPoint__c;
                if (String.isNotBlank(endpointSirCalcLimites)) {
                    multiMock.setStaticResource(endpointSirCalcLimites, 'CSBD_SIR_Respuesta_sirCalcLimites');
                }
                String endpointSirConsultaScorings = obtenerParametrosIntegracion('CSBD_SIR_ConsultaScorings')?.CC_EndPoint__c;
                if (String.isNotBlank(endpointSirConsultaScorings)) {
                    multiMock.setStaticResource(endpointSirConsultaScorings, 'CSBD_SIR_Respuesta_sirCalcLimites');
                }
                multiMock.setStatusCode(200);
                multiMock.setHeader('Content-Type', 'text/xml');
                Test.setMock(HttpCalloutMock.class, multiMock);

                Opportunity prestamo = CSBD_Opportunity.crearOportunidad('CSBD_Prestamo', new Map<String, Object>{
                    'AccountId' => cuenta.Id,
                    'CSBD_Contact__c' => contacto1.Id,
                    'CSBD_Contact_2__c' => contacto2.Id,
                    'CSBD_Now_NIF__c' => cuenta.CC_Numero_Documento__c
                });

                Test.startTest();
                CSBD_SIR.actualizarDatosRiesgoClientesOportunidades(new List<Id>{prestamo.Id}, true);
                Test.stopTest();

                Opportunity oportunidadCreada = [SELECT CSBD_Limite_Prestamos_Oficinas__c, CSBD_Limite_Prestamos_Canales__c, CSBD_Limite_Tarjetas_Oficinas__c, CSBD_Limite_Tarjetas_Canales__c, CSBD_Limite_Compra_Estrella__c
                                                    FROM Opportunity WHERE Id = :prestamo.Id];
                Contact contactoCreado = [SELECT CSBD_Actualizacion_Datos_Riesgo__c FROM Contact WHERE Id = :prestamo.CSBD_Contact__c];
                System.assertEquals(false, contactoCreado.CSBD_Actualizacion_Datos_Riesgo__c, 'El bypass de la VR de bloqueo de ALF no se ha desmarcado');

                System.assertNotEquals(null, oportunidadCreada.CSBD_Limite_Prestamos_Oficinas__c, 'El límite de préstamos de oficinas no se ha actualizado');
                System.assertNotEquals(null, oportunidadCreada.CSBD_Limite_Prestamos_Canales__c, 'El límite de préstamos de canales no se ha actualizado');
                System.assertNotEquals(null, oportunidadCreada.CSBD_Limite_Tarjetas_Oficinas__c, 'El límite de tarjetas de oficinas no se ha actualizado');
                System.assertNotEquals(null, oportunidadCreada.CSBD_Limite_Tarjetas_Canales__c, 'El límite de tarjetas de canales no se ha actualizado');
                System.assertNotEquals(null, oportunidadCreada.CSBD_Limite_Compra_Estrella__c, 'El límite de compra de estrella no se ha actualizado');
            }
        }
    }

    private static CC_InterfaceSettings__mdt obtenerParametrosIntegracion(String interfazDevName) {
        List<CC_InterfaceSettings__mdt> parametrosInterfaz = [SELECT DeveloperName, CC_Certificado__c, CC_Endpoint__c, CC_TipoPeticion__c, CC_ContentType__c
                                                                FROM CC_InterfaceSettings__mdt WHERE DeveloperName = :interfazDevName AND CC_Activa__c = true LIMIT 1];
        if (!parametrosInterfaz.isEmpty()) {
            return parametrosInterfaz[0];
        } else {
            return null;
        }
    }
}