force-app/main/default/objects/Account/fields/AV_Negocio__c.field-meta.xml
<CustomField>
    <fullName>AV_Negocio__c</fullName>
    <description>Negocio del cliente (multivalor)</description>
    <label>Negocio</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AV_Negocio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <description>AV_Numperso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>AV_Numperso de la cuenta</inlineHelpText>
    <label>NumPerso AV</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/AV_OficinaPrincipal__c.field-meta.xml
<CustomField>
    <fullName>AV_OficinaPrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oficina principal del cliente</description>
    <label>Oficina Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (AV_OficinaPrincipal)</relationshipLabel>
    <relationshipName>AccountsOficina</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de centro</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Oficina_Empresa__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina_Empresa__c</fullName>
    <description>Número de oficina y empresa</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Número de oficina y empresa</inlineHelpText>
    <label>Número oficina-empresa</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ__SourceSystemId__c.field-meta.xml
<CustomField>
    <fullName>FinServ__SourceSystemId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/AV_ExternalId__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalId__c</fullName>
    <description>External Id of Account Contact Relationship</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/AV_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>AV_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerson</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/AV_UsuarioAsociado__c.field-meta.xml
<CustomField>
    <fullName>AV_UsuarioAsociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Asociado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <formula>Account.CC_Numero_Oficina__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número Oficina</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FinServ__SourceSystemId__c.field-meta.xml
<CustomField>
    <fullName>FinServ__SourceSystemId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source System ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/User/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CIBE_AccExtAccConRel_Batch_Test.cls
/********************************************************************************************************************
Name: CIBE_AccExtAccConRel_Batch_Test
Copyright © 2024 CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito:
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
	VERSION		USER_STORY		AUTHOR				DATE			Description
	1.0			US493757	    Borja Lavesiera	    21/01/24		Init version

************************************************************************************************************************/
@isTest
public with sharing class CIBE_AccExtAccConRel_Batch_Test {
    @TestSetup
    public static void testSetup() {
        RecordType rt = CIBE_AppUtilities.getRecordType(CIBE_AppConstants.OBJECT_NAME_ACCOUNT, CIBE_AppConstants.ACCOUNT_CENTROCAIXABANK_RT);
        list<account> acclist = new list<account>();
        Account centroCaixa = new Account();
        centroCaixa.Name = 'oficina1';
        centroCaixa.CC_Numero_Oficina_Empresa__c = '123456789';
        centroCaixa.CC_Numero_Oficina__c = '00615';
        centroCaixa.RecordTypeId = rt.Id;
        insert centroCaixa;

        Account centroCaixa2 = new Account();
        centroCaixa2.Name = 'oficina2';
        centroCaixa2.CC_Numero_Oficina_Empresa__c = '987654321';
        centroCaixa2.CC_Numero_Oficina__c = '00616';
        centroCaixa2.RecordTypeId = rt.Id;
        insert centroCaixa2;
        user usr = CIBE_TestHelper.createUser('CIBE_Gestor', 'U011');
        List<User> sysAdminUser = [SELECT Id FROM User WHERE Profile.name LIKE 'System Administrator' AND IsActive=true];
        if (!sysAdminUser.isEmpty()) {
            System.runAs(sysAdminUser[0]) {
            contact con = CIBE_TestHelper.createEmployee(centroCaixa2, usr);
            account acc1 = new Account(Name = 'Test Account 1',
             AV_OficinaPrincipal__c = centroCaixa.id,
             AV_NumPerso__c = '123',
             AV_Negocio__c = 'EMP',
             RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('CC_Cliente').getRecordTypeId());

             account acc2 = new Account(Name = 'Test Account 1',
             AV_OficinaPrincipal__c = centroCaixa.id,
             AV_NumPerso__c = '456',
             AV_Negocio__c = 'CIB',
             RecordTypeId = Schema.SObjectType.Account.RecordTypeInfosByDeveloperName.get('CC_Cliente').getRecordTypeId());
             list<account> accList2 = new list<account>();
             accList2.add(acc1);
             accList2.add(acc2);
             insert accList2;
        }
    }
    }
    @isTest
    static void testUpdate() {
        account acc = [SELECT ID, owner.name FROM ACCOUNT WHERE NAME = 'oficina1' limit 1];
        contact con = [select id from contact where av_usuarioAsociado__r.AV_ExternalID__c = 'U011' limit 1];
        user us = [select id from user WHERE Profile.Name = 'API Only' AND Alias = 'AV-TF9' AND IsActive = true LIMIT 1];
        AccountContactRelation acr1;
        acr1 = new AccountContactRelation(AccountId = acc.Id, ContactId = con.Id, FinServ__SourceSystemId__c = '');
        insert acr1;
        list<id> listacr = new list<id>{acr1.id};
        Test.startTest();
        system.runAs(us){
            CIBE_AccExtAccConRel_Batch btch = new CIBE_AccExtAccConRel_Batch(listacr);
            Database.executeBatch(btch);
        }  
        test.stopTest();
        system.assertEquals([SELECT FinServ__SourceSystemId__c, isDirect from AccountContactRelation WHERE FinServ__SourceSystemId__c != null AND IsDirect = false].size(),1, 'Se debería haber modificado el registro con externalId y Indirect to false');
    }
}