force-app/main/default/objects/Account/fields/CC_Email__c.field-meta.xml
<CustomField>
    <fullName>CC_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SAC_Accion__c/SAC_Accion__c.object-meta.xml
<CustomObject>
    <description>Objeto juntion entre el Maestro de acciones y el objeto Case creando una relación acción-reclamación/pretensión, para el proyecto de SAC Reclamaciones.</description>
    <label>Acción</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Nombre</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Acciones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_CaseReclamante__c/SAC_CaseReclamante__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado en el proyecto SAC para almacenar los reclamantes de una Reclamación.</description>
    <label>Reclamante</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Código reclamante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_CaseReclamante__c/fields/SAC_Case__c.field-meta.xml
<CustomField>
    <fullName>SAC_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Caso relacionado al reclamante.</description>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Reclamantes</relationshipLabel>
    <relationshipName>Reclamantes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SPV_HandlerWithoutSharingMethods.cls
public without sharing class SPV_HandlerWithoutSharingMethods {

    @AuraEnabled
    public static void actualizarReclamanteNoClienteWithoutSharing(String caseId, String accountId){
        try{
            List<SAC_CaseReclamante__c> reclamantes = new List<SAC_CaseReclamante__c>();
            Case casoActual;
            Account cuentaActual;
            Contact contactActual;

            if(caseId != null) {
                casoActual = [SELECT Id, AccountId FROM Case WHERE id =: caseId LIMIT 1];
                reclamantes = [SELECT Id FROM SAC_CaseReclamante__c WHERE SAC_Case__c =: caseId];
            }
            if(accountId != null && accountId != '') {
                cuentaActual = [SELECT Id, CC_Email__c, Name FROM Account WHERE Id =: accountId LIMIT 1];
                contactActual = [SELECT Id FROM Contact WHERE AccountId =: accountId LIMIT 1];
            } 
            
            if(reclamantes.isEmpty()){
                casoActual.AccountId = cuentaActual.Id;
                casoActual.ContactId = contactActual.Id;
                update casoActual;
            }
            else{
                SPV_LCMP_BusquedaCliente.crearReclamanteSecundario(accountId, accountId, caseId);
            }
        }
        catch (Exception e) {CBK_Log.error(e);throw new AuraHandledException(e.getMessage());}
    }

    public static void insertarAccionShare(SAC_Accion__c tarea) {
        List<SAC_Accion__Share> accionesShare = new List<SAC_Accion__Share>();
                    accionesShare.add(new SAC_Accion__Share(
                            ParentId = tarea.Id,
                            UserOrGroupId = userInfo.getUserId(),
                            AccessLevel = 'Edit'
                        ));
        Database.insert(accionesShare);
    }

}