force-app/main/default/objects/Account/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_DominioMail__c.field-meta.xml
<CustomField>
    <fullName>SEG_DominioMail__c</fullName>
    <description>Dominio del e-mail asociado a la empresa</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Dominio de e-mail</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SEG_Zona__c.field-meta.xml
<CustomField>
    <fullName>SEG_Zona__c</fullName>
    <description>Determina la &apos;Zona&apos; a la que pertenece el caso. Se trata de un campo que depende del campo &apos;Organización&apos;</description>
    <label>Zona</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SEG_Organizacion__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Corporativa</fullName>
            </value>
            <value>
                <fullName>Créditos Sindicados</fullName>
            </value>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>Empresas Andalucía</fullName>
            </value>
            <value>
                <fullName>Empresas Andalucía Occidental-Extremadura</fullName>
                <isActive>false</isActive>
                <label>Empresas Andalucía Occidental-Extremadura</label>
            </value>
            <value>
                <fullName>Empresas Andalucía Oriental</fullName>
                <isActive>false</isActive>
                <label>Empresas Andalucía Oriental</label>
            </value>
            <value>
                <fullName>Empresas Baleares</fullName>
            </value>
            <value>
                <fullName>Empresas Barcelona</fullName>
            </value>
            <value>
                <fullName>Empresas Canarias</fullName>
            </value>
            <value>
                <fullName>Empresas Castilla La Mancha</fullName>
            </value>
            <value>
                <fullName>Empresas Castilla y León</fullName>
            </value>
            <value>
                <fullName>Empresas Cataluña</fullName>
            </value>
            <value>
                <fullName>Empresas Ebro</fullName>
            </value>
            <value>
                <fullName>Empresas Madrid</fullName>
            </value>
            <value>
                <fullName>Empresas Murcia</fullName>
            </value>
            <value>
                <fullName>Empresas Norte</fullName>
            </value>
            <value>
                <fullName>Empresas Valencia</fullName>
            </value>
            <value>
                <fullName>ESB</fullName>
                <isActive>false</isActive>
                <label>ESB</label>
            </value>
            <value>
                <fullName>Export Finance</fullName>
            </value>
            <value>
                <fullName>Instituciones Canarias</fullName>
            </value>
            <value>
                <fullName>Instituciones Cataluña</fullName>
            </value>
            <value>
                <fullName>Instituciones Catalunya</fullName>
                <isActive>false</isActive>
                <label>Instituciones Catalunya</label>
            </value>
            <value>
                <fullName>Instituciones Centro</fullName>
            </value>
            <value>
                <fullName>Instituciones Este</fullName>
            </value>
            <value>
                <fullName>Instituciones Norte</fullName>
            </value>
            <value>
                <fullName>Instituciones Sur</fullName>
            </value>
            <value>
                <fullName>Oficinas Representación</fullName>
            </value>
            <value>
                <fullName>Operaciones</fullName>
            </value>
            <value>
                <fullName>Seguimiento</fullName>
            </value>
            <value>
                <fullName>Soporte</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CC_ClienteSEG.recordType-meta.xml
<RecordType>
    <fullName>CC_ClienteSEG</fullName>
    <active>true</active>
    <description>Record Type para clientes manuales de Segmentos</description>
    <label>Cliente (Segmentos)</label>
</RecordType>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <description>Número de documento de identidad proporcionado para la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Número de documento de identidad proporcionado para la creación del caso</inlineHelpText>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Grupo__c.field-meta.xml
<CustomField>
    <fullName>SEG_Grupo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Grupo asignado al caso</description>
    <label>Grupo de trabajo</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>CC_Grupo_Colaborador__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Grupo colaborador, Grupo Operativo Segmentos</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Cliente (SEG), Seguimiento</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Cases (Grupo)</relationshipLabel>
    <relationshipName>SEG_Grupo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Numero_de_centro__c.field-meta.xml
<CustomField>
    <fullName>SEG_Numero_de_centro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nombre de centro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Número de centro)</relationshipLabel>
    <relationshipName>SEG_Numero_de_centro</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SEG_Subestado__c.field-meta.xml
<CustomField>
    <fullName>SEG_Subestado__c</fullName>
    <label>Subestado</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subestado1</fullName>
            </value>
            <value>
                <fullName>Pendiente aplicación reglas de CR</fullName>
            </value>
            <value>
                <fullName>Pendiente clasificación Cognitive</fullName>
            </value>
            <value>
                <fullName>Pendiente asignación grupo por MCC</fullName>
            </value>
            <value>
                <fullName>Pendiente asignación de propietario</fullName>
            </value>
            <value>
                <fullName>Pendiente valija</fullName>
            </value>
            <value>
                <fullName>Incongruencia reglas de clasificación</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Reactivada por comunicación de cliente</fullName>
            </value>
            <value>
                <fullName>Incidencia Valija</fullName>
            </value>
            <value>
                <fullName>Casos vinculados pendientes</fullName>
            </value>
            <value>
                <fullName>Contratos pendientes</fullName>
            </value>
            <value>
                <fullName>En canal BPO</fullName>
            </value>
            <value>
                <fullName>En canal Valija</fullName>
            </value>
            <value>
                <fullName>En canal Valija pendiente recepción justificantes</fullName>
            </value>
            <value>
                <fullName>En colaborador</fullName>
            </value>
            <value>
                <fullName>En Gestor Operativo de la empresa</fullName>
            </value>
            <value>
                <fullName>Por agrupación</fullName>
            </value>
            <value>
                <fullName>Tareas finalizadas</fullName>
            </value>
            <value>
                <fullName>Por gestor</fullName>
            </value>
            <value>
                <fullName>Lista negra</fullName>
            </value>
            <value>
                <fullName>Por duplicidad</fullName>
            </value>
            <value>
                <fullName>Por comunicación de cliente</fullName>
            </value>
            <value>
                <fullName>Planificado manualmente</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Recibida respuesta Colaborador</fullName>
            </value>
            <value>
                <fullName>Pendiente Robot</fullName>
            </value>
            <value>
                <fullName>Envío cierre Cliente</fullName>
            </value>
            <value>
                <fullName>Envío cierre Colaborador</fullName>
            </value>
            <value>
                <fullName>Envío pendiente respuesta Cliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SEG_Cliente.recordType-meta.xml
<RecordType>
    <fullName>SEG_Cliente</fullName>
    <active>true</active>
    <businessProcess>SEG_Clientes</businessProcess>
    <label>Cliente (SEG)</label>
</RecordType>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/OS_Negocio__c.field-meta.xml
<CustomField>
    <fullName>OS_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CSI_Bankia</fullName>
            </value>
            <value>
                <fullName>GRR</fullName>
            </value>
            <value>
                <fullName>HDT</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>SEGMENTOS</fullName>
            </value>
            <value>
                <fullName>SPV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SEG_envio_a_TaskConnect__c.field-meta.xml
<CustomField>
    <fullName>SEG_envio_a_TaskConnect__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CheckBox que indica si el Grupo pertenece a TaskConnect</description>
    <label>Envío a TaskConnect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SEG_GrupoSegmentos__c.field-meta.xml
<CustomField>
    <fullName>SEG_GrupoSegmentos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Grupo Segmentos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/SEG_Tipologia__c.field-meta.xml
<CustomField>
    <fullName>SEG_Tipologia__c</fullName>
    <label>Tipología</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CSO</fullName>
            </value>
            <value>
                <fullName>Firmas</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>CSO FFEE</fullName>
            </value>
            <value>
                <fullName>BO FFEE</fullName>
            </value>
            <value>
                <fullName>CSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/recordTypes/SEG_GrupoOperativoSegmentos.recordType-meta.xml
<RecordType>
    <fullName>SEG_GrupoOperativoSegmentos</fullName>
    <active>true</active>
    <label>Grupo Operativo Segmentos</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/classes/SEG_WS_Cognitive_FFEE_Test.cls
@isTest
public class SEG_WS_Cognitive_FFEE_Test {
@testSetup
    static void datosIniciales() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
            User thisUser = new User(
                alias = 'tsegmen',
                email = 'testSEGBI@acme.com',
                emailencodingkey = 'UTF-8',
                lastname = 'Smith',
                languagelocalekey = 'en_US',
                localesidkey = 'en_US',
                profileid = [SELECT Id FROM Profile WHERE Name= 'System administrator'].Id,
                userroleid = [SELECT Id FROM UserRole WHERE Name = 'Segmentos + FFEE'].Id,
                timezonesidkey ='America/Los_Angeles',
                username ='testSEGBI@acme.com'
            );
            insert thisUser;

            List<PermissionSetAssignment> listPermissionSetAssignment = new List<PermissionSetAssignment>();
            for (PermissionSetGroupComponent permisoUnitario : [SELECT PermissionSetGroupId, PermissionSetId, PermissionSet.Name
                                                                FROM PermissionSetGroupComponent
                                                                WHERE PermissionSetGroup.DeveloperName IN ('SEG_Operativo','SEG_Supervisor')]) {
                PermissionSetAssignment nuevoPermiso = new PermissionSetAssignment();
                nuevoPermiso.PermissionSetId = permisoUnitario.PermissionSetId;
                nuevoPermiso.AssigneeId = thisUser.id;
                listPermissionSetAssignment.add(nuevoPermiso);
            }
            if (listPermissionSetAssignment.isEmpty()) {
                insert listPermissionSetAssignment;
            }
        }

        Set<String> objetos = new Set<String>{'CC_Grupo_Colaborador__c'};
		Map<String,Map<String,Schema.RecordTypeInfo>> rtObjetos = SEG_GetRT.getRecordTypesObjects(objetos);
		 Id grupoOpSegId = rtObjetos.get('CC_Grupo_Colaborador__c').get('SEG_GrupoOperativoSegmentos').getRecordTypeId();
        
        List<CC_Grupo_Colaborador__c> lstGruposCol = new List<CC_Grupo_Colaborador__c>();
            CC_Grupo_Colaborador__c grupoColab = new CC_Grupo_Colaborador__c();
            grupoColab.Name = 'GrupoColabSeg';
            grupoColab.SEG_Tipologia__c = 'BO';
            grupoColab.RecordTypeId = grupoOpSegId;
            grupoColab.SEG_GrupoSegmentos__c = true;
            grupoColab.SEG_envio_a_TaskConnect__c = true;
            grupoColab.OS_Negocio__c = 'SEGMENTOS';
            lstGruposCol.add(grupoColab);
        
        CC_Grupo_Colaborador__c grupoRTGrupoCol = new CC_Grupo_Colaborador__c();
            grupoRTGrupoCol.Name='Grupo Colaborador';
            grupoRTGrupoCol.RecordTypeId = grupoOpSegId;
            grupoRTGrupoCol.SEG_envio_a_TaskConnect__c = true;
            grupoRTGrupoCol.SEG_GrupoSegmentos__c = true;
            grupoRTGrupoCol.OS_Negocio__c = 'SEGMENTOS';
            lstGruposCol.add(grupoRTGrupoCol);
        
        insert lstGruposCol;


        Account cuentaSEG1 = new Account();
        cuentaSEG1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CC_ClienteSEG').getRecordTypeId();
        cuentaSEG1.Name = 'Empresa segmentos';
        cuentaSEG1.SEG_DominioMail__c = '@cuentaSEG';
        cuentaSEG1.CC_Numero_Documento__c = '11111171H';
        insert cuentaSEG1;
        
        // Crear contactos para cuentas SEG.
        Contact contactoSEG1 = new Contact();
        contactoSEG1.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('CC_Cliente').getRecordTypeId();
        contactoSEG1.LastName = 'Contacto SEG 1';
        contactoSEG1.AccountId = cuentaSEG1.Id;
        contactoSEG1.Email = 'test@test.com';
        insert contactoSEG1;
        
        Case caso = new Case(
            AccountId = cuentaSEG1.id,
            SEG_Numero_de_centro__c = cuentaSEG1.id,
            RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('SEG_Cliente').getRecordTypeId(),
            SEG_Grupo__c = grupoColab.id,
            Origin = 'Email',
            CC_Canal_Procedencia__c = 'Formulario web',
            Status = 'Activo',
            SEG_Subestado__c = 'En curso',
            SEG_Zona__c = 'Corporativa',
            SEG_Organizacion__C = 'Banca Corporativa',
            Subject = 'test 2',
            ContactId = contactoSEG1.Id
        );
        insert caso;
        
        // CR
        SEG_ClasificacionRapida__c clasRapida = new SEG_ClasificacionRapida__c(
            name = 'Test CR',
            SEG_Nombre_CR_Cognitive__c = 'Credit Cards',
            SEG_Canaldeentrada__c = 'Email',
            CBK_Negocio__c = 'Segmentos',
            SEG_Organizacion__C = 'Banca Corporativa'
        );
        insert clasRapida;
    }

	@isTest
    public static void clasificarCasoConOwnerIndicado() {
        User usuarioTest = [SELECT Id, Profile.Name, UserRole.Name FROM User WHERE Username = 'testSEGBI@acme.com' LIMIT 1];
        
        Case caso = [SELECT Id, CaseNumber, Status, SEG_Subestado__c FROM Case LIMIT 1];

        SEG_WS_Cognitive_FFEE.Input datosEntrada = new SEG_WS_Cognitive_FFEE.Input();
        
		datosEntrada.pkCodSr = String.valueOf(caso.CaseNumber);
        datosEntrada.pkIdSalesforce = String.valueOf(caso.Id);
        datosEntrada.model = '';
        datosEntrada.hasAttachments = true;
        datosEntrada.category = '';
        
        // Inicializar la lista de categorías
        datosEntrada.categories = new List<SEG_WS_Cognitive_FFEE.Categorias>();
        
        // Crear instancias de la clase Categorias
        SEG_WS_Cognitive_FFEE.Categorias category1 = new SEG_WS_Cognitive_FFEE.Categorias();
        category1.category = 'Category1';
        category1.prob = '0.95';
        
        SEG_WS_Cognitive_FFEE.Categorias category2 = new SEG_WS_Cognitive_FFEE.Categorias();
        category2.category = 'Category2';
        category2.prob = '0.85';
        
        // Añadir las categorías a la lista
        datosEntrada.categories.add(category1);
        datosEntrada.categories.add(category2);

        //datosEntrada.ContenidoAdicional
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/clasificarCasoFFEE/*';
        req.httpMethod = 'PUT';
        req.requestBody = Blob.valueOf(JSON.serialize(datosEntrada));
        RestContext.request = req;
        RestContext.response = res;
        System.runAs (usuarioTest) {
            Test.startTest();
            	SEG_WS_Cognitive_FFEE.Output output =  SEG_WS_Cognitive_FFEE.clasificarCaso();
            Test.stopTest();
            
        System.assertNotEquals(null, output, 'El output no debe ser nulo');
        }
    }
    
    @isTest
    public static void clasificarCasoCrNoExistente() {
        User usuarioTest = [SELECT Id, Profile.Name, UserRole.Name FROM User WHERE Username = 'testSEGBI@acme.com' LIMIT 1];
        
        List<Group> colasBO = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'SEG_BO' ];
        Case caso = [SELECT Id, CaseNumber, Status, SEG_Subestado__c FROM Case LIMIT 1];
        caso.OwnerId = colasBO[0].id;
        update caso;

        SEG_WS_Cognitive_FFEE.Input datosEntrada = new SEG_WS_Cognitive_FFEE.Input();
        
		datosEntrada.pkCodSr = String.valueOf(caso.CaseNumber);
        datosEntrada.pkIdSalesforce = String.valueOf(caso.Id);
        datosEntrada.model = '';
        datosEntrada.hasAttachments = true;
        datosEntrada.category = 'TestNoExiste';
        
        // Inicializar la lista de categorías
        datosEntrada.categories = new List<SEG_WS_Cognitive_FFEE.Categorias>();
        
        // Crear instancias de la clase Categorias
        SEG_WS_Cognitive_FFEE.Categorias category1 = new SEG_WS_Cognitive_FFEE.Categorias();
        category1.category = 'Category1';
        category1.prob = '0.95';
        
        SEG_WS_Cognitive_FFEE.Categorias category2 = new SEG_WS_Cognitive_FFEE.Categorias();
        category2.category = 'Category2';
        category2.prob = '0.85';
        
        // Añadir las categorías a la lista
        datosEntrada.categories.add(category1);
        datosEntrada.categories.add(category2);

        //datosEntrada.ContenidoAdicional
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/clasificarCasoFFEE/*';
        req.httpMethod = 'PUT';
        req.requestBody = Blob.valueOf(JSON.serialize(datosEntrada));
        RestContext.request = req;
        RestContext.response = res;
        System.runAs (new User(Id = UserInfo.getUserId())) {
            Test.startTest();
            	SEG_WS_Cognitive_FFEE.Output output =  SEG_WS_Cognitive_FFEE.clasificarCaso();
            Test.stopTest();
            
        // Assert para verificar el resultado
        System.assertNotEquals(null, output, 'El output no debe ser nulo');      
        }
    }
        
    @isTest
    public static void clasificarCasoConOwnerNoIndicado() {
        User usuarioTest = [SELECT Id, Profile.Name, UserRole.Name FROM User WHERE Username = 'testSEGBI@acme.com' LIMIT 1];
        
        List<Group> colasBO = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'SEG_BO' ];
        Case caso = [SELECT Id, CaseNumber, Status, SEG_Subestado__c FROM Case LIMIT 1];
        caso.OwnerId = colasBO[0].id;
        update caso;
        
        SEG_WS_Cognitive_FFEE.Input datosEntrada = new SEG_WS_Cognitive_FFEE.Input();
        
		datosEntrada.pkCodSr = String.valueOf(caso.CaseNumber);
        datosEntrada.pkIdSalesforce = String.valueOf(caso.Id);
        datosEntrada.model = '';
        datosEntrada.hasAttachments = true;
        datosEntrada.category = 'Credit Cards';
        
        // Inicializar la lista de categorías
        datosEntrada.categories = new List<SEG_WS_Cognitive_FFEE.Categorias>();
        
        // Crear instancias de la clase Categorias
        SEG_WS_Cognitive_FFEE.Categorias category1 = new SEG_WS_Cognitive_FFEE.Categorias();
        category1.category = 'Category1';
        category1.prob = '0.95';
        
        SEG_WS_Cognitive_FFEE.Categorias category2 = new SEG_WS_Cognitive_FFEE.Categorias();
        category2.category = 'Category2';
        category2.prob = '0.85';
        
        // Añadir las categorías a la lista
        datosEntrada.categories.add(category1);
        datosEntrada.categories.add(category2);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/clasificarCasoFFEE/*';
        req.httpMethod = 'PUT';
        req.requestBody = Blob.valueOf(JSON.serialize(datosEntrada));
        RestContext.request = req;
        RestContext.response = res;
        System.runAs(usuarioTest) {
            Test.startTest();
            	SEG_WS_Cognitive_FFEE.Output output =  SEG_WS_Cognitive_FFEE.clasificarCaso();
            Test.stopTest();
            
        // Assert para verificar el resultado
        System.assertNotEquals(null, output, 'El output no debe ser nulo'); 
        }
    }
    
        @isTest
    public static void clasificarCasoSinCategoria() {
        User usuarioTest = [SELECT Id, Profile.Name, UserRole.Name FROM User WHERE Username = 'testSEGBI@acme.com' LIMIT 1];
        
        List<Group> colasBO = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'SEG_BO' ];
        Case caso = [SELECT Id, CaseNumber, Status, SEG_Subestado__c FROM Case LIMIT 1];
        caso.OwnerId = colasBO[0].id;
        update caso;
        
        SEG_WS_Cognitive_FFEE.Input datosEntrada = new SEG_WS_Cognitive_FFEE.Input();
        
		datosEntrada.pkCodSr = String.valueOf(caso.CaseNumber);
        datosEntrada.pkIdSalesforce = String.valueOf(caso.Id);
        datosEntrada.model = '';
        datosEntrada.hasAttachments = true;
        datosEntrada.category = '';
        
        // Inicializar la lista de categorías
        datosEntrada.categories = new List<SEG_WS_Cognitive_FFEE.Categorias>();
        
        // Crear instancias de la clase Categorias
        SEG_WS_Cognitive_FFEE.Categorias category1 = new SEG_WS_Cognitive_FFEE.Categorias();
        category1.category = 'Category1';
        category1.prob = '0.95';
        
        SEG_WS_Cognitive_FFEE.Categorias category2 = new SEG_WS_Cognitive_FFEE.Categorias();
        category2.category = 'Category2';
        category2.prob = '0.85';
        
        // Añadir las categorías a la lista
        datosEntrada.categories.add(category1);
        datosEntrada.categories.add(category2);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/clasificarCasoFFEE/*';
        req.httpMethod = 'PUT';
        req.requestBody = Blob.valueOf(JSON.serialize(datosEntrada));
        RestContext.request = req;
        RestContext.response = res;
        System.runAs (usuarioTest) {
            Test.startTest();
            	SEG_WS_Cognitive_FFEE.Output output =  SEG_WS_Cognitive_FFEE.clasificarCaso();
            Test.stopTest();
            
        // Assert para verificar el resultado
        System.assertNotEquals(null, output, 'El output no debe ser nulo'); 
        }
    }
    
    @isTest
    public static void clasificarCasoSinCaso() {
        User usuarioTest = [SELECT Id, Profile.Name, UserRole.Name FROM User WHERE Username = 'testSEGBI@acme.com' LIMIT 1];
        
        SEG_WS_Cognitive_FFEE.Input datosEntrada = new SEG_WS_Cognitive_FFEE.Input();
        
		datosEntrada.pkCodSr = String.valueOf('');
        datosEntrada.pkIdSalesforce = String.valueOf('');
        datosEntrada.model = '';
        datosEntrada.hasAttachments = true;
        datosEntrada.category = '';
        
        // Inicializar la lista de categorías
        datosEntrada.categories = new List<SEG_WS_Cognitive_FFEE.Categorias>();
        
        // Crear instancias de la clase Categorias
        SEG_WS_Cognitive_FFEE.Categorias category1 = new SEG_WS_Cognitive_FFEE.Categorias();
        category1.category = 'Category1';
        category1.prob = '0.95';
        
        SEG_WS_Cognitive_FFEE.Categorias category2 = new SEG_WS_Cognitive_FFEE.Categorias();
        category2.category = 'Category2';
        category2.prob = '0.85';
        
        // Añadir las categorías a la lista
        datosEntrada.categories.add(category1);
        datosEntrada.categories.add(category2);

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/clasificarCasoFFEE/*';
        req.httpMethod = 'PUT';
        req.requestBody = Blob.valueOf(JSON.serialize(datosEntrada));
        RestContext.request = req;
        RestContext.response = res;
        System.runAs (usuarioTest) {
            Test.startTest();
            	SEG_WS_Cognitive_FFEE.Output output =  SEG_WS_Cognitive_FFEE.clasificarCaso();
            Test.stopTest();
            
        // Assert para verificar el resultado
        System.assertNotEquals(null, output, 'El output no debe ser nulo'); 
        }
    }
}