force-app/main/default/objects/Account/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo colaborador</label>
    <referenceTo>CC_Grupo_Colaborador__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>NumPerso de la cuenta</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Cola_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Cola_Procedencia__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cola de Procedencia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Detalles_Consulta__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalles_Consulta__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalles consulta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Detalles_Solucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Detalles_Solucion__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Detalles solución</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Grupo_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>CC_Grupo_Colaborador__c</fullName>
    <description>Nos guardamos el grupo colaborador al que se traslada para reporting</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Grupo Colaborador</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_ProdServ__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_ProdServ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto / Servicio del caso</description>
    <inlineHelpText>Producto / Servicio del caso</inlineHelpText>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <filterItems>
            <field>$Source.CC_MCC_Tematica__c</field>
            <operation>equals</operation>
            <valueField>CC_MCC__c.CC_Tematica__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Referéncia Externa Producto/Servicio)</relationshipLabel>
    <relationshipName>ProdServ</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso proporcionado en la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>NumPerso proporcionado en la creación del caso</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Producto/Servicio (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <defaultValue>&apos;Cliente&apos;</defaultValue>
    <description>Campo para indicar si el contacto es cliente o empleado.</description>
    <label>Tipología cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
                <default>true</default>
                <label>Cliente</label>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor</fullName>
            </value>
            <value>
                <fullName>No Cliente</fullName>
            </value>
            <value>
                <fullName>Prescriptor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SACH_Cliente.recordType-meta.xml
<RecordType>
    <fullName>SACH_Cliente</fullName>
    <active>true</active>
    <businessProcess>SACH_Support_Process</businessProcess>
    <label>Cliente (SACH)</label>
</RecordType>

force-app/main/default/objects/CC_Grupo_Colaborador__c/CC_Grupo_Colaborador__c.object-meta.xml
<CustomObject>
    <label>Grupo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/CC_Tipo_cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_cliente__c</fullName>
    <label>Tipo cliente</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/fields/OS_Negocio__c.field-meta.xml
<CustomField>
    <fullName>OS_Negocio__c</fullName>
    <label>Negocio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>COPS</fullName>
            </value>
            <value>
                <fullName>CSI_Bankia</fullName>
            </value>
            <value>
                <fullName>GRR</fullName>
            </value>
            <value>
                <fullName>HDT</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>SEGMENTOS</fullName>
            </value>
            <value>
                <fullName>SPV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Grupo_Colaborador__c/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Fecha_Vigencia_Inicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Fecha_Vigencia_Inicio__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Fecha de inicio de vigencia</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio vigencia</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerso</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/classes/SACH_EmailService01_Test.cls
@isTest
public class SACH_EmailService01_Test {

    @TestSetup
    public static void crearDatosPrueba() {


        CC_Grupo_Colaborador__c grupoColaborador = new CC_Grupo_Colaborador__c();
        grupoColaborador.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Grupo_Colaborador__c', 'CC_CentroCaixaBank');
        grupoColaborador.OS_Negocio__c = 'CC';
        grupoColaborador.Name = 'Oficina01';
        insert grupoColaborador;

        Account cuenta = new Account();
        cuenta.Name = 'Cuenta01';
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_Cliente'); 
        
        insert cuenta;

        Account cuenta2 = new Account();
        cuenta2.Name = 'Cuenta02';
        cuenta2.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_CentroCaixaBank'); 
        
        insert cuenta2;

        Contact contacto = new Contact();
        contacto.FirstName = 'Contacto01';
        contacto.LastName = 'Contacto01';
        contacto.CC_NumPerso__c = '25345561';
        contacto.AccountId = cuenta.Id;
        contacto.CC_Idioma__c = 'Es';
        contacto.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Empleado');
        contacto.Email = 'test@example.com';
        insert contacto;

        Contact contacto3 = new Contact();
        contacto3.FirstName = 'Contacto03';
        contacto3.LastName = 'Contacto03';
        contacto3.CC_NumPerso__c = '25345563';
        contacto3.AccountId = cuenta.Id;
        contacto3.CC_Idioma__c = 'Es';
        contacto3.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
        contacto3.Email = 'CGE_BUSTIA2@FAKE.COM';
        insert contacto3;

        Contact contacto2 = new Contact();
        contacto2.FirstName = 'Contacto02';
        contacto2.LastName = 'Contacto02';
        contacto2.CC_NumPerso__c = '25345562';
        contacto2.AccountId = cuenta2.Id;
        contacto2.CC_Idioma__c = 'Es';
        contacto2.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Empleado');
        contacto2.Email = 'CGE_BUSTIA22@FAKE.COM';
        
        insert contacto2;
        
        Group grp = new Group();
        grp.Name = 'Buzón Valores';
        insert grp;
        
        CC_MCC__c tematica = new CC_MCC__c();
		tematica.Name = 'tematica cops test';
        tematica.CC_Tipo_Cliente__c = 'Cliente (CAM)/Empleado (CAM)';
        tematica.CC_Fecha_Vigencia_Inicio__c = System.now();
        tematica.RecordTypeId = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
        tematica.CC_Codigo_Externo__c = 'TEC-000001';
        insert tematica;

        CC_MCC__c producto = new CC_MCC__c();
        producto.Name = 'producto cops test';
        producto.CC_Tipo_Cliente__c = 'Cliente (CAM)/Empleado (CAM)';
        producto.CC_Fecha_Vigencia_Inicio__c = System.now();
        producto.RecordTypeId = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
        producto.CC_Tematica__c = tematica.Id;
        producto.CC_Codigo_Externo__c = 'PRC-000001'; 
        insert producto;
        
        CC_MCC__c motivo = new CC_MCC__c();
        motivo.Name = 'motivo cops test';
        motivo.CC_Tipo_Cliente__c = 'Cliente (CAM)/Empleado (CAM)';
        motivo.CC_Fecha_Vigencia_Inicio__c = System.now();
        motivo.RecordTypeId = Schema.getGlobalDescribe().get('CC_MCC__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();
        motivo.CC_Tematica__c = tematica.Id;
        motivo.CC_Producto_Servicio__c = producto.Id;
        motivo.CC_Codigo_Externo__c = 'MOC-000001';
        insert motivo;

        Case caso = new Case();
        caso.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'SACH_Cliente');
        caso.Subject = 'Caso SACH_EmailService_Test';
        caso.Origin = 'Chat';
        caso.Status = 'Activo';
        caso.AccountId = cuenta.Id;
        caso.ContactId = contacto.Id;
        caso.CC_Canal_Procedencia__c='SACH';
        //caso.CC_Cola_Procedencia__c='AM_Buzon_Carteras';
        caso.CC_Idioma__c = 'es';
        caso.CC_Detalles_Consulta__c = 'Detalles consulta';
        caso.CC_Detalles_Solucion__c = 'Detalles solución';
        caso.CC_MCC_Tematica__c = tematica.Id;
        caso.CC_MCC_ProdServ__c = producto.Id;
        caso.CC_MCC_Motivo__c = motivo.Id;
        insert caso;
                      
        Case caso2 = new Case();
        caso2.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'SACH_Cliente');
        caso2.Subject = 'caso2 SACH_EmailService_Test';
        caso2.Origin = 'Email';
        caso2.Status = 'Activo';
        caso2.OS_Remitente_Inicial__c = 'CGE_BUSTIA22@FAKE.COM';
        caso2.AccountId = cuenta.Id;
        caso2.ContactId = contacto2.Id;
        caso2.CC_Canal_Procedencia__c='SACH';
        caso2.CC_Cola_Procedencia__c='AM_Buzon_Valores';
        caso2.CC_Idioma__c = 'es';
        caso2.CC_Detalles_Consulta__c = 'Detalles consulta';
        caso2.CC_Detalles_Solucion__c = 'Detalles solución';
        caso2.CC_MCC_Tematica__c = tematica.Id;
        caso2.CC_MCC_ProdServ__c = producto.Id;
        caso2.CC_MCC_Motivo__c = motivo.Id;
        caso2.CC_Referencia_Correo_Saliente__c = CC_EmailMessage.generarReferenciaCorreoSaliente();
        insert caso2;

        Task tarea = new Task();
        tarea.RecordTypeId=CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'SACH_Task');
        tarea.Type = 'Traslado Colaborador';
        tarea.WhatId=caso2.Id;
        tarea.CC_Referencia_Correo_Saliente__c='20210371164838';
        insert tarea;
    }

    @isTest
    public static void testCorreoEntrante() {

        System.runAs(new User(Id = UserInfo.getUserId())) {

        Case caso = [SELECT Id,CC_Canal_Procedencia__c FROM Case WHERE Subject=:'Caso SACH_EmailService_Test' LIMIT 1];
        
        Task tarea2 = new Task();
        tarea2.RecordTypeId=CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'SACH_Task');
        tarea2.Type = 'Remitir Colaborador';
        tarea2.WhatId=caso.Id;
        tarea2.CC_Referencia_Correo_Saliente__c='1610385724430';
        insert tarea2;

        HDT_Correos_Buzones_Entrada__mdt correoCAMmdt = [SELECT HDT_Email_Redireccion_Buzon__c FROM HDT_Correos_Buzones_Entrada__mdt WHERE HDT_Canal_Procedencia__c='Incidencias Técnicas'];
        
        //Crear un InboundEnvelope e InboundEmail de entrada
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        Messaging.InboundEmail.Header header = new Messaging.InboundEmail.Header();
		header.value = 'hello';
        header.name = 'HEADER DE PRUEBA';
        envelope.fromAddress = 'CGE_BUSTIA@FAKE.COM';
        envelope.toAddress = correoCAMmdt.HDT_Email_Redireccion_Buzon__c;
        correo.subject = 'asunto';
        correo.fromAddress = 'CGE_BUSTIA@FAKE.COM';
        correo.plainTextBody = 'email body #@n2225256325# nTitle .';
        //correo.plainTextBody = 'email body\n2225256325\nTitle .';
        correo.toAddresses =  new List<String>{'bluewolf.devcam.test@gmail.com'};
        //correo.htmlBody = 'email body\n#@SEG:1610385724410#\n#@SEG:1610473621456# 03928088';
		correo.htmlBody = 'email body\n#@1610385724430#\n#@SEG:1610473621456# 03928088';
        //Adjuntos binarios
        Messaging.InboundEmail.BinaryAttachment adjuntoBinario1 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario1.body = blob.valueOf('my attachment text');
        adjuntoBinario1.fileName = 'textfileone.txt';
        adjuntoBinario1.mimeTypeSubType = 'text/plain';
        adjuntoBinario1.headers = new List<Messaging.InboundEmail.Header>{header};

        Messaging.InboundEmail.BinaryAttachment adjuntoBinario2 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario2.body = blob.valueOf('my attachment text 2');
        adjuntoBinario2.fileName = 'text2fileone.txt';
        adjuntoBinario2.mimeTypeSubType = 'text/plain';
        
        correo.binaryAttachments = new List<Messaging.inboundEmail.BinaryAttachment>{adjuntoBinario1, adjuntoBinario2};
        
		//Adjunto de texto
		Messaging.InboundEmail.TextAttachment adjuntoTexto = new Messaging.InboundEmail.TextAttachment();
        adjuntoTexto.body = 'my attachment text';
        adjuntoTexto.fileName = 'textfiletwo3.txt';
        adjuntoTexto.mimeTypeSubType = 'texttwo/plain';
        correo.textAttachments = new List<Messaging.inboundEmail.TextAttachment>{adjuntoTexto};

        test.startTest();
        SACH_EmailService emailServiceCAM = new SACH_EmailService();
        emailServiceCAM.handleInboundEmail(correo, envelope);
        test.stopTest();

        List<Case> casoCreado = [SELECT Id, RecordType.DeveloperName, ContactId FROM Case WHERE OS_Remitente_Inicial__c = 'CGE_BUSTIA22@FAKE.COM' LIMIT 1];
        List<Contact> contactoAsociado= [SELECT Id FROM Contact WHERE FirstName = 'Contacto02'];
        List<Task> tareaAsociada= [SELECT Id,Type FROM Task WHERE CC_Referencia_Correo_Saliente__c IN ('1610385724430')];
        System.assertEquals('Remitir Colaborador', tareaAsociada[0].Type, 'El RT del caso no es correcto');
        System.assertEquals('SACH_Cliente', casoCreado[0].RecordType.DeveloperName, 'El RT del caso no es correcto');
        System.assertEquals(contactoAsociado[0].Id, casoCreado[0].ContactId, 'El RT del caso no es correcto');
        System.assert(caso.Id<>null);

        Task t2 = [SELECT WhatId, Type, CC_Referencia_Correo_Saliente__c FROM Task WHERE Id = :tarea2.Id];
        System.assertEquals('1610385724430', t2.CC_Referencia_Correo_Saliente__c, 'Task t1 not updated correctly');
         System.assertEquals('Remitir Colaborador', t2.Type, 'Task t2 not updated correctly');
       
        }
    }
     @isTest
    public static void testCorreoEntrante2() {
        
        System.runAs(new User(Id = UserInfo.getUserId())) {

        Case caso = [SELECT Id,CC_Canal_Procedencia__c FROM Case WHERE Subject=:'caso2 SACH_EmailService_Test' LIMIT 1];
        
        Task tarea2 = new Task();
        tarea2.RecordTypeId=CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'SACH_Task');
        tarea2.Type = 'Solicitud Información';
        tarea2.WhatId=caso.Id;
        tarea2.CC_Referencia_Correo_Saliente__c='1610385724420';
        insert tarea2;

        HDT_Correos_Buzones_Entrada__mdt correoCAMmdt = [SELECT HDT_Email_Redireccion_Buzon__c FROM HDT_Correos_Buzones_Entrada__mdt WHERE HDT_Canal_Procedencia__c='Incidencias Técnicas'];
        
        //Crear un InboundEnvelope e InboundEmail de entrada
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        Messaging.InboundEmail.Header header = new Messaging.InboundEmail.Header();
		header.value = 'hello';
        header.name = 'HEADER DE PRUEBA';
        envelope.fromAddress = 'CGE_BUSTIA@FAKE.COM';
        envelope.toAddress = correoCAMmdt.HDT_Email_Redireccion_Buzon__c;
        correo.subject = 'asunto';
        //correo.plainTextBody = 'email body #@n2225256325# nTitle .';
        correo.fromAddress = 'CGE_BUSTIA@FAKE.COM';
        //correo.plainTextBody = 'email body\n2225256325\nTitle Por favor, mantenga las siguientes referencias al responder a este correo electrónico: #@20210371164838#.';
        correo.toAddresses =  new List<String>{'bluewolf.devcam.test@gmail.com'};
		correo.htmlBody = 'email body\n#@1610385724420#\n#@SEG:1610473621456# 03928088';

        //Adjuntos binarios
        Messaging.InboundEmail.BinaryAttachment adjuntoBinario1 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario1.body = blob.valueOf('my attachment text');
        adjuntoBinario1.fileName = 'textfileone.txt';
        adjuntoBinario1.mimeTypeSubType = 'text/plain';
        adjuntoBinario1.headers = new List<Messaging.InboundEmail.Header>{header};

        Messaging.InboundEmail.BinaryAttachment adjuntoBinario2 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario2.body = blob.valueOf('my attachment text 2');
        adjuntoBinario2.fileName = 'text2fileone.txt';
        adjuntoBinario2.mimeTypeSubType = 'text/plain';
        
        correo.binaryAttachments = new List<Messaging.inboundEmail.BinaryAttachment>{adjuntoBinario1, adjuntoBinario2};
        
		//Adjunto de texto
		Messaging.InboundEmail.TextAttachment adjuntoTexto = new Messaging.InboundEmail.TextAttachment();
        adjuntoTexto.body = 'my attachment text';
        adjuntoTexto.fileName = 'textfiletwo3.txt';
        adjuntoTexto.mimeTypeSubType = 'texttwo/plain';
        correo.textAttachments = new List<Messaging.inboundEmail.TextAttachment>{adjuntoTexto};

        test.startTest();
        SACH_EmailService emailServiceCAM = new SACH_EmailService();
        emailServiceCAM.handleInboundEmail(correo, envelope);
        test.stopTest();

        List<Case> casoCreado = [SELECT Id, RecordType.DeveloperName, ContactId FROM Case WHERE OS_Remitente_Inicial__c = 'CGE_BUSTIA22@FAKE.COM' LIMIT 1];
        List<Contact> contactoAsociado= [SELECT Id FROM Contact WHERE FirstName = 'Contacto02'];
        List<Task> tareaAsociada= [SELECT Id,Type FROM Task WHERE CC_Referencia_Correo_Saliente__c IN ('1610385724420')];
        System.assertEquals('Solicitud Información', tareaAsociada[0].Type, 'El RT del caso no es correcto');
        System.assertEquals('SACH_Cliente', casoCreado[0].RecordType.DeveloperName, 'El RT del caso no es correcto');
        System.assertEquals(contactoAsociado[0].Id, casoCreado[0].ContactId, 'El RT del caso no es correcto');
        System.assert(caso.Id<>null);

        Task t2 = [SELECT WhatId, Type, CC_Referencia_Correo_Saliente__c FROM Task WHERE Id = :tarea2.Id];
        System.assertEquals('1610385724420', t2.CC_Referencia_Correo_Saliente__c, 'Task t1 not updated correctly');
         System.assertEquals('Solicitud Información', t2.Type, 'Task t2 not updated correctly');
        }
    }

    @isTest
    public static void testCorreoEntrante3() {       
        System.runAs(new User(Id = UserInfo.getUserId())) {

        HDT_Correos_Buzones_Entrada__mdt correoCAMmdt = [SELECT HDT_Email_Redireccion_Buzon__c FROM HDT_Correos_Buzones_Entrada__mdt WHERE HDT_Canal_Procedencia__c = 'Incidencias Técnicas'];
        
        //Crear un InboundEnvelope e InboundEmail de entrada
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        Messaging.InboundEmail.Header header = new Messaging.InboundEmail.Header();
		header.value = 'hello';
        header.name = 'HEADER DE PRUEBA';
        envelope.fromAddress = 'CGE_BUSTIA2@FAKE.COM';
        envelope.toAddress = correoCAMmdt.HDT_Email_Redireccion_Buzon__c;
        correo.subject = 'asunto';
        correo.fromAddress = 'CGE_BUSTIA2@FAKE.COM';
        correo.plainTextBody = 'email body\n2225256325\nTitle Por favor, mantenga las siguientes referencias al responder a este correo electrónico:';//' #@20210371164838#.';
        correo.toAddresses =  new List<String>{'bluewolf.devcam.test@gmail.com'};
		correo.htmlBody = 'email body\n#@1610385724410#\n#@SEG:1610473621456# 03928088';

        //Adjuntos binarios
        Messaging.InboundEmail.BinaryAttachment adjuntoBinario1 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario1.body = blob.valueOf('my attachment text');
        adjuntoBinario1.fileName = 'textfileone.txt';
        adjuntoBinario1.mimeTypeSubType = 'text/plain';
        adjuntoBinario1.headers = new List<Messaging.InboundEmail.Header>{header};

        Messaging.InboundEmail.BinaryAttachment adjuntoBinario2 = new Messaging.InboundEmail.BinaryAttachment();
        adjuntoBinario2.body = blob.valueOf('my attachment text 2');
        adjuntoBinario2.fileName = 'text2fileone.txt';
        adjuntoBinario2.mimeTypeSubType = 'text/plain';
        
        correo.binaryAttachments = new List<Messaging.inboundEmail.BinaryAttachment>{adjuntoBinario1, adjuntoBinario2};
        
		//Adjunto de texto
		Messaging.InboundEmail.TextAttachment adjuntoTexto = new Messaging.InboundEmail.TextAttachment();
        adjuntoTexto.body = 'my attachment text';
        adjuntoTexto.fileName = 'textfiletwo3.txt';
        adjuntoTexto.mimeTypeSubType = 'texttwo/plain';
        correo.textAttachments = new List<Messaging.inboundEmail.TextAttachment>{adjuntoTexto};

        case caso2 = [SELECT Id, RecordType.DeveloperName, ContactId FROM Case WHERE OS_Remitente_Inicial__c = 'CGE_BUSTIA22@FAKE.COM' LIMIT 1];

        Task tarea1 = new Task();
        tarea1.RecordTypeId=CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'SACH_Task');
        tarea1.Type = 'Traslado Colaborador';
        tarea1.WhatId=caso2.Id;
        tarea1.CC_Referencia_Correo_Saliente__c='1610385724410';
        insert tarea1;

        


        test.startTest();
        SACH_EmailService emailServiceCAM = new SACH_EmailService();
        emailServiceCAM.handleInboundEmail(correo, envelope);


        test.stopTest();
        
        List<Case> casoCreado = [SELECT Id, RecordType.DeveloperName, ContactId FROM Case WHERE OS_Remitente_Inicial__c = 'CGE_BUSTIA22@FAKE.COM' LIMIT 1];
        List<Contact> contactoAsociado= [SELECT Id FROM Contact WHERE FirstName = 'Contacto02'];
        List<Task> tareaAsociada= [SELECT Id,Type FROM Task WHERE CC_Referencia_Correo_Saliente__c IN ('1610385724410')];


        System.assertEquals('Traslado Colaborador', tareaAsociada[0].Type, 'El RT del caso no es correcto');
       
        System.assertEquals('SACH_Cliente', casoCreado[0].RecordType.DeveloperName, 'El RT del caso no es correcto');
        System.assertEquals(contactoAsociado[0].Id, casoCreado[0].ContactId, 'El RT del caso no es correcto');

        // Verify the results using assertions
       Task t1 = [SELECT WhatId, Type, CC_Referencia_Correo_Saliente__c FROM Task WHERE Id = :tarea1.Id];
       System.assertEquals('1610385724410', t1.CC_Referencia_Correo_Saliente__c, 'Task t1 not updated correctly');
        System.assertEquals('Traslado Colaborador', t1.Type, 'Task t1 not updated correctly');

        }
        
    }

    @isTest
    private static void testConTareaTrasladoColab() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
        Case caso = new Case();
        caso.RecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByDeveloperName().get('SACH_Cliente').getRecordTypeId();
        caso.Subject = 'Caso Test';
        caso.AccountId = [SELECT Id FROM Account WHERE Name = 'Cuenta01'].Id;
        caso.ContactId = [SELECT Id FROM Contact WHERE LastName = 'Contacto01'].Id;
        insert caso;

        Task tarea = new Task();
        tarea.recordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Task', 'SACH_Task');
        tarea.Type = 'Traslado Colaborador';
        tarea.Subject = 'Traslado Colaborador';
        tarea.WhatId = caso.Id;
        tarea.Status = 'Open';
        tarea.CC_Referencia_Correo_Saliente__c = 'n2225256325';
        tarea.CC_Grupo_Colaborador_Id__c = [SELECT Id FROM CC_Grupo_Colaborador__c WHERE Name = 'Oficina01'].Id;
        tarea.ActivityDate = System.today();
        insert tarea;

        
       HDT_Correos_Buzones_Entrada__mdt buzonSach = [SELECT HDT_Email_Redireccion_Buzon__c FROM HDT_Correos_Buzones_Entrada__mdt WHERE HDT_Canal_Procedencia__c = 'Incidencias Técnicas'];

        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        envelope.fromAddress = 'direccionFrom@test.com';
        envelope.toAddress = buzonSach.HDT_Email_Redireccion_Buzon__c;
        Messaging.InboundEmail correo = new Messaging.InboundEmail() ;
        correo.subject = 'asunto';
        correo.fromAddress = 'test@test.COM';
        correo.plainTextBody = 'email body #@n2225256325# nTitle .';
        correo.toAddresses =  new List<String>{'devsach.test@gmail.com'};
        correo.htmlBody = 'email body\n#@SEG:1610385724410#\n#@SEG:1610473621456# 03928088';


        Test.startTest();
        SACH_EmailService emailService = new SACH_EmailService();
        Messaging.InboundEmailResult result = emailService.handleInboundEmail(correo, envelope);
        Test.stopTest();

        Map<Account, List<Contact>> mapaCuentasContactos = SACH_Identificacion_Auto.identificarCliente('Email', 'test@example.com');
       //System.assertEquals(1, mapaCuentasContactos.size());
    //System.assertEquals(1, mapaCuentasContactos.values()[0].size());

		System.assert(result.success, 'Resultado incorrecto');
        }
    }

    @IsTest
    static void testIdentificarCliente() {
        System.runAs(new User(Id = UserInfo.getUserId())) {
        // Crear una cuenta con un contacto que tenga el email del remitente
        Account account = new Account(Name = 'Test Account');
        insert account;
        Contact contact = new Contact(FirstName = 'Contacto01',LastName = 'Contacto01',AccountId = account.Id, Email = 'testn@example.com',RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Empleado'));
        insert contact;
        
        // Crear otro contacto que no tenga el email del remitente
        Contact contact2 = new Contact(FirstName = 'Contacto02',LastName = 'Contacto02',AccountId = account.Id, Email = 'another@example.com');
        insert contact2;

        // Llamar al método identificarCliente para el email de prueba
        Map<Account, List<Contact>> mapaCuentasContactos = SACH_Identificacion_Auto.identificarCliente('Email', 'testn@example.com');
        
        // Verificar que se identificó correctamente la cuenta y contacto
        //System.assertEquals(1, mapaCuentasContactos.size());
        //System.assertEquals(1, mapaCuentasContactos.values()[0].size());
        //System.assertEquals(account.Id, mapaCuentasContactos.keySet()[0].Id);
        //System.assertEquals(contact.Id, mapaCuentasContactos.values()[0][0].Id);

        //0035E000033B5aTQAS, Actual: 0035E000033B5PtQAK
        //0035E000033B5gBQAS, Actual: 0035E000033B5g7QAC
        }
    }

}