force-app/main/default/objects/Account/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>NumPerso de la cuenta</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/CBK_OTP_Generado__c.object-meta.xml
<CustomObject>
    <label>OTP Generado</label>
    <nameField>
        <displayFormat>OTP-{0000}</displayFormat>
        <label>OTP Generado Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OTP Generados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Codigo_OTP__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código OTP</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Fecha_Codigo_OTP__c.field-meta.xml
<CustomField>
    <fullName>CBK_Fecha_Codigo_OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha Código OTP</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CBK_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OTP Generados</relationshipLabel>
    <relationshipName>OTP_Generados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor2__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Estado__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>Activa</fullName>
                <default>true</default>
                <label>Activa</label>
            </value>
            <value>
                <fullName>Pendiente Interno</fullName>
            </value>
            <value>
                <fullName>Pendiente Cita</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Pendiente Cliente</fullName>
            </value>
            <value>
                <fullName>Con Venta</fullName>
                <isActive>false</isActive>
                <label>Con Venta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSBD_Delete_OTP_Batch_Test.cls
/**********************************************************************************************************************
Name:     CSBD_Delete_OTP_Batch_Test
Copyright © 2022  CaixaBank
=======================================================================================================================
Proposito: Clase test de la clase CSBD_Delete_OTP_Batch
=======================================================================================================================
Historial
---------------------
VERSION     USER_STORY      AUTHOR              DATE                Description
1.0         App CSBD        Esperanza Conde     09/06/2022          Init version
***********************************************************************************************************************/
@isTest
public with sharing class CSBD_Delete_OTP_Batch_Test {
    
    @testSetup static void setup() {
        User usuarioGestor = CSBD_Usuarios.usuarioGestor();

        Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Particular').getRecordTypeId();
        Id rtListaValores = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByName().get('Lista de valores').getRecordTypeId();
        Id rtValores = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByName().get('Valor').getRecordTypeId();
        Id rtChatId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Chat').getRecordTypeId();
        Id rtOTPId = Schema.SObjectType.CBK_OTP_Generado__c.getRecordTypeInfosByName().get('Chat').getRecordTypeId();
        List<Opportunity> lstOpp = new List<Opportunity>();
        
        Account cliente = new Account(
            FirstName = 'OLGA',
            LastName = 'ROBLES GEA',
            RecordTypeId = rt,
            CC_NumPerso__c = '16849239'
        );
        
        insert cliente;
        //Insertamos la lista de valores
        CC_Lista_Valores__c listValoresHorario = new CC_Lista_Valores__c();
        listValoresHorario.Name = 'CSBD: Relación de valores Now - Salesforce: Turno';
        listValoresHorario.CC_Activa__c = true;
        listValoresHorario.RecordTypeId = rtListaValores;
        
        insert listValoresHorario;
        
        CC_Lista_Valores__c valoresHorario = new CC_Lista_Valores__c();
        valoresHorario.Name = '08-10h';
        valoresHorario.RecordTypeId = rtValores;
        valoresHorario.CC_Lista__c = listValoresHorario.Id;
        valoresHorario.CC_Valor__c = 'Mañana';
        valoresHorario.CC_Valor2__c = '08:00 - 10:00';
        valoresHorario.CC_Valor2__c = '8';
        
        insert valoresHorario;
        
        //Insertamos la lista de valores
        CC_Lista_Valores__c listValoresProducto = new CC_Lista_Valores__c();
        listValoresProducto.Name = 'CSBD: Relación de valores Now - Salesforce: Empresa, familia y producto';
        listValoresProducto.CC_Activa__c = true;
        listValoresProducto.RecordTypeId = rtListaValores;
        
        insert listValoresProducto;
        
        CC_Lista_Valores__c valoresProducto = new CC_Lista_Valores__c();
        valoresProducto.Name = 'Prestamo Online';
        valoresProducto.RecordTypeId = rtValores;
        valoresProducto.CC_Lista__c = listValoresProducto.Id;
        valoresProducto.CC_Valor__c = 'Préstamos';
        valoresProducto.CC_Valor2__c = 'Genérico';
        valoresProducto.CC_Valor2__c = 'CaixaBank';
        valoresProducto.CC_Activa__c = true;
        
        insert valoresProducto;
        
        Opportunity opp1 = new Opportunity(
            Name = 'Chat CSBD',
            StageName = 'Solicitud',
            RecordTypeId = rtChatId,
            CSBD_Estado__c = 'Nueva',
            AccountId = cliente.Id
        );
        
        lstOpp.add(opp1);

        Opportunity opp2 = new Opportunity(
            Name = 'Chat CSBD',
            StageName = 'Solicitud',
            RecordTypeId = rtChatId,
            CSBD_Estado__c = 'Nueva',
            AccountId = cliente.Id
        );
        
        lstOpp.add(opp2);

        Opportunity opp3 = new Opportunity(
            Name = 'Chat CSBD',
            StageName = 'Solicitud',
            RecordTypeId = rtChatId,
            CSBD_Estado__c = 'Nueva',
            AccountId = cliente.Id
        );
        
        lstOpp.add(opp3);

        insert lstOpp;

        CBK_OTP_Generado__c otp = new CBK_OTP_Generado__c();
        otp.CBK_Codigo_OTP__c = '11111111111'; 
        otp.CBK_Fecha_Codigo_OTP__c = DateTime.NOW().addHours(1);
        otp.CBK_Oportunidad__c = opp2.Id;
        otp.recordtypeId = rtOTPId;

        CBK_OTP_Generado__c otp2 = new CBK_OTP_Generado__c();
        otp2.CBK_Codigo_OTP__c = '11111111112'; 
        otp2.CBK_Fecha_Codigo_OTP__c = DateTime.NOW().addHours(1);
        otp2.CBK_Oportunidad__c = opp3.Id;
        otp2.recordtypeId = rtOTPId;

        List<CBK_OTP_Generado__c> lstOTP = new List<CBK_OTP_Generado__c>();
        lstOTP.add(otp);
        lstOTP.add(otp2);

        insert lstOTP;

   }

    /** 
     * Probamos el borrado de los OTP generados
    */
    @isTest static void testComprobarBorrado(){
        User usuarioGestor = [SELECT Id FROM User WHERE FirstName = 'GestorCSBD' AND Profile.Name = 'CSBD Gestor' LIMIT 1];

        System.runAs (usuarioGestor) {
            List<CBK_OTP_Generado__c> lstOTP = [Select Id from CBK_OTP_Generado__c];
            system.assertEquals(2, lstOTP.size(), 'Comprobamos que al principio hay 2.');

            Test.startTest();
            CSBD_Delete_OTP_Batch obj = new CSBD_Delete_OTP_Batch();
            DataBase.executeBatch(obj); 
            Test.stopTest();

            List<CBK_OTP_Generado__c> lstOTPFinal = [Select Id from CBK_OTP_Generado__c];
            system.assertEquals(0, lstOTPFinal.size(), 'Comprobamos que se borran los 2.');
        }
    }

}