force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Case/fields/CBK_Case_Extension_Id__c.field-meta.xml
<CustomField>
    <fullName>CBK_Case_Extension_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Field to Case Extension object</description>
    <label>Case Extension Id</label>
    <referenceTo>CBK_Case_Extension__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <description>Número de documento de identidad proporcionado para la creación del caso</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Número de documento de identidad proporcionado para la creación del caso</inlineHelpText>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <businessProcess>CC_Clientes</businessProcess>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/CBK_Case_Extension__c/CBK_Case_Extension__c.object-meta.xml
<CustomObject>
    <description>Extension Object related to Case object</description>
    <label>Case Extension</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Extension Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cases Extension</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_IntegrationSetting__c/CBK_IntegrationSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CBK Integration Setting</label>
</CustomObject>

force-app/main/default/objects/CBK_IntegrationSetting__c/fields/NamedCredential__c.field-meta.xml
<CustomField>
    <fullName>NamedCredential__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_IntegrationSetting__c/fields/RegistroTrazaIntegracion__c.field-meta.xml
<CustomField>
    <fullName>RegistroTrazaIntegracion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox para indicar si la integración ha de dejar registro en el objeto de traza de integración CC_Traza_Int (por defecto estará desactivado)</description>
    <label>Registro Traza Integración</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Mensajes_Mostrar__c.field-meta.xml
<CustomField>
    <fullName>CC_Mensajes_Mostrar__c</fullName>
    <description>Utilizado para mostrar mensajes largos</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Mensajes a mostrar</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor2__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Lista_Valores.recordType-meta.xml
<RecordType>
    <fullName>CC_Lista_Valores</fullName>
    <active>true</active>
    <label>Lista de valores</label>
</RecordType>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Valor.recordType-meta.xml
<RecordType>
    <fullName>CC_Valor</fullName>
    <active>true</active>
    <label>Valor</label>
</RecordType>

force-app/main/default/classes/CC_WS_Onboarding_Test.cls
@isTest
public class CC_WS_Onboarding_Test {
    @TestSetup
    static void makeData() {
        User usuarioAdmin = CC_TestDataFactory.insertUserAdmin();

        System.runAs(usuarioAdmin) {
            User operador = CC_TestDataFactory.insertUserOperadorCliente('');

            CBK_IntegrationSetting__c customSetting = new CBK_IntegrationSetting__c();
            customSetting.Name = 'CC_Onboarding';
            customSetting.NamedCredential__c = 'callout:API_GWT_TST/assetProductsBackofficeOperations/cbpo02/v1/teamworks/webservices/GDS707A/ConsultaEstadoSolicitud.tws';
            customSetting.RegistroTrazaIntegracion__c = true;
            insert customSetting;

            Id idCCListaValores = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Lista_Valores');
            Id idCCValor = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Valor');
            Id idCCValorSubestado = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_ValorSubestado');

            CC_Lista_Valores__c listaVal = new CC_Lista_Valores__c();
            listaVal.Name = 'testMatrizOnboarding';
            listaVal.CC_Activa__c = true;
            listaVal.RecordTypeId = idCCListaValores;
            insert listaVal;

            List<CC_Lista_Valores__c> listavalores = new List<CC_Lista_Valores__c>();
            CC_Lista_Valores__c val1 = new CC_Lista_Valores__c();
            val1.Name = 'testclienteyaexistente';
            val1.CC_Activa__c = true;
            val1.RecordTypeId = idCCValor;
            val1.CC_Lista__c = listaVal.Id;
            val1.CC_Valor2__c = 'Motivo Cierre';
            val1.CC_Mensajes_Mostrar__c = 'testmensajemotivocierre';
            listavalores.add(val1);

            CC_Lista_Valores__c val2 = new CC_Lista_Valores__c();
            val2.Name = 'testvalidacionvideo';
            val2.CC_Activa__c = true;
            val2.RecordTypeId = idCCValor;
            val2.CC_Lista__c = listaVal.Id;
            val2.CC_Valor2__c = 'Estado';
            listavalores.add(val2);
            insert listavalores;

            CC_Lista_Valores__c val3 = new CC_Lista_Valores__c();
            val3.Name = 'testvalidacionvideoSubestado';
            val3.CC_Activa__c = true;
            val3.RecordTypeId = idCCValorSubestado;
            val3.CC_Lista__c = val2.Id;
            val3.CC_Valor2__c = 'Subestado';
            val3.CC_Mensajes_Mostrar__c = 'testmensajesubestado';
            insert val3;
        }

        
    }

    @isTest
    public static void testOK() {
        Test.setMock(HttpCalloutMock.class, new CC_WS_Mock_Onboarding(200));
        String mensajeIntegracion;
        System.runAs(CC_TestDataFactory.getUserOperadorCliente()) {
            Account cuenta = new Account();
            cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_ClientePA');
            cuenta.FirstName = 'Cuenta';
            cuenta.LastName = 'Prueba';
            cuenta.CC_Numero_Documento__c = '29053641H';
            insert cuenta;

            Case caso = new Case();
            caso.AccountId = cuenta.Id;
            caso.Subject = 'Caso Prueba';
            caso.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'CC_Cliente');
            insert caso;
            
            Test.startTest();
                mensajeIntegracion = CC_WS_Onboarding.recuperarCliente(caso.Id, caso.Account.CC_Numero_Documento__c);
            Test.stopTest();
        }
        System.assertNotEquals('El cliente no esta en proceso de Onboarding', mensajeIntegracion);
    }

    @isTest
    public static void testOK2() {
        Test.setMock(HttpCalloutMock.class, new CC_WS_Mock_Onboarding(200));
        String mensajeIntegracion;
        System.runAs(CC_TestDataFactory.getUserOperadorCliente()) {
            CBK_Case_Extension__c caseExtension = new CBK_Case_Extension__c();
            insert caseExtension;

            Case caso = new Case();
            caso.Subject = 'Caso Prueba 2';
            caso.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Case', 'CC_Cliente');
            caso.CBK_Case_Extension_Id__c = caseExtension.Id;
            insert caso;

            Test.startTest();
                mensajeIntegracion = CC_WS_Onboarding.recuperarClienteOnboarding(caso.Id, '77788590F');
            Test.stopTest();
        }
        System.assertNotEquals('El cliente no esta en proceso de Onboarding', mensajeIntegracion);
    }

    @isTest
    public static void matrizmotivoCierreTest() {
        List<String> lstString = new List<String>();
        String result = '';
        System.runAs(CC_TestDataFactory.getUserOperadorCliente()) {
            Test.startTest();
                result = CC_WS_Onboarding.matrizOnboarding('testvalidacionvideo', 'testvalidacionvideoSubestado', 'testclienteyaexistente');
            Test.stopTest();
        }
        System.assertEquals('testmensajemotivocierre', result, 'No se ha recogido el mensaje');
    }

    @isTest
    public static void matrizEstadoTest() {
        List<String> lstString = new List<String>();
        String result = '';
        System.runAs(CC_TestDataFactory.getUserOperadorCliente()) {
            Test.startTest();
                result = CC_WS_Onboarding.matrizOnboarding('testvalidacionvideo', 'testvalidacionvideoSubestado', '');
            Test.stopTest();
        }
        System.assertEquals('testmensajesubestado', result, 'No se ha recogido el mensaje');
    }
}