force-app/main/default/objects/Account/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de centro</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AV_UsuarioAsociado__c.field-meta.xml
<CustomField>
    <fullName>AV_UsuarioAsociado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario Asociado</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Oficina__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Oficina__c</fullName>
    <formula>Account.CC_Numero_Oficina__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número Oficina</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador de CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CIBE_HomeOportVencEMP_Controller_Test.cls
/**********************************************************************************************************************
Name:     CIBE_HomeOportVencEMP_Controller_Test
Copyright © 2022  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito: Class Test of CIBE_HomeOportVencEMP_Controller
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
    VERSION  USER_STORY				AUTHOR			DATE            Description
    1.0      Initial				Bea     		17/11/2023      Init version

***********************************************************************************************************************/
    @isTest
    public class CIBE_HomeOportVencEMP_Controller_Test {
        
        @TestSetup
        static void setup(){
            List <String> ps = new list<String>{CIBE_AppConstants.CIBE_OPERATIVACIB,CIBE_AppConstants.CIBE_CUSTOMMETADATA,CIBE_AppConstants.CIBE_ANALYTICS,CIBE_AppConstants.CIBE_OPERATIVAEMP};
            CIBE_TestInitialSetup.setupInitialData(null, null, null, null, null, ps);
            User usrSetup = [SELECT Id FROM User WHERE AV_ExternalID__c = 'U0000000' LIMIT 1];
            User managerUser = [SELECT Id FROM User WHERE AV_ExternalID__c = 'U0000001' LIMIT 1];
            
            System.runAs(usrSetup) {
                Contact employee = [SELECT Id FROM Contact WHERE Account.Name = '00001 - CENTER' LIMIT 1];
                employee.AV_UsuarioAsociado__c = managerUser.Id;
                update(employee);
                Account acc = [SELECT Id FROM Account WHERE CC_Numero_Oficina__c = '00001' LIMIT 1];
                Date today = Date.today();
                Opportunity opp = CIBE_TestHelper.createOpportunityWithEmpleado(acc, employee, 'CIBE_Vencido', today, null, managerUser.Id);
            }
        }
    
        @isTest
        public static void opportunitiesTest() {
            User managerUser = [SELECT Id, name, AV_ExternalId__c FROM User WHERE AV_ExternalID__c = 'U0000001' LIMIT 1];
    
            System.runAs(managerUser) {
    
                Test.startTest();
                List<CIBE_HomeOportVencEMP_Controller.Wrapper> results = CIBE_HomeOportVencEMP_Controller.homeOppVencidas();
                System.assert(!results.isEmpty());
                Test.stopTest();
            }
        }  
        
    }