force-app/main/default/objects/Account/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <description>NumPerso de la cuenta</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>NumPerso de la cuenta</inlineHelpText>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/CBK_OTP_Generado__c.object-meta.xml
<CustomObject>
    <label>OTP Generado</label>
    <nameField>
        <displayFormat>OTP-{0000}</displayFormat>
        <label>OTP Generado Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OTP Generados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Codigo_OTP__c.field-meta.xml
<CustomField>
    <fullName>CBK_Codigo_OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código OTP</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Fecha_Codigo_OTP__c.field-meta.xml
<CustomField>
    <fullName>CBK_Fecha_Codigo_OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha Código OTP</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_OTP_Generado__c/fields/CBK_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CBK_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OTP Generados</relationshipLabel>
    <relationshipName>OTP_Generados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor2__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CC_NumPerso__c.field-meta.xml
<CustomField>
    <fullName>CC_NumPerso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>NumPerso</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Tipo_Chat_Transcript</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CSBD_Now_Codigo_Producto__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Now_Codigo_Producto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código producto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CSBD_Oportunidad_Id__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Oportunidad_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transcripciones de chat</relationshipLabel>
    <relationshipName>Transcripciones_de_chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CSBD_OTP_Chat__c.field-meta.xml
<CustomField>
    <fullName>CSBD_OTP_Chat__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OTP Chat</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Estado__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
            </value>
            <value>
                <fullName>Activa</fullName>
                <default>true</default>
                <label>Activa</label>
            </value>
            <value>
                <fullName>Pendiente Interno</fullName>
            </value>
            <value>
                <fullName>Pendiente Cita</fullName>
            </value>
            <value>
                <fullName>Cerrada</fullName>
            </value>
            <value>
                <fullName>Rechazada</fullName>
            </value>
            <value>
                <fullName>Pendiente Cliente</fullName>
            </value>
            <value>
                <fullName>Con Venta</fullName>
                <isActive>false</isActive>
                <label>Con Venta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Now_Codigo_Producto__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Now_Codigo_Producto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Código de producto</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSBD_LiveChatTriggerHelper_Test.cls
/**********************************************************************************************************************
Name:     CSBD_LiveChatTriggerHelper_Test
Copyright © 2022  CaixaBank
=======================================================================================================================
Proposito: Clase test de la clase CSBD_LiveChatTranscriptTriggerHelper
=======================================================================================================================
Historial
---------------------
VERSION     USER_STORY      AUTHOR              DATE                Description
1.0         App CSBD        Esperanza Conde     02/02/2022          Init version
***********************************************************************************************************************/
@isTest
public with sharing class CSBD_LiveChatTriggerHelper_Test {
    
    @testSetup static void setup() {

    	Id rt = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cliente Particular').getRecordTypeId();
        Id rtListaValores = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByName().get('Lista de valores').getRecordTypeId();
        Id rtValores = Schema.SObjectType.CC_Lista_Valores__c.getRecordTypeInfosByName().get('Valor').getRecordTypeId();
       	Id rtChatId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Chat').getRecordTypeId();
        
        Account cliente = new Account(
            FirstName = 'OLGA',
            LastName = 'ROBLES GEA',
            RecordTypeId = rt,
            CC_NumPerso__c = '16849239'
        );
        
        insert cliente;
        //Insertamos la lista de valores
        CC_Lista_Valores__c listValoresHorario = new CC_Lista_Valores__c();
        listValoresHorario.Name = 'CSBD: Relación de valores Now - Salesforce: Turno';
        listValoresHorario.CC_Activa__c = true;
        listValoresHorario.RecordTypeId = rtListaValores;
        
        insert listValoresHorario;
        
        CC_Lista_Valores__c valoresHorario = new CC_Lista_Valores__c();
        valoresHorario.Name = '08-10h';
        valoresHorario.RecordTypeId = rtValores;
        valoresHorario.CC_Lista__c = listValoresHorario.Id;
        valoresHorario.CC_Valor__c = 'Mañana';
        valoresHorario.CC_Valor2__c = '08:00 - 10:00';
        valoresHorario.CC_Valor2__c = '8';
        
        insert valoresHorario;
        
        //Insertamos la lista de valores
        CC_Lista_Valores__c listValoresProducto = new CC_Lista_Valores__c();
        listValoresProducto.Name = 'CSBD: Relación de valores Now - Salesforce: Empresa, familia y producto';
        listValoresProducto.CC_Activa__c = true;
        listValoresProducto.RecordTypeId = rtListaValores;
        
        insert listValoresProducto;
        
        CC_Lista_Valores__c valoresProducto = new CC_Lista_Valores__c();
        valoresProducto.Name = 'Prestamo Online';
        valoresProducto.RecordTypeId = rtValores;
        valoresProducto.CC_Lista__c = listValoresProducto.Id;
        valoresProducto.CC_Valor__c = 'Préstamos';
        valoresProducto.CC_Valor2__c = 'Genérico';
        valoresProducto.CC_Valor2__c = 'CaixaBank';
        valoresProducto.CC_Activa__c = true;
        
        insert valoresProducto;
        
        Opportunity opp = new Opportunity(
            Name = 'Chat CSBD',
            StageName = 'Solicitud',
            RecordTypeId = rtChatId,
            CSBD_Estado__c = 'Nueva',
            AccountId = cliente.Id
        );
        
        insert opp;
        
        CBK_OTP_Generado__c otp = new CBK_OTP_Generado__c();
        otp.CBK_Codigo_OTP__c = '11111111111'; 
        otp.CBK_Fecha_Codigo_OTP__c = DateTime.NOW().addHours(1);
        otp.CBK_Oportunidad__c = opp.Id;
        
        insert otp;

   }

   /** 
     * Cambiar el owner de la oportunidad al traspasar el chat a otro agente
    */
    @isTest static void cambiarOwner(){
        LiveChatVisitor liveChatVisitor = new LiveChatVisitor();
        insert liveChatVisitor;

        LiveChatTranscript transcript = new LiveChatTranscript();
        transcript.CC_Tipo__c = 'CSBD';
        transcript.CSBD_OTP_Chat__c = '11111111111';
        transcript.LiveChatVisitorId = liveChatVisitor.Id;
        insert transcript;
        
        User agente = CSBD_Usuarios.usuarioAdministrador();
        System.runAs (agente) {
            transcript.OwnerId = agente.Id;
            Test.startTest();
            update transcript;
            Test.stopTest();

            List<Opportunity> oportunidades = [SELECT Id FROM Opportunity where OwnerId =: agente.Id];
            
            System.assertEquals(1, oportunidades.size());
        }
    }

    /** 
     * Probamos la asignacion del RT segun el tipo de la transcripción y la creacion correcta con el OTP
    */
    @isTest static void testAsignarRT(){

        Account cliente = [Select id from Account where CC_NumPerso__c = '16849239'];

        LiveChatVisitor liveChatVisitor = new LiveChatVisitor();
        insert liveChatVisitor;

        LiveChatTranscript transcript = new LiveChatTranscript();
        transcript.CC_Tipo__c = 'CSBD';
        transcript.CSBD_OTP_Chat__c = '11111111111';
        transcript.LiveChatVisitorId = liveChatVisitor.Id;
        transcript.CSBD_Now_Codigo_Producto__c = 'Prestamo Online';
        
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Test.startTest();
            insert transcript;
            Test.stopTest();
            
            LiveChatTranscript transcriptUpdate = [Select RecordTypeId, AccountId, CSBD_Oportunidad_Id__c from LiveChatTranscript where Id = :transcript.Id];
            Id rtChatId = Schema.SObjectType.LiveChatTranscript.getRecordTypeInfosByName().get('Gestor').getRecordTypeId();

            system.assertEquals(rtChatId, transcriptUpdate.RecordTypeId, 'Comprobamos coincide el rt de la transcripción.');
            system.assertEquals(cliente.Id, transcriptUpdate.AccountId, 'Comprobamos coincide el cliente de la transcripción.');
            system.assert(transcriptUpdate.CSBD_Oportunidad_Id__c != Null, 'Comprobamos coincide la opp de la transcripción.');
            
            List<Task> lstTarea = [Select Id, Subject from Task where WhatId = :transcriptUpdate.CSBD_Oportunidad_Id__c];
            Task tarea = lstTarea.get(0);
            
            system.assertEquals('Conversación con agente chat',tarea.Subject, 'Comprobamos coincide el asunto de la tarea.');
        }
    }

    /** 
     * Probamos error de que no introducen el OTP
    */
    @isTest static void testValidaOTPNullError(){

        LiveChatVisitor liveChatVisitor = new LiveChatVisitor();
        insert liveChatVisitor;

        LiveChatTranscript transcript = new LiveChatTranscript();
        transcript.CC_Tipo__c = 'CSBD';
        transcript.LiveChatVisitorId = liveChatVisitor.Id;

        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Test.startTest();
            Database.SaveResult result = Database.insert(transcript, false);
            Test.stopTest();
            
            system.assert(result.getErrors()[0].getMessage().contains('Es necesario obtener el sessionId para conectar.'), 'Comprobamos el mensaje de error.');
        }
    }
    
    /** 
     * Probamos error de que no coincide el OTP
    */
    @isTest static void testValidaOTPError(){

        CBK_OTP_Generado__c otp = [Select id, CBK_Fecha_Codigo_OTP__c from CBK_OTP_Generado__c where CBK_Codigo_OTP__c = '11111111111'];

        otp.CBK_Fecha_Codigo_OTP__c = DateTime.now().addHours(-1);
        update otp;
        
        LiveChatVisitor liveChatVisitor = new LiveChatVisitor();
        insert liveChatVisitor;

        LiveChatTranscript transcript = new LiveChatTranscript();
        transcript.CC_Tipo__c = 'CSBD';
        transcript.CSBD_OTP_Chat__c = '11111111111';
        transcript.LiveChatVisitorId = liveChatVisitor.Id;

        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Test.startTest();
            Database.SaveResult result = Database.insert(transcript, false);
            Test.stopTest();
            
            system.assert(result.getErrors()[0].getMessage().contains('Transcurrido el tiempo de validez de la sesión. Por favor, solicita de nuevo el SessionId.'), 'Comprobamos el mensaje de error.');
        }
    }

}