force-app/main/default/objects/Account/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Agente__c.field-meta.xml
<CustomField>
    <fullName>CC_Agente__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que indica si los casos se deben pasa a agente (que entren en la cola de Comentarios Apps y estado Activo), en caso contrario que queden cerrados y sin contar SLA.</description>
    <label>Entra a Agente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Lista_Valores.recordType-meta.xml
<RecordType>
    <fullName>CC_Lista_Valores</fullName>
    <active>true</active>
    <label>Lista de valores</label>
</RecordType>

force-app/main/default/objects/CC_Lista_Valores__c/recordTypes/CC_Valor.recordType-meta.xml
<RecordType>
    <fullName>CC_Valor</fullName>
    <active>true</active>
    <label>Valor</label>
</RecordType>

force-app/main/default/objects/CC_Llamada__c/CC_Llamada__c.object-meta.xml
<CustomObject>
    <label>Llamada</label>
    <nameField>
        <displayFormat>L-{00000000}</displayFormat>
        <label>Llamada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Llamadas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Agente__c.field-meta.xml
<CustomField>
    <fullName>CC_Agente__c</fullName>
    <description>Nombre de usuario en Genesys</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Agente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_ConnId__c.field-meta.xml
<CustomField>
    <fullName>CC_ConnId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ConnId llamada</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CC_Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 AND 2) OR (3 AND 4) OR (5 AND 6) OR (8 AND 9)) OR (7)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente, Cliente (Outbound), Cliente (CSBD), Cliente (COPS), Cliente (SACH)</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente, Cliente Particular</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado, Empleado (HDT)</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Empleado (COPS)</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank, Buzón COPS</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>ReadOnly</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cliente (FRA)</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Centro CaixaBank, Cliente, Cliente Particular</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Llamadas</relationshipLabel>
    <relationshipName>Llamadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_DNIS__c.field-meta.xml
<CustomField>
    <fullName>CC_DNIS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DNIS</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Extension__c.field-meta.xml
<CustomField>
    <fullName>CC_Extension__c</fullName>
    <description>Extensión en Genesys</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Extensión</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>es</fullName>
                <label>Castellano</label>
            </value>
            <value>
                <fullName>ca</fullName>
                <label>Catalán</label>
            </value>
            <value>
                <fullName>en</fullName>
                <label>Inglés</label>
            </value>
            <value>
                <fullName>va</fullName>
                <label>Valenciano</label>
            </value>
            <value>
                <fullName>eu</fullName>
                <label>Euskera</label>
            </value>
            <value>
                <fullName>ga</fullName>
                <label>Gallego</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Servicio_Genesys__c.field-meta.xml
<CustomField>
    <fullName>CC_Servicio_Genesys__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Servicio Genesys</label>
    <referenceTo>CC_Servicio_Genesys__c</referenceTo>
    <relationshipLabel>Llamadas (Servicio Genesys)</relationshipLabel>
    <relationshipName>Llamadas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/fields/CC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo__c</fullName>
    <label>Tipo de llamada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Entrante</fullName>
                <default>true</default>
                <label>Entrante</label>
            </value>
            <value>
                <fullName>Saliente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Llamada__c/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/CC_Llamada__c/recordTypes/CSBD_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CSBD_Cliente</fullName>
    <active>true</active>
    <label>Cliente (CSBD)</label>
</RecordType>

force-app/main/default/objects/CC_Servicio_Genesys__c/CC_Servicio_Genesys__c.object-meta.xml
<CustomObject>
    <label>Servicio Genesys</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios Genesys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Servicio_Genesys__c/fields/CC_Codigo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_Servicio_Genesys__c/fields/CC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segundo nivel</fullName>
            </value>
            <value>
                <fullName>Servicio</fullName>
            </value>
            <value>
                <fullName>Tercer nivel</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Servicio_Genesys__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo de cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Servicio_Genesys__c/fields/CC_VDN__c.field-meta.xml
<CustomField>
    <fullName>CC_VDN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>VDN</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CC_Usuario_Genesys__c/CC_Usuario_Genesys__c.object-meta.xml
<CustomObject>
    <label>Usuario Genesys</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Login</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usuarios Genesys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Usuario_Genesys__c/fields/CC_Acceso__c.field-meta.xml
<CustomField>
    <fullName>CC_Acceso__c</fullName>
    <description>Medios en los cuales el usuario puede atender a clientes.</description>
    <label>Acceso</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Teléfono</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Call me now</fullName>
            </value>
            <value>
                <fullName>Call me back</fullName>
            </value>
            <value>
                <fullName>Otros CSBD</fullName>
            </value>
            <value>
                <fullName>Teléfono, Chat</fullName>
                <isActive>false</isActive>
                <label>Teléfono, Chat</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Usuario_Genesys__c/fields/CC_DN__c.field-meta.xml
<CustomField>
    <fullName>CC_DN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Extensión</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Usuario_Genesys__c/fields/CC_Negocio__c.field-meta.xml
<CustomField>
    <fullName>CC_Negocio__c</fullName>
    <label>Negocio</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CC</fullName>
                <default>true</default>
                <label>CC</label>
            </value>
            <value>
                <fullName>CSBD</fullName>
            </value>
            <value>
                <fullName>CSBD + CC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Usuario_Genesys__c/fields/CC_User__c.field-meta.xml
<CustomField>
    <fullName>CC_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Usuarios_Genesys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Numero_Documento__c.field-meta.xml
<CustomField>
    <fullName>CC_Numero_Documento__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Número de documento</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Cliente.recordType-meta.xml
<RecordType>
    <fullName>CC_Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/CSBD_Contact__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Idioma_Solicitud__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Idioma_Solicitud__c</fullName>
    <label>Idioma solicitud</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CSBD_Prestamo.recordType-meta.xml
<RecordType>
    <fullName>CSBD_Prestamo</fullName>
    <active>true</active>
    <businessProcess>CSBD_Sales_Process_Prestamos</businessProcess>
    <label>Consumo</label>
</RecordType>

force-app/main/default/classes/CSBD_Llamada_Test.cls
@isTest
public class CSBD_Llamada_Test {
    /*
    @testSetup
    public static void altaDatosPrueba() {
        User adminUser = usuarioAdministrador();
        System.runAs(adminUser) {
            //Alta de las parametrizaciones que necesita el trigger BI de oportunidades
            CC_Lista_Valores__c listaValores = new CC_Lista_Valores__c();
            listaValores.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Lista_Valores');
            listaValores.Name = 'CSBD: Días cierre oportunidad por defecto';
            listaValores.CC_Activa__c = true;
            insert listaValores;

            CC_Lista_Valores__c valorPrestamo = new CC_Lista_Valores__c();
            valorPrestamo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Valor');
            valorPrestamo.CC_Lista__c = listaValores.Id;
            valorPrestamo.Name = 'Préstamo';
            valorPrestamo.CC_Valor__c = '1';
            insert valorPrestamo;

            CC_Lista_Valores__c valorTpv = new CC_Lista_Valores__c();
            valorTpv.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Valor');
            valorTpv.CC_Lista__c = listaValores.Id;
            valorTpv.Name = 'TPV';
            valorTpv.CC_Valor__c = '5';
            insert valorTpv;

            CC_Lista_Valores__c valorLLamadaServicio = new CC_Lista_Valores__c();
            valorPrestamo.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Lista_Valores__c', 'CC_Valor');
            valorPrestamo.CC_Lista__c = listaValores.Id;
            valorPrestamo.Name = 'LLamada Servicio';
            valorPrestamo.CC_Valor__c = '0';
            insert valorLLamadaServicio;

            Pricebook2 listaPrecios = new Pricebook2();
            listaPrecios.Name = 'Standard Price Book';
            insert listaPrecios;

            Pricebook2 listaPreciosCsbd = new Pricebook2();
            listaPreciosCsbd.Name = 'CSBD Price Book';
            listaPreciosCsbd.Description = 'CSBD Price Book';
            listaPreciosCsbd.IsActive = true;
            insert listaPreciosCsbd;

            Id userId = adminUser.Id;
            CC_Usuario_Genesys__c usuarioGen = new CC_Usuario_Genesys__c(
                CC_User__c = userId,
                Name = 'LOGINTEST',
                CC_DN__c = '1234',
                CC_Acceso__c = 'Teléfono;Chat',
                CC_Negocio__c = 'CSBD + CC'
            );
            insert usuarioGen;

            CC_Servicio_Genesys__c servicioGenesys = new CC_Servicio_Genesys__c();
            servicioGenesys.Name = 'testEntrante';
            servicioGenesys.CC_VDN__c = '2';
            servicioGenesys.CC_Tipo_Cliente__c = 'Cliente';
            servicioGenesys.CC_Codigo__c='1234';
            insert servicioGenesys;
        }
    }

    @isTest
    public static void registrarLlamadaSaliente() {

        Account cuenta = new Account();
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_Cliente');
        cuenta.Name = 'test@test.com';
        cuenta.CC_Numero_Documento__c = '12312312K';
        insert cuenta;

        Contact contacto = new Contact();
        contacto.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
        contacto.Email = 'test@test.com';
        contacto.FirstName = 'Nombre';
        contacto.LastName = 'Apellido';
        contacto.AccountId = cuenta.Id;
        insert contacto;

        Map<String, String> campos = new Map<String, String>();
        campos.put('AccountId', cuenta.Id);
        campos.put('CSBD_Contact__c', contacto.Id);
        campos.put('CSBD_Idioma_Solicitud__c', 'Catalán');
        Opportunity oportunidad = CSBD_Opportunity.crearOportunidad('CSBD_Prestamo', campos);

        User usuarioAdmin = [SELECT Id FROM User WHERE Email = 'usuario_test@test.com'];
        System.runAs (usuarioAdmin) {
            Test.startTest();
            CC_Llamada_Input inputLlamada = new CC_Llamada_Input();
            inputLlamada.usuario = 'Usuario1';
            inputLlamada.extension = 'Extensión1';
            inputLlamada.connId = 'connId1';
            inputLlamada.ani = '123456789';
            inputLlamada.dnis = '234567890';
            inputLlamada.negocio = 'CSBD';
            inputLlamada.casoId = oportunidad.Id;
            CC_Llamada__c llamada = CSBD_Llamada.registrarLlamadaSaliente(inputLlamada);
            Test.stopTest();

            System.assertEquals(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Llamada__c', 'CSBD_Cliente'), llamada.RecordTypeId, 'RecordType de llamada incorrecto');
            System.assertEquals('Saliente', llamada.CC_Tipo__c, 'Tipo de llamada incorrecto');
            System.assertEquals(inputLlamada.usuario, llamada.CC_Agente__c, 'Agente de llamada incorrecto');
            System.assertEquals(inputLlamada.extension, llamada.CC_Extension__c, 'Extensión de llamada incorrecta');
            System.assertEquals(inputLlamada.connId, llamada.CC_ConnId__c, 'CC_ConnId__c de llamada incorrecto');
            System.assertEquals(inputLlamada.dnis, llamada.CC_DNIS__c, 'CC_DNIS__c de llamada incorrecto');
            System.assertEquals('ca', llamada.CC_Idioma__c, 'Idioma de llamada incorrecto');
            System.assertEquals(oportunidad.AccountId, llamada.CC_Cuenta__c, 'Cuenta de llamada incorrecta');
            System.assertEquals(oportunidad.CSBD_Contact__c, llamada.CC_Contacto__c, 'Contacto de llamada incorrecto');
        }
    }

    @isTest
    public static void finalizarLlamada() {

        Account cuenta = new Account();
        cuenta.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Account', 'CC_Cliente');
        cuenta.Name = 'test@test.com';
        cuenta.CC_Numero_Documento__c = '12312312K';
        insert cuenta;

        Contact contacto = new Contact();
        contacto.RecordTypeId = CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('Contact', 'CC_Cliente');
        contacto.Email = 'test@test.com';
        contacto.FirstName = 'Nombre';
        contacto.LastName = 'Apellido';
        contacto.AccountId = cuenta.Id;
        insert contacto;

        Map<String, String> campos = new Map<String, String>();
        campos.put('AccountId', cuenta.Id);
        campos.put('CSBD_Contact__c', contacto.Id);
        campos.put('CSBD_Idioma_Solicitud__c', 'Catalán');
        Opportunity oportunidad = CSBD_Opportunity.crearOportunidad('CSBD_Prestamo', campos);

        CC_Llamada_Input inputLlamada = new CC_Llamada_Input();
        inputLlamada.usuario = 'Usuario1';
        inputLlamada.extension = 'Extensión1';
        inputLlamada.connId = 'connId1';
        inputLlamada.ani = '123456789';
        inputLlamada.dnis = '234567890';
        inputLlamada.negocio = 'CSBD';
        inputLlamada.casoId = oportunidad.Id;
        CC_Llamada__c llamada = CSBD_Llamada.registrarLlamadaSaliente(inputLlamada);
        String inputLlamadaString = JSON.serialize(inputLlamada);

        User usuarioAdmin = [SELECT Id FROM User WHERE Email = 'usuario_test@test.com'];
        System.runAs (usuarioAdmin) {
            Test.startTest();
            CC_OpenCTI.finalizarLlamada(inputLlamadaString, 'Llamada finalizada');
            Test.stopTest();

            System.assert([SELECT CC_Fecha_Fin__c FROM CC_Llamada__c WHERE Id = :llamada.Id].CC_Fecha_Fin__c != null, 'Llamada no finalizada');
        }
    }

    @isTest
    public static void finalizarLlamadaDobleNegocio() {
        CC_Llamada_Input inputLlamada = new CC_Llamada_Input();
        inputLlamada.usuario = 'Usuario1';
        inputLlamada.extension = 'Extensión1';
        inputLlamada.connId = 'connId1';
        inputLlamada.ani = '123456789';
        inputLlamada.dnis = '234567890';
        inputLlamada.negocio = 'CSBD + CC';
        inputLlamada.numPerso = '12345678';
        inputLlamada.idioma = 'Castellano';
        inputLlamada.servicio = '1234';
        inputLlamada.asunto = ', , 1, #, 02213133, hablar con operador, 4, hablar con operador';
        Opportunity oportunidad = CSBD_Llamada.registrarLlamadaEntrante(inputLlamada);
        inputLlamada.llamadaId = oportunidad.Id;

        String inputLlamadaString = JSON.serialize(inputLlamada);

        User usuarioAdmin = [SELECT Id FROM User WHERE Email = 'usuario_test@test.com'];
        System.runAs (usuarioAdmin) {
            Test.startTest();
            CC_OpenCTI.finalizarLlamada(inputLlamadaString, 'Llamada finalizada');
            Test.stopTest();

            List<Task> task = [SELECT id, CC_Llamada_Id__c from Task where CC_Llamada_Id__c != null and WhatId = : oportunidad.Id];

            System.assert([SELECT CC_Fecha_Fin__c FROM CC_Llamada__c WHERE Id = :task[0].CC_Llamada_Id__c].CC_Fecha_Fin__c != null, 'Llamada no finalizada');
        }
    }

    @isTest
    public static void getIdiomaOportunidad() {
        Map<String, String> campos = new Map<String, String>();
        campos.put('CSBD_Idioma_Solicitud__c', 'Castellano');
        Opportunity oportunidad = CSBD_Opportunity.crearOportunidad('CSBD_Prestamo', campos);

        User usuarioAdmin = [SELECT Id FROM User WHERE Email = 'usuario_test@test.com'];
        System.runAs (usuarioAdmin) {
            Test.startTest();
            String idiomaOportunidad = CSBD_Llamada.getIdiomaOportunidad(oportunidad.Id);
            Test.stopTest();

            System.assertEquals('es', idiomaOportunidad, 'Idioma de la oportunidad incorrecto');
        }
    }

    @isTest
    public static void registrarLlamadaEntrante() {
        User usuarioAdmin = [SELECT Id FROM User WHERE Email = 'usuario_test@test.com'];
        System.runAs (usuarioAdmin) {
            Test.startTest();
            CC_Llamada_Input inputLlamada = new CC_Llamada_Input();
            inputLlamada.usuario = 'Usuario1';
            inputLlamada.extension = 'Extensión1';
            inputLlamada.connId = 'connId1';
            inputLlamada.ani = '123456789';
            inputLlamada.dnis = '234567890';
            inputLlamada.negocio = 'CSBD';
			inputLlamada.numPerso = '12345678';
            inputLlamada.idioma = 'Castellano';
            inputLlamada.servicio = '1234';
            inputLlamada.asunto = ', , 1, #, 02213133, hablar con operador, 4, hablar con operador';
            Opportunity oportunidad = CSBD_Llamada.registrarLlamadaEntrante(inputLlamada);
            Test.stopTest();

            List<Opportunity> opp = [SELECT id from Opportunity where Id = :oportunidad.Id limit 1];
            List<Task> task = [SELECT id, WhatId from Task where CC_Llamada_Id__c != null and WhatId = : opp[0].Id];

            System.assertEquals(opp.isEmpty(), false, 'No se ha creado oportunidad relacionada con la llamada');
            System.assertEquals(task.isEmpty(), false, 'No se ha creado tarea relacionada con la llamada y la oportunidad');

        }
    }

    public static User usuarioAdministrador(){
        User admin = new User();
        admin.FirstName = 'Admin';
        admin.LastName = '1';
        admin.IsActive = true;
        admin.Alias = 'Admin';
        admin.Email = 'usuario_test@test.com';
        admin.EmailEncodingKey = 'ISO-8859-1';
        admin.LanguageLocaleKey = 'es';
        admin.LocaleSidKey = 'es_ES';
        admin.UserRoleId = [SELECT Id FROM UserRole WHERE Name = 'CSBD Genérico'].Id;
        admin.ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        admin.TimeZoneSidKey = 'Europe/Madrid';
        admin.UserName = 'usuariotest_' + UserInfo.getOrganizationId() + '_' + System.currentTimeMillis() + '@test.com';
        insert admin;

        List<PermissionSetAssignment> nuevosPermisos = new List<PermissionSetAssignment>();
        List<PermissionSet> permissionSet = [SELECT Id FROM PermissionSet WHERE Name LIKE 'CSBD%'];

        for (PermissionSet permissionSet1:permissionSet ) {
            PermissionSetAssignment nuevoPermiso = new PermissionSetAssignment();
            nuevoPermiso.PermissionSetId = permissionSet1.Id;
            nuevoPermiso.AssigneeId = admin.Id;
            nuevosPermisos.add(nuevoPermiso);
        }
        insert nuevosPermisos;

        return admin;
    }
    */
}