force-app/main/default/objects/Account/fields/CC_SubTipo_Centro__c.field-meta.xml
<CustomField>
    <fullName>CC_SubTipo_Centro__c</fullName>
    <description>Subtipo de Centro</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Subtipo de Centro</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CC_Tipo_Centro__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Centro__c</fullName>
    <description>Tipo de Centro</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Tipo de Centro</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Admin__c.field-meta.xml
<CustomField>
    <fullName>CC_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que hace bypass a las validation rules que lo tengan en cuenta.</description>
    <label>CC_Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Origin</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de resolución</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CC_Canal_Procedencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_En_Tercer_Nivel__c.field-meta.xml
<CustomField>
    <fullName>CC_En_Tercer_Nivel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>En Tercer Nivel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Matricula_Empleado__c.field-meta.xml
<CustomField>
    <fullName>CC_Matricula_Empleado__c</fullName>
    <formula>IF (ContactId != null, Contact.CC_Matricula__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Matricula Empleado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_MCC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_MCC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Temática del caso</description>
    <inlineHelpText>Temática del caso</inlineHelpText>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Cases (Temática)</relationshipLabel>
    <relationshipName>Tematica</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Referencia_Correo_Saliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Referencia_Correo_Saliente__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Referencia correo saliente</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Temática (interno)</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_URL_Encuesta_3N__c.field-meta.xml
<CustomField>
    <fullName>CC_URL_Encuesta_3N__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>URL Encuesta 3N</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CC_CSI_Bankia.recordType-meta.xml
<RecordType>
    <fullName>CC_CSI_Bankia</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado Bankia</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <businessProcess>CC_Empleados</businessProcess>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/CC_Agrupador__c.object-meta.xml
<CustomObject>
    <label>Agrupador</label>
    <nameField>
        <displayFormat>GRP-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Agrupador__c/fields/CC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>!! PENDENT !!</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa</fullName>
    <active>true</active>
    <label>Comunicación Informativa</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Comunicacion_Informativa_de_Campana.recordType-meta.xml
<RecordType>
    <fullName>CC_Comunicacion_Informativa_de_Campana</fullName>
    <active>true</active>
    <label>Comunicación Informativa de Campaña</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Incidencia.recordType-meta.xml
<RecordType>
    <fullName>CC_Incidencia</fullName>
    <active>true</active>
    <label>Incidencia</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Masiva_Control.recordType-meta.xml
<RecordType>
    <fullName>CC_Masiva_Control</fullName>
    <active>true</active>
    <label>Masiva de control</label>
</RecordType>

force-app/main/default/objects/CC_Agrupador__c/recordTypes/CC_Seguimiento.recordType-meta.xml
<RecordType>
    <fullName>CC_Seguimiento</fullName>
    <active>true</active>
    <label>Seguimiento</label>
</RecordType>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/CC_Buzones_Por_Defecto__mdt.object-meta.xml
<CustomObject>
    <label>Buzón por defecto</label>
    <pluralLabel>Buzones por defecto</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <label>Canal de procedencia</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Direccion_Correo__c.field-meta.xml
<CustomField>
    <fullName>CC_Direccion_Correo__c</fullName>
    <label>Dirección de correo</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CC_Buzones_Por_Defecto__mdt/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Envio_Encuesta__c/CC_Envio_Encuesta__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Seteo de Link para LimeSurvey - Envío de encuestas (chat)</description>
    <label>CC_Envio_Encuesta</label>
</CustomObject>

force-app/main/default/objects/CC_Envio_Encuesta__c/fields/CC_Id_Encuesta__c.field-meta.xml
<CustomField>
    <fullName>CC_Id_Encuesta__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC_Id_Encuesta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Envio_Encuesta__c/fields/CC_Link_LimeSurvey__c.field-meta.xml
<CustomField>
    <fullName>CC_Link_LimeSurvey__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC_Link_LimeSurvey</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/CC_Envio_Encuesta__c/fields/CC_Tipo_Encuesta__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Encuesta__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC_Tipo_Encuesta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/CC_Lista_Valores__c.object-meta.xml
<CustomObject>
    <description>Lista de valores</description>
    <label>Lista de valores</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listas de valores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Activa__c.field-meta.xml
<CustomField>
    <fullName>CC_Activa__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Lista__c.field-meta.xml
<CustomField>
    <fullName>CC_Lista__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lista de valores</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resoluciones</value>
        </filterItems>
        <filterItems>
            <field>CC_Lista_Valores__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Familias</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_Lista_Valores__c</referenceTo>
    <relationshipLabel>Valores</relationshipLabel>
    <relationshipName>CC_Valores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_Lista_Valores__c/fields/CC_Valor__c.field-meta.xml
<CustomField>
    <fullName>CC_Valor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Valor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Canal_Resolucion__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Resolucion__c</fullName>
    <label>Canal de Resolucion</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_resolucion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_idCognitivo__c.field-meta.xml
<CustomField>
    <fullName>CC_idCognitivo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Enlace encuesta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CC_Idioma__c.field-meta.xml
<CustomField>
    <fullName>CC_Idioma__c</fullName>
    <label>Idioma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Codigo_Idioma</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/LiveChatTranscript/fields/CC_Canal_Procedencia__c.field-meta.xml
<CustomField>
    <fullName>CC_Canal_Procedencia__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Canal Procedencia</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CC_Espacio__c.field-meta.xml
<CustomField>
    <fullName>CC_Espacio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Espacio</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/CC_Tipo__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Tipo_Chat_Transcript</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/recordTypes/CC_Empleados.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleados</fullName>
    <active>true</active>
    <description>Chat del área de empleados</description>
    <label>Empleados</label>
</RecordType>

force-app/main/default/classes/CC_Envio_Encuestas_3N.cls
public without sharing class CC_Envio_Encuestas_3N {
    @InvocableMethod
    public static void enviarEncuesta(List<Id> idsCasos) {
        List<CC_Lista_Valores__c> listaCanalResolucion = [SELECT CC_Valor__c, CC_Activa__c FROM CC_Lista_Valores__c WHERE CC_Lista__r.Name = 'Envío de Encuesta 3N - Canales de resolución'];
        Set<String> valoresCanales = new Set<String>();
        for (CC_Lista_Valores__c resolucion : listaCanalResolucion) {
            if(resolucion.CC_Activa__c){
                valoresCanales.add(resolucion.CC_Valor__c);
            }
        }
        //Comprobar que el valor de canal de resolucion este en la lista
        ////No enviar encuesta si es un caso de CSI Bankia
        
    	List<Case> casosTelefonia = Database.query('SELECT Id, Origin, CaseNumber, CC_En_Tercer_Nivel__c, ContactId, CC_Canal_Resolucion__c, CC_Canal_Procedencia__c, CC_Idioma__c, CC_URL_Encuesta_3N__c, RecordTypeId, CC_Matricula_Empleado__c, CC_MCC_Tematica__c,CC_Tematica__c, CC_MCC_Tematica__r.Name, CC_MCC_Tematica__r.CC_IdCognitivo__c, RecordType.Name FROM Case WHERE Id IN :idsCasos AND RecordType.DeveloperName = \'CC_Empleado\' AND ContactId <> NULL AND Contact.Email <> NULL AND Origin = \'Phone\' AND AccountId <> NULL AND Account.CC_Tipo_Centro__c = \'OF\' AND Account.CC_SubTipo_Centro__c = \'BP\'');
        if (casosTelefonia.size() > 0) {
            enviarEncuestaFuture(casosTelefonia, true);
        } else{
        	List<Case> casos = Database.query('SELECT Id, Origin, CaseNumber, ContactId, CC_En_Tercer_Nivel__c, CC_Canal_Resolucion__c, CC_Canal_Procedencia__c, CC_Idioma__c, CC_URL_Encuesta_3N__c, RecordTypeId, CC_Matricula_Empleado__c, CC_MCC_Tematica__c,CC_Tematica__c, CC_MCC_Tematica__r.Name, CC_MCC_Tematica__r.CC_IdCognitivo__c, RecordType.Name FROM Case WHERE Id IN :idsCasos AND CC_Canal_Resolucion__c IN :valoresCanales AND RecordType.DeveloperName  <> \'CC_CSI_Bankia\' AND ContactId <> NULL AND Contact.Email <> NULL');       
			if (casos.size() > 0) {
            	enviarEncuestaFuture(casos, false);
            }
        }
    }
    
    public static void enviarEncuestaFuture(List<Case> casos, Boolean casoTelefonia) {
        Set<Id> idsCasosSet = new Set<Id>();
        Set<Id> idsCasosEnvioEncuesta = new Set<Id>();
        //Solucion IN Too many Email Invocations: 11
        List<Messaging.SingleEmailmessage> oListMail = new List<Messaging.SingleEmailmessage>();
        
        if(casoTelefonia) {
            for (Case caso : casos) {
                idsCasosEnvioEncuesta.add(caso.Id);
            }
        } else {
            Map<Id, String> mapAgrupadores = new Map<Id, String>();        
            mapAgrupadores.put(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Seguimiento'), 'CC_Seguimiento');
            mapAgrupadores.put(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa'), 'CC_Comunicacion_Informativa');
            mapAgrupadores.put(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Comunicacion_Informativa_de_Campana'), 'CC_Comunicacion_Informativa_de_Campana');
            mapAgrupadores.put(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Incidencia'), 'CC_Incidencia');
            mapAgrupadores.put(CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('CC_Agrupador__c', 'CC_Masiva_Control'), 'CC_Masiva_Control');
            
            for (Case caso : casos) {
                idsCasosSet.add(caso.Id);
            }
            
            for(Task oTask : [SELECT Id, Type, status, Agrupador__c, WhatId FROM Task WHERE WhatId IN :idsCasosSet]){
                if((oTask.Type=='Traslado Tercer Nivel' && oTask.status != 'Rechazada') ||
                (oTask.Type=='Traslado Colaborador' && oTask.status != 'Rechazada') ||
                oTask.Type=='Traslado Incidencia' && mapAgrupadores.get(oTask?.Id) != 'CC_Seguimiento')
                {
                    idsCasosEnvioEncuesta.add(oTask.WhatId);
                }
            }
        }
        
        //Comprobar que hay un caso para enviar la encuesta
        if (idsCasosEnvioEncuesta.size() > 0) {
            
            List<Case> listCasos = new List<Case>();
            for (Case caso : casos) {
                if(idsCasosEnvioEncuesta.contains(caso?.Id)) {
                    listCasos.add(caso);
                }             
            }
            
            Map<String, Id> mapIdIdiomaPlantilla = new Map<String, Id>();
            List<EmailTemplate> emailPlantillas = [SELECT Id, htmlvalue, DeveloperName FROM EmailTemplate WHERE DeveloperName = 'Encuesta_Offline' OR DeveloperName = 'Enquesta_Offline'];
            for(EmailTemplate emailp : emailPlantillas){
                if(emailp.DeveloperName == 'Enquesta_Offline'){
                    mapIdIdiomaPlantilla.put('ca', emailp.Id);
                } else if (emailp.DeveloperName == 'Encuesta_Offline') {
                    mapIdIdiomaPlantilla.put('es', emailp.Id);
                }
            }
            
            //Traigo la base del link LimeSurvey para usar con Empleado
            List<CC_Envio_Encuesta__c> linkEncuestaEmpleado = [SELECT CC_Link_LimeSurvey__c, CC_Id_Encuesta__c, CC_Tipo_Encuesta__c FROM CC_Envio_Encuesta__c WHERE Name IN ( 'CC_URL_Encuesta', 'CC_TipoLlamada', 'TipoChat', 'CC_TercerNivel')];
            String idEncuestaLlamada, idEncuestaChat, idEncuestaTercerNivel, linkBase, idEncuestaGenerico;
            Map<Id, String> mapInfoChat = new  Map<Id,String>();
            List<LiveChatTranscript> listaChats = new List<LiveChatTranscript>([SELECT CC_Espacio__c, CaseId FROM LiveChatTranscript WHERE CaseId IN :listCasos AND CC_Tipo__c = 'Agente'AND RecordTypeId = :CC_MetodosUtiles.getRecordTypeIdFromDeveloperName('LiveChatTranscript', 'CC_Empleados') ORDER BY CreatedDate DESC]);
             //Map<Id, LiveChatTranscript> mapInfoChat = new Map<Id, LiveChatTranscript>([SELECT CC_Espacio__c FROM Case WHERE CaseId IN :setIdsCasos]);
    
            //Divido asigno los ids correspondientes a cada string
            for(CC_Envio_Encuesta__c e : linkEncuestaEmpleado){
                if(e.CC_Tipo_Encuesta__c == 'URL base'){
                    linkBase = e.CC_Link_LimeSurvey__c;
                    idEncuestaGenerico = e.CC_Id_Encuesta__c;
                }else if (e.CC_Tipo_Encuesta__c == 'Phone'){
                    idEncuestaLlamada = e.CC_Id_Encuesta__c;
                }else if(e.CC_Tipo_Encuesta__c == 'Chat'){
                    idEncuestaChat = e.CC_Id_Encuesta__c;
                }else if(e.CC_Tipo_Encuesta__c == 'Caso Tercer Nivel'){
                    idEncuestaTercerNivel = e.CC_Id_Encuesta__c;
                }
            }
    
            if(!listCasos.isEmpty()){
                if(!listaChats.isEmpty()){
                    for (LiveChatTranscript chat :listaChats) {
                       Id key = chat.CaseId; 
                            if (!mapInfoChat.containsKey(key)) {
                                mapInfoChat.put(key, chat.CC_Espacio__c);
                            }
                    }
                }
           }
           String referencia;
           Map<Id, Case> mapReferenciaCasos = new Map<Id, Case>();
            if(!linkEncuestaEmpleado.isEmpty()){
                //Actualizar URL de la encuesta en el caso

                for(Case caso :listCasos){
                    referencia = CC_EmailMessage.generarReferenciaCorreoSaliente(caso.Id);
                    if(caso.CC_Idioma__c != null && caso.CC_Matricula_Empleado__c != null && caso.CC_MCC_Tematica__c != null && caso.CC_Tematica__c != null && !linkEncuestaEmpleado.isEmpty()){
                        caso.CC_Admin__c = true;
                        if(caso.CC_En_Tercer_Nivel__c){
                            if(!mapInfoChat.isEmpty()){
                                caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+idEncuestaTercerNivel+'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+mapInfoChat.get(caso.Id).replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                            }else{
                                caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+ idEncuestaTercerNivel +'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+caso.CC_Tematica__c.replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                            }
                        }else {
                            if(caso.Origin == 'Phone'){
                                caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+idEncuestaLlamada+'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+caso.CC_Tematica__c.replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                            }
                            else if(caso.Origin == 'Chat'){
                                if(!mapInfoChat.isEmpty()){
                                    caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+idEncuestaChat+'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+mapInfoChat.get(caso.Id).replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                                }else{
                                    caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+ idEncuestaChat +'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+caso.CC_Tematica__c.replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                                }
                            } else{
                                caso.CC_URL_Encuesta_3N__c = linkBase +'sid='+ idEncuestaGenerico +'&lang='+ caso.CC_Idioma__c+'&userid='+caso.CC_Matricula_Empleado__c+'&ticketid='+caso.CaseNumber+'&idet='+caso.CC_Tematica__c.replace(' ', '_')+'&et='+ caso.CC_Tematica__c.replace(' ', '_')+'&newtest=Y';
                                
                            }
                        }
                    }
                    caso.CC_Referencia_Correo_Saliente__c = referencia;
                    mapReferenciaCasos.put(caso.Id, caso);
                }
                update listCasos;
            }
            
            List<Task> tasks = new List<Task>();          
            List<CC_Buzones_Por_Defecto__mdt> buzones = [SELECT CC_Direccion_Correo__c, CC_Canal_Procedencia__c FROM CC_Buzones_Por_Defecto__mdt
            WHERE (CC_Canal_Procedencia__c = 'Por defecto empleados' OR CC_Canal_Procedencia__c = 'Por defecto') AND CC_Idioma__c <> 'CSI'];
            Map<String, String> mapBuzonesDefecto = new Map<String, String> ();            
            for(CC_Buzones_Por_Defecto__mdt buzondefecto : buzones){
                mapBuzonesDefecto.put(buzondefecto.CC_Canal_Procedencia__c, buzondefecto.CC_Direccion_Correo__c);
            }
            
            List<OrgWideEmailAddress> remitentesEmails = [SELECT Id, Address FROM OrgWideEmailAddress];
            Map<String, Id> mapIdOrgWide = new Map<String, String> ();            
            for(OrgWideEmailAddress idOrgWide : remitentesEmails){
                mapIdOrgWide.put(idOrgWide.Address, idOrgWide.Id);
            }
            
            for(Integer i = 0; i< listCasos.size(); i++){
                
                String remitente = mapBuzonesDefecto.get('Por defecto empleados');
                
                Id remitenteId;
                remitenteId = mapIdOrgWide.get(remitente);             
                
                //Si el caso es de FCO no se debe enviar la encuesta (US859756)
                if (listCasos[i].CC_Canal_Procedencia__c != 'Formulario Consultas Operativas') {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setSaveAsActivity(true);
                    mail.setWhatId(listCasos[i].Id);
                    
                    //Elegir idioma de la plantilla
                    if(listCasos[i].CC_Idioma__c != 'ca'){
                        mail.setTemplateId(mapIdIdiomaPlantilla.get('es'));
                    } else {
                        mail.setTemplateId(mapIdIdiomaPlantilla.get('ca'));
                    }
                    mail.setTargetObjectId(listCasos[i].ContactId);
                    mail.setTreatTargetObjectAsRecipient(true);
                    mail.setOrgWideEmailAddressId(remitenteId);
                    oListMail.add(mail);
                }
            }            
            
            // Lanzar las peticiones de mensajes a enviar.
            if (!oListMail.isEmpty()) {
                List<Messaging.SingleEmailmessage> oMaxEnvios = new List<Messaging.SingleEmailmessage>();
                Integer iMensaje = 0;
                Integer iTotalMsj = oListMail.size();
                
                for (Integer iMens = 0; iMens < iTotalMsj; iMens++) {
                    oMaxEnvios.add(oListMail[iMens]);
                    iMensaje = iMensaje + 1;
                    if (iMensaje == 10 || iMens == iTotalMsj-1){
                        // Enviar bloques de 10 mensajes máximo.
                        List<Messaging.SendEmailResult> oDataRes = Messaging.sendEmail(oMaxEnvios, false);
                        // Suponemos que el orden de devolución de resultados, es el orden de entrada de la lista de e-mails.
                        // Actualizamos estado en función de ello.
                        for (Integer iRes = 0; iRes<oDataRes.size(); iRes++) {
                            if (oDataRes[iRes].isSuccess()) {
                                for (Case caso : listCasos) {
                                    Task tarea = new Task();
                                    tarea.Status = 'Completed';
                                    if(casoTelefonia) {
                                        tarea.Type = 'Envío de petición encuesta Banca Privada C2C';
                                    } else {
                                        tarea.Type = 'Envío de petición encuesta 3N';
                                    }
                                    tarea.Subject = 'Email: Encuesta Satisfacción Contact Center Oficinas';
                                    tarea.WhatId = oMaxEnvios[iRes].getWhatId();
                                    tasks.add(tarea);
                                }
                            }
                        }
                        // Resetear variable de conteo y lista de envíos.
                        oMaxEnvios.clear();
                        iMensaje = 0;
                    }
                }
                //insert tasks;
                CC_Activity.crearActividades(tasks);
            }
        }
    }
}