force-app/main/default/objects/Account/fields/CIBE_CentrosCarteras__c.field-meta.xml
<CustomField>
    <fullName>CIBE_CentrosCarteras__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Centros-Carteras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIBE_Comisiones__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Comisiones__c</fullName>
    <description>campo &quot;Comisiones Gestion/Gastos asociados&quot; del TF importado en la integración IGC</description>
    <label>Comisiones</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIBE_Negocios__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Negocios__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Negocios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIBE_RedesSegmentos__c.field-meta.xml
<CustomField>
    <fullName>CIBE_RedesSegmentos__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Redes-Segmentos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CIBE_SectoresPaises__c.field-meta.xml
<CustomField>
    <fullName>CIBE_SectoresPaises__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sectores-Paises</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_PicklistValues__c/CBK_PicklistValues__c.object-meta.xml
<CustomObject>
    <label>CBK Picklist Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CBK Picklists Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_PicklistValues__c/fields/CBK_Dependencies__c.field-meta.xml
<CustomField>
    <fullName>CBK_Dependencies__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Dependencies</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CBK_PicklistValues__c/fields/CBK_HasDependency__c.field-meta.xml
<CustomField>
    <fullName>CBK_HasDependency__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Dependency</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CBK_PicklistValues__c/fields/CBK_Object__c.field-meta.xml
<CustomField>
    <fullName>CBK_Object__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_PicklistValues__c/fields/CBK_Picklist__c.field-meta.xml
<CustomField>
    <fullName>CBK_Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CBK Picklist</label>
    <referenceTo>CBK_PicklistValues__c</referenceTo>
    <relationshipLabel>CBK Picklists Values</relationshipLabel>
    <relationshipName>CBK_Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CBK_PicklistValues__c/recordTypes/CBK_Picklist.recordType-meta.xml
<RecordType>
    <fullName>CBK_Picklist</fullName>
    <active>true</active>
    <label>CBK Picklist</label>
</RecordType>

force-app/main/default/objects/CBK_PicklistValues__c/recordTypes/CBK_PicklistValue.recordType-meta.xml
<RecordType>
    <fullName>CBK_PicklistValue</fullName>
    <active>true</active>
    <label>CBK Picklist Value</label>
</RecordType>

force-app/main/default/objects/CIBE_Hierarchy__c/CIBE_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Hierarchy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarchies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIBE_Hierarchy__c/fields/CIBE_CentrosCarteras__c.field-meta.xml
<CustomField>
    <fullName>CIBE_CentrosCarteras__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup al valor del registro Centro-Carteras del objeto cbk_picklistValues__c</description>
    <label>Centros-Carteras</label>
    <referenceTo>CBK_PicklistValues__c</referenceTo>
    <relationshipLabel>Hierarchies</relationshipLabel>
    <relationshipName>Hierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIBE_Hierarchy__c/fields/CIBE_Contact__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hierarchies</relationshipLabel>
    <relationshipName>Hierarchies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIBE_Hierarchy__c/fields/CIBE_Negocios__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Negocios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup al valor del registro Negocios del objeto cbk_picklistValues__c</description>
    <label>Negocios</label>
    <referenceTo>CBK_PicklistValues__c</referenceTo>
    <relationshipLabel>Hierarchies (Negocios)</relationshipLabel>
    <relationshipName>Hierarchies2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIBE_Hierarchy__c/fields/CIBE_RedesSegmentos__c.field-meta.xml
<CustomField>
    <fullName>CIBE_RedesSegmentos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup al valor del registro Redes-Segmentos del objeto cbk_picklistValues__c</description>
    <label>Redes-Segmentos</label>
    <referenceTo>CBK_PicklistValues__c</referenceTo>
    <relationshipLabel>Hierarchies (Redes-Segmentos)</relationshipLabel>
    <relationshipName>Hierarchies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIBE_Hierarchy__c/fields/CIBE_SectoresPaises__c.field-meta.xml
<CustomField>
    <fullName>CIBE_SectoresPaises__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup al valor del registro Sectores-Paises del objeto cbk_picklistValues__c</description>
    <label>Sectores-Paises</label>
    <referenceTo>CBK_PicklistValues__c</referenceTo>
    <relationshipLabel>Hierarchies (Sectores-Paises)</relationshipLabel>
    <relationshipName>Hierarchies3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIBE_Hierarchy__c/recordTypes/CIBE_Employee.recordType-meta.xml
<RecordType>
    <fullName>CIBE_Employee</fullName>
    <active>true</active>
    <label>Employee</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Matricula__c.field-meta.xml
<CustomField>
    <fullName>CC_Matricula__c</fullName>
    <description>Campo Matricula del empleado.
Cuando un empleado esté activo este campo será de 8 caracteres con el código U01 del empleado.
Cuando un empleado no se encuentre activo este campo será de 31 caracteras con el siguiente formato:
MATRICULA + - + YYYYMMDDHHMMSS + &quot;-INVALID&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Matrícula</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador de CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AV_PF__c.field-meta.xml
<CustomField>
    <fullName>AV_PF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PF asociado a la oportunidad</description>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.AV_Nivel__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Product2.AV_ExternalID__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities (PF)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_AmountDivisa__c.field-meta.xml
<CustomField>
    <fullName>CIBE_AmountDivisa__c</fullName>
    <label>Importe</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_Balance__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Balance__c</fullName>
    <inlineHelpText>Amount of Impact on Balance Sheet</inlineHelpText>
    <label>Impacto en balance €</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_BalanceDivisa__c.field-meta.xml
<CustomField>
    <fullName>CIBE_BalanceDivisa__c</fullName>
    <label>Impacto en balance</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_Comisiones__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Comisiones__c</fullName>
    <inlineHelpText>Estimated commissions in the opportunity closing month</inlineHelpText>
    <label>Impacto en com. upfront / firma €</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_ComisionesDivisa__c.field-meta.xml
<CustomField>
    <fullName>CIBE_ComisionesDivisa__c</fullName>
    <label>Impacto en com. upfront / firma</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_Divisa__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Divisa__c</fullName>
    <label>Divisa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CLF</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CVE</fullName>
            </value>
            <value>
                <fullName>CZK</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>DOP</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_Fechaaprobacionprecio__c.field-meta.xml
<CustomField>
    <fullName>CIBE_Fechaaprobacionprecio__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha aprobación precio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_ProbabilidadExito__c.field-meta.xml
<CustomField>
    <fullName>CIBE_ProbabilidadExito__c</fullName>
    <label>Probabilidad de éxito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
                <default>true</default>
                <label>Media</label>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CIBE_TipoOperacion__c.field-meta.xml
<CustomField>
    <fullName>CIBE_TipoOperacion__c</fullName>
    <label>Tipo de Operacion</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nueva</fullName>
                <default>true</default>
                <label>Nueva</label>
            </value>
            <value>
                <fullName>Disposición</fullName>
            </value>
            <value>
                <fullName>Ampliación importe</fullName>
            </value>
            <value>
                <fullName>Renovación</fullName>
            </value>
            <value>
                <fullName>Modificación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <description>Identificador CAIXA</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/AV_ExternalID__c.field-meta.xml
<CustomField>
    <fullName>AV_ExternalID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>AV ID Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CIBE_TabListOpportunityCIB_Test.cls
/**********************************************************************************************************************
Name:	  CIBE_TabListOpportunityCIB_Test
Copyright © 2022  CaixaBank
-----------------------------------------------------------------------------------------------------------------------
Proposito: Clase de cobertura para class CIBE_TabListOpportunityCIB_Controller
-----------------------------------------------------------------------------------------------------------------------
Historial
---------------------
	VERSION		USER_STORY		AUTHOR			DATE			Description
	1.0			US461563    	Lucía	  	    16/03/2023		Init version 

***********************************************************************************************************************/

@isTest
public with sharing class CIBE_TabListOpportunityCIB_Test {
    
    @TestSetup
    public static void setup() {
        string rtIdPickVal = Schema.getGlobalDescribe().get('CBK_PicklistValues__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CBK_PicklistValue').getRecordTypeId();
        string rtIdPick = Schema.getGlobalDescribe().get('CBK_PicklistValues__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CBK_Picklist').getRecordTypeId();
        string rtContact = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByDeveloperName().get('CC_Empleado').getRecordTypeId();
        string rtJerarquia = Schema.getGlobalDescribe().get('CIBE_Hierarchy__c').getDescribe().getRecordTypeInfosByDeveloperName().get('CIBE_Employee').getRecordTypeId();

        CIBE_TestInitialSetup.setupInitialDataCIB();
        User usuario = [SELECT Id FROM User WHERE AV_ExternalID__c = 'U0000001'];
        Contact contacto = [SELECT Id FROM Contact WHERE CC_Matricula__c = 'U0000001'];
        
        System.runAs(new User(Id = UserInfo.getUserId())) {
            Account cliente = CIBE_TestHelper.createCustomer();
    
            CBK_PicklistValues__c pick = new CBK_PicklistValues__c();
            pick.RecordTypeId = rtIdPick;
            pick.Name = 'Field Picklist';
            pick.CBK_Object__c = 'Object';
            insert pick;
    
            CBK_PicklistValues__c pickVal = new CBK_PicklistValues__c();
            pickVal.RecordTypeId = rtIdPickVal;
            pickVal.CBK_Picklist__c = pick.Id;
            pickVal.Name = 'Opcion1';
            pickVal.CBK_HasDependency__c = true;
            pickVal.CBK_Dependencies__c = 'Valor1';
            insert pickVal;
    
            CBK_PicklistValues__c pickVal2 = new CBK_PicklistValues__c();
            pickVal2.RecordTypeId = rtIdPickVal;
            pickVal2.CBK_Picklist__c = pick.Id;
            pickVal2.Name = 'Opcion2';
            pickVal2.CBK_HasDependency__c = true;
            pickVal2.CBK_Dependencies__c = 'Valor12';
            insert pickVal2;
    
            CBK_PicklistValues__c pickVal3 = new CBK_PicklistValues__c();
            pickVal3.RecordTypeId = rtIdPickVal;
            pickVal3.CBK_Picklist__c = pick.Id;
            pickVal3.Name = 'Opcion3';
            pickVal3.CBK_HasDependency__c = true;
            pickVal3.CBK_Dependencies__c = 'Valor2';
            insert pickVal3;
    
            CBK_PicklistValues__c pickVal4 = new CBK_PicklistValues__c();
            pickVal4.RecordTypeId = rtIdPickVal;
            pickVal4.CBK_Picklist__c = pick.Id;
            pickVal4.Name = 'Opcion4';
            pickVal4.CBK_HasDependency__c = true;
            pickVal4.CBK_Dependencies__c = 'Valor22';
            insert pickVal4;
                  
            CBK_PicklistValues__c pickVal5 = new CBK_PicklistValues__c();
            pickVal5.RecordTypeId = rtIdPickVal;
            pickVal5.CBK_Picklist__c = pick.Id;
            pickVal5.Name = 'Opcion5';
            pickVal5.CBK_HasDependency__c = true;
            pickVal5.CBK_Dependencies__c = 'Valor12';
            insert pickVal5;
    
            CBK_PicklistValues__c pickVal6 = new CBK_PicklistValues__c();
            pickVal6.RecordTypeId = rtIdPickVal;
            pickVal6.CBK_Picklist__c = pick.Id;
            pickVal6.Name = 'Opcion6';
            pickVal6.CBK_HasDependency__c = true;
            pickVal6.CBK_Dependencies__c = 'Valor2';
            insert pickVal6;
    
            CBK_PicklistValues__c pickVal7 = new CBK_PicklistValues__c();
            pickVal7.RecordTypeId = rtIdPickVal;
            pickVal7.CBK_Picklist__c = pick.Id;
            pickVal7.Name = 'Opcion7';
            pickVal7.CBK_HasDependency__c = true;
            pickVal7.CBK_Dependencies__c = 'Valor22';
            insert pickVal7;
            
            CBK_PicklistValues__c pickVal8 = new CBK_PicklistValues__c();
            pickVal8.RecordTypeId = rtIdPickVal;
            pickVal8.CBK_Picklist__c = pick.Id;
            pickVal8.Name = 'Opcion8';
            pickVal8.CBK_HasDependency__c = true;
            pickVal8.CBK_Dependencies__c = 'Valor22';
            insert pickVal8;
    
            //jerarquia
            CIBE_Hierarchy__c jerarquia = new CIBE_Hierarchy__c();
            jerarquia.CIBE_Negocios__c = pickVal.Id;
            jerarquia.CIBE_RedesSegmentos__c = pickVal2.Id;
            jerarquia.CIBE_SectoresPaises__c = pickVal3.Id;
            jerarquia.CIBE_CentrosCarteras__c = pickVal4.Id;
            jerarquia.CIBE_Contact__c = contacto.Id;
            jerarquia.RecordTypeId = rtJerarquia;
            insert jerarquia;
            
            CIBE_Hierarchy__c jerarquia2 = new CIBE_Hierarchy__c();
            jerarquia2.CIBE_Negocios__c = pickVal5.Id;
            jerarquia2.CIBE_RedesSegmentos__c = pickVal6.Id;
            jerarquia2.CIBE_SectoresPaises__c = pickVal7.Id;
            jerarquia2.CIBE_CentrosCarteras__c = pickVal8.Id;
            jerarquia2.CIBE_Contact__c = contacto.Id;
            jerarquia2.RecordTypeId = rtJerarquia;
            insert jerarquia2;
            
            Product2 prodPF = CIBE_TestHelper.createProduct(null,null);
            RecordType rt = CIBE_AppUtilities.getRecordType(CIBE_AppConstants.OBJECT_NAME_OPPORTUNITY, CIBE_AppConstants.OPP_INICIATIVACIB_RT);
            //creamos la oportunidad
            Opportunity opp = new Opportunity();
            opp.CIBE_Fechaaprobacionprecio__c = Date.newInstance(2023, 02, 03);
            opp.AccountId = cliente.Id;
            opp.Name = 'Alerta Comercial';
            opp.StageName = 'En curso';
            opp.RecordTypeId = rt.Id;
            opp.CloseDate = System.today() + 5;
            opp.AV_PF__c = prodPF.Id;
            opp.CIBE_AmountDivisa__c = 2;
            opp.CIBE_Divisa__c = 'USD';
            opp.CIBE_BalanceDivisa__c = 342.874;
            opp.CIBE_ComisionesDivisa__c = 323;
            opp.CIBE_Balance__c = 342.874;
            opp.CIBE_Comisiones__c = 323.248;
            opp.CIBE_TipoOperacion__c = 'Nueva';
            opp.CIBE_ProbabilidadExito__c = 'Alta';
            opp.CIBE_CerradoNegativo__c = 'Anulada';
            opp.CIBE_ESG__c = false;
            opp.CIBE_ECAs__c = true;
            opp.CIBE_AlgunaOperRAR__c = true;
            opp.CIBE_DictamenALM__c = false;
            opp.CIBE_Visto__c = 'IG';
            opp.CIBE_Nivel__c = '';
            opp.CIBE_Sindicaciones__c = false;
            opp.CIBE_Observaciones__c = '';
            opp.CIBE_VigenciaOferta__c = null;
            opp.OwnerId = usuario.Id;
            opp.AV_FechaAlta__c = System.today() - 5;
            insert opp;
        }
    }
    
    @isTest
    public static void getOpportunityTest() {
        User usuario = [SELECT Id FROM User WHERE AV_ExternalID__c = 'U0000001'];
        
        Test.startTest();
        System.runAs(usuario) {
            Date fecha = Date.newInstance(2023, 02, 03);
            Date fechaDesde = null;
            Date fechaHasta = null;

            List<CIBE_TabListOpportunityCIB_Controller.OpportunityWrapper> wrapperList = CIBE_TabListOpportunityCIB_Controller.getOpportunity(0, fecha, fechaDesde, fechaHasta);
            System.assert(!wrapperList.isEmpty());
        }
        Test.stopTest();
    }
    
    @isTest
    public static void exportTest() {
        User usuario = [SELECT Id FROM User WHERE AV_ExternalID__c = 'U0000001'];
        
        Test.startTest();
        System.runAs(usuario) {
            Date fecha = Date.newInstance(2023, 02, 03);
            Date fechaDesde = null;
            Date fechaHasta = null;

            List<String> csv = CIBE_TabListOpportunityCIB_Controller.exportOpportunities();
            System.assert(!csv.isEmpty());
        }
        Test.stopTest();
    }
}