force-app/main/default/objects/Account/fields/OS_Cartera__c.field-meta.xml
<CustomField>
    <fullName>OS_Cartera__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cartera</label>
    <referenceTo>OS_Cartera__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CC_CentroCaixaBank.recordType-meta.xml
<RecordType>
    <fullName>CC_CentroCaixaBank</fullName>
    <active>true</active>
    <label>Centro CaixaBank</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CC_Inactivo__c.field-meta.xml
<CustomField>
    <fullName>CC_Inactivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactivo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/CC_Empleado.recordType-meta.xml
<RecordType>
    <fullName>CC_Empleado</fullName>
    <active>true</active>
    <label>Empleado</label>
</RecordType>

force-app/main/default/objects/OS_Cartera__c/OS_Cartera__c.object-meta.xml
<CustomObject>
    <description>Objeto para almacenar la cola de telefonía y su grupo de trabajo</description>
    <label>Cartera</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CSBD_WS_PreAltaOportunidad.cls
// @RestResource(urlMapping='/PreAltaOportunidad/*')
public with sharing class CSBD_WS_PreAltaOportunidad extends CBK_HttpServiceIntegration_Abstract {


    public with sharing class Output {
        public String referenciaUsuario {get;set;}
        public String resultado {get;set;}
        public String codigoError {get;set;}
        public String detalleError {get;set;}
        public String opportunityId {get;set;}
        public String opportunityNumero {get;set;}
        public String detalleOportunidad {get;set;}
    }


    // @HttpGet
    public static Output preAltaOportunidad() {
        Output output = new Output();
        output.referenciaUsuario =  UUID.randomUUID().toString();
        output.resultado = 'OK';
        output.codigoError = '0';
        output.detalleError = null;
        output.opportunityId = null;
        output.opportunityNumero = null;
        output.detalleOportunidad = null;
        return output;

        Contact empleado = [SELECT AccountId, Name, Phone FROM Contact
                            WHERE Account.RecordType.DeveloperName = 'CC_CentroCaixaBank' AND RecordType.DeveloperName = 'CC_Empleado'
                            AND (Phone = :valor OR MobilePhone = :valor) AND CC_Inactivo__c = false LIMIT 1];

    // Recuperar las cuentas de los contactos
    Set<Id> idCuentas = new Set<Id>();
    Set<Id> idCuentasEmpleados = new Set<Id>();
    for (Contact contacto : contactos) {
        idCuentasEmpleados.add(contacto.AccountId);
        contactosEmpleados.add(contacto);
    }
    else {
        for (Account cuenta : [SELECT RecordType.DeveloperName, Name, OS_Cartera__c FROM Account WHERE Id IN :idCuentas]) {
            //Añadimos cada cuenta al mapa con la lista de sus contactos encontrados
            List<Contact> contactosCuenta = new List<Contact>();
            for (Contact contacto : contactos) {
                if (contacto.AccountId == cuenta.Id) {
                    contactosCuenta.add(contacto);
                }
            }
            resultados.put(cuenta, contactosCuenta);
        }
    }
    return resultados;
    }
}