force-app/main/default/objects/CC_Config_Stores__mdt/CC_Config_Stores__mdt.object-meta.xml
<CustomObject>
    <label>Configuración de Store</label>
    <pluralLabel>Configuración de Stores</pluralLabel>
</CustomObject>

force-app/main/default/objects/CC_Config_Stores__mdt/fields/Identificador__c.field-meta.xml
<CustomField>
    <fullName>Identificador__c</fullName>
    <label>Identificador</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Config_Stores__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google Play</fullName>
                <default>true</default>
                <label>Google Play</label>
            </value>
            <value>
                <fullName>Apple Store</fullName>
            </value>
            <value>
                <fullName>Huawei Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_ST_AppReviews__c/CC_ST_AppReviews__c.object-meta.xml
<CustomObject>
    <label>App Reviews</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>AppReview Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_ST_AppReviews__c/fields/App__c.field-meta.xml
<CustomField>
    <fullName>App__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_ST_AppReviews__c/fields/App_ID__c.field-meta.xml
<CustomField>
    <fullName>App_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>App ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_ST_AppReviews__c/fields/Author_Name__c.field-meta.xml
<CustomField>
    <fullName>Author_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Author Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_ST_AppReviews__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apple App Store</fullName>
            </value>
            <value>
                <fullName>Google Play Store</fullName>
            </value>
            <value>
                <fullName>Huawei App Store</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Google_SA_Token__c/Google_SA_Token__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google SA Token</label>
</CustomObject>

force-app/main/default/classes/CC_ST_ReviewsHuaweiBatch_Test.cls
@istest
public with sharing class CC_ST_ReviewsHuaweiBatch_Test {
	
    @testSetup
    static void datos(){
	
    	Google_SA_Token__c tokenSA = new Google_SA_Token__c();
        tokenSA.Name = 'Huawei_Store';
        tokenSA.Timestamp__c = null;
        tokenSA.Value__c = '';
        insert tokenSA;
        
        CC_ST_AppReviews__c st1 = new CC_ST_AppReviews__c();
        st1.Source__c = 'Huawei App Store';
        st1.App__c = 'CaixaBank';
        st1.App_ID__c = '111111111111';
        st1.Author_Name__c = 'ST1';
        insert st1;
        
        CC_ST_AppReviews__c st2 = new CC_ST_AppReviews__c();
        st2.Source__c = 'Huawei App Store';
        st2.App__c = 'CaixaBank';
        st2.App_ID__c = '111111111112';
        st2.Author_Name__c = 'ST2';
        insert st2;

    }
    
    @istest
    public static void test() {
        
        Test.StartTest();
        CC_ST_ReviewsHuaweiBatch batch = new CC_ST_ReviewsHuaweiBatch();
		Database.executeBatch(batch);
        Test.stopTest();
        
        List<CC_Config_Stores__mdt> lstConf = [Select DeveloperName, Identificador__c, countryCode__c, Tipo__c from CC_Config_Stores__mdt where Activo__c = true];
        
        system.assert(lstConf.size()>0, 'Comprobamos existe configuración para los comentarios.');
    }
    
}