force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Codigo_Externo__c.field-meta.xml
<CustomField>
    <fullName>CC_Codigo_Externo__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Código Externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Producto_Servicio__c.field-meta.xml
<CustomField>
    <fullName>CC_Producto_Servicio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup para poder seleccionar un producto/servicio.</description>
    <label>Producto/Servicio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>B - Producto/Servicio</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Motivos</relationshipLabel>
    <relationshipName>CC_MCC_Motivos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tematica__c.field-meta.xml
<CustomField>
    <fullName>CC_Tematica__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup para poder seleccionar una temática.</description>
    <label>Temática</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>A - Temática</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipLabel>Productos/Servicios</relationshipLabel>
    <relationshipName>CC_MCC_Productos_Servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_Tipo_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CC_Tipo_Cliente__c</fullName>
    <label>Tipo cliente</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente/Empleado</fullName>
            </value>
            <value>
                <fullName>Prejubilado</fullName>
            </value>
            <value>
                <fullName>Proveedor / Empleado</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)</fullName>
            </value>
            <value>
                <fullName>Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (COPS)/Empleado (COPS)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)</fullName>
            </value>
            <value>
                <fullName>Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>Cliente (CAM)/Empleado (CAM)</fullName>
            </value>
            <value>
                <fullName>CSI Bankia</fullName>
            </value>
            <value>
                <fullName>SAC</fullName>
            </value>
            <value>
                <fullName>Segmentos</fullName>
            </value>
            <value>
                <fullName>Cliente (SACH)</fullName>
            </value>
            <value>
                <fullName>Cliente (FRA)</fullName>
            </value>
            <value>
                <fullName>HDT Empleado</fullName>
                <label>Empleado (HDT)</label>
            </value>
            <value>
                <fullName>Cliente (GRR)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Motivo.recordType-meta.xml
<RecordType>
    <fullName>CC_Motivo</fullName>
    <active>true</active>
    <label>C - Motivo</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Producto_Servicio.recordType-meta.xml
<RecordType>
    <fullName>CC_Producto_Servicio</fullName>
    <active>true</active>
    <label>B - Producto/Servicio</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_Tematica.recordType-meta.xml
<RecordType>
    <fullName>CC_Tematica</fullName>
    <active>true</active>
    <label>A - Temática</label>
</RecordType>

force-app/main/default/objects/CC_MCC__c/recordTypes/SAC_Detalle.recordType-meta.xml
<RecordType>
    <fullName>SAC_Detalle</fullName>
    <active>true</active>
    <label>SAC_Detalle</label>
</RecordType>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/SAC_ParametrizacionSLATME__c.object-meta.xml
<CustomObject>
    <label>Parametrización SLA / TMO</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizaciones SLA / TMO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_CanalProcedencia__c.field-meta.xml
<CustomField>
    <fullName>SAC_CanalProcedencia__c</fullName>
    <label>Procedencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CC_Canal_Procedencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_Duracion__c.field-meta.xml
<CustomField>
    <fullName>SAC_Duracion__c</fullName>
    <label>Duración(Días)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/fields/SAC_MCC__c.field-meta.xml
<CustomField>
    <fullName>SAC_MCC__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MCC</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CC_MCC__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>SAC Detalle</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CC_MCC__c</referenceTo>
    <relationshipName>Parametrizaciones_SLA_TME</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAC_ParametrizacionSLATME__c/recordTypes/SAC_Maestro.recordType-meta.xml
<RecordType>
    <fullName>SAC_Maestro</fullName>
    <active>true</active>
    <description>Record type para la insercción de las parametrizaciones SLA/TMO en los MCC Detalle</description>
    <label>Maestro</label>
</RecordType>

force-app/main/default/classes/SAC_MCC_AI_TRHan_Test.cls
/*****************************************************************
 * Name: SAC_MCC_AI_TRHan_Test
 * Copyright © 2021  CaixaBank
 *  
 * Proposito: Test para la clase SAC_MCC_AI_TRHan
 *  
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR               DATE         Description
 * 1.0            US515086  	   Sergio Martín        07/02/23     Creación
 * 1.1            US643756         Jose Carlos Blanco  	04/07/23     Modificación (test modificada usando el SAC_TestDataFactory) 
*****************************************************************/
@isTest
public with sharing class SAC_MCC_AI_TRHan_Test {
    @TestSetup
    static void makeData(){
        String mccTematicaRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Tematica').getRecordTypeId();
        String mccProdServRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Producto_Servicio').getRecordTypeId();
        String mccMotivoRecordTypeId = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_Motivo').getRecordTypeId();


        CC_MCC__c mccTematica = new CC_MCC__c(Name='Tematica', CC_Codigo_Externo__c='a', RecordTypeId=mccTematicaRecordTypeId, CC_Tipo_Cliente__c='Empleado');

        CC_MCC__c mccProdServ = new CC_MCC__c(Name='ProdServ',CC_Tematica__c = mccTematica.id , CC_Codigo_Externo__c='b', RecordTypeId=mccProdServRecordTypeId, CC_Tipo_Cliente__c='Cliente');

        CC_MCC__c mccMotivo = new CC_MCC__c(Name='Motivo',CC_Producto_Servicio__c = mccProdServ.id, CC_Codigo_Externo__c='c', RecordTypeId=mccMotivoRecordTypeId, CC_Tipo_Cliente__c='Cliente');

        List<CC_MCC__c> listaMCCs = new List<CC_MCC__c>();
        listaMCCs.add(mccTematica);
        listaMCCs.add(mccProdServ);
        listaMCCs.add(mccMotivo);
        Database.insert(listaMCCs);

        User usuarioGeneral;
        System.runAs(new User(Id = Userinfo.getUserId())) {
            //Usuario SAC General
            usuarioGeneral = SAC_TestDataFactory.crearUsuarioSACGeneral(1)[0];     
            Database.insert(usuarioGeneral);
        }
    }

    @isTest
    static void asignacionParametrizacionSLATME_Test() { 
        String recordTypeIdMCCDetalle = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('SAC_Detalle').getRecordTypeId();
        Id rtMaestro = Schema.SObjectType.SAC_ParametrizacionSLATME__c.getRecordTypeInfosByDeveloperName().get('SAC_Maestro').getRecordTypeId();

        CC_MCC__c mccMotivo = [SELECT id FROM CC_Mcc__c WHERE CC_Codigo_Externo__c='c' LIMIT 1];
        CC_MCC__c mccDetalle = new CC_MCC__c(Name='Banca Electrónica', CC_Codigo_Externo__c='d', RecordTypeId=recordTypeIdMCCDetalle, CC_Tipo_Cliente__c='SAC');

        Test.startTest();
        User usuario = [SELECT id FROM User WHERE Username = 'usertest0@test.com.testSetup' AND IsActive = true LIMIT 1];
		PermissionSet ps = [select id from PermissionSet where PermissionSet.Label ='SAC_General'];
        PermissionSetAssignment psa = new PermissionSetAssignment (PermissionSetId = ps.id, AssigneeId = usuario.id);
        Database.insert(psa);

        PermissionSet ps2 = [select id from PermissionSet where PermissionSet.Label ='SAC_Administrador'];
        PermissionSetAssignment psa2 = new PermissionSetAssignment (PermissionSetId = ps2.id, AssigneeId = usuario.id);
        Database.insert(psa2);
        
        System.runAs(usuario) {
            SAC_ParametrizacionSLATME__c parametrizacion1 = new SAC_ParametrizacionSLATME__c (Name = 'Test Regulatorio Junta Andalucía', SAC_Duracion__c = 10 , SAC_CanalProcedencia__c = 'Junta Andalucia', RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion2 = new SAC_ParametrizacionSLATME__c (Name = 'Test Letrado Junta Andalucía', SAC_Duracion__c = 5 , SAC_CanalProcedencia__c = 'Junta Andalucia', RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion3 = new SAC_ParametrizacionSLATME__c (Name = 'TestAlta Junta Andalucía', SAC_Duracion__c = 1 , SAC_CanalProcedencia__c = 'Junta Andalucia', RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion4 = new SAC_ParametrizacionSLATME__c (Name = 'Test Regulatorio', SAC_Duracion__c = 30 , RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion5 = new SAC_ParametrizacionSLATME__c (Name = 'Test Alta', SAC_Duracion__c = 1 , RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion6 = new SAC_ParametrizacionSLATME__c (Name = 'Test Letrado', SAC_Duracion__c = 15 , RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion7 = new SAC_ParametrizacionSLATME__c (Name = 'Test Regulatorio Castilla La Mancha', SAC_Duracion__c = 10 , SAC_CanalProcedencia__c = 'Castilla La Mancha', RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion8 = new SAC_ParametrizacionSLATME__c (Name = 'Test Letrado Castilla La Mancha', SAC_Duracion__c = 5 , SAC_CanalProcedencia__c = 'Castilla La Mancha', RecordTypeId = rtMaestro);
            SAC_ParametrizacionSLATME__c parametrizacion9 = new SAC_ParametrizacionSLATME__c (Name = 'Test Alta Castilla La Mancha', SAC_Duracion__c = 1 , SAC_CanalProcedencia__c = 'Castilla La Mancha', RecordTypeId = rtMaestro);
            
            List<SAC_ParametrizacionSLATME__c> listaParametrizaciones = new List<SAC_ParametrizacionSLATME__c>();
            listaParametrizaciones.add(parametrizacion1);
            listaParametrizaciones.add(parametrizacion2);
            listaParametrizaciones.add(parametrizacion3);
            listaParametrizaciones.add(parametrizacion4);
            listaParametrizaciones.add(parametrizacion5);
            listaParametrizaciones.add(parametrizacion6);
            listaParametrizaciones.add(parametrizacion7);
            listaParametrizaciones.add(parametrizacion8);
            listaParametrizaciones.add(parametrizacion9);
            Database.insert(listaParametrizaciones);

            Database.insert(mccDetalle);
            Database.update(mccDetalle);
        }   
        Test.stopTest();

        List<SAC_ParametrizacionSLATME__c> lstParametrizaciones = [SELECT Id, name, SAC_Duracion__c, SAC_CanalProcedencia__c FROM SAC_ParametrizacionSLATME__c WHERE RecordType.id =: rtMaestro];
        
        // Se comprueban si se han insertado las 9 parametrizaciones con Record Type "Maestro"
        List<SAC_ParametrizacionSLATME__c> parametrizacionesInsertadas = [SELECT id FROM SAC_ParametrizacionSLATME__c WHERE SAC_MCC__c =: mccDetalle.id];
        System.assertEquals(lstParametrizaciones.size(), parametrizacionesInsertadas.size(), 'No se han insertado todas la parametrizaciones.');      
    }
}