force-app/main/default/objects/CC_MCC__c/CC_MCC__c.object-meta.xml
<CustomObject>
    <description>Entidad para la administración del MCC.</description>
    <label>MCC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_MCC__c/fields/CC_Equivalencia_Formulario__c.field-meta.xml
<CustomField>
    <fullName>CC_Equivalencia_Formulario__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Clasificación externa</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_MCCWeb_Ambito__c.field-meta.xml
<CustomField>
    <fullName>CC_MCCWeb_Ambito__c</fullName>
    <description>Código de ámbito del formulario web</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Código de ámbito del formulario web</inlineHelpText>
    <label>Ámbito Web</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_MCCWeb_Motivo__c.field-meta.xml
<CustomField>
    <fullName>CC_MCCWeb_Motivo__c</fullName>
    <description>Código de motivo de los formularios web</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Código de motivo de los formularios web</inlineHelpText>
    <label>Motivo Web</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_MCCWeb_Origen__c.field-meta.xml
<CustomField>
    <fullName>CC_MCCWeb_Origen__c</fullName>
    <description>Código de origen del formulario web</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Código de origen del formulario web</inlineHelpText>
    <label>Origen Web</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/fields/CC_MCCWeb_Producto__c.field-meta.xml
<CustomField>
    <fullName>CC_MCCWeb_Producto__c</fullName>
    <description>Código de producto del formulario web</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Código de producto del formulario web</inlineHelpText>
    <label>Producto Web</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_MCC__c/recordTypes/CC_ConvMCCWeb.recordType-meta.xml
<RecordType>
    <fullName>CC_ConvMCCWeb</fullName>
    <active>true</active>
    <description>Registros para la equivalencia del MCC entre Web y Salesforce</description>
    <label>Conversion MCC Web</label>
</RecordType>

force-app/main/default/classes/CC_MCC_BU_TRHan.cls
public with sharing class CC_MCC_BU_TRHan extends CC_TriggerHandlerBase{
    public override void mainEntry(CC_TriggerParameters tp) {
		process((List<CC_MCC__c>)tp.newList, (Map<Id, CC_MCC__c>)tp.oldMap);
    }

    private void process(List<CC_MCC__c> listNewObj, Map<Id, CC_MCC__c> mapOldObj) { //Map<Id, CC_MCC__c> mapNewObj
        Id rtConversionWeb = Schema.SObjectType.CC_MCC__c.getRecordTypeInfosByDeveloperName().get('CC_ConvMCCWeb').getRecordTypeId();
        //Actualizar el nombre y la equivalencia del formulario para los registros de tipo ConvMCCWeb
        for(CC_MCC__c mcc : listNewObj){
            if(mcc.RecordTypeId == rtConversionWeb){
                
                mcc.Name = ((mcc.CC_MCCWeb_Origen__c!=null)? mcc.CC_MCCWeb_Origen__c:'')+'-'+((mcc.CC_MCCWeb_Motivo__c!=null)? mcc.CC_MCCWeb_Motivo__c:'')+'-'+((mcc.CC_MCCWeb_Producto__c!=null)? mcc.CC_MCCWeb_Producto__c:'')+'-'+((mcc.CC_MCCWeb_Ambito__c!=null)? mcc.CC_MCCWeb_Ambito__c:'');
                mcc.CC_Equivalencia_Formulario__c = ((mcc.CC_MCCWeb_Origen__c!=null)? mcc.CC_MCCWeb_Origen__c:'')+'-'+((mcc.CC_MCCWeb_Motivo__c!=null)? mcc.CC_MCCWeb_Motivo__c:'')+'-'+((mcc.CC_MCCWeb_Producto__c!=null)? mcc.CC_MCCWeb_Producto__c:'')+'-'+((mcc.CC_MCCWeb_Ambito__c!=null)? mcc.CC_MCCWeb_Ambito__c:'');
            }
        }
    }
}