force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contenido</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/CSBD_NombresProductos__c.field-meta.xml
<CustomField>
    <fullName>CSBD_NombresProductos__c</fullName>
    <description>Tiene los nombres de los productos asociados a este articulo. Usa los valores que hay en CSBD_Producto__c.</description>
    <label>Nombres Productos</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deposito Bonificado</fullName>
            </value>
            <value>
                <fullName>MyBox Vida</fullName>
            </value>
            <value>
                <fullName>MyBox Auto TR</fullName>
            </value>
            <value>
                <fullName>MyBox Hogar</fullName>
            </value>
            <value>
                <fullName>MyBox Salud</fullName>
            </value>
            <value>
                <fullName>Mascotas</fullName>
            </value>
            <value>
                <fullName>Seviam</fullName>
            </value>
            <value>
                <fullName>MyBox Jubilación</fullName>
            </value>
            <value>
                <fullName>Nómina</fullName>
            </value>
            <value>
                <fullName>MyCard Imagin</fullName>
            </value>
            <value>
                <fullName>MyBox Auto</fullName>
            </value>
            <value>
                <fullName>MyCard</fullName>
            </value>
            <value>
                <fullName>Nomina</fullName>
            </value>
            <value>
                <fullName>MyBox Alarmas</fullName>
            </value>
            <value>
                <fullName>Previsión Profesional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Producto__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Producto__c</fullName>
    <label>Producto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accidentes</fullName>
            </value>
            <value>
                <fullName>Acción PREMIER</fullName>
            </value>
            <value>
                <fullName>Activación tarjetas errores</fullName>
            </value>
            <value>
                <fullName>Activa Tarjeta de prepago/ regalo</fullName>
            </value>
            <value>
                <fullName>Adeslas pymes</fullName>
            </value>
            <value>
                <fullName>Alarma</fullName>
            </value>
            <value>
                <fullName>Alta Cliente</fullName>
            </value>
            <value>
                <fullName>Alta Cliente Digital</fullName>
            </value>
            <value>
                <fullName>Alta Cliente Holabank</fullName>
            </value>
            <value>
                <fullName>Alta Cliente Residentes</fullName>
            </value>
            <value>
                <fullName>Alta clientes Kids&amp;Teens</fullName>
            </value>
            <value>
                <fullName>Alta Cuenta</fullName>
            </value>
            <value>
                <fullName>Alta Cuenta Multititulares</fullName>
            </value>
            <value>
                <fullName>Alta digital de menores</fullName>
            </value>
            <value>
                <fullName>Alta nuevo cliente</fullName>
            </value>
            <value>
                <fullName>Altas Digitales</fullName>
            </value>
            <value>
                <fullName>Asistencia en viaje</fullName>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Auto &amp; Moto</fullName>
            </value>
            <value>
                <fullName>Autónomos</fullName>
            </value>
            <value>
                <fullName>Bajas Imagin</fullName>
            </value>
            <value>
                <fullName>Básico</fullName>
            </value>
            <value>
                <fullName>Baterias solares</fullName>
            </value>
            <value>
                <fullName>Bienvenida</fullName>
            </value>
            <value>
                <fullName>Building Center</fullName>
            </value>
            <value>
                <fullName>C&amp;G</fullName>
            </value>
            <value>
                <fullName>C&amp;G LEADS PORTAL</fullName>
            </value>
            <value>
                <fullName>C&amp;G LONO PORTAL</fullName>
            </value>
            <value>
                <fullName>CaixaBank Now</fullName>
            </value>
            <value>
                <fullName>Caixa Futuro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSBD_ArticulosProducto.cls
/*****************************************************************
 * Name: CSBD_ArticulosProducto
 * Copyright © 2024  CaixaBank
 * 
 * Proposito: Buscar los articulos del producto asociado a la oportunidad
 * 
 * Historial
 * -------
 * VERSION        USER_STORY       AUTHOR            DATE         Description
 * 1.0            US967512         David Ramos       01/08/24     Creación
*****************************************************************/
/**
 * @description     clase invocable para Obtener los articulos del producto asociado a la oportunidad
 */
public with sharing class CSBD_ArticulosProducto {
    @InvocableMethod(label='Buscar articulos producto'
      description='Buscar los articulos del producto asociado a la oportunidad '
      CapabilityType='PromptTemplateType://einstein_gpt__recordSummary')
    public static List<Response> buscarArticulos(List<Request> requests) {
        // validate the expected number of requests as an input
        if (requests.size() != 1){
            throw new ListException('The requests list must contain one entry only');
        }
        Opportunity opo = requests[0].objectToSummarize;
        string responseData = '';
        //segun CSBD_WS_AltaOportunidad_Campos.informarEmpresaFamiliaProducto se tendria que poner el nombre del producto 
        //en CSBD_Producto__c
        String casteoNombreProd = opo.CSBD_Producto__c;
        if (casteoNombreProd != null){
            // List<Knowledge__kav> acticulosProducto =
            //      [SELECT Id, Title, Question__c, Answer__c, CSBD_NombresProductos__c
            //          FROM Knowledge__kav
            //          WHERE Title Like :casteoNombreProd]; 
            List<Knowledge__kav> acticulosProducto =
                [SELECT Id, Title, Question__c, Answer__c, CSBD_NombresProductos__c
                    FROM Knowledge__kav
                    WHERE CSBD_NombresProductos__c INCLUDES (:casteoNombreProd) AND PublishStatus = 'Online' WITH SECURITY_ENFORCED]; 
            if(acticulosProducto.isEmpty()) {
                responseData = 'No se han encontrado articulos relacionados con ese producto.';
            } else {
                // TodosArticulosProducto conjuntoArt = new TodosArticulosProducto();
                // conjuntoArt.articulos = new list<DatosArticulo>();
                for(Knowledge__kav k : acticulosProducto) {
                    // DatosArticulo datosArt = new DatosArticulo();
                    // datosArt.title = k.Title;
                    // datosArt.question = k.Question__c.stripHtmlTags();
                    // datosArt.answer = k.Answer__c.stripHtmlTags();
                    // datosArt.productos = k.CSBD_NombresProductos__c;

                    // conjuntoArt.articulos.add(datosArt);

                        //responseData += 'Detalles MyBox Auto :/n';

						responseData += 'Detalles ' + k.Title + ':/n';
                        //que solo se añada contenido a la response si el campo no es nulo
                        responseData += k.Question__c != null ? k.Question__c.stripHtmlTags()+'/n' : '';
                        responseData += k.Answer__c != null ? k.Answer__c.stripHtmlTags()+'/n' : '';
                }
                // responseData += JSON.serialize(conjuntoArt);
            }
        }
        else {
            responseData = 'No hay un producto en CSBD_Producto__c.';
        }
        List<Response> responses = new List<Response>();
        Response res = new Response();
        res.Prompt = responseData;
        responses.add(res);
        return responses;
    }

    public class Request {
        @InvocableVariable
        public Opportunity objectToSummarize;
    }

    public class Response {
        @InvocableVariable
        public String Prompt;
    }

    public class TodosArticulosProducto {
        list<DatosArticulo> articulos;
    }

    public class DatosArticulo {
        string title;
        string question;
        string answer;
        string productos;
    }
}