force-app/main/default/objects/CBK_Framework_Batch__c/CBK_Framework_Batch__c.object-meta.xml
<CustomObject>
    <label>Framework Batch</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Dependencia__c.field-meta.xml
<CustomField>
    <fullName>Dependencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dependencia</label>
    <referenceTo>CBK_Framework_Batch__c</referenceTo>
    <relationshipLabel>Framework Batch</relationshipLabel>
    <relationshipName>Framework_Batch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Email_Notif__c.field-meta.xml
<CustomField>
    <fullName>Email_Notif__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Notificación</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/JobPath__c.field-meta.xml
<CustomField>
    <fullName>JobPath__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>JobPath</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/NextExec__c.field-meta.xml
<CustomField>
    <fullName>NextExec__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Próxima Ejecución</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Notif__c.field-meta.xml
<CustomField>
    <fullName>Notif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notificar errores</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/params__c.field-meta.xml
<CustomField>
    <fullName>params__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parámetros</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Proyecto__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Proyecto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/runningJobId__c.field-meta.xml
<CustomField>
    <fullName>runningJobId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Job en ejecución</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estado</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Framework_Batch__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Periodico</fullName>
                <label>Periódico</label>
            </value>
            <value>
                <fullName>Puntual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CBK_Log__c/CBK_Log__c.object-meta.xml
<CustomObject>
    <label>Framework Loging</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Loging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Apex Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <defaultValue>100</defaultValue>
    <label>Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/createdDate__c.field-meta.xml
<CustomField>
    <fullName>createdDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Inicio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/FwkJobId__c.field-meta.xml
<CustomField>
    <fullName>FwkJobId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Framework Batch</label>
    <referenceTo>CBK_Framework_Batch__c</referenceTo>
    <relationshipName>Framework_Logging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/jobType__c.field-meta.xml
<CustomField>
    <fullName>jobType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>jobType</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/Log_Message__c.field-meta.xml
<CustomField>
    <fullName>Log_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Log Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/priority__c.field-meta.xml
<CustomField>
    <fullName>priority__c</fullName>
    <label>Prioridad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/retries__c.field-meta.xml
<CustomField>
    <fullName>retries__c</fullName>
    <label>retries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/state__c.field-meta.xml
<CustomField>
    <fullName>state__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/fields/systemModstamp__c.field-meta.xml
<CustomField>
    <fullName>systemModstamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>systemModstamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_Log__c/recordTypes/Async_Apex_Job.recordType-meta.xml
<RecordType>
    <fullName>Async_Apex_Job</fullName>
    <active>true</active>
    <label>Async Apex Job</label>
</RecordType>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/CBK_SCH_PendingProcess__c.object-meta.xml
<CustomObject>
    <label>CBK SCH PendingProcess</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Schedule Pendig Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CBK SCH PendingProcess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/CBK_ParamTextArea__c.field-meta.xml
<CustomField>
    <fullName>CBK_ParamTextArea__c</fullName>
    <description>Parámetro que permite indicar gran cantidad de texto</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ParamTextArea</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Check__c.field-meta.xml
<CustomField>
    <fullName>Check__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Check</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Param1__c.field-meta.xml
<CustomField>
    <fullName>Param1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Param1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Param2__c.field-meta.xml
<CustomField>
    <fullName>Param2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Param2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/QueuedDate__c.field-meta.xml
<CustomField>
    <fullName>QueuedDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>QueuedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Retries__c.field-meta.xml
<CustomField>
    <fullName>Retries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Schedule_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CBK_SCH_PendingProcess__c/fields/UsuarioContexto__c.field-meta.xml
<CustomField>
    <fullName>UsuarioContexto__c</fullName>
    <label>Usuario de contexto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSBD</fullName>
                <label>Now in Sales</label>
            </value>
            <value>
                <fullName>CC</fullName>
                <label>Now in Contact</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Mis Clientes</label>
            </value>
            <value>
                <fullName>EV</fullName>
                <label>Eventos</label>
            </value>
            <value>
                <fullName>CIBE</fullName>
            </value>
            <value>
                <fullName>MCSOL</fullName>
                <label>MC Solutions</label>
            </value>
            <value>
                <fullName>SEG</fullName>
                <label>Segmentos</label>
            </value>
            <value>
                <fullName>SACH</fullName>
            </value>
            <value>
                <fullName>CAM</fullName>
            </value>
            <value>
                <fullName>OS</fullName>
                <label>COPS</label>
            </value>
            <value>
                <fullName>OT</fullName>
                <label>Oficina Técnica</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CBK_ContextTrigger_Helper.cls
public without Sharing class CBK_ContextTrigger_Helper {
   
    /**
     * @description Helper para triggers de eventos de FWK Batch
     * @param batchJob  : Id del Batch planificable
     */
    public static void procesaBatchApex(list<String> lstJobs){      
        
        Id recordTypeId =Schema.SObjectType.CBK_Log__c.getRecordTypeInfosByDeveloperName().get('Async_Apex_Job').getRecordTypeId();
        list<Id> lstJobId = New list<Id>();    
        Map<Id,String> mapStatus = New Map<Id,String>();
        list<CBK_Log__c> lstDetail = New list<CBK_Log__c>();
        list<CBK_Framework_Batch__c> lstJobDef = [select Id,Name,status__c,Class_Name__c,batchSize__c,params__c,tipo__c,priority__c,proyecto__c,NextExec__c, Activo__c,
                                                           Email_Notif__c, Notif__c,RunningJobId__c,dependencia__r.Name,JobPath__c
                                                        from CBK_Framework_Batch__c 
                                                       where id in :lstJobs
                                                       LIMIT 20];
        Id batchprocessid;
        for (CBK_Framework_Batch__c jobDef : lstJobDef) {
            try {
                cbk_log.debug(jobDef.name);
                map<String,Object> params = New map<String,Object>();
                if(jobDef.params__c!=null){        
                    params = (Map<String, Object>)JSON.deserializeUntyped(jobDef.params__c);
                }
                
                batchprocessid = CBK_BatchJob.runBatch(jobDef.Class_Name__c, (integer)jobDef.batchSize__c, params);
                lstJobId.add(batchprocessid);
                jobDef.RunningJobId__c=batchprocessid; 
                
                if (jobDef.NextExec__c==null) {
                    jobDef.NextExec__c=DateTime.now();
                }
            } catch (Exception e) {
                CBK_BatchJob_Helper.errorJob(e, jobDef);                
                CBK_Log__c detail = New CBK_Log__c ();    
                detail.recordtypeId = recordTypeId;
                detail.FwkJobId__c = jobDef.Id;
                detail.Apex_Class__c=jobDef.Class_Name__c;
                detail.state__c = 'Error';
                detail.batchSize__c=jobDef.BatchSize__c;
                detail.params__c = jobDef.params__c;
                detail.jobType__c = jobDef.tipo__c;
                detail.priority__c = jobDef.priority__c;
                detail.project__c = jobDef.proyecto__c;
                detail.Log_Message__c = e.getMessage()?.left(2000);
                detail.createdDate__c = System.now();
                detail.systemModstamp__c = System.now();
                lstDetail.add(detail);
                
                if(jobDef.Tipo__c=='Puntual'){ 
                    jobDef.NextExec__c=null;
                    jobDef.status__c='Error';
                }
            }
        }
        
        list<AsyncApexJob> lstStatus = [SELECT Id, Status FROM AsyncApexJob WHERE ID =: lstJobId];
            
        for (AsyncApexJob iStatus : lstStatus){
            mapStatus.put(iStatus.Id,iStatus.Status);
        }
        
        for (CBK_Framework_Batch__c jobDef : lstJobDef) {
            if (jobDef.RunningJobId__c!=null){
                jobDef.status__c=mapStatus.get(jobDef.RunningJobId__c);     
            }
        }
        database.update(lstJobDef,false);
        database.insert(lstDetail,false);
    }
    /**
     * @description Helper para triggers de eventos de FWK de Schedulables Process
     * @param lstJobs  : List Ids del procesos Schedulable
     */
    public static void procesaSchedProc(list<String> lstJobs){  
        system.debug('ENTRA procesaSchedProc: ' + lstJobs);
        string DISPACHER_SCH = 'CBK_ScheduleProcess_Dispacher';
        
        List<CBK_SCH_PendingProcess__c> lstPP = [SELECT Id, ClassName__c, Type__c, RecordId__c, Param1__c, Param2__c, Check__c, Retries__c, Schedule_Time__c, QueuedDate__c,UsuarioContexto__c,CBK_ParamTextArea__c FROM CBK_SCH_PendingProcess__c
		                                         WHERE Id in :lstJobs];

        Map<String, List<CBK_SCH_PendingProcess__c>> mapPendingProcess = new Map<String, List<CBK_SCH_PendingProcess__c>> ();

        for (CBK_SCH_PendingProcess__c pp : lstPP){           
            if (!mapPendingProcess.containsKey(pp.ClassName__c)){
                mapPendingProcess.put(pp.ClassName__c, new List<CBK_SCH_PendingProcess__c> { pp });
            }else {
                mapPendingProcess.get(pp.ClassName__c).add(pp);
            }
        }

        if (mapPendingProcess.size()> 0)
		{
            Type typeProcessAction = Type.forName(DISPACHER_SCH);
            CBK_log.debug('CBK_ScheduleProcess_Controller - ' + DISPACHER_SCH + ' Map: ' + mapPendingProcess, LoggingLevel.INFO);	
    	    CBK_ScheduleProcess_Abstract processAction = (CBK_ScheduleProcess_Abstract) typeProcessAction.newInstance();
        	processAction.execute(mapPendingProcess);           
        }
        
    }
}