force-app/main/default/objects/CC_Canal_Com__c/CC_Canal_Com__c.object-meta.xml
<CustomObject>
    <description>Canales de comunicación del cliente y del contacto.</description>
    <label>Canal de comunicación</label>
    <nameField>
        <displayFormat>COM-{00000000}</displayFormat>
        <label>Identificador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canales de comunicación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CC_Canal_Com__c/fields/CC_Telefono__c.field-meta.xml
<CustomField>
    <fullName>CC_Telefono__c</fullName>
    <description>Teléfono del cliente / contacto</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Teléfono del cliente / contacto</inlineHelpText>
    <label>Teléfono</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/CC_Canal_Com__c/fields/CC_TelefonoIDX__c.field-meta.xml
<CustomField>
    <fullName>CC_TelefonoIDX__c</fullName>
    <description>Campo teléfono indexado (para búsquedas)</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Campo teléfono indexado (para búsquedas)</inlineHelpText>
    <label>Teléfono (Indexado)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CC_Canal_Com__c/recordTypes/CC_Telefono.recordType-meta.xml
<RecordType>
    <fullName>CC_Telefono</fullName>
    <active>true</active>
    <description>Teléfono</description>
    <label>Teléfono</label>
</RecordType>

force-app/main/default/objects/CC_Telefono__c/CC_Telefono__c.object-meta.xml
<CustomObject>
    <label>Teléfono</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Telefono Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teléfonos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CC_Canal_Com_BU_BI_Test.cls
@isTest
public with sharing class CC_Canal_Com_BU_BI_Test {

    @isTest
    public static void testCanalComBIBU() {
        User admin = CC_TestDataFactory.getUserAdmin();
        System.runAs(admin) {
            CC_Canal_Com__c canalCom = new CC_Canal_Com__c();
            canalCom.RecordTypeId = Schema.SObjectType.CC_Canal_Com__c.getRecordTypeInfosByDeveloperName().get('CC_Telefono').getRecordTypeId();
            canalCom.CC_Telefono__c = '1234567890';
            Test.startTest();
            insert canalCom;
            canalCom = [SELECT Id, CC_TelefonoIDX__c FROM CC_Canal_Com__c WHERE Id = :canalCom.Id];
            System.assertEquals('1234567890', canalCom.CC_TelefonoIDX__c, 'El teléfono no se ha insertado correctamente');

            canalCom.CC_Telefono__c = '0987654321';
            update canalCom;
            canalCom = [SELECT Id, CC_TelefonoIDX__c FROM CC_Canal_Com__c WHERE Id = :canalCom.Id];
            System.assertEquals('0987654321', canalCom.CC_TelefonoIDX__c, 'El teléfono no se ha actualizado correctamente');

            Test.stopTest();
            


        }
    }
}