force-app/main/default/objects/CSBD_IdentificarOppsPHDSetting__c/CSBD_IdentificarOppsPHDSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Utilizado para el WS consumido desde puntos de servicio y/o plataformas hipotecarias para identificar si existen Leads (Oportunidades)</description>
    <label>CSBD Identificar Opp desde PHD</label>
</CustomObject>

force-app/main/default/objects/CSBD_IdentificarOppsPHDSetting__c/fields/CSBD_FrecuenciaAvisosAuto__c.field-meta.xml
<CustomField>
    <fullName>CSBD_FrecuenciaAvisosAuto__c</fullName>
    <defaultValue>15</defaultValue>
    <description>Frecuencia en minutos de los avisos automáticos (vacío o &quot;0&quot;: avisos desactivados)</description>
    <inlineHelpText>Frecuencia en minutos de los avisos automáticos (vacío o &quot;0&quot;: avisos desactivados)</inlineHelpText>
    <label>Frecuencia avisos automaticos (min)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_FechaEntradaUltimoLead__c.field-meta.xml
<CustomField>
    <fullName>CSBD_FechaEntradaUltimoLead__c</fullName>
    <description>Se utilizará para identificar las oportunidades que se encuentran al recibir una petición de punto de servicio con características similares.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Fecha entrada último Lead existente</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Identificador__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Identificador__c</fullName>
    <displayFormat>OP-{0000000}</displayFormat>
    <externalId>true</externalId>
    <label>Identificador</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_MostrarAviso__c.field-meta.xml
<CustomField>
    <fullName>CSBD_MostrarAviso__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mostrar aviso</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_Now_Origen__c.field-meta.xml
<CustomField>
    <fullName>CSBD_Now_Origen__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Origen</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CSBD_OrigenLeadExistente__c.field-meta.xml
<CustomField>
    <fullName>CSBD_OrigenLeadExistente__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Origen Lead Existente</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSBD_AvisosOportunidadesUtility_Apex.cls
public with sharing class CSBD_AvisosOportunidadesUtility_Apex {

    @AuraEnabled
    public static Integer getFrecuenciaAvisosAuto() { //en minutos (0 o null: sin avisos automáticos)
        return Integer.valueOf(CSBD_IdentificarOppsPHDSetting__c.getInstance().CSBD_FrecuenciaAvisosAuto__c);
    }

    @AuraEnabled
    public static List<Opportunity> getNuevasSolicitudesPhd() {
        return [SELECT CSBD_Identificador__c, CSBD_OrigenLeadExistente__c,
                CSBD_FechaEntradaUltimoLead__c, Account.Name FROM Opportunity
                WHERE RecordType.DeveloperName LIKE 'CSBD_%'
                AND CSBD_FechaEntradaUltimoLead__c != NULL  AND CSBD_MostrarAviso__c = 'Nueva búsqueda en facilitea casa'
                AND CSBD_Now_Origen__c = 'faciliteacasa'
                AND OwnerId = :UserInfo.getUserId() ORDER BY CreatedDate ASC LIMIT 100];
    }
}